### ISSUE TITLE
withgoogle.com

### ISSUE THREAD

**Issue by dgeibi** [gfwlist/gfwlist#100]
网站如

https://earthview.withgoogle.com

从来就不能访问

**Comment by cicku** [comment]
#27

**Comment by cicku** [comment]
请问，您是通过什么方式使用 gfwlist 的？

**Comment by dgeibi** [comment]
用别人的工具转换成 dnsmasq 的 ipset conf，表达式失效了😌

**Comment by dgeibi** [comment]
我才意识到 gfwlist 不仅仅是 list

**Comment by cicku** [comment]
是的，gfwlist 包含了几个正则的规则，不过，withgoogle 不需要正则匹配，我稍后添加。

**Comment by dgeibi** [comment]
好的，谢谢😀
2016年1月5日 上午9:34，"Christopher Meng" <notifications@github.com>写道：
