### ISSUE TITLE
*.github.io, github.io

### ISSUE THREAD

**Issue by rikakomoe** [gfwlist/gfwlist#1005]
This site is being conditionally blocked, 
According to my test, requests over https are available, while http receives `connection reset`,
which means you are probably ok with opening a website you used once before -- your browser will remember the permanent move to https, but it's likely to fail if it is the first time you visit, unless you type "https" manually.
So I recommend to add this into gfwlist.

**Comment by paperbag** [comment]
Nope.
http://104.24.8.40/github.io

**Comment by cicku** [comment]
You'd better comment those encountering the same here.
