### ISSUE TITLE
google play 被定向为国内节点无法正常使用

### ISSUE THREAD

**Issue by 474364707** [gfwlist/gfwlist#1009]
google play 从服务器检索信息时出错 [DF-DFERH-01]

最近在路由器装ss用gfwlist模式无法连接google play，猜测play商店指定了cn域名，但是谷歌cn的加密域名是废的，play又必须加密。
所以请把谷歌的CN域名的IP 重定向到指定IP
google.cn
g.cn
services.googleapis.cn
172.217.25.3
74.125.24.94
172.217.194.94
非常感谢...

**Comment by suntiny** [comment]
是一样的，今天用dnsmsaq强制将services.googleapis.cn定向到美国的，google play访问正常了。

**Comment by cicku** [comment]
GFWList 没有强制重定向 IP 的能力，貌似这是 hosts 应该做的事情。

**Comment by 474364707** [comment]
address=/services.googleapis.cn/172.217.25.3
就好了 
是Hosts
sorry  之前弄错了

**Comment by cicku** [comment]
See also #427, #464
