### ISSUE TITLE
stackoverflow.com/

### ISSUE THREAD

**Issue by CNmanyue** [gfwlist/gfwlist#1013]
执行了从gfwlist更新PAC到本地，查看本地的PAC文件，搜索stackoverflow，只有http://stackoverflow.com/users/895245。

![image](https://user-images.githubusercontent.com/9784893/39105939-365fd2ee-46eb-11e8-9ece-66a530408374.png)

**Comment by cicku** [comment]
我有一个小问题，请问您想表达什么?

**Comment by CNmanyue** [comment]
咋不把直接把域名添加进去呢，有时候是需要翻墙才能访问的。

**Comment by imageslr** [comment]
stackoverflow 无法直接访问呢
