### ISSUE TITLE
Please remove Nyaa from the list

### ISSUE THREAD

**Issue by JohnSmithdesu** [gfwlist/gfwlist#1014]
For now, _nyaa.eu_ and _nyaa.si_ is not blocked in Mainland China, please remove them from the list.

**Comment by cicku** [comment]
-`nyaa.si`

**Comment by JohnSmithdesu** [comment]
@paperbag @cicku According to the test result under my environment, it seems like `http://nyaa.eu` has been blocked but `https://nyaa.eu` has not.
