### ISSUE TITLE
https://docs.docker.com

### ISSUE THREAD

**Issue by Jake-Qu** [gfwlist/gfwlist#1015]
注意在https下，访问此域名会超时，
http访问会301到https
https://docs.docker.com

**Comment by Jake-Qu** [comment]
望添加到list

**Comment by paperbag** [comment]
如果 301 重定向到 HTTPS，那么代表是可以访问的。

**Comment by Jake-Qu** [comment]
[http://tool.chinaz.com/speedtest.aspx](不知道您是哪里，我用站长工具测试https://docs.docker.com) 90%大陆地区是超时的。

**Comment by paperbag** [comment]
> 不知道您是哪里，我用站长工具测试https://docs.docker.com 90%大陆地区是超时的。

你可以去用那个网站试试 https://github.com，它也都是超时的。

**Comment by paperbag** [comment]
> 不知道您是哪里，我用站长工具测试https://docs.docker.com 90%大陆地区是超时的。

![image](https://user-images.githubusercontent.com/19257585/39163133-b566299c-47ab-11e8-89f4-33839dad180f.png)

**Comment by cicku** [comment]
访问正常。
