### ISSUE TITLE
www.chinatimes.com 部分http页面屏蔽，数量较多，请求添加http整站

### ISSUE THREAD

**Issue by Toxic-Cat** [gfwlist/gfwlist#1022]
example: 
http://www.chinatimes.com/cn/newspapers/20170126000683-260301
http://www.chinatimes.com/cn/realtimenews/20170129001658-260407
http://www.chinatimes.com/cn/realtimenews/20170129001902-260405

浙江电信
ERR_CONNECTION_ABORTED

**Comment by houbaron** [comment]
可以用 HTTPS，Chrome 有个插件叫 HTTPS Everywhere．

**Comment by cicku** [comment]
Duplicate of #977
