### ISSUE TITLE
请求添加谷歌邮箱背景图片网址   ggpht.com

### ISSUE THREAD

**Issue by Quiet95scholar** [gfwlist/gfwlist#1047]
我使用的user-rule   .ggpht.com
原始站点URL: https://lh5.ggpht.com/rFYLYSIRwfX8qGC39nHKepf06zn507lmBsUdtp1zBU8ioDyoP1WiEOgOh4JHe4aOr8EHIwyaww=w1680-h1123-p-e365-fVignette=1,50,1.4,0,000000:Soften=1,0,0:-k-no

**Comment by paperbag** [comment]
这条规则`||ggpht.com`已经存在。

**Comment by cicku** [comment]
这域名很久前添加的。

您应该更新一下当前使用的规则列表了，严重过时 🤣

**Comment by Quiet95scholar** [comment]
@cicku 在pac规则中 ||ggpht.com 可以匹配到https://lh5.ggpht.com/rFYLYS... 这个地址吗?  
在我的理解中 ||ggpht.com 匹配出的是  *://ggpht.com   并不能匹配二级域名
我看的文档是https://github.com/shadowsocks/ShadowsocksX-NG/issues/333

**Comment by paperbag** [comment]
> 在pac规则中 ||ggpht.com 可以匹配到https://lh5.ggpht.com/rFYLYS... 这个地址吗?
> 在我的理解中 ||ggpht.com 匹配出的是 *://ggpht.com 并不能匹配二级域名

当然能匹配到二级域名，请参考：https://adblockplus.org/filters

**Comment by Quiet95scholar** [comment]
@paperbag get到了,感谢

**Comment by cicku** [comment]
https://github.com/gfwlist/gfwlist/wiki/Syntax
