### ISSUE TITLE
The page display of goodreads.com is messy

### ISSUE THREAD

**Issue by psychelzh** [gfwlist/gfwlist#1053]
Seemingly it is because of the site `s.gr-assets.com` is blocked, but I am not sure.

**Comment by paperbag** [comment]
wozheli我这里是正常的，看起来像是 CloudFront 在国内访问不是很好的问题。
![image](https://user-images.githubusercontent.com/19257585/39748562-fa3d0f3a-52e2-11e8-8d8b-5dfef3d32de2.png)

**Comment by psychelzh** [comment]
看起来今天可以了。
