### ISSUE TITLE
SwitchyOmega 自动切换模式下 Chrome 无法登陆谷歌账户

### ISSUE THREAD

**Issue by the-eric-kwok** [gfwlist/gfwlist#1056]
SwitchyOmega 自动切换模式下 Chrome 无法登陆谷歌账户
只有切换成全局代理才能正常登录/同步谷歌账号
如图所示
![_google-chrome_20180508173721](https://user-images.githubusercontent.com/16463312/39749986-a7d04704-52e6-11e8-95f2-b65b2210fe6c.gif)

SwitchOmega 使用gfwlist规则
![image](https://user-images.githubusercontent.com/16463312/39750040-cb6bc666-52e6-11e8-838d-2423314a4130.png)

自定义的规则如下：
```
[SwitchyOmega Conditions]
@with result

*.google.ca +proxy
*.maps.googleapis.com +proxy
*.fonts.googleapis.com +proxy
*.google-analytics.com +proxy
*.googlevideo.com +proxy
*.googlesyndication.com +proxy
*.google.com +proxy
*.googletagmanager.com +proxy
*.googletagservices.com +proxy
*.ajax.googleapis.com +proxy
*.googleusercontent.com +proxy
*.youtube.com +proxy
*.findyoutube.net +proxy

* +direct
```

系统信息：
```
[11:28]eric~$ uname -a
Linux eric-PC 4.14.0-deepin2-amd64 #1 SMP PREEMPT Deepin 4.14.12-2 (2018-01-06) x86_64 GNU/Linux
```

**Comment by erickwoc** [comment]
添加规则
```
*.googleapis.com +proxy
```
之后便可正常登陆

**Comment by paperbag** [comment]
这条规则早就有了 `||googleapis.com`

**Comment by fengyuyizai** [comment]
请问你的proxy代理项中填写的是什么, 我也遇到这个问题了, 我调成系统代理、直接代理都不行, 后来将SwitchyOmega插件关闭, 才同步成功, 我按照你们的说法将google的host指向proxy,但是我不知到你们的proxy里面如何配置. 谁能帮忙解决下
