### ISSUE TITLE
能否增加steamcommunity的域名

### ISSUE THREAD

**Issue by wang93wei** [gfwlist/gfwlist#1060]
当使用中国ip访问https://steamcommunity.com/discussions/ 会提示不可用。但是如果用代理服务器IP就不会出现这个问题
![qq 20180513011200](https://user-images.githubusercontent.com/6371053/39959866-d0ce1f0c-564a-11e8-955d-dca60799f8ae.jpg)
![qq 20180513011306](https://user-images.githubusercontent.com/6371053/39959867-d1036b3a-564a-11e8-94d9-f09073f183c8.jpg)

**Comment by paperbag** [comment]
https://github.com/gfwlist/gfwlist/issues/1060

> `steamcommunity.com` 是必须加的，这辈子都必须加的，不加社区根本打不开，就是加了，才能维持得了能访问这个样子。

😂😂😂

**Comment by cicku** [comment]
Duplicate of #837
