### ISSUE TITLE
建议删除“google.cn”

### ISSUE THREAD

**Issue by StandAlong** [gfwlist/gfwlist#1064]
google.cn域下被墙的网址只有www.google.cn，目前还添加了一些没有被墙的站点，服务器在中国并且能正常使用，如developer.google.cn，因此希望能删除list中"google.cn"条目，避免不必要的代理。

**Comment by cicku** [comment]
没有`google.cn`相关条目，您是不是搞错了什么。

**Comment by StandAlong** [comment]
.pac第1877行难道不是吗？

**Comment by paperbag** [comment]
>.pac第1877行难道不是吗？

你确定你看的是 gfwlist？

**Comment by StandAlong** [comment]
我也想知道我是不是搞错了什么。我是这样使用的：`genpac --pac-proxy="SOCKS5 127.0.0.1:1080" --gfwlist-proxy="SOCKS5 127.0.0.1:1080" -o autoproxy.pac --gfwlist-url="https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt"`，随后在home下生成的"autoproxy.pac"里找到google.cn。这样的使用方式不正确或者跟你们说的不是一件事吗？

**Comment by paperbag** [comment]
你用的是 [genpac](https://github.com/JinnLynn/genpac) 吧？我觉得这应该是 [genpac](https://github.com/JinnLynn/genpac) 的问题，他们的 README.md 有这么一句：
> 例外规则 `@@` ，如 `@@*.example.com/*` 满足 `@@` 后规则的地址不使用代理

实际上规则应该写成 `@@||example.com`，而不是像 `@@*.example.com` 这样，这里有个 shadowsocks-windows 的例子 https://github.com/shadowsocks/shadowsocks-windows/issues/1856#issuecomment-390161673  ，具体请参考：https://adblockplus.org/en/filters 。目前 gfwlist.txt 只有三个有关 `google.cn` 的规则，`www.google.cn` 和 `translate.google.cn` 都是例外规则。看起来应该是 [genpac](https://github.com/JinnLynn/genpac) 处理例外规则的锅。

	Line 1171: ||groups.google.cn
	Line 7591: @@|http://translate.google.cn
	Line 7592: @@|http://www.google.cn/maps

**Comment by StandAlong** [comment]
你们是用什么配置的代理规则啊，或者是用的哪一套解决方案？是否全平台呢？

**Comment by gucong3000** [comment]
@StandAlong 这个项目是为其他工具提供可在线更新的规则的。不直接提供解决方案。
