### ISSUE TITLE
希望删掉 hopto.org 的条目

### ISSUE THREAD

**Issue by sceic** [gfwlist/gfwlist#1072]
因为这个域名是来自noip的免费域名范围，我也再用，每次pac更新后都造成我自己的网址无法使用，做为一个公共的域名，希望不要加入到pac。 希望啦，谢谢。

**Comment by cicku** [comment]
这什么逻辑，我咋没看懂……公不公共和 GFWList 没有任何关系好吧，这个域名是被墙的。
