### ISSUE TITLE
btdigg.cc 请加入

### ISSUE THREAD

**Issue by justforadblock** [gfwlist/gfwlist#1076]
btdigg.cc 请加入

**Comment by cicku** [comment]
访问未见异常，请告知 ISP。

**Comment by justforadblock** [comment]
麻烦路过的朋友测试一下是不是可以直接访问，我这里是不可以的。

**Comment by nxtreaming** [comment]
可以访问，是个小yellow website

-----------------------------------------
Productive. Reliable. Fast.

**Comment by paperbag** [comment]
> 麻烦路过的朋友测试一下是不是可以直接访问，我这里是不可以的。

「请告知 ISP。」你的 ISP 是电信/移动/联通？@justforadblock

**Comment by accountforadg** [comment]
我是移动

**Comment by justforadblock** [comment]
@cicku   @paperbag  广东移动， 移动宽带。        
 我同时也用手机的移动4G网络试了下，也是无法访问。

**Comment by justforadblock** [comment]
「请告知 ISP。」
这句话有歧义，我还以为你们的意思是。 让我向ISP报告这个问题。

**Comment by cicku** [comment]
其实这句话没毛病，您应该向 ISP 投诉，同时也应该告诉我 ISP。

既然是移动墙中墙造成的，那我就关 Issue 了。
