### ISSUE TITLE
dns.v2ex.com被reset了

### ISSUE THREAD

**Issue by sadan9** [gfwlist/gfwlist#108]
root@OpenWrt:~# curl dns.v2ex.com -I -v
> HEAD / HTTP/1.1
> User-Agent: curl/7.40.0
> Host: dns.v2ex.com
> Accept: */*
> 
* Recv failure: Connection reset by peer
curl: (56) Recv failure: Connection reset by peer

**Comment by cicku** [comment]
:signal_strength: Still working, tracking in CHU Network
