### ISSUE TITLE
www.mobile01.com是否从列表中移除？

### ISSUE THREAD

**Issue by aescin** [gfwlist/gfwlist#1087]
https://github.com/gfwlist/gfwlist/issues/626

看到mobile01是已经添加在列表中，最近一段时间发现默认PAC打不开。强制代理可以打开。

**Comment by paperbag** [comment]
没读懂；为什么标题说要从列表里移除？

**Comment by JohnCanny52** [comment]
意思是用代理可以打开，用PAC打不开，那应该是列表内没有才能解释的通吧？

**Comment by cicku** [comment]
HTTPS 打不开，HTTP 正常。

**Comment by cicku** [comment]
也不对，我再观测一下。

**Comment by cicku** [comment]
我现在观测的结果是 HTTPS 正常，HTTP 自动跳转 HTTPS。

**Comment by wordlesswind** [comment]
@paperbag 
少了个“被”字导致表意不明。
理应是“www.mobile01.com是否从列表中被移除？”

**Comment by cicku** [comment]
HTTPS TIMEOUT
