### ISSUE TITLE
Why !--||googleadservices.com ?

### ISSUE THREAD

**Issue by davidshen84** [gfwlist/gfwlist#11]
在commit: bd0628aaa09a4a2095617f7f8157c8861e13eff6 里看到

> !--||googleadservices.com

这句是注释掉的意思吧。但是 googleadservices.com 还是没有解禁啊。

**Comment by davidshen84** [comment]
同样的，还有以下这些：

> !--||googlesyndication.com
> !--||googletagmanager.com
> !--||googletagservices.com

**Comment by cicku** [comment]
What's your ISP?

**Comment by davidshen84** [comment]
联通，电信都试过

**Comment by davidshen84** [comment]
Again,

> @@||fonts.googleapis.com

Why it is an exception? I tried many times on different network, I am not able to access this domain without punching a hole on the wall.

**Comment by cicku** [comment]
fonts.googleapis.com 是自动解析到中国服务器的，只能说你的 ISP 太奇葩。

**Comment by cicku** [comment]
fonts.googleapis.com is not blocked, it's resolved to Google Beijing.

**Comment by davidshen84** [comment]
Well, in my case, in Shanghai, I am not able to access.

Also, I am unable to access domains which are set as exception by this rule:

> @@||fonts.gstatic.com



On Mon, Sep 14, 2015 at 10:35 AM Christopher Meng <notifications@github.com>
wrote:

> fonts.googleapis.com is not blocked, it's resolved to Google Beijing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gfwlist/gfwlist/issues/11#issuecomment-139945222>.
>
-- 

Regards,
David
