### ISSUE TITLE
cloudfront.net

### ISSUE THREAD

**Issue by 007gzs** [gfwlist/gfwlist#1100]
d301sr5gafysq2.cloudfront.net
d257l1zb7u5fh9.cloudfront.net
不能访问，我看到cloudfront.net的有些子域名已经在了，
这个是amazon的cdn,应该是整个都被墙了，建议直接都加上

**Comment by Flandoll** [comment]
我访问你发的这两个域名，都能访问。
AWS控制台也用了cloudfront，也没有出现不能访问或者页面加载出错的情况。

**Comment by 007gzs** [comment]
今天又能访问了，可能是isp问题
