### ISSUE TITLE
wenzhao.ca

### ISSUE THREAD

**Issue by luqiuwen** [gfwlist/gfwlist#1105]
wenzhao.ca
ISP: Beijing Unicom

**Comment by kangzhangqi** [comment]
https://www.wenzhao.ca   can't connect ~~~

**Comment by luqiuwen** [comment]
![image](https://user-images.githubusercontent.com/1797063/42608764-e2185732-85bb-11e8-80ae-cb50146dda05.png)
Here is the performance test result for www.wenzhao.ca, which provided by tools.keycdn.com. It shows that the website can be connected from all test servers.

**Comment by luqiuwen** [comment]
https://tools.keycdn.com/performance?url=https://www.wenzhao.ca

**Comment by luqiuwen** [comment]
this website is blocked in china mainland. @kangzhangqi
