### ISSUE TITLE
Please add ||chinatimes.com

### ISSUE THREAD

**Issue by OrekiDawson** [gfwlist/gfwlist#1110]

**Comment by OrekiDawson** [comment]
虽然首页可以访问，但是部分新闻页面疑似被墙，比如**http://www.chinatimes.com/cn/realtimenews/20170509003251-260407**

**Comment by wordlesswind** [comment]
HTTP协议无法访问，HTTPS正常。

**Comment by wordlesswind** [comment]
#977
重复issue

**Comment by cicku** [comment]
Duplicate of #977
