### ISSUE TITLE
增加 bitbucket.org

### ISSUE THREAD

**Issue by SerCom-KC** [gfwlist/gfwlist#1112]
虽然没有 DNS 污染，但是似乎已经被 RESET 了。

**Comment by ye21st** [comment]
同求，不能访问的话，对我们提交代码影响很大。

**Comment by Flandoll** [comment]
似乎已经恢复正常了

**Comment by SerCom-KC** [comment]
好像还真是，先 close 算了。
墙这几天是怎么了，总感觉这个 case 跟维基百科有点相似啊……
