### ISSUE TITLE
Request for Addition of Address rfalive1.akacast.akamaistream.net

### ISSUE THREAD

**Issue by vexetron** [gfwlist/gfwlist#1117]
http://rfalive1.akacast.akamaistream.net/7/984/433977/v1/ibb.akacast.akamaistream.net/RFALive1.m3u

An address found on Radio Free Asia.

Thank you.

**Comment by vexetron** [comment]
It seems to be its server's problem causing resetting errors for that I have found this address on the first line of the pac.txt.

打扰了。

**Comment by cicku** [comment]
`rfalive1.akacast.akamaistream.net`
