### ISSUE TITLE
Please remove v2ex

### ISSUE THREAD

**Issue by AnyMoe** [gfwlist/gfwlist#1118]
V2ex can be directly accessed in Mainland China for a long time. As a website has been migrated to servers in China, it may collect proxy address due to policy reasons. There is no need to leave it in the list.

**Comment by railjty** [comment]
I often see 'Connection Reset' when I visit it in China by http/https, so needn't do remove it.

**Comment by minbaby** [comment]
v2ex server has move to Mainland China.

http://ip.tool.chinaz.com/www.v2ex.com

http://ip.tool.chinaz.com/v2ex.com
