### ISSUE TITLE
Please add *.flyzy2005.com

### ISSUE THREAD

**Issue by flyzy2005** [gfwlist/gfwlist#1133]
The domain was banned by GFW a few days ago and it's my blog address. Thanks a lot. 
Or do I need to apply for this add action somewhere else?

**Comment by flyzy2005** [comment]
https://flyzy2005.com
https://www.flyzy2005.com

**Comment by flyzy2005** [comment]
谢谢大佬！

**Comment by cicku** [comment]
I'm not 大佬. Call me Lei Feng.

**Comment by flyzy2005** [comment]
Thank you, Lei Feng in the 21st century.
