### ISSUE TITLE
Please Add *.feedly.com

### ISSUE THREAD

**Issue by imidway** [gfwlist/gfwlist#1135]
可不可以把feedly加入？？？这个网站基本上大陆的ip访问起来很困难，即使能打开也会卡的很慢很慢，而手机端则根本无法加载图片

**Comment by wordlesswind** [comment]
你完全可以自己添加个自定义PAC。

**Comment by cicku** [comment]
很困难？？？

我这里测试都是秒开的……

**Comment by cicku** [comment]
麻烦您看一下 #1288，我最近更新了列表，是否您还是打不开呢？

**Comment by cicku** [comment]
Duplicate of #1941
