### ISSUE TITLE
Imgur

### ISSUE THREAD

**Issue by wordlesswind** [gfwlist/gfwlist#1140]
https://imgur.com

Can't sign in account and upload pictures on this website.

**Comment by mraandtux** [comment]
你ISP有问题挂

**Comment by wordlesswind** [comment]
@mraandtux 提示我是说“当前国家容载量已超负荷”

**Comment by mraandtux** [comment]
试左一下，发现系呢个错误信息：

> Imgur is temporarily over capacity. Please try again later.

唔系国内国外嘅问题，搜以上错误信息后，发现问题无论系边度登录都有

**Comment by cicku** [comment]
我遇到的是挂了代理500错误会消失，能够登陆，但是也不确定。

Imgur历史上有主动屏蔽中国大陆的先例，并且是很隐晦的屏蔽。

**Comment by wordlesswind** [comment]
@cicku
我遇到的就是500错误，而且这个问题不是一天两天的事情，至少15年开始就这样。

**Comment by cicku** [comment]
是的，我知道这个问题。

现在 Chrome 不允许匹配 HTTPS 的 URL 了，我如果把全站加入列表，也不合适。

**Comment by wordlesswind** [comment]
@cicku 
这个问题是不是也应该考虑一下

**Comment by wordlesswind** [comment]
现在我发现，这个问题出现在QQ邮箱上，换个邮箱恢复正常……
