### ISSUE TITLE
我有个疑问：为什么不明文显示列表内容？

### ISSUE THREAD

**Issue by cryptogun** [gfwlist/gfwlist#1148]
现在的列表是base64加密的。我觉得明文显示的好处有：
* 对人类友好。一看就知道内容。
* 对机器友好。根据git的原理，改1行的话，diff输出没有多少；而加密的话，整个文件都变了，不好储存，也不好进行版本对比、代码查看。
* 利于搜索。搜索引擎能抓取到某条域名是什么时候加进来的。时间长了还可以对
GFW有一个宏观的感知。就像一个个的里程碑。

加密是基于什么原因，或者有什么考虑吗？

**Comment by cryptogun** [comment]
找到一个解释：防止明文被拦截
https://github.com/gfwlist/gfwlist/issues/356#issuecomment-248563499
那也可以考虑同时放2个txt吧，一个明文的一个加密的。想用哪个就用哪个。

**Comment by wordlesswind** [comment]
对机器友好，不认同
下载源文件又不是通过Git。

说白了，就是懒。

**Comment by cicku** [comment]
GFWList 对此类建议没有任何兴趣，请勿以后汇报此类内容。

谢谢。

**Comment by UjuiUjuMandan** [comment]
> 或者有什么考虑吗？

Probably, Meng wants to hide such confidential information from foreign forces.
