### ISSUE TITLE
CDN Domains for xHamster

### ISSUE THREAD

**Issue by StoneMoe** [gfwlist/gfwlist#115]
us-st.xhcdn.com 
==
For xHamster Static Resources..

ut*.xhcdn.com
==
ut03.xhcdn.com ~ ut13.xhcdn.com, what range I found is available.
Contains Some User Contents, Video previews.

upt.xhcdn.com
==
Contains Gallery Covers.

So...maybe just add `.xhcdn.com`?

**Comment by cicku** [comment]
There is no problem accessing these websites above now.

**Comment by cicku** [comment]
Hello, please tell me the issue you met, if not I will close it.

**Comment by StoneMoe** [comment]
I test some stuff.

DNS Request to domains is ok.(114DNS)
Domain/IP Direct HTTP request to xhcdn is ok.

but in the xHamster website, Chrome's Network panel shows many resource from this domain just "Stalled".

Sometimes it load succeed after a very long time, or just keep "Stalled" mostly.

Maybe it's just local ISP network issue.

**Comment by StoneMoe** [comment]
ChinaTelecom ADSL2
