### ISSUE TITLE
AbemaTV点播需要全局代理

### ISSUE THREAD

**Issue by ZYZ665** [gfwlist/gfwlist#1160]
使用JP代理后，发现abemaTV的gfwlist还存在问题
比如
https://abema.tv/video/episode/19-29_s1_p5
https://abema.tv/video/episode/25-93_s1_p15
这种点播的网址还是需要全局代理访问，直播没有问题。

**Comment by cicku** [comment]
我现在觉得没问题了，麻烦看一下。

**Comment by ZYZ665** [comment]
嗯 好了  多谢。
