### ISSUE TITLE
请教一个问体,我访问了很多gfwlist里的网站,发现网站本身早已作废.发现了上千个了.是否可以删除

### ISSUE THREAD

**Issue by lan542662** [gfwlist/gfwlist#1163]
这些已经失效的网站可以从里面去除了吧.

**Comment by cicku** [comment]
不知道什么叫上千个。

你可以都发上来。

**Comment by lan542662** [comment]
是几百个。没有上千。不好意思。我只是随机挑了一些。尤其发现那些敏感的，早就失效了。

**Comment by zhangchunlin** [comment]
@lan542662 是怎么确认失效的呢?域名已经没用了?

**Comment by lan542662** [comment]
是的,我就是没事做.就从Z开始找那些不常见的,网址,一个一个复制打开来看.然后发现很多关于64的啦.或者什么的,其实网站早就失效了.宗教类的基本都在,很多个人的,其实网站早已作废了. 还有很多国外不知道什么网站也是失效的,

**Comment by lan542662** [comment]
另外我同步的是archlinux,就想请教mirrors.atviras.lt   mirrors.atviras.lt/archlinux/ 这两个地址我是用第一个行吗,我是放路由器里的他里面都是这样网址.为保险我把mirrors.atviras.lt/archlinux/ 也放进去了.有必要吗.请教

**Comment by lan542662** [comment]
打个比方 我想添加这个 我是用哪个 arch.midov.pl  还是midov.pl 还是 arch.midov.pl/arch/   因为midov.pl 在网址里看的话 前后都是灰色的.所以 我用哪个放路由器里就好了呢.第一个? 第二个? 第3个感觉好像没必要.路由器的域名地址没有这个

**Comment by yichangshengwu** [comment]
应该是有，但也没那么多吧。。。
我闲着没事也在挨个试，挨个注解，
有域名 到期/变更跳转 之类的，也有一些应该是已经换了主人明显不应该被呛的，但没那么大比例吧！

至于一些“看起来重复”了的，还真不一定是多余的！
我猜，之所以那么做应该也是实践后发现必须那么干，你试试注释掉那些条目应该能发现。

**Comment by lan542662** [comment]
> 应该是有，但也没那么多吧。。。
> 我闲着没事也在挨个试，挨个注解，
> 有域名 到期/变更跳转 之类的，也有一些应该是已经换了主人明显不应该被呛的，但没那么大比例吧！
> 
> 至于一些“看起来重复”了的，还真不一定是多余的！
> 我猜，之所以那么做应该也是实践后发现必须那么干，你试试注释掉那些条目应该能发现。

我先在把twitter那些网站的cdn都放进去了。打开有用浏览器查看源码，然后网站都放进去。不过觉的。GFW模式依然很有必要。虽然绕过模式现在我更喜欢。但是GFW黑名单，这面旗帜会一直在。GFW在他就在哪。

**Comment by cicku** [comment]
Duplicate of #290
