### ISSUE TITLE
Slack CSS CDN 服务器 + Akamaistream

### ISSUE THREAD

**Issue by gongjianhui** [gfwlist/gfwlist#117]
slack.global.ssl.fastly.net
访问 slack.com 由于上述 CSS 文件无法访问，导致页面布局异常。

Akamaistream.com
部署在该域名上的一些境外媒体广播节目（比如 VOA）无法访问。
e.g. http://voa-11.akacast.akamaistream.net/7/317/322023/v1/ibb.akacast.akamaistream.net/voa-11

**Comment by cicku** [comment]
voa-11.akacast.akamaistream.net RST

**Comment by gongjianhui** [comment]
and rfalive1.akacast.akamaistream.net

**Comment by cicku** [comment]
fastly 暂时无法添加，教育网正常，联通+电信间歇性“故障”。

**Comment by gongjianhui** [comment]
*.cloud-cdn-digitalocean-com.global.ssl.fastly.net 无法加载导致 Digitalocean 页面布局异常，上海移动。

**Comment by cicku** [comment]
移动网络不在 gfwlist 的考虑范围内。

**Comment by gongjianhui** [comment]
中国公民冯正虎的个人博客：fengzhenghu.net，辽宁联通 RST。






On Fri, Jan 15, 2016 at 7:52 PM -0800, "Christopher Meng" <notifications@github.com> wrote:












移动网络不在 gfwlist 的考虑范围内。

**Comment by cicku** [comment]
fengzhenghu.net added.
