### ISSUE TITLE
engadget 癮科技 中文版 以及 TVB APP《無線新聞》 新聞直播 無法訪問

### ISSUE THREAD

**Issue by ntgeralt** [gfwlist/gfwlist#118]
Router:SS+pdnsd+gfwlist

http://chinese.engadget.com/  能打開，但打開網頁不全。用VPN則順利打開整個網頁；
另外android的 TVB APP 《無線新聞》，裡面的預錄節目能流暢訪問。
但‘直播’的節目似乎還是走國內，訪問緩慢。您看看能不能再優化一下 :)

ps:刚发现http://chinese.engadget.com/ 通过gfwlist没问题，能完整打开了~

**Comment by cicku** [comment]
`似乎還是走國內`

请问怎么定义`似乎`？

**Comment by ntgeralt** [comment]
router關閉SS+pdnsd+gfwlist，啟動PPTP客戶端、全局代理，點APP‘新聞直播’能在1秒后出現直播畫面；
router之前的SS+pdnsd+gfwlist ，點直播會一直黑屏

**Comment by cicku** [comment]
您好，不清楚您的 router 是怎么配置 gfwlist 的。

gfwlist 只对如下 tvb.com 链接生效：

```
forum.tvb.com
news.tvb.com/list/world
news.tvb.com/local
```

而我对客户端的抓包均显示试图连接：
```
p1.mobile.hk3.tvb.com
c1.newsapp.vip.hk3.tvb.com
```

gfwlist 并不会生效。

**Comment by ntgeralt** [comment]
用的是恩山論壇 改華碩7620固件。發現自帶有條list
server=/.tvb.com/208.67.222.222#443
ipset=/.tvb.com/gfw_black_list
可能這條list讓TVB APP一半走國外吧，我之後添加你抓包的2條list 直播能看了。

**Comment by cicku** [comment]
tvb 的规则在近期做过更新，固件作者在当初制作的时候使用的 gfwlist 规则已不再适用于现在的封锁，建议您联系固件作者请求更新固件。
