### ISSUE TITLE
三个台湾网站

### ISSUE THREAD

**Issue by MoeKing** [gfwlist/gfwlist#1182]
gamer-cds.cdn.hinet.net
gamer2-cds.cdn.hinet.net
巴哈姆特动画疯中华电信cdn地址 不走代理无法观看
http://gamer2-cds.cdn.hinet.net/vod_gamer/_definst_/smil:gamer2/0905087d704eb5c8f19563e9807c2c03b2a2c424/hls-ae-2s.smil/chunklist_b5000000.m3u8?token=Pi34DQGZqBohJ7aeQnfQOg&expires=1534188379&bahaData=MoeKing:10340:0:PC:4eab5

www.bookwalker.com.tw
台湾的一家电子书网站 部分书籍限定区域 不走代理无法购买
https://www.bookwalker.com.tw/product/10133 台澎金马
https://www.bookwalker.com.tw/product/10941 港澳台

tw.iqiyi.com
爱奇艺台湾站 可正常访问 不走代理版权提示无法观看
https://tw.iqiyi.com/v_19rqy2srfs.html

**Comment by MoeKing** [comment]
完整地址是我忘了贴 补上
能正常访问就不加？netflix也能访问 有需求的自然会挂台湾代理 没需求的也不会上这网站
假定加入名单
挂非台湾代理购买非限定区域毫无影响
挂台湾代理买非限定区域毫无影响
挂台湾代理可以购买限定区域
然后不挂代理和非台湾代理都买不了限定区域
本来大陆也没多少人过去买 影响不了不少人 也没有什么不良影响 又不是B站这么大的网站
图个方便而已 觉得不妥就不加吧 1和3没毛病吧

**Comment by cicku** [comment]
Merged into #1311
