### ISSUE TITLE
Reddit is blocked now

### ISSUE THREAD

**Issue by marikid** [gfwlist/gfwlist#1184]
Great Fire Analyzer: https://zh.greatfire.org/https/www.reddit.com
Related Post:
TechNews: http://technews.tw/2018/08/13/reddit-is-finally-ban-in-china/
Reddit: https://www.reddit.com/r/saraba1st/comments/965szz/%E7%8E%B0%E5%9C%A8%E8%A2%AB%E5%A2%99%E4%BA%86/

**Comment by wordlesswind** [comment]
#1183 
Duplicate issue

**Comment by cicku** [comment]
Duplicate of #1183

**Comment by idealclover** [comment]
@marikid lol, I just saw the duplication and closed the issue.
