### ISSUE TITLE
Netflix

### ISSUE THREAD

**Issue by altayhunter** [gfwlist/gfwlist#1193]
Netflix now requires an additional rule:
||netflix.net

With the current set of rules most shows run into a "Proxy detected" error.
https://gist.github.com/jamesmacwhite/6a642cb6bad00c5cefa91ec3d742e2a6#netflix-domains-that-need-be-specifically-treated
https://github.com/shadowsocks/shadowsocks-libev/issues/2083#issuecomment-395690765
https://gist.github.com/jamesmacwhite/eed8768239ab661ad475e1a8f6b45c8c#rule-1-netflix-top-level-domains

**Comment by marikid** [comment]
This rule is already on the list :)

**Comment by altayhunter** [comment]
It's not in [gfwlist.txt](https://github.com/gfwlist/gfwlist/blob/master/gfwlist.txt). The only Netflix-related rules already there are:

```
||netflix.com
||nflximg.com
||nflximg.net
||nflxext.com
||nflxso.net
||nflxvideo.net
!-||blog.netflix.com
```

It's missing `||netflix.net` which results in a proxy error.
