### ISSUE TITLE
Pixiv.net refuse IP from BGP connecting to it

### ISSUE THREAD

**Issue by ghost** [gfwlist/gfwlist#1194]
pixiv.net are dns spoofing,not blocked.
So remove it from the list?

We can use non-pollution DNS to connect to it.
So remove it from the list?

**Comment by wordlesswind** [comment]
没看懂，既然是DNS污染，为什么要从列表里移除。

**Comment by cicku** [comment]
虽然楼主已经灰飞烟灭了，但我还是要说一下：

现有被 DNS 污染的域名越来越多，大部分走 CDN 的网站直接访问 IP 并不被允许，不考虑修改 hosts 的情况下（与本项目目标用户冲突），无论更改 DNS 是否能绕过，均添加处理。

PIXIV 这种拒绝机房 IP 的行为不清楚到底存不存在，如果存在也没有办法，毕竟无法保证所有人都用的是机房的梯子。

**Comment by wordlesswind** [comment]
@cicku
何况现在基本都被TCP阻断了，无污染DNS作用不大。
