### ISSUE TITLE
非常不好意思的问一个关于gfwlist.txt的初级问题

### ISSUE THREAD

**Issue by SoraAnn** [gfwlist/gfwlist#1199]
我在windows的官方ss客户端里面想使用在线PAC，于是我将https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt这个地址填入了在线pac下面，结果发现pac模式我啥也没法访问
后面我打开这个最新的gfwlist.txt一看，里面全部是乱码，貌似是加过密的内容，和我本地的之前使用的pac文件完全不一样...

本人小白，请问应该如何将gwlist.txt转换为客户端能读取的pac文件呢？翻了半天主页和wiki 没发现怎么弄，所以再次提问。抱歉了。

**Comment by multics** [comment]
base64编码的，如果你非要看内容，反编码就行了。



发自手机

**Comment by multics** [comment]
如果你用linux或者mac，可以用下面的命令，转成明文。

    url=https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
    curl -s $url | base64 -D

**Comment by pig-let** [comment]
https://raw.githubusercontent.com/petronny/gfwlist2pac/master/gfwlist.pac
这里有个项目，每天更新，你填这个就行

**Comment by dogloving** [comment]
```Python
import base64
with open('gfwlist.txt') as f:
        for line in f.readlines():
            print(str(base64.b64decode(line), encoding='utf-8'))
```

**Comment by sun816** [comment]
请问安卓版的 shadowsockes FOSS的custom rules是否能导入GFWILST? 我试图从剪贴板粘贴和URL to online config两个选项，在生成规则后，profile中route选custom rules似乎没有效果。谢谢。
