### ISSUE TITLE
dl.google.com 已经没有国内的cdn了，删除白名单吧

### ISSUE THREAD

**Issue by goudiao** [gfwlist/gfwlist#121]
如题：dl.google.com 从白名单中移除吧，
苹果iTunes的下载页面 www.apple.com/hk/itunes/download/  中的 *.akamai.net 域名资源无法加载，请加入列表

**Comment by cicku** [comment]
`a248.e.akamai.net ` 与其他 node 不同，彻底被封锁，如果把链接中的资源路径改为 a249 或者 a247 均可以打开。该问题出现于所有非`cn` iTunes 下载页面中。（证书报错，但是这是 akamai 方面的故障）

目前初步探测是因为`greatfire`也在用这个网址，所以 apple 躺枪了。
