### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by lan542662** [gfwlist/gfwlist#1218]
看到名单中很多共用一个顶级域名的,很多个.有顶级域名不就可以了吗,为什么还要单独列这么多出来呢.(我是放到路由ss里的).感谢. 打个比方 1. bbkz.com  2.  bbkz.com/forum 是否有1 就行了

**Comment by cicku** [comment]
There is only ONE bbkz-related rule in the list: `.bbkz.com/forum`.

I don't know where you saw `bbkz.com` rule, as it shouldn't be anywhere.
