### ISSUE TITLE
services.googleapis.cn被DNS污染

### ISSUE THREAD

**Issue by kurimusan** [gfwlist/gfwlist#1227]
大陆手机内建谷歌服务很多实用了services.googleapis.cn这个域名，但是这个域名在大陆被DNS污染了，会指向到北京的某几个IP，导致谷歌play商店出现从服务器检索信息时出错【DF-DFERH-01】的错误。建议把此域名加入gfwlist，让其能正常解析到谷歌美国的IP地址。

**Comment by paperbag** [comment]
#464

**Comment by cicku** [comment]
请参考 #464
