### ISSUE TITLE
http://google.org/ please check

### ISSUE THREAD

**Issue by mage0535** [gfwlist/gfwlist#123]
The address http://google.org/ I cann't access by SS pac, but I use global can access it,and after I add it to my local pac file access is normal, so I think the URL at GFW not at GFWLIST, please check it.
My internet is Shandong Unicom optical cable

我的网络环境为山东联通光纤用户
http://google.org/ 这个域名在使用SS的pac模式无法访问，更新GFWLIST后仍然无法访问，切换为全局模式和手动添加到本地pac文件后可通过SS正常访问，因而我想这个域名是被GFW而未添加到GFWLIST中的，请核实。

**Comment by cicku** [comment]
暂时无法确认

**Comment by cicku** [comment]
RST 确认。

`.google.*twitter`

**Comment by cicku** [comment]
需要注意的是，google.org 本身并未受到干扰。
