### ISSUE TITLE
cdn.ampproject.org 解析到国内IP可正常连接

### ISSUE THREAD

**Issue by Loukky** [gfwlist/gfwlist#1232]
如上，并未被墙

**Comment by HashLiver** [comment]
经nslookup命令测试其解析至172.217.24.193，是Google的IP

**Comment by Loukky** [comment]
https://i.imgur.com/H19MASX.png

**Comment by Loukky** [comment]
同时 *.ampproject.net 这个域名是解析到国外的谷歌IP段的，麻烦添加一下到列表中~

**Comment by paperbag** [comment]
```
@@||ampproject.org
@@||cdn.ampproject.org
||.cdn.ampproject.org
```
这里有个特例 AMP cache `*.cdn.ampproject.org`仍然是无法访问的：

比如 https://www-ampproject-org.cdn.ampproject.org/c/s/www.ampproject.org/ （缓存的是 https://www.ampproject.org/ 页面）

AMP cache URL 格式可以见： https://developers.google.com/amp/cache/overview
