### ISSUE TITLE
Pixiv.net疑似已经不再使用DNS Poisoning来拦截

### ISSUE THREAD

**Issue by rainCandyU** [gfwlist/gfwlist#1236]
hosts更改依然不能访问，需要代理才可以了

**Comment by Tarhyru** [comment]
听说gfw整体升级了..现在应该没有改个DNS就能上的墙外站点了...

**Comment by initializeZero** [comment]
据说使用了TCP旁路阻断技术,Wireshark抓包分析得知tls握手第二步被GFW干扰返回RST;可以使用nginx做反代+pixiv证书暂时解决.从这位博主看到的https://m.weibo.cn/status/Gzdi6ahff,使用时IE浏览器效果更佳

**Comment by Tarhyru** [comment]
楼上那个方法我来补充一个...
https://github.com/mashirozx/Pixiv-Nginx
