### ISSUE TITLE
twitch.tv

### ISSUE THREAD

**Issue by chengr28** [gfwlist/gfwlist#1242]
DNS cache poisoning

```
>nslookup twitch.tv 8.8.8.8
服务器:  google-public-dns-a.google.com
Address:  8.8.8.8

非权威应答:
名称:    twitch.tv
Addresses:  31.13.82.23
          66.220.147.44

>nslookup twitch.tv 1.1.1.1
服务器:  one.one.one.one
Address:  1.1.1.1

非权威应答:
名称:    twitch.tv
Addresses:  208.101.60.87
          64.13.232.149

>nslookup -vc twitch.tv 1.1.1.1
服务器:  one.one.one.one
Address:  1.1.1.1

*** one.one.one.one 找不到 twitch.tv: Unspecified error
```

**Comment by zhangqq008** [comment]
only "twtich.tv" been added in pac couldn't make this site's video flow use in proxy
other adddress suffix should add in for watch live streaming
Log display when the streaming transmission by proxy：connect to video-weaver.dfw02.hls.ttvnw.net:443

**Comment by cicku** [comment]
@zhangqq008 You're right, but I wasn't wrong because this issue is only related to main domain.

For other domains, I will add them soon, most of them covered in wiki and I will update the wiki as well.
