### ISSUE TITLE
请全面兼容https

### ISSUE THREAD

**Issue by ivysrono** [gfwlist/gfwlist#1249]
搜了下，7700+条规则中有 http:// 的大约有 500 条。
其中很多都支持，甚至是默认支持https了。
仅以白名单为例：
@@|http://translate.google.cn
@@|http://www.google.cn/maps
这两条都失效了，因为Google默认启用了https。
麻烦全面清理下，最简单粗暴的办法就是加一条对应的 https 规则。

**Comment by cicku** [comment]
Google configuration does support both.
