### ISSUE TITLE
这些网址麻烦家入。

### ISSUE THREAD

**Issue by hhof90** [gfwlist/gfwlist#125]
http://www.glass8.eu
*.cloudfront.net
http://cn.nytimes.com
https://autoproxy.org
*.gravatar.com
www.vultr.com
my.vultr.com
xuqk.tk
http://google.org
https://www.digitalocean.com
*.googleusercontent.com

**Comment by cicku** [comment]
部分已经存在于列表中，部分无法添加

**Comment by cicku** [comment]
#123
