### ISSUE TITLE
only "twtich.tv" been added in pac couldn't make this site's video flow use in proxy

### ISSUE THREAD

**Issue by zhangqq008** [gfwlist/gfwlist#1250]
other adddress suffix should add in for watch live streaming
Log display when the streaming transmission by proxy：connect to video-weaver.dfw02.hls.ttvnw.net:443

_Originally posted by @zhangqq008 in https://github.com/gfwlist/gfwlist/issues/1242#issuecomment-423928337_

**Comment by sczhg** [comment]
The following patterns work (at least for me)
```
||jtvnw.net
||twitchcdn.net
||ttvnw.net
||twitch.tv
```
