### ISSUE TITLE
www.v2ray.com

### ISSUE THREAD

**Issue by Albert9364** [gfwlist/gfwlist#1275]
You know!
Please!
Thank you very much!!

**Comment by cicku** [comment]
Are you sure the HTTPS version having connection issues?

My observation is HTTPS is not affected.

**Comment by Albert9364** [comment]
> Are you sure the HTTPS version having connection issues?
> 
> My observation is HTTPS is not affected.

I can't connect to websites in HTTPS in mainland China unless I use VPS.
