### ISSUE TITLE
bwh1.net is blocked

### ISSUE THREAD

**Issue by 1779729350** [gfwlist/gfwlist#1277]
![default](https://user-images.githubusercontent.com/22658616/47080691-44902180-d23b-11e8-894f-8d192dab41a3.png)
测试时广东仅移动能够访问

**Comment by catscarlet** [comment]
DNS cache pollution confirmed with Beijing Unicom.

**Comment by kozora** [comment]
![20181103195655.png](https://i.loli.net/2018/11/03/5bdd8d1958143.png)
