### ISSUE TITLE
台湾动漫网站 動画瘋 需要全局代理才能播放视频

### ISSUE THREAD

**Issue by ZYZ665** [gfwlist/gfwlist#1282]
動画瘋网站
https://ani.gamer.com.tw/
这种视频
https://ani.gamer.com.tw/animeVideo.php?sn=7294#
需要全局台湾代理才能正常播放
请加入gfwlist，谢谢！

**Comment by MoeKing** [comment]
1、巴哈姆特本來就在列表裡
![](https://i.loli.net/2018/10/23/5bce0729c30e7.png)
2、看不了是CDN不在列表裡 自己加一行
`||gamer*-cds.cdn.hinet.net`
![](https://i.loli.net/2018/10/23/5bce07325de6e.png)

**Comment by ZYZ665** [comment]
> 1、巴哈姆特本來就在列表裡
> ![](https://camo.githubusercontent.com/a443a0c89acba5eb9eb589520085a65c50d3fd0c/68747470733a2f2f692e6c6f6c692e6e65742f323031382f31302f32332f356263653037323963333065372e706e67)
> 2、看不了是CDN不在列表裡 自己加一行
> `||gamer*-cds.cdn.hinet.net`
> ![](https://camo.githubusercontent.com/e1dd6e82ca1870163ce33253030c6afa0d64f7fa/68747470733a2f2f692e6c6f6c692e6e65742f323031382f31302f32332f356263653037333235646536652e706e67)

嗯pac里加上就好了，谢谢

**Comment by cicku** [comment]
Duplicate of #1311
