### ISSUE TITLE
请去掉规则@@||storage.googleapis.com

### ISSUE THREAD

**Issue by cop007** [gfwlist/gfwlist#1283]
请去掉规则@@||storage.googleapis.com
成都电信只能设置全局代理或者手动删除规则才能正常访问，感谢！

 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by ZeddG93** [comment]
这两个域名大多数地方都能访问，比如通过17ce.com来测试。如果你不能访问建议检查一下DNS，正确的解析应该是解析到上海谷翔的IP地址。

**Comment by ZeddG93** [comment]
```zsh
~
❯ dig ssl.gstatic.com

; <<>> DiG 9.11.3-1ubuntu1.2-Ubuntu <<>> ssl.gstatic.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 2453
;; flags: qr rd ra; QUERY: 1, ANSWER: 8, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;ssl.gstatic.com.               IN      A

;; ANSWER SECTION:
ssl.gstatic.com.        81      IN      A       203.208.41.183
ssl.gstatic.com.        81      IN      A       203.208.41.175
ssl.gstatic.com.        81      IN      A       203.208.41.191
ssl.gstatic.com.        81      IN      A       203.208.41.184
ssl.gstatic.com.        81      IN      A       203.208.41.184
ssl.gstatic.com.        81      IN      A       203.208.41.191
ssl.gstatic.com.        81      IN      A       203.208.41.175
ssl.gstatic.com.        81      IN      A       203.208.41.183

;; Query time: 141 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Tue Oct 30 09:09:57 DST 2018
;; MSG SIZE  rcvd: 292


~
❯ geoip 203.208.41.183
["中国","上海","上海","","电信"]

```

**Comment by cop007** [comment]
> ```shell
> ~
> ❯ dig ssl.gstatic.com
> 
> ; <<>> DiG 9.11.3-1ubuntu1.2-Ubuntu <<>> ssl.gstatic.com
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 2453
> ;; flags: qr rd ra; QUERY: 1, ANSWER: 8, AUTHORITY: 0, ADDITIONAL: 1
> 
> ;; OPT PSEUDOSECTION:
> ; EDNS: version: 0, flags:; udp: 512
> ;; QUESTION SECTION:
> ;ssl.gstatic.com.               IN      A
> 
> ;; ANSWER SECTION:
> ssl.gstatic.com.        81      IN      A       203.208.41.183
> ssl.gstatic.com.        81      IN      A       203.208.41.175
> ssl.gstatic.com.        81      IN      A       203.208.41.191
> ssl.gstatic.com.        81      IN      A       203.208.41.184
> ssl.gstatic.com.        81      IN      A       203.208.41.184
> ssl.gstatic.com.        81      IN      A       203.208.41.191
> ssl.gstatic.com.        81      IN      A       203.208.41.175
> ssl.gstatic.com.        81      IN      A       203.208.41.183
> 
> ;; Query time: 141 msec
> ;; SERVER: 127.0.0.1#53(127.0.0.1)
> ;; WHEN: Tue Oct 30 09:09:57 DST 2018
> ;; MSG SIZE  rcvd: 292
> 
> 
> ~
> ❯ geoip 203.208.41.183
> ["中国","上海","上海","","电信"]
> ```

抱歉没有及时回复，我这边更换了114的公共DNS以后ssl.gstatic.com确实可以被解析到上海谷翔了，但是storage.googleapis.com这个我换了好多个DNS解析出来的IP都是掉包严重，可能是我这边电信网络环境的问题了，非常感谢您前面给的建议！
