### ISSUE TITLE
apkpure安卓客户端无法打开

### ISSUE THREAD

**Issue by LittleGrocery** [gfwlist/gfwlist#1286]
随着apkpure客户端也被墙，原来的apkpure规则远远不足以支持打开apkpure，导致打开apkpure时会卡在第一屏，一但使用全局模式秒进，可能是软件在于服务器通信时某些域名未被添加进list中

**Comment by mraandtux** [comment]
参见 googlehosts/hosts#264

**Comment by malagebidi** [comment]
请把api.pureapk.com添加一下，或者pureapk.com整个域名
