### ISSUE TITLE
欧洲新闻台获G发课W认证

### ISSUE THREAD

**Issue by mraandtux** [gfwlist/gfwlist#1289]
域名： www.euronews.com
DNS查询结果：解出DNS污染专用IP (69.171.244.15)
测试ISP：广东有线U宽频（联通）
参考Greatfire的测试结果：
https://zh.greatfire.org/www.euronews.com
https://zh.greatfire.org/https/www.euronews.com

**Comment by cicku** [comment]
非常抱歉这个 Issue 拖了这么久，已经添加。
