### ISSUE TITLE
In the file gfwlist.txt, the home page need to be modified to https://github.com/gfwlist/gfwlist

### ISSUE THREAD

**Issue by GangZhuo** [gfwlist/gfwlist#13]
see below:

    [AutoProxy 0.2.9]
    ! Checksum: qzHpPMliVD4RmeSQ7PPeiQ
    ! Expires: 6h
    ! Last Modified: Tue, 08 Sep 2015 21:29:11 +0800
    ! HomePage: https://autoproxy-gfwlist.googlecode.com/

**Comment by cicku** [comment]
Yes, I've planned to bump reformat the header of GFWList. But this will be accomplished after the final shutdown of Google Code.

**Comment by cicku** [comment]
Done.
