### ISSUE TITLE
www.getmdl.io被墙，建议加入gfwlist

### ISSUE THREAD

**Issue by Acris** [gfwlist/gfwlist#130]

**Comment by cicku** [comment]
无法确认，请提供  DNS 及 ISP 信息。

**Comment by nxtreaming** [comment]
没有被墙.

**Comment by Acris** [comment]
发现该域名已经在gfwlist里面了，之前没仔细看，抱歉。

**Comment by cicku** [comment]
今天手滑了，这个域名没有被墙，我还是加进去了。

明天我会移除...

**Comment by Acris** [comment]
@cicku 我用http://ping.chinaz.com/和http://www.ipip.net/ping.php分别测试了一下,全国范围几乎98%以上都是超时.

**Comment by cicku** [comment]
@Acris 不，我测试的时候都是可以正常访问的，你说的网站我测试了都可以 ping 通。还有我自己访问测试，中国联通正常，中国电信就不行，教育网也是正常的。

继续跟踪。

**Comment by Acris** [comment]
嗯，那可能是部分被墙了

**Comment by cicku** [comment]
嗯，经测试应该是基本被墙了，我先放列表里面吧。
