### ISSUE TITLE
edge.avangate.net

### ISSUE THREAD

**Issue by vibbow** [gfwlist/gfwlist#1306]
edge.avangate.net is been DNS cache poisoning
![photo_2018-11-08_18-22-49](https://user-images.githubusercontent.com/6408107/48192661-5e78dc00-e383-11e8-94e2-d840c051a0e2.jpg)

**Comment by yeogo** [comment]
你的来信已收到，谢谢！

**Comment by cicku** [comment]
@yeogo 您哪位？
