### ISSUE TITLE
南早又被认证了

### ISSUE THREAD

**Issue by mraandtux** [gfwlist/gfwlist#1308]
域名： www.scmp.com
DNS查询结果：解出DNS污染专用IP (67.228.221.221) ，新的污染IP？
测试ISP：广东有线U宽频（联通）
https://zh.greatfire.org/https/www.scmp.com
https://zh.greatfire.org/www.scmp.com
老马无语，明明9月份都能上的，现在却被SNI重置······

**Comment by yichangshengwu** [comment]
原来相关的条目有3个，看来需要改改了喵

**Comment by cicku** [comment]
I'm not quite sure about cases like this, one possible factor is G20 summit.

Revising as ERRATA.
