### ISSUE TITLE
Please add 'softs.wtf'.

### ISSUE THREAD

**Issue by Sam0230** [gfwlist/gfwlist#1323]
Please add 'softs.wtf'. We can not access it in mainland China.

**Comment by zao123h** [comment]
I just prepared to submit and found that someone has submitted it, I hope the author will update as soon as possible.

**Comment by cicku** [comment]
Duplicate of #1262

**Comment by cicku** [comment]
I cannot access this domain, would you please tell me how to access it? Is it now `wget.shop`?
