### ISSUE TITLE
thenation.com and economist.com

### ISSUE THREAD

**Issue by Yu4n** [gfwlist/gfwlist#1326]
Both can be pinged but not accessed.

**Comment by paperbag** [comment]
`economist.com`：https://github.com/gfwlist/gfwlist/issues/200#issuecomment-208665117
`thenation.com` ：https://github.com/gfwlist/gfwlist/issues/489#issuecomment-278566747 （but not in the list）

**Comment by cicku** [comment]
Duplicate of #489
