### ISSUE TITLE
Can not use Siri when using it on macOS

### ISSUE THREAD

**Issue by sayomelu** [gfwlist/gfwlist#1334]
Siri will loads
<img width="380" alt="screen shot 2018-11-24 at 12 53 07" src="https://user-images.githubusercontent.com/16492117/48964674-e566bf00-efe7-11e8-8851-002e22309600.png">

And shows
<img width="382" alt="screen shot 2018-11-24 at 12 53 37" src="https://user-images.githubusercontent.com/16492117/48964681-016a6080-efe8-11e8-8b9f-54a4f2e0db63.png">

**Comment by sayomelu** [comment]
Siri also can not work on Global Mode

**Comment by cicku** [comment]
Have you checked the internet?

**Comment by sayomelu** [comment]
> Have you checked the internet?
I can visit YouTube, but Siri won't work on Global mode

**Comment by Ghostish** [comment]
I have the same problem.

**Comment by chuxubank** [comment]
add to PAC rules Credit: https://github.com/shadowsocks/ShadowsocksX-NG/issues/950#issuecomment-517165861
```
if ( (shExpMatch(url, "*guzzoni.apple.com*")) || (shExpMatch(url, "*.guzzoni-apple.com.akadns.net*")) ) return "DIRECT";
```

or bypass this domains Credit: https://github.com/Cenmrev/V2RayX/issues/153#issuecomment-425592834
```
127.0.0.1,192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,100.64.0.0/10,17.0.0.0/8,localhost,*.local,*.crashlytics.com
```
