### ISSUE TITLE
.googleplex.com域名

### ISSUE THREAD

**Issue by kongy** [gfwlist/gfwlist#134]
无法直接访问，比如https://moma.googleplex.com/

**Comment by cicku** [comment]
访问正常，请检查您的 DNS 设置。

**Comment by cicku** [comment]
如果您的 DNS 设置正确，应该会跳转到 corp.google.com。

但是需要登录，请问登录后是跳转回 googleplex 吗？

**Comment by cicku** [comment]
您是否还有疑问？
