### ISSUE TITLE
cachefly.net

### ISSUE THREAD

**Issue by SadPencil** [gfwlist/gfwlist#135]
联通，无法访问cachefly.net

**Comment by cicku** [comment]
您好，请问您是直接访问失败还是访问页面资源时遇到问题？

**Comment by SadPencil** [comment]
DNS 查找失败，因此找不到 cachefly.net 的服务器

**Comment by SadPencil** [comment]
目前使用的DNS：114.114.114.114
这个网站打不开，直接导致没法访问codeproject.com这种使用了他们CDN的网站

**Comment by cicku** [comment]
请使用未受干扰的 DNS 访问（可能会牺牲用户体验）。
