### ISSUE TITLE
请求补充逗比根据地 新站名(原doub.io已弃用)

### ISSUE THREAD

**Issue by kannad** [gfwlist/gfwlist#1376]
**URL**:https://doubmirror.cf/
**原地址**: doub.io
**原因**:站长因个人原因放弃更新，新的镜像站需要GFW收录
站点是一个用于安装各种一键SSR、SS已经一些其他协议的工具的站点

**Comment by kannad** [comment]
测试地址：南部移动
服务器:  MI-R3G.lan
Address:  192.168.123.1

*** MI-R3G.lan 找不到 https://doubmirror.cf/: Non-existent domain

**Comment by MoeKing** [comment]
https://github.com/gfwlist/gfwlist/issues/1346

**Comment by cicku** [comment]
Duplicate of #1346
