### ISSUE TITLE
Please add pincong.rocks, thanks

### ISSUE THREAD

**Issue by OrekiDawson** [gfwlist/gfwlist#1391]
hello, 
I just discovered a new site behind gfw, it's called "New Pincong", the domain name is pincong.rocks . but it isn't on the gfwlist. so can you add it, please? thanks a lot.
yours, sincerely
Jan 18, 2019

**Comment by SJTUboy** [comment]
++

**Comment by SJTUboy** [comment]
vpnmentor.com
