### ISSUE TITLE
please add "cn.bing.com"

### ISSUE THREAD

**Issue by PragmaTwice** [gfwlist/gfwlist#1398]
Observable in many places of mainland China:
```
λ nslookup cn.bing.com
...

Non-authoritative answer:
Name:    cn.bing.com
Address:  127.0.0.1
```

Discussion on v2ex : https://www.v2ex.com/t/529895

**Comment by Coxxs** [comment]
**Related News:** 

The Verge: [Microsoft’s Bing search engine reportedly blocked in China](https://www.theverge.com/2019/1/23/18195200/microsoft-bing-search-engine-blocked-in-china-internet-censorship)

CNN: [Microsoft search engine Bing is blocked in China](https://edition.cnn.com/2019/01/23/tech/bing-microsoft-china/index.html)

The New York Times: [China Appears to Block Microsoft’s Bing, Despite Company’s Own Censorship](https://www.nytimes.com/2019/01/23/business/china-microsoft-bing.html)

**Comment by LyleLaii** [comment]
Please add 'bing.com'

**Comment by mraandtux** [comment]
广东有线U宽频所使用的DNS服务器没问题（参见 googlehosts/hosts#298 ），联通广东如1楼。
暂时别添，再观望几天。

**Comment by ithou** [comment]
```shell
$ nslookup cn.bing.com
Server:		183.60.83.19
Address:	183.60.83.19#53

Non-authoritative answer:
cn.bing.com	canonical name = cn-bing-com.cn.a-0001.a-msedge.net.
cn-bing-com.cn.a-0001.a-msedge.net	canonical name = cn.cn-0001.cn-msedge.net.
cn.cn-0001.cn-msedge.net	canonical name = cn-0001.cn-msedge.net.
Name:	cn-0001.cn-msedge.net
Address: 202.89.233.100
Name:	cn-0001.cn-msedge.net
Address: 202.89.233.101

```

**Comment by lautis0503** [comment]
Please DO NOT add.
