### ISSUE TITLE
spring4u.info被墙

### ISSUE THREAD

**Issue by iyan611** [gfwlist/gfwlist#140]
望添加，谢谢

**Comment by cicku** [comment]
spring4u.info 早先已经已被加入，请更新您使用的 gfwlist

**Comment by iyan611** [comment]
最新列表并未找到此条目。
Last Modified: Thu, 18 Feb 2016 14:26:12 +0800

**Comment by cicku** [comment]
`.spring4u.info` 早已加入。

不过如果您以 `http://spring4u.info` 访问，依旧会被重置，因为主站规则尚未添加，主要愿意是没找到不带 `www` 的访问（尽管服务器允许），如果您平时以此地址访问，我将稍后加入。

**Comment by iyan611** [comment]
原来如此，确实是不带www访问的，因为该站早年间换网址时给的公告就是不带域名的，于是乎鉴于手打也方便就没养成加www的习惯。

**Comment by cicku** [comment]
好的，我将稍后处理。

**Comment by zpliang94** [comment]
用了vpn都不能访问
