### ISSUE TITLE
Shadowsocks最新版上的GFWList不能兼容firefox

### ISSUE THREAD

**Issue by renziyao** [gfwlist/gfwlist#141]
如何解决？？

**Comment by cicku** [comment]
抱歉，不太明白您说的是什么。

**Comment by renziyao** [comment]
@cicku 我的ss如果使用旧版的PAC文件，可以正常使用，使用新的PAC无法正常使用（firefox44.0.2，shadowsocks2.5.8）

**Comment by cicku** [comment]
能否告诉我旧版的修订日期？

**Comment by renziyao** [comment]
@cicku 抱歉，我不知道怎么查修订日期，我要不要把能用的PAC和不能用的PAC发给你？

**Comment by cicku** [comment]
请发送到我的邮箱吧，我个人资料页面有。

**Comment by renziyao** [comment]
已发送

**Comment by cicku** [comment]
等我抽空再分析一下吧，目测是和新添加的规则有关，但是我排查了几个有嫌疑比较大的规则后并不能解决问题。

建议您令 Firefox 使用系统代理设置暂时规避。

**Comment by renziyao** [comment]
好。我现在先用着旧的PAC

**Comment by 187j3x1** [comment]
ss生成的问题 我用[genpac](https://github.com/JinnLynn/genpac)一切正常

**Comment by kaidaning** [comment]
同样碰到这个问题。ff44，使用foxyproxy插件+ss，订阅这份list，订阅成功但是即使是全局模式也无法穿墙。用googlecode上的list就没问题

**Comment by cicku** [comment]
请联系 shadowsocks 相关人员解决。
