### ISSUE TITLE
Could you please add *.storage.googleapis.com *.atlassian.net *.openvpn.org *.packagecloud.io

### ISSUE THREAD

**Issue by duckzhouya** [gfwlist/gfwlist#1410]
Could you please add the links below?Thank you very much.
 *.storage.googleapis.com *.atlassian.net *.openvpn.org *.packagecloud.io

**Comment by wordlesswind** [comment]
I can access

storage.googleapis.com 
*.storage.googleapis.com
atlassian.net
*.atlassian.net
packagecloud.io
*.packagecloud.io

and *.openvpn.org is already on the list.

So what happened with you? What is your ISP?

**Comment by duckzhouya** [comment]
Sorry,I think it is my network problem.Thank you for your concern.
