### ISSUE TITLE
Please add "translate.google.cn"

### ISSUE THREAD

**Issue by mxdh** [gfwlist/gfwlist#1411]
I'm not sure it's blocked.
I can't connect it using the list.

**Comment by mxdh** [comment]
Please add "translate.googleapis.com",too.

**Comment by wordlesswind** [comment]
These domains have servers in China.
I can access them normally.
What is your ISP?

**Comment by mxdh** [comment]
China Mobile

**Comment by wordlesswind** [comment]
This is the behavior of China Mobile and has nothing to do with GFW.

So it is not suitable to submit to this list.

**Comment by mxdh** [comment]
Thank you very much.
