### ISSUE TITLE
please add gougoubt.org, thanks

### ISSUE THREAD

**Issue by tyszya** [gfwlist/gfwlist#1428]

**Comment by wordlesswind** [comment]
This seems to be because some public DNS has not updated the data?
I can access it with HOSTS. It has not been blocked by GFW.

**Comment by troutperch** [comment]
Please reopen, I can confirm it is blocked.
![2019-02-22_16-58](https://user-images.githubusercontent.com/47532693/53231323-a10cbd00-36c3-11e9-93c5-4aec0f5d7328.png)

**Comment by wordlesswind** [comment]
@troutperch Check your ISP, thanks :)
![1](https://user-images.githubusercontent.com/9050713/53245771-a4b33a80-36e9-11e9-9ccb-c27067c3690c.png)
