### ISSUE TITLE
谷歌搜索自动跳转bing

### ISSUE THREAD

**Issue by StephenAnboer** [gfwlist/gfwlist#1444]
我使用xx-net，配合switchyomega使用的时候，使用gae-proxy自动切换模式，规则列表网址https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt ，当规则列表格式为auto-proxy的时候，用谷歌搜索，会自动跳转到https://www.search323892.xyz/search/un/?n=50&q= ，然后跳转到bing搜索，不知道是为什么。。
（原本规则列表格式为switchy时没有问题，现在不知道为什么这个格式的时候也会跳转。。）

**Comment by wordlesswind** [comment]
你应该咨询 XX-Net ，而不是 gfwlist
