### ISSUE TITLE
https://www.seagate.com/cn/zh/ ERR_CONNECTION_ABORTED

### ISSUE THREAD

**Issue by xFelino** [gfwlist/gfwlist#1452]

**Comment by wordlesswind** [comment]
I can access it. What is your ISP.

**Comment by xFelino** [comment]
> I can access it. What is your ISP.

ChinaNet

**Comment by xFelino** [comment]
> I can access it. What is your ISP.

China Telecom Shanghai

**Comment by wordlesswind** [comment]
> > I can access it. What is your ISP.
> 
> China Telecom Shanghai

Can you try to change a DNS? E.g. [Ali Pubic DNS](http://www.alidns.com/)
