### ISSUE TITLE
reddit CDN server

### ISSUE THREAD

**Issue by dianlujitao** [gfwlist/gfwlist#1455]
Please add *.rlcdn.com which is used by reddit and (probably) other services.

**Comment by wordlesswind** [comment]
I can access https://cdn.rlcdn.com . What's your ISP?

**Comment by dianlujitao** [comment]
I can access https://cdn.rlcdn.com as well, but id.rlcdn.com seems to be blocked

**Comment by wordlesswind** [comment]
I also can access https://id.rlcdn.com .
There are some test results:
https://zh.greatfire.org/https/id.rlcdn.com
https://www.17ce.com/site/http/20190301_954b3a803c0111e99bd18105c7345e92:1.html
