### ISSUE TITLE
Malwarebytes

### ISSUE THREAD

**Issue by StrollStars** [gfwlist/gfwlist#146]
https://www.malwarebytes.org/

**Comment by StrollStars** [comment]
这个网站还是不能访问

**Comment by cicku** [comment]
您是否使用了受污染的 DNS？

**Comment by StrollStars** [comment]
使用114DNS

**Comment by cicku** [comment]
建议您切换为非大陆的公共 DNS 服务器 (e.g. 8.8.4.4 )。

**Comment by StrollStars** [comment]
nslookup解析结果是93.184.216.111，应该没有问题。
用谷歌家的，怕是直接被拦截然后返回假的或无效IP了。

**Comment by cicku** [comment]
您可尝试使用 DNSCrypt。

**Comment by StrollStars** [comment]
多谢提醒
