### ISSUE TITLE
share.dmhy.org

### ISSUE THREAD

**Issue by MoeKing** [gfwlist/gfwlist#1487]
![](https://i.loli.net/2019/03/25/5c98b7829fbea.png)
DNS Spoofing

**Comment by MoeKing** [comment]
发疯了功夫网 内站外站全挂

**Comment by MoeKing** [comment]
19:53更新
dl.dmhy.org

**Comment by chenshaoju** [comment]
Hunan telecom confirm `*.dmhy.org` has been DNS cache poisoning.

![image](https://user-images.githubusercontent.com/515763/55141394-4ad4e300-5175-11e9-8dbe-dd513dbdcb09.png)

**Comment by chengr28** [comment]
```
>nslookup dmhy.org 8.8.4.4
Server:  google-public-dns-b.google.com
Address:  8.8.4.4

Non-authoritative answer:
Name:    dmhy.org
Addresses:  31.13.77.55
          31.13.71.7
```

**Comment by MoeKing** [comment]
`Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>nslookup -q=aaaa u2.dmhy.org
服务器:  UnKnown
Address:  240e:ec:26b:8d00::1

非权威应答:
名称:    u2.dmhy.org
Addresses:  2606:4700:20::6819:1b1f
          2606:4700:20::6819:1a1f


C:\Users\Administrator>`
污染还只污染一半...

**Comment by reezhu** [comment]
share.dmhy.org
@@|https://share.dmhy.org
https现在也访问不了了，这条规则得改回
||share.dmhy.org
了吧

**Comment by aflyhorse** [comment]
https又好了，不过又被墙了……

**Comment by cicku** [comment]
即日起本列表不再移除相关域名。
