### ISSUE TITLE
請問這個list的維護者是誰？

### ISSUE THREAD

**Issue by zzzgit** [gfwlist/gfwlist#149]
請問這個list的維護者是誰？
「福」的作者不是消失了嗎？
這個list為什麼還會有official list一說？

**Comment by cicku** [comment]
现在是我，有什么问题吗？

福的作者“消失”了？请问您怎么定义“消失”？

这里就是 official list，autoproxy 的作者 @lovelywcm 也在 gfwlist 组织中，只不过身份是隐藏的，你们看不到而已，想看我可以给您截图。

我在 Google Code 的账户名为 cickumqt，您可以通过 http://archive.is 自行查看。
