### ISSUE TITLE
请移除cdn-apple.com

### ISSUE THREAD

**Issue by forever8938** [gfwlist/gfwlist#1496]
这个没有被墙，ios系统升级都要访问这个，强制走代理反而没速度

**Comment by wyf88** [comment]
+1
E.g. updates-http.cdn-apple.com，用于iOS系统升级，可以解析到国内IP

**Comment by chenzhuoyu** [comment]
@cicku 请问这个什么时候能够更新~

**Comment by cicku** [comment]
已更新。苹果现在和过去情况不一样，没有必要走代理了。

**Comment by PHCSJC** [comment]
原来更新慢是这个原因呢
