### ISSUE TITLE
这个项目 是干什么 用的？如何获取所有被墙的ip地址列表 ？

### ISSUE THREAD

**Issue by linuxsir008** [gfwlist/gfwlist#150]
我的目的是 获取所有被墙的ip地址列表。
在google上搜索才发现你的这个项目。
不过我没看懂你的项目，怎么使用？

**Comment by linuxsir008** [comment]
我的目的是 获取所有被墙的ip地址列表

**Comment by CNMan** [comment]
这个是域名列表，不是IP列表

**Comment by yfdyh000** [comment]
“所有”是做不到的。每时每刻各地都在发生变化。如何判断和辨别被墙与连不上。这里只是被墙域名的列表。自己写工具测试吧。

**Comment by linuxsir008** [comment]
被墙域名的列表 ？
我只看到 了一个文件 gfwlist.txt
这个文件中并不包含 被墙域名的列表 ？

**Comment by linuxsir008** [comment]
我应该如何使用这个项目？

**Comment by yfdyh000** [comment]
base64解码。

**Comment by linuxsir008** [comment]
slackware#base64 --decode gfwlist.txt > gfwlist
谢谢了
我建议应该 把这样的base64解码说明 加到readme中去。
可能我的建议是不必要的，但是对于菜鸟来说，还是有点需要的。

**Comment by linuxsir008** [comment]
如果我发现
有个 域名被墙了，gfwlist.txt中没有包含这个域名。
我可以添加这个域名到这个文件中去吗？
我应该 如何做？

**Comment by yfdyh000** [comment]
在这个项目开个新issue，等维护者验证和处理。
