### ISSUE TITLE
请添加 deviantart.com

### ISSUE THREAD

**Issue by Lowwwwww** [gfwlist/gfwlist#1501]
本来是不用翻墙就可以访问的，但最近就无法访问了，需要翻墙才行，极大可能被墙了，请添加

**Comment by liuweihang-2019** [comment]
DNS污染了，修改HOSTS可以

**Comment by LuoShuai218** [comment]
> DNS污染了，修改HOSTS可以

这可就不是DNS污染了…我正好是移动……
![2019-04-29 18-19-28 的屏幕截图](https://user-images.githubusercontent.com/44076275/56890228-78ca8180-6aab-11e9-9147-94c406d0b5b4.png)

**Comment by liuweihang-2019** [comment]
我知道，只能找污染处理专家了...:(

LuoShuai218 <notifications@github.com> 于2019年4月29日周一 下午6:22写道：

**Comment by liuweihang-2019** [comment]
> > DNS污染了，修改HOSTS可以
> 
> 这可就不是DNS污染了…我正好是移动……
> ![2019-04-29 18-19-28 的屏幕截图](https://user-images.githubusercontent.com/44076275/56890228-78ca8180-6aab-11e9-9147-94c406d0b5b4.png)

我也是移动

**Comment by iamapig120** [comment]
deviantart.com
deviantart.net
中国电信同样无法正常访问

**Comment by 2plus2equals4** [comment]
||.deviantart.com
中国联通，华北区，无法正常访问
