### ISSUE TITLE
将 1.1.1.1 从列表中移除

### ISSUE THREAD

**Issue by SadPencil** [gfwlist/gfwlist#1509]
1.1.1.1 在部分地区无法访问的原因与 GFW 无关，而是那些设备将此 IP 作为了内部 IP 导致的。此现象在全球均存在。随着 1.1.1.1 DNS 的流行，很多设备厂家修复了这个问题。
因此，无论 1.1.1.1 是否可访问，不应将其加入 gfwlist。

**Comment by cicku** [comment]
其实当初加入列表的时候我也是很怀疑的，因为我自己测试的结果明显偏向于服务器设置问题。
