### ISSUE TITLE
请求添加 233blog.com 和 233v2.com

### ISSUE THREAD

**Issue by 233boy** [gfwlist/gfwlist#1516]
请求添加：233v2.com，233blog.com，2333blog.com

域名均已被 DNS 方式污染，非常感谢。 😄

**Comment by XueTeng2** [comment]
呦，我正要反馈呢，发现大佬已经亲自来了。

**Comment by 233boy** [comment]
@XueTeng2 
哈哈…

**Comment by 233boy** [comment]
更新一下
再增加一个 233v2.com
谢谢 😂

**Comment by cocgenius** [comment]
> 请求添加：233v2.com，233blog.com，2333blog.com
> 
> 域名均已被DNS方式污染，非常感谢。 😄

大神。我看了你的V2RAY教学。。我还是没懂怎么弄，还有你的搬瓦工我理解的是 相当于之前国内的vpn对吗？现在ss不让上了。这个v2ray真的不明白啊。。感觉好复杂？能给私信我教教么。。emmmm 邮件地址

**Comment by 233boy** [comment]
> > 请求添加：233v2.com，233blog.com，2333blog.com
> > 域名均已被DNS方式污染，非常感谢。 😄
> 
> 大神。我看了你的V2RAY教学。。我还是没懂怎么弄，还有你的搬瓦工我理解的是 相当于之前国内的vpn对吗？现在ss不让上了。这个v2ray真的不明白啊。。感觉好复杂？能给私信我教教么。。emmmm 邮件地址

你按照这个 [教程](https://github.com/233boy/v2ray/wiki/V2Ray%E6%90%AD%E5%BB%BA%E8%AF%A6%E7%BB%86%E5%9B%BE%E6%96%87%E6%95%99%E7%A8%8B) 认真多看几遍，肯定能理解的。搭建什么的都超级简单的其实。
