### ISSUE TITLE
请求添加*.gstatic.com，访问一些网址时会导致部分资源无法加载。

### ISSUE THREAD

**Issue by ladyrick** [gfwlist/gfwlist#1522]
比如访问http://playground.tensorflow.org
会出现一些字体文件无法加载。

**Comment by TaskForce86** [comment]
同样问题,之前dns 1.1.1.1,8.8.8.8 改成阿里云的223.5.5.5和223.6.6.6就好了,仅作参考

**Comment by BoWuGit** [comment]
这个我觉得还是要加一下，很多网站会用，Google 登录页 *.gstatic.com 不代理都连不上。

**Comment by imba-tjd** [comment]
@BoWuGit 你说的“Google登录页”指的是 `https://accounts.google.com/ServiceLogin` 吗？这个页面只会用 `fonts.gstatic.com` 和 `ssl.gstatic.com`。

http://ping.chinaz.com/fonts.gstatic.com
http://ping.chinaz.com/ssl.gstatic.com

怎么连不上了？

**Comment by BoWuGit** [comment]
这个东西时好时不好吧，我前两天用的时候半天都连不上，仔细看了下，才发现是这个问题，一般的非技术用户如果碰上了就只能被挡住了。本来想提 issue 的，发现已经有人提了。

wordpress 就有个插件[Self-Hosted Google Fonts](https://www.williamlong.info/archives/5523.html)

> 默认加载Google Font，导致中国用户访问“变慢”，因此安装Self-Hosted Google Fonts插件后，可以提升中国用户访问速度

**Comment by jessicapd2020** [comment]
我也遇到这个问题，有啥解决办法？
