### ISSUE TITLE
Speedtest.net

### ISSUE THREAD

**Issue by ljl024** [gfwlist/gfwlist#153]
- http://www.speedtest.net
- http://beta.speedtest.net
- http://speedtest.net

无响应
浙江电信
#### 提醒
- c.speedtest.net
- zdstatic.speedtest.net

等域名**访问正常**

#### 潜在问题
包含
- http://www.speedtest.net
- http://beta.speedtest.net

将导致该网站解析的用户IP为代理IP，测速时需要手工选择server

**Comment by cicku** [comment]
访问正常，请检查您的ISP设置

**Comment by ljl024** [comment]
> www.speedtest.net
服务器:  hangzhou.zjhzptt.net.cn
Address:  202.101.172.35

非权威应答:
名称:    cs62.adn.xicdn.net
Address:  110.232.178.82
Aliases:  www.speedtest.net

这个IP我这边ping不通
用chinaz的全国ping发现只有浙江电信ping不通
我联系下电信客服试试
