### ISSUE TITLE
en.wikipedia.org 也被 DNS 污染了

### ISSUE THREAD

**Issue by NimaQu** [gfwlist/gfwlist#1530]
![img](https://i.loli.net/2019/04/23/5cbf2be45291d.png)

**Comment by troutperch** [comment]
你来迟了：https://github.com/gfwlist/gfwlist/issues/1528

**Comment by Prcuvu** [comment]
不光是 DNS 污染，我通过 DNS-over-HTTPS 得到的 IP 进行连接，被重置。

**Comment by chemharuka** [comment]
恭喜wiki全站加入gfwlist豪华套餐（

**Comment by 0kaguya** [comment]
it is fixed now? now I added an additional rule for Wikipedia.

**Comment by b-z** [comment]
快更新啊= =

**Comment by cicku** [comment]
Duplicate pf #1528
