### ISSUE TITLE
请移除api.ai或者强化规则

### ISSUE THREAD

**Issue by felixhao28** [gfwlist/gfwlist#1531]
我们公司是www.aixcoder.com，我们的部分用户反映我们的服务延迟很大，经调查，发现是我们的API端口 https://api.aixcoder.com/ 匹配了用户电脑上的gfwlist里面的"api.ai"规则，从而走了代理。

目前 https://api.ai 自动跳转到https://dialogflow.com/ ，刚才在北京联通网络环境下测试可以两个域名均可直接连接。故申请加强匹配规则比如修改"||api.ai"为“||api.ai/”或移除此规则。谢谢。

**Comment by troutperch** [comment]
> 目前 https://api.ai 自动跳转到https://dialogflow.com/ ，刚才在北京联通网络环境下测试可以两个域名均可直接连接。故申请加强匹配规则比如修改"||api.ai"为“||api.ai/”或移除此规则。谢谢。

首先，api.ai 解析到谷歌服务器的 IP 地址（172.217.6.78），因此并不能像你所声称的那样可以直接访问，你应该是已经使用代理访问过 api.ai，而浏览器记住了它的 301 永久重定向响应：
```
$ dig api.ai @8.8.8.8

; <<>> DiG 9.10.3-P4-Debian <<>> api.ai @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 6692
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;api.ai.				IN	A

;; ANSWER SECTION:
api.ai.			299	IN	A	172.217.6.78

;; Query time: 318 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Thu Apr 25 14:19:58 CST 2019
;; MSG SIZE  rcvd: 51
```

其次，根据 Adblock Plus filters 官方的规则写法解释，`||api.ai` 并没有什么问题，因此这不是 gfwlist.txt 的问题，请去你客户使用的相关规则工具报 bug。

**Comment by felixhao28** [comment]
言之有理，但 api.ai 的规则匹配到了 api.aixcoder.com 怎么想都不是当初加入 api.ai 规则时所期望的行为。这还是一个bug。

**Comment by troutperch** [comment]
> 但 api.ai 的规则匹配到了 api.aixcoder.com 怎么想都不是当初加入 api.ai 规则时所期望的行为。这还是一个bug。

这是相关工具实现的问题，在我的 uBlock origin 里，`||www.baidu` 不会匹配到 `https://www.baidu.com/img/bd_logo1.png`，而另一些工具可能会匹配到。你可能没看到我编辑后的链接，它已经明确说明前者是没有问题的：https://github.com/gfwlist/gfwlist/wiki/Syntax

**Comment by felixhao28** [comment]
好的，那我把问题汇报到shadowsocks那边
