### ISSUE TITLE
http://www.BBC.com/zhongwen/

### ISSUE THREAD

**Issue by gongjianhui** [gfwlist/gfwlist#154]
e.g. http://www.bbc.com/zhongwen/simp/hong_kong_review/2016/02/160223_hkreview_chinese_characters

浙江移动 Chrome： ERR_EMPTY_RESPONSE
GreatFire Analyzer： 屏蔽

浙江移动 www.bbc.com 使用 119.29.29.29 解析，解析到了 Fastly。

**Comment by gongjianhui** [comment]
浙江移动 curl www.bbc.com/zhongwen/ RST

**Comment by cicku** [comment]
您好，gfwlist 早已包含 BBC 规则，并且测试通过未发现异常，请问您是否更新到了最新的 gfwlist？

**Comment by gongjianhui** [comment]
有关其他 BBC 网站，
我在 GFWList base 64 解码后 512-519 行找到了
`.bbc.co.uk*chinese
.bbc.co.uk/tv
.bbc.co*zhongwen
news.bbc.co.uk/onthisday*newsid_2496000/2496277
newsforums.bbc.co.uk
.bbcchinese.com
||bbcchinese.com
|http://bbc.in`

并没有搜索到 bbc.com 相关结果。

**Comment by gongjianhui** [comment]
我使用 Surge for Mac 客户端，配置文件由 https://github.com/R0uter/ss.conf-for-surge 生成，
 .bbc.co*zhongwen 由该工具生成后结果为 DOMAIN-SUFFIX,bbc.co,Proxy，所以应该是该 repo 对该特性的兼容问题。
