### ISSUE TITLE
历史条目有定期筛查么？

### ISSUE THREAD

**Issue by yichangshengwu** [gfwlist/gfwlist#1562]
闲着没事挨条看，
发现一些站貌似是清空了，
项目对这些有定期筛查么？
看Issue列表满屏都是求添加呀。。。

ps：我是查看了站点的历史页面后，发现一些很长时间之前就出现异常了的站点

**Comment by cicku** [comment]
很少，一般来讲添加进列表之后，如果不是主动上报失效，基本上是不会动的。

过去受到 GFW 关照的网站，即使网站倒了，大部分情况 GFW 的规则也是不动的，尤其是政治敏感类的。

**Comment by cicku** [comment]
Duplicate of #290
