### ISSUE TITLE
Plz add this one

### ISSUE THREAD

**Issue by steveoOn** [gfwlist/gfwlist#158]
Plz guys add this address below:

https://www.dropboxatwork.com/

**Comment by cicku** [comment]
Hi,

If you set up your DNS correctly, you will be redirected to dropbox.com.

Please check your DNS.

**Comment by steveoOn** [comment]
Thx for check the item bro. but what do u mean "correct DNS" which my is 192.168.0.x(seems like local address?)

**Comment by cicku** [comment]
You need to take a look at WAN port settings and seek if there is any ISP specific DNS address.
