### ISSUE TITLE
kubernetes的很多默认访问都是谷歌的域名

### ISSUE THREAD

**Issue by vperson** [gfwlist/gfwlist#1585]
@kubernetes的很多默认访问都是谷歌的域名，发现很多域名PAC中貌似没有加入，比如这个https://storage.googleapis.com，一定要开全局才行

**Comment by imba-tjd** [comment]
https://github.com/gfwlist/gfwlist/issues/1283

**Comment by cicku** [comment]
Duplicate of #1283
