### ISSUE TITLE
idm, 7-zip, archive.apache, foobar2000, xnview, rarlab

### ISSUE THREAD

**Issue by imba-tjd** [gfwlist/gfwlist#1590]
* ~~www.internetdownloadmanager.com~~ ; 但 internetdownloadmanager.com 可以访问，未测试其它
* ~~www.7-zip.org~~
* archive.apache.org ; 但 apache.org 和 www.apache.org 可以访问
* ~~www.foobar2000.org~~
* ~~www.xnview.com~~
* ~~www.rarlab.com~~

猜测是IP Blocking.

所以现在就只剩下一个 archive.apache.org 了:joy:

**Comment by mraandtux** [comment]
GFuckW想疯了是不？附GreatFire测试结果（站长中国的Ping结果不贴了，反正都是超时）：
https://zh.greatfire.org/www.7-zip.org
https://zh.greatfire.org/www.xnview.com
#ThisWillNotGonnaEndWell

**Comment by mraandtux** [comment]
附WinRar官网的GreatFire测试结果，我猜2345系、360系或其他本地软件或成最大赢家（AIMP：？）
https://zh.greatfire.org/www.rarlab.com

**Comment by imba-tjd** [comment]
看起来archive.apache.org和其它的不一样，其它的应该都解了。我单开一个吧

**Comment by cicku** [comment]
敏感时期请直接全局 🤣
