### ISSUE TITLE
Add this 2

### ISSUE THREAD

**Issue by duguying** [gfwlist/gfwlist#160]
please add this two domain, `githubusercontent.com` and `assets-cdn.github.com`. thanks.

**Comment by cicku** [comment]
Hi,

Please give me the reason of adding these 2 into the list.

Thanks.

**Comment by duguying** [comment]
this two site intermittent blocked by GFW in China Telecom

**Comment by cicku** [comment]
Hi,

Currently it's not possible for gfwlist to include them since they are not completely blocked. Please add them into user rules.

Thanks.
