### ISSUE TITLE
add api.trakt.tv

### ISSUE THREAD

**Issue by austin-chang** [gfwlist/gfwlist#1604]
api.trakt.tv

**Comment by VaslD** [comment]
Trakt.tv 相关网站没有被墙，它是 Cloudflare CDN 的网站。Cloudflare 好像在国内统一是百度负责 CDN，每次访问都需要输验证码；所以 API 请求会过不去。

这类网站加入 GFWList 会让百度 CDN 失效，的确没有了验证码，但 CDN 服务器也不一样了。

**Comment by austin-chang** [comment]
嗯，後來發現了，忘了關issue
