### ISSUE TITLE
是否有将gfwlist部署到代理服务器上的方案？

### ISSUE THREAD

**Issue by siaimes** [gfwlist/gfwlist#1607]
如果代理服务器有多人同时使用，那么维护者无法保证用户不使用代理服务器访问国内网站，从而导致服务器暴露。如果可以将gfwlist部署在服务器端即可解决这个问题，最好是配置防火墙，即在gfwlist列表中的域名allow，不在gfwlist中的域名reject。当然，这样还会存在另一个问题，有的网站没有被墙，但是速度慢，用户也需要代理的怎么办，也许可以留一个接口给管理员添加特定的网站？不知道有没有人有实现这个方案？

**Comment by tomac4t** [comment]
> 这个项目是为其他工具提供可在线更新的规则的。不直接提供解决方案。

**Comment by siaimes** [comment]
@tomac4t 
> > 这个项目是为其他工具提供可在线更新的规则的。不直接提供解决方案。

我知道gfwlist只是提供一个列表，所以来这里问问大家有没有人实现了这个方案呢！

**Comment by forever8938** [comment]
防火墙怎么得到域名？

**Comment by siaimes** [comment]
> 防火墙怎么得到域名？

所以需要有人写脚本之类的，先nslookup一下，然后写到防火墙里面！

**Comment by forever8938** [comment]
> > 防火墙怎么得到域名？
> 
> 所以需要有人写脚本之类的，先nslookup一下，然后写到防火墙里面！

人才啊

**Comment by haohaoh4** [comment]
提供一个本地方案URenko/Accesser/

**Comment by cicku** [comment]
不是很清楚这方面的应用，不清楚大陆现在是什么情况。很多鸡场场长都有这样的顾虑，但是无论怎么做，鸡场永远无法避开被暴露的这个问题。

所以最简单的办法就是场长不在国内，且协议条款加上一条：“使用本服务造成的一切后果由您个人承担”。（这真不是笑话）
