### ISSUE TITLE
Please add 'gateway.reddit.com'

### ISSUE THREAD

**Issue by eesa** [gfwlist/gfwlist#1619]
To show the comments on reddit.
Thx!

**Comment by tomac4t** [comment]
Existed: `||reddit.com`

**Comment by eesa** [comment]
But the comments didn't show until manually adding 'gateway.reddit.com' into gfwlist.

**Comment by tomac4t** [comment]
`||reddit.com` is cover all subdomain, see https://github.com/gfwlist/gfwlist/wiki/Syntax.

**Comment by cicku** [comment]
Duplicate of #1173
