### ISSUE TITLE
Please add "windy.com"

### ISSUE THREAD

**Issue by CSharperMantle** [gfwlist/gfwlist#1626]
As I have tested recently, windy.com can't be visited in China and it's not included in GFWList. Adding it to GFWList would be appreciated.

**Comment by tomac4t** [comment]
https://github.com/gfwlist/gfwlist/issues/1424

**Comment by CSharperMantle** [comment]
> #1424, and `www.windy.com` is not blocked.

Thank you for your reply. Sorry for my carelessness.

**Comment by cicku** [comment]
Duplicate of #1424
