### ISSUE TITLE
ETToday新闻云获得认证

### ISSUE THREAD

**Issue by mraandtux** [gfwlist/gfwlist#1650]
ISP：广东有线U宽频，直连被DNS污染，DoH和改h0575是SNI重置，GreatFire的结果也一样：
https://zh.greatfire.org/https/www.ettoday.net
同属三木系的东森财经也认证了：
https://zh.greatfire.org/https/fnc.ebc.net.tw
#三木也不够红#

**Comment by P-256** [comment]
旺旺系的中时电子报倒是解封了，三木系之前被封还抓不到把柄，这下黄世聪在关键时刻里边说中国人吃不起榨菜，我看三木系全都很危险。

**Comment by mraandtux** [comment]
看了一下GreatFire测试结果，发现ETToday新闻云已于上星期解除认证并得到组织肯定了，封贴。
