### ISSUE TITLE
news.ycombinator.com, oxfordscholarship.com etc.

### ISSUE THREAD

**Issue by tomac4t** [gfwlist/gfwlist#1662]
- [x] news.ycombinator.com `DNS poisoning`
- [x] mastodon.xyz `DNS poisoning`
- [x] oxfordscholarship.com `DNS poisoning`
- [x] www.firstpost.com `Geoblocking`

**Comment by tomac4t** [comment]
- [ ] nbcnews.com

**Comment by tomac4t** [comment]
- [ ] project-syndicate.org `DNS poisoning`
- [ ] cryptographyengineering.com `Timeout` `Google Cloud`
- [ ] trojan-gfw.github.io `DNS poisoning`
- [ ] cnn.com `error-data: .cnn.com/video`
- [ ] hkmap.live `Geo-blocking` `DNS poisoning`
- [ ] dailysabah.com `DNS poisoning`
- [ ] sinoca.com `TCP RST`

**Comment by cicku** [comment]
我在今天看到这个issue之前，很意外的加了不少网址。

不知道为什么这个issue在当年完全没看到，十分抱歉。
