### ISSUE TITLE
pixiv.com  can connect directly,please remove it from gfwlist

### ISSUE THREAD

**Issue by w7yuu** [gfwlist/gfwlist#1665]
pixiv.com  can connect directly,please remove it from gfwlist

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub For GitHub</a></sub>

**Comment by Cat7102** [comment]
I can't connect it without vpn.

**Comment by cicku** [comment]
Duplicate of #1236
