### ISSUE TITLE
zh.ifixit.com can not be access directly

### ISSUE THREAD

**Issue by TSStudio** [gfwlist/gfwlist#1667]
zh.ifixit.com is NOT in the List right now.
However,you cannot access it directly, but OK if with some magical ways

**Comment by nexw** [comment]
正好过来提交，看到你已经提交了，但是奇怪几百条没有处理了。

**Comment by imba-tjd** [comment]
这是他们网站自己的问题，和墙没有关系

**Comment by cicku** [comment]
解析出大陆 IP，无法添加。
