### ISSUE TITLE
e站提示检测到我使用ehviewer ，封了我ip一天怎么办?

### ISSUE THREAD

**Issue by wmwmwm3** [gfwlist/gfwlist#1675]
![Screenshot_2019-08-19-21-33-13-352_com hippo ehviewer](https://user-images.githubusercontent.com/42052010/63637699-d7c19100-c66e-11e9-9704-50a3551969f9.png)

如题，不敢再用了，怕永久封，怎么屏蔽e站的检测?

**Comment by yogaskung** [comment]
ip超出配额，和ehv没关系吧
