### ISSUE TITLE
使用pac模式无法登录google账号

### ISSUE THREAD

**Issue by DannyVim** [gfwlist/gfwlist#1678]
使用全局模式的时候还是可以正常登录的，但是使用gfwlist的pac模式下，却无法登录，只能打开google的登陆页面。

**Comment by cicku** [comment]
平台？浏览器？路由器？ISP？问题是否仍存在？

**Comment by DannyVim** [comment]
> 平台？浏览器？路由器？ISP？问题是否仍存在？

因为后来没再使用，所以我不清楚现在情况。
