### ISSUE TITLE
bbc 中文网 无法访问 

### ISSUE THREAD

**Issue by gaoyan1234** [gfwlist/gfwlist#169]
bbc 中文  最新网址变成 http://www.bbc.com/zhongwen/simp
原本的规则：
.bbc.co.uk*chinese
.bbc.co.uk/tv
.bbc.co*zhongwen
news.bbc.co.uk/onthisday*newsid_2496000/2496277
newsforums.bbc.co.uk
.bbcchinese.com
||bbc.com
|http://bbc.in
.bbg.gov
.bbsdigest.com/thread
||bbsfeed.com
bbsland.com
.bbsone.com
.bcc.com.tw/board
.bcchinese.net
貌似无法涵盖到

**Comment by cicku** [comment]
您好，请更新您当前使用的 gfwlist。
