### ISSUE TITLE
||blog.de 这条匹配规则导致blog.de开头的域名被强制走代理

### ISSUE THREAD

**Issue by DearTanker** [gfwlist/gfwlist#1699]
目前ggwlist有一条规则是：

、、、
"||blog.de",
、、、

这条匹配规则会导致所有de开头的主域名且子域名是blog的站点都会被匹配到，导致走了代理。

比如，blog.dexxxx.com、blog.de1234.com

希望可以修复一下这个问题。谢谢啦~

**Comment by imba-tjd** [comment]
https://github.com/gfwlist/gfwlist/wiki/Syntax

```
||: Stands for matching specific URI, in such a case, no need to write down scheme, e.g. ||example.com will match (replace www with any subdomain):

http://example.com
http://www.example.com
https://example.com
https://www.example.com

It will NOT match:

http://anotherexample.com
https://anotherexample.com
http://example.com.co
https://example.com.co
```

**Comment by DearTanker** [comment]
> https://github.com/gfwlist/gfwlist/wiki/Syntax
> 
> ```
> ||: Stands for matching specific URI, in such a case, no need to write down scheme, e.g. ||example.com will match (replace www with any subdomain):
> 
> http://example.com
> http://www.example.com
> https://example.com
> https://www.example.com
> 
> It will NOT match:
> 
> http://anotherexample.com
> https://anotherexample.com
> http://example.com.co
> https://example.com.co
> ```

@imba-tjd, thank you for your information. but, I was reporting for this issue about the gfwlist.

**Comment by imba-tjd** [comment]
你可以举一个没有问题的例子吗？

**Comment by DearTanker** [comment]
@imba-tjd 实在抱歉，不是很明白你的意思。你可以看一下这个帖子，也许会更加清楚我说的：https://www.v2ex.com/t/601959

**Comment by imba-tjd** [comment]
`@shansing`说的没错。我说的也没错，不过在我回复你之前他已经回复过同样意思的话了。
