### ISSUE TITLE
digitalocean.com无法打开 github.com无法打开

### ISSUE THREAD

**Issue by stevenchanghz** [gfwlist/gfwlist#170]
我升级了列表，digitalocean无法打开，github（额这个）无法打开
在switchyomega里手工把这两个网址加上就好了。
这算不算需要提交的呢。

辛苦啦。

**Comment by gongjianhui** [comment]
这两个网站应该不在 GFW （以及移动）的屏蔽列表中，请检查你自己的网络环境。

**Comment by cicku** [comment]
中国移动经常上不去使用 CDN 的这些站点。
