### ISSUE TITLE
google翻译被封

### ISSUE THREAD

**Issue by zhuzw1015** [gfwlist/gfwlist#1727]
translate.google.com

**Comment by zhuzw1015** [comment]
translate.googleapis.com

**Comment by imba-tjd** [comment]
1. `translate.google.com` 在 `.google.com` 里
2. `translate.googleapis.com` 没有被封：http://ping.chinaz.com/translate.googleapis.com

**Comment by cicku** [comment]
应该是 ISP 做的手脚，建议投诉运营商
