### ISSUE TITLE
houxu.app

### ISSUE THREAD

**Issue by Amaterasu33** [gfwlist/gfwlist#1729]
http://ping.chinaz.com/houxu.app
![image](https://user-images.githubusercontent.com/28757641/66574792-6babd580-eba7-11e9-84be-03fa89e83204.png)
![image](https://user-images.githubusercontent.com/28757641/66575282-4075b600-eba8-11e9-9316-e871702fe882.png)

科学上网就之后可以打开

**Comment by imba-tjd** [comment]
第一幅图是他们主动禁ping，第二幅图我打得开。
