### ISSUE TITLE
纽约时报RSS

### ISSUE THREAD

**Issue by StrollStars** [gfwlist/gfwlist#173]
RSS地址：http://cn.nytimes.com/rss.html
内容地址：*.cloudfront.net

**Comment by cicku** [comment]
nytimes.com 是全站代理规则。

**Comment by StrollStars** [comment]
但是你不加入*.cloudfront.net，通过RSS阅读就没法看，你可以试试从http://cn.nytimes.com/rss.html跳转的链接。

**Comment by cicku** [comment]
cloudfront 暂时无法加入
