### ISSUE TITLE
search.avira.com && suche.gmx.net && r0.ru

### ISSUE THREAD

**Issue by imba-tjd** [gfwlist/gfwlist#1734]
搜索引擎。

http://ping.chinaz.com/search.avira.com
http://ping.chinaz.com/suche.gmx.net

这俩主域名都是正常的。

http://ping.chinaz.com/r0.ru

**Comment by cicku** [comment]
https://support.avira.com/hc/en-us/articles/360012814297-Discontinuation-of-the-Avira-Safe-Search
