### ISSUE TITLE
shopee.tw

### ISSUE THREAD

**Issue by keke1023** [gfwlist/gfwlist#1751]
this site has been blocked, please add it, thanks

**Comment by keke1023** [comment]
C:\Users\keke>ping shopee.tw
正在 Ping shopee.tw [173.252.73.48] 具有 32 字节的数据:
请求超时。
请求超时。
C:\Users\keke>nslookup
默认服务器:  EA6700-21C4
Address:  192.168.21.1
> shopee.tw
服务器:  EA6700-21C4
Address:  192.168.21.1
非权威应答:
名称:    shopee.tw
Address:  173.252.73.48

China telecom Xi'an
there are 7 site under shopee.com, only shopee.tw cant be connected.

**Comment by cicku** [comment]
Duplicate of #1952
