### ISSUE TITLE
本项目是否存在激进/保守版的问题？

### ISSUE THREAD

**Issue by aquamarine236** [gfwlist/gfwlist#1753]
我对本项目的更新速度有所不满。项目有时候一个月更新几次，也有时候几个月才更新一次。
是否可以搞一个机器自动化的流程，同时让人更方便的提交问题，比方说可以按照某种表单的格式填写被封或者被解封的网站。
基于GFWList的分流翻墙，相比全局翻墙，对于增加墙的检测难度有很多好处，然而每次都自行编辑自己的PAC实在是太累了，期望能有一个某种基于机器的“自动编辑并上报GFWList”的机制，并且，我希望大家的GFWList都能及时更新，节约上报者的时间。

不过，我目前并不确定，本项目更新速度之慢，是否有意这么考虑？还是仅仅是人手不足，时间不足的问题？如果是有意的考虑的话，那是否是考虑到会像某些软件的各种发行版一样，不同的激进/保守程度会给下游带来不同的兼容性问题？

**Comment by aquamarine236** [comment]
我比较能接受的更新速度是每天一次。

如果做到每分钟瞬时提交，瞬时更新的话，这种机制会被敌人利用。因为墙也可以只瞬时封掉一个网站，然后瞬时解封，这种做法可以方便墙的维护者定位某个网站的浏览者，带来隐私风险。

**Comment by tomac4t** [comment]
> 我对本项目的更新速度有所不满。项目有时候一个月更新几次，也有时候几个月才更新一次。

这个项目本身就是志愿者维护的，维护者也很忙，而且没有盈利目的，所以没什么可以不满的。

> 然而每次都自行编辑自己的PAC实在是太累了，期望能有一个某种基于机器的“自动编辑并上报GFWList”的机制，并且，我希望大家的GFWList都能及时更新，节约上报者的时间。

首先，电信移动教育网的屏蔽是不同的，这个需要分别测量。DNS 屏蔽是很好判断的，但超时、关键词屏蔽并不方便。“自动上报”到哪里？上报的合适地点除了 GitHub 还有其他吗，显然并没有。编辑 PAC 太累可以使用 [SwitchyOmega](https://github.com/FelisCatus/SwitchyOmega) 等工具。

> 我比较能接受的更新速度是每天一次。

没必要，这个项目一周都没有多少上报，恰巧能用上的概率更低了。另外，大部分 PAC 工具都是一个多月更新一次的。

> 如果做到每分钟瞬时提交，瞬时更新的话，这种机制会被敌人利用。因为墙也可以只瞬时封掉一个网站，然后瞬时解封，这种做法可以方便墙的维护者定位某个网站的浏览者，带来隐私风险。

你想太多了。

**Comment by aquamarine236** [comment]
SwitchyOmega还不是要手动编辑？
这个项目之所以一周没多少上报，就是缺乏自动机制导致的。会PAC的人都很少，还要从PAC中找出哪些网站被封，还要手动找，不怕手抽筋吗？

超时问题也不是完全没有解决办法，只要有多位上报者上报，累积到一定次数，就优先处理嘛。

现在HTTPS已经很普及了，基于关键词的GFWList到底有没有继续维护的必要？如果你们觉得还有必要的话，我自己去别处找别的项目。

**Comment by aquamarine236** [comment]
声明一下，“对项目不满”这句话是对事不对人，特别是不针对维护者。我还是特别尊重维护者的劳动的，我当然也知道他们时间不够。我仅仅是指出这个方面有改进空间，就好象我对某民主国家的某个政策不满一样，这并不代表我对议员不满。

我不知道为何说了一句“不满”就好像会得罪人一样，维护者确实很幸苦，但是幸苦的时候也不要忘了，别人对你还是肯定的。

**Comment by aquamarine236** [comment]
而且我也从未指望维护者花费更多一点的时间去频繁更新本项目，只不过是讨论一下有没有【机器】可以代劳的余地而已。所以，你就不要想太多了，什么我对项目没什么可不满的，我这可真的不是指要维护者做牛做马一样。

**Comment by aquamarine236** [comment]
发在github
首先，如果如果不按照格式，就必须一个一个人工审查，然后手动关闭项目，多累？如果要机器介入的话，顶多是写一个正则表达式，只能起到搜索URL的作用，但是你又不知道这个URL到底是什么问题，有时候还得人进来看。这就是为什么我想搞一个分类的动机，比方说如果分类在DNS污染之下，那这类issue交给机器一下子就解决了。

除了github之外，其他办法也不是不可以讨论的，比如基于P2P的聊天工具本身难以被墙掉，这类聊天工具说不定也能成为上报者的可选渠道。只是恶意刷屏太容易。

**Comment by aquamarine236** [comment]
关于瞬时封锁的问题，一句“你想太多了。” 这并不是一个讨论问题该有的态度。我认为这里是有问题的，你可能认为在你那个环境下没问题，这点我俩并不能达成一致。我也懒的说了。
