### ISSUE TITLE
GitHub raw被污染

### ISSUE THREAD

**Issue by BFDZ** [gfwlist/gfwlist#1756]
域名：raw.githubusercontent.com

**Comment by mraandtux** [comment]
之前联通和部分广电网络连接*.githubusercontent.com不时出现问题，现在连raw.githubusercontent.com都全局DNS污染，那群PD侯今吾 ( @ donho ) 的XFH要负全责！
附Greatfire的测试结果：
https://zh.greatfire.org/https/raw.githubusercontent.com
