### ISSUE TITLE
reutersmedia.net 

### ISSUE THREAD

**Issue by ahfeng** [gfwlist/gfwlist#176]
路透社的静态资源网址

**Comment by cicku** [comment]
能否有具体的页面链接？我测试了多个二级域名均无问题。

**Comment by cybort** [comment]
怀疑是域名换了

This site can’t be reached

网址为 http://reutersmedia.net/ 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。
ERR_NAME_RESOLUTION_FAILED


Python Urlfetch Error: 'GET'

DNSLookupFailedError('DNS lookup failed for URL: http://reutersmedia.net/',), timeout=19
DNSLookupFailedError('DNS lookup failed for URL: http://reutersmedia.net/',), timeout=38

**Comment by cicku** [comment]
There are multiple subdomains (af, s1, s2, sn...), but none of them are blocked based on test.
