### ISSUE TITLE
www.w3schools.com check this 

### ISSUE THREAD

**Issue by steveoOn** [gfwlist/gfwlist#177]
plz check this www.w3schools.com seem like not go through proxy with automatic model

**Comment by cicku** [comment]
Please update the gfwlist you are using.

**Comment by steveoOn** [comment]
wow~ it works, thank you bro~

**Comment by jarod** [comment]
`Last Modified: Fri, 03 Jun 2016 12:20:21 +0800`
这个网站没有加到gfwlist吗，访问还是要手动添加到代理列表

**Comment by octopusthu** [comment]
This site is blocked again...
