### ISSUE TITLE
删除白名单@@|https://share.dmhy.org

### ISSUE THREAD

**Issue by 1265578519** [gfwlist/gfwlist#1773]
删除白名单@@|https://share.dmhy.org
该网站已被dns污染，并且pac列表有share.dmhy.org，但是由于有两份，导致了白名单冲突
该网站为顶级域名全站污染，请删除之前的并且整合修改为
"dmhy.org",

**Comment by imba-tjd** [comment]
我没看到这条白名单啊

**Comment by cicku** [comment]
请确保您在使用最新版

**Comment by 1265578519** [comment]
哦，好的，我用的v2rayn对接的pac更新接口，我问问gui那边是什么情况

![image](https://user-images.githubusercontent.com/6442439/69058358-797a3380-0a4e-11ea-9268-8bde3c5f32d5.png)

**Comment by 1265578519** [comment]
已解决，对方软件内置了过时的文件，更新后就行了
