### ISSUE TITLE
nhentai.net

### ISSUE THREAD

**Issue by TonyZZX** [gfwlist/gfwlist#178]
http://nhentai.net
http://i.nhentai.net
http://t.nhentai.net

望添加，谢谢

**Comment by cicku** [comment]
nhentai.net 早已添加，请更新您的 gfwlist。

需要注意的是，添加的规则是 .nhentai.net，因此如果您以 http://nhentai.net 访问该站点主页，仍不会走代理规则。

这将在稍后修正。
