### ISSUE TITLE
please add *.githubusercontent.com #urgent

### ISSUE THREAD

**Issue by niubaoshu** [gfwlist/gfwlist#1795]
大多数人使用https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt 来更新gfwlist,但是似乎raw.githubusercontent.com被屏蔽了.

Most people use https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt to update gfwlist, but it seems raw.githubusercontent.com is blocked.

**Comment by imba-tjd** [comment]
1. 此域名在列表里。
2. 有没有被屏蔽你可以用 http://ping.chinaz.com/raw.githubusercontent.com 测试一下，答案是没有。它只挂了几天，之后就恢复了。

**Comment by niubaoshu** [comment]
好的,我关了issue.
