### ISSUE TITLE
我什么都不懂，可以问下这个项目可以用来干嘛吗？

### ISSUE THREAD

**Issue by llh1187** [gfwlist/gfwlist#1815]
我自己有SSR账号已经可以翻墙了，这个项目我还需要吗？

**Comment by VaslD** [comment]
GitHub Issues 不是论坛或使用经验反馈，以后不建议提此类问题，请在网上搜索相关使用指南。

至于这个项目你需不需要，取决于你使用什么翻墙工具或方法。既然你并不确定这个项目用来干什么、怎么用，那就仅在有翻墙工具要求你使用此项目的时候再用。

**Comment by tjseek** [comment]
github从来都是一面高墙，百分之九十的人都搞不懂这是干什么的
