### ISSUE TITLE
请添加llvm.org

### ISSUE THREAD

**Issue by vonhezhou** [gfwlist/gfwlist#1825]
llvm.org是(goolg, apple等)编译器框架llvm的网站。clang/clang++/lldb编译器，调试器都是这个框架下的.
码农基本都知道吧

**Comment by imba-tjd** [comment]
所以这个网站有什么问题？

**Comment by vonhezhou** [comment]
我弄错了，在公司的网络无法访问，我以为是被xx了。
我错了
