### ISSUE TITLE
Reddit media

### ISSUE THREAD

**Issue by altayhunter** [gfwlist/gfwlist#1831]
Reddit-hosted content is now served from v.redd.it, which is blocked by the GFW, requiring the following rule to be added to the list:
```
||v.redd.it
```
With the current set of rules the frontpage is able to load, but any self-hosted images and videos fail to load.

**Comment by imba-tjd** [comment]
![图片](https://user-images.githubusercontent.com/24759802/71401167-0161e780-2664-11ea-98ba-c4e19217981a.png)

**Comment by altayhunter** [comment]
Oops. It looks like I hadn't updated my GFWList in a while. Sorry to bother you.
