### ISSUE TITLE
关于规则的一些问题

### ISSUE THREAD

**Issue by studentmain** [gfwlist/gfwlist#1857]
1. 为何使用base64而不是提供明文？
2. 由于SNI不再安全，对于`|http://img.dlsite.jp/`一类的情况（只匹配特定网站的HTTP版）可否不再使用从头匹配规则？
3. 为何某些域名在使用域名匹配的同时还使用关键字匹配？例如`||nytimes.com`和`.nytimes.com`，这种情况可否只保留域名匹配规则？进一步，`.dyndns.org`可否换为`||dyndns.org`
4. 为何对google域名使用正则表达式匹配？
5. 能否移除纯IP地址关键字？
6. 对于使用通配符的规则，能否设法移除通配符？

**Comment by studentmain** [comment]
更进一步，由于TLS的部署，现在是否可以不再考虑匹配路径，只匹配域名?

**Comment by imba-tjd** [comment]
第一点见 https://github.com/gfwlist/gfwlist/issues/1148
第三点我解释过……比如`http://example.com/asdf`，斜杠后面可以随便加东西，都能访问。`http://example.com/nytimes.com`也能访问，但是`http://example.com/.nytimes.com`就会被重置。但这也使得`https://wordpress.com`这个本来不需要代理的因为`.wordpress.com`规则走了代理。

**Comment by studentmain** [comment]
关于第一点我目前找到的解释是防止明文传输中被拦截，但是现在部署TLS并没有难度，主要客户端也在使用TLS加载gfwlist。只提供混淆后的代码也可能违反协议：https://github.com/gfwlist/gfwlist/blob/e191e4974092b2826f92e380de1cbfa14e74a82a/COPYING.txt#L136-L137
不过问题不大，顶多不方便其他人维护而已。

第三点第五点知道了

**Comment by LeoYuan** [comment]
```
"@@||fonts.gstatic.com",
"@@||ssl.gstatic.com",
```
这两条为什么要排除？期望的是这两个子域名也能走代理，我手工加入了 `||fonts.gstatic.com`，发现没法覆盖原来的~

**Comment by imba-tjd** [comment]
这两条为什么要走代理？

**Comment by LeoYuan** [comment]
好吧，我下午发现这两条一直 pending，现在好了~

**Comment by cicku** [comment]
很抱歉 很多今年的 issue 我没有看过。

1. 历史遗留，没有改动必要。何况，很多 gfwlist 实现就是基于 base64 的，这项目已经超过10年了，改不改意义不大，而且我更新 list，就是一行脚本的事情，根本对我没影响。

2. 今后列表的规则，更倾向于 || 全站匹配，因为随着 SSL 的普及，HTTP 已经没有什么市场。至于您说的 SNI 安全问题，我这方面没有关注，您可以给我一个链接我来学习一下。

3. 历史遗留加上防火墙实现。防火墙至今都会有关键字屏蔽，所以我倾向于保留这种设置。但是今后我也说了，基本上不会再添加。

4. 因为正则很好用。

5. 纯 IP 可以移除，但是 Telegram 用户更希望加入，我没法决定。Telegram 和 Twitter 都是封锁 IP 的。我这些年也没有把所有 IP 都加进来，我曾经加过一次但是没有 push，因为发现所有 IP 加进来，list 貌似有 10mb 大小吧？

6. 通配符的规则，如果防火墙依旧有效，肯定我不会动他们的。至于各种实现，他们可以忽略这些规则，无论是技术有限还是其他原因。
