### ISSUE TITLE
add ampproject.org

### ISSUE THREAD

**Issue by LiTianxiong** [gfwlist/gfwlist#1859]
The site has been banned by gfw.

**Comment by Loukky** [comment]
该网站会自动跳转到 amp.dev

**Comment by LiTianxiong** [comment]
> 该网站会自动跳转到 amp.dev

电脑上是会自动跳转这个的, 但在手机上访问通过amp加速的网页时需要直接访问这个域名

例如(需要在手机上才能访问, 桌面端会直接跳转到原本的网站): 
https://www.google.com/amp/s/amp.base64decode.org/

也可以参考这个帖子: [V2EX 的 AMP 页面 404 了](https://www.v2ex.com/t/332817)

**Comment by Loukky** [comment]
> > 该网站会自动跳转到 amp.dev
> 
> 电脑上是会自动跳转这个的, 但在手机上访问通过amp加速的网页时需要直接访问这个域名
> 
> 例如(需要在手机上才能访问, 桌面端会直接跳转到原本的网站):
> https://www.google.com/amp/s/amp.base64decode.org/
> 
> 也可以参考这个帖子: [V2EX 的 AMP 页面 404 了](https://www.v2ex.com/t/332817)
测试正常。目前的策略是 cdn.ampproject.org 直连，其他走gfwlist
![](https://imgur.loukky.com/imgs/2020/01/3902625588d8466d.png)

**Comment by lzfxxx** [comment]
ampproject.org 直联感觉还是有点问题的, 请测试一下下面这些链接
https://amp-reddit-com.cdn.ampproject.org/wp/s/amp.reddit.com/r/webdev/comments/ctu2gw/google_amp_how_is_this_okay_in_2019/?usqp=mq331AQOKAGYAe_V2JqKssLH6gE%3D

https://www-xda--developers-com.cdn.ampproject.org/wp/s/www.xda-developers.com/bypass-amp-links-deampify/amp/?usqp=mq331AQNKAGYAc2WmfbV_cu6Ng%3D%3D

https://amp-dev.cdn.ampproject.org/wp/s/amp.dev/about/websites/?usqp=mq331AQOKAGYAe69xdCymPSwiwE%3D

https://www.google.com/amp/s/www.pinterest.cl/amp/pin/439452876114504685/
