### ISSUE TITLE
nicovideo.jp 已解封

### ISSUE THREAD

**Issue by aoisummer** [gfwlist/gfwlist#186]
```
curl -I http://www.nicovideo.jp/watch/1459020127
HTTP/1.1 200 OK
```

**Comment by cybort** [comment]
This site can’t be reached

nicovideo.jp took too long to respond.
ERR_CONNECTION_TIMED_OUT

**Comment by cicku** [comment]
sp.nicovideo.jp seems unblocked from China Unicom, tracking.

**Comment by chengr28** [comment]
www.nicovideo.jp's IP seems to be blocked.

**Comment by aoisummer** [comment]
In my area, use local ISP dns server (China Telecom), looks like all of domains can be connected directly.

**Comment by aoisummer** [comment]
Update: Blocking method seems to change from url reset to block IP.

**Comment by cicku** [comment]
规则已经移除，如有问题请手工添加自定义规则。
