### ISSUE TITLE
Github User Content子域名增加了,提交新的域名

### ISSUE THREAD

**Issue by gzzchh** [gfwlist/gfwlist#1860]
最近发现 
* avatars2.githubusercontent.com
* camo.githubusercontent.com
等域名无法加载,猜测usercontent可能拆分了子域名,故在这里提交新的域名.
建议直接添加 *.githubusercontent.com

**Comment by uniartisan** [comment]
*.github.io 好像也不行

**Comment by ningsibuqu** [comment]
github.com都不行了

**Comment by wordlesswind** [comment]
duplicate #1828
