### ISSUE TITLE
可以添加一个无porn的版本吗

### ISSUE THREAD

**Issue by JarmoHu** [gfwlist/gfwlist#1865]
为了孩子和那些长不大的大孩子，谢谢帮助

**Comment by imba-tjd** [comment]
那你如何阻止全局？

**Comment by waynon** [comment]
不支持这个issue，本来这个项目就是anti-censorship，你还去搞封锁，不符合这个项目的宗旨

**Comment by hustarbor** [comment]
> 
> 
> 不支持这个issue，本来这个项目就是anti-censorship，你还去搞封锁，不符合这个项目的宗旨

作者说过，v2ray本身是想作为一个工具箱，而不是单纯的一个FQ工具

**Comment by hustarbor** [comment]
> 
> 
> 那你如何阻止全局？

就是在v2ray里面拦截啊
