### ISSUE TITLE
media.fantv.hk is dns poisoned

### ISSUE THREAD

**Issue by wyf88** [gfwlist/gfwlist#1870]
This is the domain for streaming Hong Kong Open TV (`http://media.fantv.hk/m3u8/archive/channel2.m3u8`). 

Tested with `http://ping.chinaz.com/media.fantv.hk`, and the resolved IPs from China Telecom and Unicom are poisoned, to the IPs of Facebook, Twitter, etc.

**Comment by mraandtux** [comment]
楼主火星，去年9月就已DNS污染，联动：
#1695

**Comment by cicku** [comment]
+hkopentv.com
