### ISSUE TITLE
 #1584 续：中时电子报已解封

### ISSUE THREAD

**Issue by mraandtux** [gfwlist/gfwlist#1877]
#1584 续：
2020/02更新：G发课W已于2019年8月左右解除了对中时电子报的封锁，附GreatFire的测试结果：
https://zh.greatfire.org/https/www.chinatimes.com
https://zh.greatfire.org/www.chinatimes.com
 #旺旺真红#

**Comment by waynon** [comment]
打不开的

**Comment by mraandtux** [comment]
> 打不开的

哪里的ISP？广东广电可以。
