### ISSUE TITLE
About the question of restriction of reports from some region.

### ISSUE THREAD

**Issue by LivingInPortal** [gfwlist/gfwlist#188]
I am confused of why these regions (Tibet, Shinjang, Qinghai) are forbidden from reporting.
I found no reason to block these people.
Is there having been applied some special treatment from their government(network environment) so you can't accept their reports?

**Comment by cicku** [comment]
`Is there having been applied some special treatment from their government(network environment) so you can't accept their reports?`

Yes, that's all.
