### ISSUE TITLE
xbox.com被墙了

### ISSUE THREAD

**Issue by 1265578519** [gfwlist/gfwlist#1894]
http://xbox.com/windows/Teredo
http://xbox.com/windows/QoS

![image](https://user-images.githubusercontent.com/6442439/74931304-4fa02680-541a-11ea-8fdf-2e83bb92223f.png)

**Comment by lazyf11** [comment]
广东电信，第一个链接没有问题

**Comment by 1265578519** [comment]
@lazyf11 第二个不行？

**Comment by mraandtux** [comment]
以上链接加三个达不溜点就可以上。
ISP：广东有线U宽频（广电，联通出口）
（最近基发课达不溜有点怪······）

**Comment by 1265578519** [comment]
@mraandtux 这个是windows10上xbox游戏自带弹出的地址，，正常人不会去手动加他的吧
