### ISSUE TITLE
please add avatars[0-3].githubusercontent.com

### ISSUE THREAD

**Issue by BFDZ** [gfwlist/gfwlist#1897]
GitHub 的头像域名都被墙了
- avatars0.githubusercontent.com
- avatars1.githubusercontent.com
- avatars2.githubusercontent.com
- avatars3.githubusercontent.com

**Comment by mraandtux** [comment]
你的ISP是不是移动或其他使用移动出口的ISP？联通未见问题。
但从2/18开始，在中移动网络下浏览架设在Fastly CDN的网站（包括你所提及的GitHub网站资源和用户架设网址 *.github.io ），虽然ping得但traceroute后可以连接上一段时间，之后就连接不上了。
向移动投诉吧！

**Comment by BFDZ** [comment]
@mraandtux 我是电信，这个域名前天全国ping都超时

**Comment by CaiJingLong** [comment]
我是北京联通,  从今年1月中旬左右开始, github头像就一直不正常
目前我是直接把 *.githubusercontent.com  都加入我的pac了
因为 raw. 也上不去,包括issue中如果提交图片, 好像也是有问题的

**Comment by whlsxl** [comment]
我的这个域名也一直不正常，目前手动添加

**Comment by wordlesswind** [comment]
duplicate #1828

**Comment by ilpl** [comment]
> githubusercontent.com

  此域名时不时抽风, 加入pac 保平安

**Comment by cicku** [comment]
Duplicate of #1860
