### ISSUE TITLE
github.githubassets.com is blocked

### ISSUE THREAD

**Issue by maidmeow4** [gfwlist/gfwlist#1900]
`github.githubassets.com`
IP addresses:
```
185.199.108.154
185.199.109.154
185.199.110.154
185.199.111.154
```

**Comment by lese123** [comment]
Looks normal. China Unicom, Hubei.
ping github.githubassets.com
PING github.githubassets.com (185.199.108.154): 56 data bytes
64 bytes from 185.199.108.154: seq=0 ttl=52 time=63.235 ms
64 bytes from 185.199.108.154: seq=1 ttl=52 time=62.538 ms
64 bytes from 185.199.108.154: seq=2 ttl=52 time=61.944 ms
^C
--- github.githubassets.com ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 61.944/62.572/63.235 ms

**Comment by maidmeow4** [comment]
Never mind, it looks like a temporary blockage.
But yesterday I was unable to access most of Github resources.

Pinging from China Unicom, Liaoning
```
ping -c 4 185.199.111.154
PING 185.199.111.154 (185.199.111.154) 56(84) bytes of data.
64 bytes from 185.199.111.154: icmp_seq=1 ttl=52 time=109 ms
64 bytes from 185.199.111.154: icmp_seq=2 ttl=52 time=98.6 ms
64 bytes from 185.199.111.154: icmp_seq=3 ttl=52 time=101 ms
64 bytes from 185.199.111.154: icmp_seq=4 ttl=52 time=95.5 ms

--- 185.199.111.154 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 7ms
rtt min/avg/max/mdev = 95.488/100.934/108.949/4.995 ms
```
