### ISSUE TITLE
关于最近Fastly CDN在部分运营商下浏览的问题

### ISSUE THREAD

**Issue by mraandtux** [gfwlist/gfwlist#1905]
从2/18开始，在中移动网络下浏览架设在Fastly CDN的网站（包括GitHub网站资源 .githubusercontent.com 和用户架设网址 .github.io 、Bandcamp, 《自然》杂志、《新科学人》杂志、《连线》杂志、《福布斯》、《今日美国报》、Vox传媒旗下网站、CBS Interactive旗下网站······等众多知名网站），虽然IP可以ping得、traceroute或curl -I后可以连接上一段时间，之后就连接不上了。使用移动出口的ISP（如长宽系、部分广电网络，如广东有线U宽频）或者其他运营商也会出现这个问题。各位快点向电信公司们投诉吧！

**Comment by mraandtux** [comment]
联动类似事故 #1695

**Comment by mraandtux** [comment]
本次事故相关讨论： #1828 , #1860 , #1863 , #1897

**Comment by Accelerator086** [comment]
Duplicate #18

**Comment by mraandtux** [comment]
@Accelerator086 这个问题和5年前的问题不一样，现在又恢复了，但*.github.io仍有问题，GFuckW是抽风之王

**Comment by mraandtux** [comment]
最近移动连CloudFlare CDN都出现类似的连接问题，移动要完
