### ISSUE TITLE
已经四个多月没更新了，开发者还在吗？

### ISSUE THREAD

**Issue by 1265578519** [gfwlist/gfwlist#1911]
已经四个多月没更新了，开发者还在吗？

**Comment by ltsvei** [comment]
同问

**Comment by lizenghui** [comment]
同问

**Comment by hunter-xue** [comment]
同问

**Comment by 643406834** [comment]
可以被请去喝茶吧

**Comment by wangwanchao** [comment]
可能已经失踪了吧

**Comment by ablebodied** [comment]
严重担心作者的安全

**Comment by falloutxxx2** [comment]
本来这种 list 的解决方案就不好！！！

**Comment by ablebodied** [comment]
@falloutxxx2 有好的方案可以提出来啊

**Comment by ablebodied** [comment]
@falloutxxx2 这种不相当于白名单模式吗？用这个list是想实现黑名单模式，而且GEOIP据说也不一定精确，不少代理软件提供了这个选项，但是这个跟该list本身就属于两种思路，不矛盾

**Comment by SekiBetu** [comment]
> @falloutxxx2 这种不相当于白名单模式吗？用这个list是想实现黑名单模式，而且GEOIP据说也不一定精确，不少代理软件提供了这个选项，但是这个跟该list本身就属于两种思路，不矛盾

geosite:!cn
这样写不就是黑名单了吗
