### ISSUE TITLE
Coronavirus related news sites blocked?

### ISSUE THREAD

**Issue by ee99ee** [gfwlist/gfwlist#1913]
I'm not longer able to access these domains from a China Telecom residential fiber connection as of today:

- https://www.bangkokpost.com/
- https://www.straitstimes.com/
- https://www.channelnewsasia.com/- 
- https://nationalinterest.org/

**Comment by mraandtux** [comment]
4个都被DNS污染，坡县海时获得双重认证（DNS污染+SNI重置）
此外电信有可能出现 #1905 的问题

**Comment by ee99ee** [comment]
yeah, so let's add to this list?

**Comment by ee99ee** [comment]
so how do I get stuff like this merged or fixed?

**Comment by cicku** [comment]
@ee99ee Fixed. Sorry for the delay during the pandemic.
