### ISSUE TITLE
onedrive.live.com  相关域名

### ISSUE THREAD

**Issue by leevensu** [gfwlist/gfwlist#1926]
onedrive.live.com

**Comment by llccd** [comment]
onedrive.live.com 好像已经在gfwlist里了  

 相关域名
- api.onedrive.com 没被墙
- skyapi.onedrive.live.com 是onedrive.live.com的子域

**Comment by SekiBetu** [comment]
这项目已经没人了，你自己写进自己的自定义pac吧

**Comment by leevensu** [comment]
多谢

llccd <notifications@github.com> 于2020年4月23日周四 下午5:45写道：

**Comment by leevensu** [comment]
多谢，我这边没有问题了

XIBIE <notifications@github.com> 于2020年4月23日周四 下午7:12写道：
