### ISSUE TITLE
封锁越来越严重，直接大陆网站白名单吧

### ISSUE THREAD

**Issue by jymr92** [gfwlist/gfwlist#1933]
地球上一半的网站都被屏蔽了。直接大陆网站白名单吧。

**Comment by BillyfffWoo** [comment]
- **万里长城永不倒** 
### 1. 千里黄河水涛涛

**Comment by bash99** [comment]
哪儿有持续更新的白名单啊？

**Comment by flynaj** [comment]
不错 那个立个项目,爬一下 beian.miit.gov.cn

**Comment by IMZCC** [comment]
> 哪儿有持续更新的白名单啊？

https://github.com/ifyour/ipac
这个好像还可以，可以试试

**Comment by baby5** [comment]
https://github.com/breakwa11/gfw_whitelist

**Comment by yiguihai** [comment]
安利一个项目
https://github.com/GameXG/TcpRoute2
撞墙自动切换代理

**Comment by SekiBetu** [comment]
https://github.com/Loyalsoldier/v2ray-rules-dat/releases
即使没有封锁，你上国外网站也会很卡的，所以白名单确实比黑名单的优势大了很多
