### ISSUE TITLE
即日起需要他人协助维护

### ISSUE THREAD

**Issue by cicku** [gfwlist/gfwlist#1945]
**非常抱歉，即日起由于各种原因，本人不再有时间打理此项目，不意味着完全退出，只不过目前是力不能及。**

**如有兴趣参与维护，可直接与本人联系。**

**请注意，如您有兴趣维护，请附上自己的 Github 链接以证明您非机器人。有明显的知名度／知名开源参与申请者优先，必须位于中国大陆。**

**再次感谢大家对 GFWList 项目的支持。**

**Comment by XhstormR** [comment]
上一次更新是去年2019年11月5日了，祝好。

**Comment by Gh0u1L5** [comment]
话说我之前看到这个项目的时候就在想了，gfwlist作为这么重要的一个项目居然要依靠一名管理员手动维护，其他人只一股脑地提交issue，这个工作量也太大了。
我们可不可以把这个流程机械化、自动化，在项目里放一个明文的gfwlist文件，其他人可以提交PR来修改这个明文list，一旦明文list得到2到3个maintainer的approve，就自动合并到master分支并且触发一次CI/CD，由TravisCI之类的系统自动把明文list编码成gfwlist.txt，那么维护压力应该会大为减小。

**Comment by SekiBetu** [comment]
> 话说我之前看到这个项目的时候就在想了，gfwlist作为这么重要的一个项目居然要依靠一名管理员手动维护，其他人只一股脑地提交issue，这个工作量也太大了。
> 我们可不可以把这个流程机械化、自动化，在项目里放一个明文的gfwlist文件，其他人可以提交PR来修改这个明文list，一旦明文list得到2到3个maintainer的approve，就自动合并到master分支并且触发一次CI/CD，由TravisCI之类的系统自动把明文list编码成gfwlist.txt，那么维护压力应该会大为减小。

一般地，认为白名单模式更加好，因为国内的网站都是可查询到的，隔壁的v2ray增强项目也有7万多个域名，89亿个IP地址记录在内，已经完美取代这个项目了

**Comment by aries15** [comment]
我的需求是能直连的就直连，不能直连的才代理。请教如何取代本项目？

**Comment by SekiBetu** [comment]
> 我的需求是能直连的就直连，不能直连的才代理。请教如何取代本项目？

黑名单：默认全局不代理，然后代理列表里的地址
白名单：默认全局代理，然后排除列表里的地址

目前现状是白名单记录的数量远超于黑名单的数量

**Comment by Gh0u1L5** [comment]
> 
> 
> > 话说我之前看到这个项目的时候就在想了，gfwlist作为这么重要的一个项目居然要依靠一名管理员手动维护，其他人只一股脑地提交issue，这个工作量也太大了。
> > 我们可不可以把这个流程机械化、自动化，在项目里放一个明文的gfwlist文件，其他人可以提交PR来修改这个明文list，一旦明文list得到2到3个maintainer的approve，就自动合并到master分支并且触发一次CI/CD，由TravisCI之类的系统自动把明文list编码成gfwlist.txt，那么维护压力应该会大为减小。
> 
> 一般地，认为白名单模式（全局代理+绕过大陆局域网路由模式）更加好，因为国内的网站都是可查询到的（甚至有正规网站提供这些国内域名或者IP），隔壁的v2ray增强项目已经有7万多个中国域名，89亿个中国IP地址记录在内（比gfwlist的5800多个域名多了很多了），已经完美取代这个项目了

Ummm，但是白名单的缺点也挺明显的。最直接的一点就是白名单的规模太大了，每发起一个新连接都要在7万域名和若干IP段里查表匹配，PC端可能压力不大，但手机端的ping值和耗电量应该都会有明显增长吧。其次白名单有时候会触发一些微妙的bug，一些大厂手机APP会在后台访问一些私有的API服务器，但白名单可能没有及时收录或者本地白名单没有更新到最新，就会触发风控之类的机制。比如我的京东白条红包，失手挂着白名单VPN触发了一次风控，到现在领红包都提示我IP地址异常无法领取。
除了上述原因之外，gfwlist还有一个白名单无可替代的功能，就是作为一个风向标指示现在的政治风向，是偏左还是偏右，收紧还是放宽，我个人还是挺喜欢观察这些细节的。

**Comment by SekiBetu** [comment]
> > > 话说我之前看到这个项目的时候就在想了，gfwlist作为这么重要的一个项目居然要依靠一名管理员手动维护，其他人只一股脑地提交issue，这个工作量也太大了。
> > > 我们可不可以把这个流程机械化、自动化，在项目里放一个明文的gfwlist文件，其他人可以提交PR来修改这个明文list，一旦明文list得到2到3个maintainer的approve，就自动合并到master分支并且触发一次CI/CD，由TravisCI之类的系统自动把明文list编码成gfwlist.txt，那么维护压力应该会大为减小。
> > 
> > 
> > 一般地，认为白名单模式（全局代理+绕过大陆局域网路由模式）更加好，因为国内的网站都是可查询到的（甚至有正规网站提供这些国内域名或者IP），隔壁的v2ray增强项目已经有7万多个中国域名，89亿个中国IP地址记录在内（比gfwlist的5800多个域名多了很多了），已经完美取代这个项目了
> 
> Ummm，但是白名单的缺点也挺明显的。最直接的一点就是白名单的规模太大了，每发起一个新连接都要在7万域名和若干IP段里查表匹配，PC端可能压力不大，但手机端的ping值和耗电量应该都会有明显增长吧。其次白名单有时候会触发一些微妙的bug，一些大厂手机APP会在后台访问一些私有的API服务器，但白名单可能没有及时收录或者本地白名单没有更新到最新，就会触发风控之类的机制。比如我的京东白条红包，失手挂着白名单VPN触发了一次风控，到现在领红包都提示我IP地址异常无法领取。
> 除了上述原因之外，gfwlist还有一个白名单无可替代的功能，就是作为一个风向标指示现在的政治风向，是偏左还是偏右，收紧还是放宽，我个人还是挺喜欢观察这些细节的。

性能差异也就毫秒级别，平常运行一个QQ的APP都比这个操作耗电量大，白名单也包含API地址，这些API很快就会被收录，（涉及购物密码操作的，为什么还要开着代理），gfwlist封锁的地址是人为添加的，可能一年前就已经封锁了，只是到了现在才被人发现，时间差导致你看到的风向标完全是错误的

**Comment by Gh0u1L5** [comment]
> 
> > 
> > 
> > Ummm，但是白名单的缺点也挺明显的。最直接的一点就是白名单的规模太大了，每发起一个新连接都要在7万域名和若干IP段里查表匹配，PC端可能压力不大，但手机端的ping值和耗电量应该都会有明显增长吧。其次白名单有时候会触发一些微妙的bug，一些大厂手机APP会在后台访问一些私有的API服务器，但白名单可能没有及时收录或者本地白名单没有更新到最新，就会触发风控之类的机制。比如我的京东白条红包，失手挂着白名单VPN触发了一次风控，到现在领红包都提示我IP地址异常无法领取。
> > 除了上述原因之外，gfwlist还有一个白名单无可替代的功能，就是作为一个风向标指示现在的政治风向，是偏左还是偏右，收紧还是放宽，我个人还是挺喜欢观察这些细节的。
> 
> 性能差异也就毫秒级别，平常运行一个QQ的APP都比这个操作耗电量大，白名单也包含API地址，这些API很快就会被收录，（涉及购物密码操作的，为什么还要开着代理），gfwlist的地址是人为提交到这个项目由作者统一添加的，可能一年前就已经封锁了，只是到了现在才被人发现，时间差导致你看到的风向标完全是错误的

嘛，我们这个讨论稍微有些跑题了，花大段的篇幅讨论“你虽然举了个例子但只是个案”、“你说的缺点其实不是缺点而是你操作有问题”或者“你说的优点并没有那么优秀所以不算优点”，跟cicku的这条issue关系不大，这条issue我觉得还是应该回归到gfwlist的维护问题上。
至于gfwlist该不该继续维护下去，我觉得其实是一个需要用户用脚投票的事情，黑白名单切换起来也就是一个按钮或者两行代码的事情，如果大家都觉得黑名单不好用，自然也就不会再过来提issue或者访问仓库，项目自然而然也就消亡了。
而现在的现状是众多的项目和用户仍然在依赖gfwlist这个项目，就算gfwlist停止维护了，也大概率会有人开一个新项目继续做黑名单，那么我觉得优化现有的gfwlist维护流程就是有意义的。

**Comment by SekiBetu** [comment]
> > > Ummm，但是白名单的缺点也挺明显的。最直接的一点就是白名单的规模太大了，每发起一个新连接都要在7万域名和若干IP段里查表匹配，PC端可能压力不大，但手机端的ping值和耗电量应该都会有明显增长吧。其次白名单有时候会触发一些微妙的bug，一些大厂手机APP会在后台访问一些私有的API服务器，但白名单可能没有及时收录或者本地白名单没有更新到最新，就会触发风控之类的机制。比如我的京东白条红包，失手挂着白名单VPN触发了一次风控，到现在领红包都提示我IP地址异常无法领取。
> > > 除了上述原因之外，gfwlist还有一个白名单无可替代的功能，就是作为一个风向标指示现在的政治风向，是偏左还是偏右，收紧还是放宽，我个人还是挺喜欢观察这些细节的。
> > 
> > 
> > 性能差异也就毫秒级别，平常运行一个QQ的APP都比这个操作耗电量大，白名单也包含API地址，这些API很快就会被收录，（涉及购物密码操作的，为什么还要开着代理），gfwlist的地址是人为提交到这个项目由作者统一添加的，可能一年前就已经封锁了，只是到了现在才被人发现，时间差导致你看到的风向标完全是错误的
> 
> 嘛，我们这个讨论稍微有些跑题了，花大段的篇幅讨论“你虽然举了个例子但只是个案”、“你说的缺点其实不是缺点而是你操作有问题”或者“你说的优点并没有那么优秀所以不算优点”，跟cicku的这条issue关系不大，这条issue我觉得还是应该回归到gfwlist的维护问题上。
> 至于gfwlist该不该继续维护下去，我觉得其实是一个需要用户用脚投票的事情，黑白名单切换起来也就是一个按钮或者两行代码的事情，如果大家都觉得黑名单不好用，自然也就不会再过来提issue或者访问仓库，项目自然而然也就消亡了。
> 而现在的现状是众多的项目和用户仍然在依赖gfwlist这个项目，就算gfwlist停止维护了，也大概率会有人开一个新项目继续做黑名单，那么我觉得优化现有的gfwlist维护流程就是有意义的。

是我跑题了，sorry，这种优化技术确实可以应用到不止是gfwlist的项目上，只能等待另一个人接手的时候再考虑如何优化了

**Comment by Daymond** [comment]
> 
> 
> > 话说我之前看到这个项目的时候就在想了，gfwlist作为这么重要的一个项目居然要依靠一名管理员手动维护，其他人只一股脑地提交issue，这个工作量也太大了。
> > 我们可不可以把这个流程机械化、自动化，在项目里放一个明文的gfwlist文件，其他人可以提交PR来修改这个明文list，一旦明文list得到2到3个maintainer的approve，就自动合并到master分支并且触发一次CI/CD，由TravisCI之类的系统自动把明文list编码成gfwlist.txt，那么维护压力应该会大为减小。
> 
> 一般地，认为白名单模式（全局代理+绕过大陆局域网路由模式）更加好，因为国内的网站都是可查询到的（甚至有正规网站提供这些国内域名或者IP），隔壁的v2ray增强项目已经有7万多个中国域名，89亿个中国IP地址记录在内（比gfwlist的5800多个域名多了很多了），已经完美取代这个项目了

有推荐的白名单列表项目么？

**Comment by lizenghui** [comment]
不管黑名单  还是白名单。
萝卜青菜各有所爱，我个人喜欢gfwlist黑名单，因为不是所有境外网站都被墙，能正常使用的还是直连最舒服。
所以还是希望gfwlist能找到一种优雅的维护方案，让喜欢他的人都参与进来。

**Comment by DoTime** [comment]
https://github.com/FelisCatus/SwitchyOmega/issues/2035#issuecomment-620318723
觉得这个可行吗?
![image](https://user-images.githubusercontent.com/15666939/81630121-5d70b100-9437-11ea-8446-b65f85ae3b1f.png)

**Comment by Gh0u1L5** [comment]
> 
> 
> [FelisCatus/SwitchyOmega#2035 (comment)](https://github.com/FelisCatus/SwitchyOmega/issues/2035#issuecomment-620318723)
> 觉得这个可行吗?
> ![image](https://user-images.githubusercontent.com/15666939/81630121-5d70b100-9437-11ea-8446-b65f85ae3b1f.png)

唔，汇总的话，这些数据会在哪里合并处理呢？如果需要投入资金单独维护一台服务器的话，可能会给服务器的维护人员带来不必要的风险，我是出于这个考虑才建议直接利用GitHub的现有系统的。

**Comment by DoTime** [comment]
> > [FelisCatus/SwitchyOmega#2035 (comment)](https://github.com/FelisCatus/SwitchyOmega/issues/2035#issuecomment-620318723)
> > 觉得这个可行吗?
> > ![image](https://user-images.githubusercontent.com/15666939/81630121-5d70b100-9437-11ea-8446-b65f85ae3b1f.png)
> 
> 唔，汇总的话，这些数据会在哪里合并处理呢？如果需要投入资金单独维护一台服务器的话，可能会给服务器的维护人员带来不必要的风险，我是出于这个考虑才建议直接利用GitHub的现有系统的。

公用的黑名单可以在gfwlist现有基础上做一个,汇总也不是必须的 用户自己维护一个自己的就可以.

**Comment by cicku** [comment]
> > > Ummm，但是白名单的缺点也挺明显的。最直接的一点就是白名单的规模太大了，每发起一个新连接都要在7万域名和若干IP段里查表匹配，PC端可能压力不大，但手机端的ping值和耗电量应该都会有明显增长吧。其次白名单有时候会触发一些微妙的bug，一些大厂手机APP会在后台访问一些私有的API服务器，但白名单可能没有及时收录或者本地白名单没有更新到最新，就会触发风控之类的机制。比如我的京东白条红包，失手挂着白名单VPN触发了一次风控，到现在领红包都提示我IP地址异常无法领取。
> > > 除了上述原因之外，gfwlist还有一个白名单无可替代的功能，就是作为一个风向标指示现在的政治风向，是偏左还是偏右，收紧还是放宽，我个人还是挺喜欢观察这些细节的。
> > 
> > 
> > 性能差异也就毫秒级别，平常运行一个QQ的APP都比这个操作耗电量大，白名单也包含API地址，这些API很快就会被收录，（涉及购物密码操作的，为什么还要开着代理），gfwlist的地址是人为提交到这个项目由作者统一添加的，可能一年前就已经封锁了，只是到了现在才被人发现，时间差导致你看到的风向标完全是错误的
> 
> 嘛，我们这个讨论稍微有些跑题了，花大段的篇幅讨论“你虽然举了个例子但只是个案”、“你说的缺点其实不是缺点而是你操作有问题”或者“你说的优点并没有那么优秀所以不算优点”，跟cicku的这条issue关系不大，这条issue我觉得还是应该回归到gfwlist的维护问题上。
> 至于gfwlist该不该继续维护下去，我觉得其实是一个需要用户用脚投票的事情，黑白名单切换起来也就是一个按钮或者两行代码的事情，如果大家都觉得黑名单不好用，自然也就不会再过来提issue或者访问仓库，项目自然而然也就消亡了。
> 而现在的现状是众多的项目和用户仍然在依赖gfwlist这个项目，就算gfwlist停止维护了，也大概率会有人开一个新项目继续做黑名单，那么我觉得优化现有的gfwlist维护流程就是有意义的。

我只是最近很忙而已...

**Comment by Gh0u1L5** [comment]
> 
> 我只是最近很忙而已...
😄 所以repo主 @cicku 对我的提案什么看法？赞同的话我倒是不介意周末花点时间简单写一下Travis CI脚本，只是写之前可能需要repo主提供一下平时更新gfwlist的步骤和相应脚本，以免有所遗漏。

**Comment by cicku** [comment]
@Gh0u1L5 https://github.com/gfwlist/apollyon

**Comment by Loyalsoldier** [comment]
I find it hard to automate the whole process.

The biggest problem is that it is hard to get neat domains or URLs from users' feedback/input in GitHub issues. Unformatted domains or URLs in GitHub issues will lead to failure to the automation process.

My perfect idea is to use GitHub API to get domains or URLs in GitHub issues, then check the rules, git commit and push.

**Comment by kslr** [comment]
> I find it hard to automate the whole process.
> 
> The biggest problem is that it is hard to get neat domains or URLs from users' feedback/input in GitHub issues. Unformatted domains or URLs in GitHub issues will lead to failure to the automation process.
> 
> IMO, the perfect idea is to use GitHub API to get domains or URLs in GitHub issues, then check the rules, git commit and push.

issue template

**Comment by Gh0u1L5** [comment]
> 
> 
> I find it hard to automate the whole process.
> 
> The biggest problem is that it is hard to get neat domains or URLs from users' feedback/input in GitHub issues. Unformatted domains or URLs in GitHub issues will lead to failure to the automation process.
> 
> IMO, the perfect idea is to use GitHub API to get domains or URLs in GitHub issues, then check the rules, git commit and push.

There's no need to do those NLP tricks. We just need to create a issue template, notify people that we no longer support reporting GFW changes via issues, if you want to change something, go make a PR. So the guys can just change a plaintext gfwlist, and the plaintext list can be automatically encoded and published to the Internet.

**Comment by cyfex** [comment]
> > > 话说我之前看到这个项目的时候就在想了，gfwlist作为这么重要的一个项目居然要依靠一名管理员手动维护，其他人只一股脑地提交issue，这个工作量也太大了。
> > > 我们可不可以把这个流程机械化、自动化，在项目里放一个明文的gfwlist文件，其他人可以提交PR来修改这个明文list，一旦明文list得到2到3个maintainer的approve，就自动合并到master分支并且触发一次CI/CD，由TravisCI之类的系统自动把明文list编码成gfwlist.txt，那么维护压力应该会大为减小。
> > 
> > 
> > 一般地，认为白名单模式（全局代理+绕过大陆局域网路由模式）更加好，因为国内的网站都是可查询到的（甚至有正规网站提供这些国内域名或者IP），隔壁的v2ray增强项目已经有7万多个中国域名，89亿个中国IP地址记录在内（比gfwlist的5800多个域名多了很多了），已经完美取代这个项目了
> 
> Ummm，但是白名单的缺点也挺明显的。最直接的一点就是白名单的规模太大了，每发起一个新连接都要在7万域名和若干IP段里查表匹配，PC端可能压力不大，但手机端的ping值和耗电量应该都会有明显增长吧。其次白名单有时候会触发一些微妙的bug，一些大厂手机APP会在后台访问一些私有的API服务器，但白名单可能没有及时收录或者本地白名单没有更新到最新，就会触发风控之类的机制。比如我的京东白条红包，失手挂着白名单VPN触发了一次风控，到现在领红包都提示我IP地址异常无法领取。 除了上述原因之外，gfwlist还有一个白名单无可替代的功能，就是作为一个风向标指示现在的政治风向，是偏左还是偏右，收紧还是放宽，我个人还是挺喜欢观察这些细节的。

性能问题真的不是一个哈希表加一个查找树就能解决的吗？

**Comment by Gh0u1L5** [comment]
@cyfex IP段数据查找优化很好做，但是域名没那么简单。各家项目的geosite数据库里面都有很多类似正则表达式的规则，因为很多网站，尤其是CDN站点，会动态创建一堆xx1.com, xx2.com, [sha1].cloudxxx.net的域名，这些域名不是特别稳定，时不时就会有新增，如果直接写死的话会有很多麻烦。
这套东西的性能优化挺复杂的，开源社区做了好几套方案。比如GFWList在用的Adblock Filter，会先把简单的、可以进行性能优化的规则识别出来，打包成一些合适的trie结构，这些结构中没匹配上才会去跑剩下那些实在无法优化的结构。
我很久之前在路由器常用的MTK平台上benchmark过这套东西，具体数据不记得了，但是性能损耗是相当明显的。
