### ISSUE TITLE
小白求助：折腾OpenWRT回国翻墙的问题陈述，解锁国内的流媒体服务，比如爱奇艺

### ISSUE THREAD

**Issue by LaureatePoet** [gfwlist/gfwlist#1948]
目前的现状：OpenWRT系统的路由作为旁路由（网关服务器）去实现功能，在使用S~S~R PLUS 模式中：海外回国模式 不能解锁网易云、爱奇艺。全局模式可以，但会影响到自己使用其他服务比如Netflix。

像求助如何编辑GFWlist，解决我的需求。谢谢大佬拯救
----
# 折腾OpenWRT回国翻墙的问题陈述

## 环境
 * 宽带：2G带宽(号称，很少见过)
 * 光猫：ZTE F660A的ONU
    * 自带路由功能，**就是主路由**
* 旁路由：一台旧电脑（一个网口，Windows环境）
    * Windows 7 环境下安装VMware，在虚拟机环境下安装的Openwrt系统（[固件下载地址-虚拟机版](https://drive.google.com/drive/folders/1pdJuzpwuhdq6vnN0Ovtb5r-JB7Z5bw38)）
 ![Openwrt系统详情](https://s1.ax1x.com/2020/05/03/YS5fjH.png)

* 硬路由：RX120 做 AP（Access Point）

## 连接配置
 光猫（主路由） **LAN**  → 旧电脑（旁路由）**唯一的网口**
* 光猫IP: `192.168.1.1`
* 旁路由: `192.1681.100`

RX120直接作为AP

## **需求**：
人在国外，需要解锁国内的流媒体，例如腾讯视频，爱奇艺。

## 配置过程
在安装好OpenWRT后，关闭了它的DHCP、ipv6等服务。设置旁路由的网关为`192.168.1.1`，配置好`S~S！R`服务后，客户机（比如手机、其他电脑）设置静态ip、DNS，**设置网关为** `192.168.1.100` 这样便使用了旁路由的网关功能。

### 折腾好久之后没有结果的GFW方法

经过**回国模式**、**全局模式**不断的BUG，我们转向使用GFW列表模式

参考[Shadowsocks-Back-China-PAC](https://github.com/groundcat/Shadowsocks-Back-China-PAC)的PAC文件，我编辑了GFW.TXT [base64加密前的文本](https://paste.ubuntu.com/p/Tpx7sCy9Bx/),并经过base64加密生成如下文件

```
W0F1dG9Qcm94eSAwLjIuOV0KISBUaXRsZTogR0ZXTGlzdCBCQUNLIFRPIENOCiEg
R0ZXTGlzdCB3aXRoIFVubG9jayBDSElOQSBzdHJlYW1pbmcKISBDaGluZXNlIHNl
Y29uZGFyeSBkb21haW4KfHxlZHUuY24KfHxnb3YuY24KISBBY0Z1bgp8fGFjZnVu
LmNuCnx8YWNmdW4uY29tCnx8YWl4aWZhbi5jb20KISBOZXRlYXNlCnx8MTYzLmNv
bQp8fDEyNi5jb20KfHwxMjcubmV0Cnx8bmV0ZWFzZS5jb20KfHwxNjN5dW4uY29t
Cnx8MTI2Lm5ldAohIFRlbmNlbnQKfHxxcS5jb20KfHxzb3NvLmNvbQp8fHFwaWMu
Y24KfHxndGltZy5jbgp8fHdlaXhpbi5jb20KfHxxbG9nby5jbgohIFNpbnMKfHx3
ZWliby5jb20KfHxzaW5hanMuY24KfHxzaW5hLmNvbQp8fHNpbmEuY24KfHxzaW5h
LmNvbS5jbgp8fHNpbmFpbWcuY24KfHxzaW5hanMuY24KfHxtaWFvcGFpLmNvbQp8
fHhpYW9rYS50dgp8fHQuY24KISBBbGliYWJhCnx8YWxpeXVuLmNvbQp8fHRhb2Jh
by5jb20KfHxhbGljZG4uY29tCnx8dG1hbGwuY29tCnx8bW1zdGF0LmNvbQp8fHRi
Y2RuLmNvbQp8fGFsaWJhYmFjbG91ZC5jb20KfHxhbGlwYXkuY29tCnx8aGljaGlu
YS5jb20KfHx4aWFtaS5jb20KfHx4aWFtaS5uZXQKISBCYWlkdQp8fGJhaWR1LmNv
bQp8fGJkc3RhdGljLmNvbQp8fGJjZWJvcy5jb20KfHxiYWlkdXBjcy5jb20KfHxx
aWFucWlhbi5jb20KISBCaWxpYmlsaQp8fGhkc2xiLmNvbQp8fGJpbGliaWxpLmNv
bQp8fGdlZXRlc3QuY29tCnx8YWNndmlkZW8uY29tCiEgaHVuYW5UVgp8fGhpdHYu
Y29tCnx8aHVuYW50di5jb20KfHxtZ3R2LmNvbQohIE1pZ3UKfHxjbXZpZGVvLmNu
Cnx8bWlndS5jbgp8fG1pZ3V2aWRlby5jb20KISBZb3VrdQp8fHNva3UuY29tCnx8
eW91a3UuY29tCnx8eWtpbWcuY29tCiEgaXFpeWkKfHxpcWl5aS5jb20KfHxpcWl5
aXBpYy5jb20KfHxxeS5uZXQKISBzb2h1Cnx8c29odS5jb20KfHxzb2h1LmNvbS5j
bgp8fGl0Yy5jbgp8fHYtNTYuY29tCiEgS3Vnb3UsIEt1d28KfHxrdWdvdS5jb20K
fHxrdXdvLmNuCnx8a29vd28uY29tCiEgemhpaHUKfHx6aGlodS5jb20KfHx6aGlt
Zy5jb20KISB4aXVtaQp8fHhpdW1pLnVzCiEgZG91YmFuCnx8ZG91YmFuLmNvbQp8
fGRvdWJhbmlvLmNvbQohIHRpYW55YW5jaGEKfHx0aWFueWFuY2hhLmNvbQoKISBJ
UCBhZGRyZXNzIHRlc3QKfHxpcDEzOC5jb20=
```
经过尝试 仍然无法解锁国内的地区限制服务，例如网易云音乐、腾讯视频、爱奇艺。

看到了 @ydq [楼上](https://github.com/gfwlist/gfwlist/issues/1948#issuecomment-623078425)的提示，我也尝试了将GFW切换为[tsilwfg](https://github.com/gfwlist/tsilwfg)，仍然没有结果。到这里我已经没有招数了，所以上网前来求助各位大佬

<font color="#dd0000">**另外当我在路由后台设置了GFW列表url后**，在状态里面无法更新GFW列表我不知道为什么</font><br /> 

见附录图片

## 情况描述

* 海外回国模式 || 测试时间：2020/5/3	8:06 PM

    | 服务 | 是否解锁 | 备注 |
    | :-----:| :-----: | :----: |
    | 腾讯视频 | 是✔ | 正常 |
    | 爱奇艺 | 否❌ | 地区受限 |
    | 网易云音乐 | 否❌ | 地区受限 |
    | Youtube | ✔ | 没问题 |
    | Google | ✔ | 没问题 |
    | Amazon Japan | ✔ | 没问题 |

    | 速度测试情况 | 速度 | 备注 |
    | :-----:| :-----: | :----: |
    | fast.com | 780Mbps | |
    | speedtest.org | 328Mbps |  |

    | ip测试情况 | 情况 | 备注 |
    | :-----:| :-----: | :----: |
    | www.ip111.cn | ![](https://s1.ax1x.com/2020/05/03/YpPVMj.png) |  |
    | https://ip.skk.moe | ![](https://s1.ax1x.com/2020/05/03/YpP3z4.png) |  |

* 全局模式（使用的广州的节点）|| 测试时间： 2020/5/3	7:52 PM

    | 服务 | 是否解锁/访问 | 备注 |
    | :-----:| :-----: | :----: |
    | 腾讯视频 | 是✔ | 正常 |
    | 爱奇艺 | 是✔ | 解决 |
    | 网易云音乐 | 不稳定✔ | 有的时候可以有的时候不可以 |
    | Youtube | ✔💀 | 全局模式不应该可以访问啊 |
    | Google | ✔💀 | 全局模式不应该可以访问啊 |
    | Amazon Japan | ❌ | 正常，全局本不能访问 |

    | 速度测试情况 | 速度 | 备注 |
    | :-----:| :-----: | :----: |
    | fast.com | 380Mbps | |
    | speedtest.org | 122Mbps | ![全局ST](https://s1.ax1x.com/2020/05/03/YpCqPO.png) |

    | ip测试情况 | 情况 | 备注 |
    | :-----:| :-----: | :----: |
    | www.ip111.cn | ![](https://s1.ax1x.com/2020/05/03/YpCzqI.png) |  |
    | https://ip.skk.moe | ![](https://s1.ax1x.com/2020/05/03/YpP9dP.png) |  |

* 不开启`S~S！R`  但客户机走“旁路由网关” || 2020/5/3	8:11 PM 

    | 服务 | 是否解锁 | 备注 |
    | :-----:| :-----: | :----: |
    | 腾讯视频 | 否❌ | 地区受限 |
    | 爱奇艺 | 否❌ | 地区受限 |
    | 网易云音乐 | 否❌ | 地区受限 |
    | Youtube | ✔ | 没问题 |
    | Google | ✔ | 没问题 |
    | Amazon Japan | ✔ | 没问题 |

    | 速度测试情况 | 速度 | 备注 |
    | :-----:| :-----: | :----: |
    | fast.com | 850Mbps | |
    | speedtest.org | 296Mbps | ![](https://s1.ax1x.com/2020/05/03/YpPYLR.png) |

    | ip测试情况 | 情况 | 备注 |
    | :-----:| :-----: | :----: |
    | www.ip111.cn | ![](https://s1.ax1x.com/2020/05/03/YpPBWD.png) |  |
    | https://ip.skk.moe | ![](https://s1.ax1x.com/2020/05/03/YpPgeI.png) |  |

* 不开启`S~S！R`  但客户机走“主路由网关” || 2020/5/3	8:26 PM

    | 服务 | 是否解锁 | 备注 |
    | :-----:| :-----: | :----: |
    | 腾讯视频 | 否❌ | 地区受限 |
    | 爱奇艺 | 否❌ | 地区受限 |
    | 网易云音乐 | 否❌ | 地区受限 |
    | Youtube | ✔ | 没问题 |
    | Google | ✔ | 没问题 |
    | Amazon Japan | ✔ | 没问题 |

    | 速度测试情况 | 速度 | 备注 |
    | :-----:| :-----: | :----: |
    | fast.com | 930Mbps | |
    | speedtest.org | 347Mbps |  |

    | ip测试情况 | 情况 | 备注 |
    | :-----:| :-----: | :----: |
    | www.ip111.cn | ![](https://s1.ax1x.com/2020/05/03/YpPBWD.png) |  |
    | https://ip.skk.moe | ![](https://s1.ax1x.com/2020/05/03/YpPgeI.png) |  |

## 问题描述（各种BUG）
1. 全局模式下：Google、Youtube都可以访问（黑人问好？？？），全局模式不应该就相当于全部走代理吗?我广州的节点为什么可以访问Google、YouTube呢？
2. 根据 “1.”提到的， 全局模式下可以访问Google、Youtube，但是不可以访问**亚马逊购物网站**
3. 当`S~S!R`打开的时候，旧电脑（运行虚拟机的客户机）网关设置为`192.168.1.1`时，除了YouTube、Google之外所有网站（包括国内国外）都打不开，像极了无法上网。但是如果其他设备比如手机恢复默认网关`192.168.1.1`正常上网是没有问题的；当`S~S!R`关闭的时候，没有上述问题。
4. 全局模式时 电报（Telegram）没法使用。回国模式，电报（Telegram）可以使用

## 其他
1. 在尝试求解的过程中，尝试刷过Openwrt的SSRPLUS的ipk文件，仍然没有结果，所以可以认为不是插件的锅。
2. OpenWRT虚拟镜像是网上下载的，应该是没有问题的

## 求助
* 希望大佬可以指导一下，是不是自己目前的网络拓扑有问题，抑或是软路由固件的问题，或者是网络设置的缘故。
* 家里网络有没有更好的配置方案，感觉NETGEAR RX120作为AP有点浪费了。（比如光猫改成桥接模式，只拨号，DHCP交给RX120）
* 在这样的需求（**解锁爱奇艺腾讯视频**）和目前的环境的情况下，有没有更好的解决方案 （*只考虑路由器端完成科学上网*）

## 附录
一些图片
![](https://s1.ax1x.com/2020/05/03/Yppyyn.png)
![](https://s1.ax1x.com/2020/05/03/YppDzj.png)
![](https://s1.ax1x.com/2020/05/03/YppsQs.png)
![](https://s1.ax1x.com/2020/05/03/YppBWQ.png)

**Comment by ydq** [comment]
将gfwlist倒过来拼就可以了：https://github.com/gfwlist/tsilwfg

**Comment by LaureatePoet** [comment]
# 折腾OpenWRT回国翻墙的问题陈述

## 环境
 * 宽带：2G带宽(号称，很少见过)
 * 光猫：ZTE F660A的ONU
    * 自带路由功能，**就是主路由**
* 旁路由：一台旧电脑（一个网口，Windows环境）
    * Windows 7 环境下安装VMware，在虚拟机环境下安装的Openwrt系统（[固件下载地址-虚拟机版](https://drive.google.com/drive/folders/1pdJuzpwuhdq6vnN0Ovtb5r-JB7Z5bw38)）
 ![Openwrt系统详情](https://s1.ax1x.com/2020/05/03/YS5fjH.png)

* 硬路由：RX120 做 AP（Access Point）

## 连接配置
 光猫（主路由） **LAN**  → 旧电脑（旁路由）**唯一的网口**
* 光猫IP: `192.168.1.1`
* 旁路由: `192.1681.100`


RX120直接作为AP

## **需求**：
人在国外，需要解锁国内的流媒体，例如腾讯视频，爱奇艺。

## 配置过程
在安装好OpenWRT后，关闭了它的DHCP、ipv6等服务。设置旁路由的网关为`192.168.1.1`，配置好`S~S！R`服务后，客户机（比如手机、其他电脑）设置静态ip、DNS，**设置网关为** `192.168.1.100` 这样便使用了旁路由的网关功能。


### 折腾好久之后没有结果的GFW方法

经过**回国模式**、**全局模式**不断的BUG，我们转向使用GFW列表模式

参考[Shadowsocks-Back-China-PAC](https://github.com/groundcat/Shadowsocks-Back-China-PAC)的PAC文件，我编辑了GFW.TXT [base64加密前的文本](https://paste.ubuntu.com/p/Tpx7sCy9Bx/),并经过base64加密生成如下文件

```
W0F1dG9Qcm94eSAwLjIuOV0KISBUaXRsZTogR0ZXTGlzdCBCQUNLIFRPIENOCiEg
R0ZXTGlzdCB3aXRoIFVubG9jayBDSElOQSBzdHJlYW1pbmcKISBDaGluZXNlIHNl
Y29uZGFyeSBkb21haW4KfHxlZHUuY24KfHxnb3YuY24KISBBY0Z1bgp8fGFjZnVu
LmNuCnx8YWNmdW4uY29tCnx8YWl4aWZhbi5jb20KISBOZXRlYXNlCnx8MTYzLmNv
bQp8fDEyNi5jb20KfHwxMjcubmV0Cnx8bmV0ZWFzZS5jb20KfHwxNjN5dW4uY29t
Cnx8MTI2Lm5ldAohIFRlbmNlbnQKfHxxcS5jb20KfHxzb3NvLmNvbQp8fHFwaWMu
Y24KfHxndGltZy5jbgp8fHdlaXhpbi5jb20KfHxxbG9nby5jbgohIFNpbnMKfHx3
ZWliby5jb20KfHxzaW5hanMuY24KfHxzaW5hLmNvbQp8fHNpbmEuY24KfHxzaW5h
LmNvbS5jbgp8fHNpbmFpbWcuY24KfHxzaW5hanMuY24KfHxtaWFvcGFpLmNvbQp8
fHhpYW9rYS50dgp8fHQuY24KISBBbGliYWJhCnx8YWxpeXVuLmNvbQp8fHRhb2Jh
by5jb20KfHxhbGljZG4uY29tCnx8dG1hbGwuY29tCnx8bW1zdGF0LmNvbQp8fHRi
Y2RuLmNvbQp8fGFsaWJhYmFjbG91ZC5jb20KfHxhbGlwYXkuY29tCnx8aGljaGlu
YS5jb20KfHx4aWFtaS5jb20KfHx4aWFtaS5uZXQKISBCYWlkdQp8fGJhaWR1LmNv
bQp8fGJkc3RhdGljLmNvbQp8fGJjZWJvcy5jb20KfHxiYWlkdXBjcy5jb20KfHxx
aWFucWlhbi5jb20KISBCaWxpYmlsaQp8fGhkc2xiLmNvbQp8fGJpbGliaWxpLmNv
bQp8fGdlZXRlc3QuY29tCnx8YWNndmlkZW8uY29tCiEgaHVuYW5UVgp8fGhpdHYu
Y29tCnx8aHVuYW50di5jb20KfHxtZ3R2LmNvbQohIE1pZ3UKfHxjbXZpZGVvLmNu
Cnx8bWlndS5jbgp8fG1pZ3V2aWRlby5jb20KISBZb3VrdQp8fHNva3UuY29tCnx8
eW91a3UuY29tCnx8eWtpbWcuY29tCiEgaXFpeWkKfHxpcWl5aS5jb20KfHxpcWl5
aXBpYy5jb20KfHxxeS5uZXQKISBzb2h1Cnx8c29odS5jb20KfHxzb2h1LmNvbS5j
bgp8fGl0Yy5jbgp8fHYtNTYuY29tCiEgS3Vnb3UsIEt1d28KfHxrdWdvdS5jb20K
fHxrdXdvLmNuCnx8a29vd28uY29tCiEgemhpaHUKfHx6aGlodS5jb20KfHx6aGlt
Zy5jb20KISB4aXVtaQp8fHhpdW1pLnVzCiEgZG91YmFuCnx8ZG91YmFuLmNvbQp8
fGRvdWJhbmlvLmNvbQohIHRpYW55YW5jaGEKfHx0aWFueWFuY2hhLmNvbQoKISBJ
UCBhZGRyZXNzIHRlc3QKfHxpcDEzOC5jb20=
```
经过尝试 仍然无法解锁国内的地区限制服务，例如网易云音乐、腾讯视频、爱奇艺。

看到了 @ydq [楼上](https://github.com/gfwlist/gfwlist/issues/1948#issuecomment-623078425)的提示，我也尝试了将GFW切换为[tsilwfg](https://github.com/gfwlist/tsilwfg)，仍然没有结果。到这里我已经没有招数了，所以上网前来求助各位大佬


<font color="#dd0000">**另外当我在路由后台设置了GFW列表url后**，在状态里面无法更新GFW列表我不知道为什么</font><br /> 

见附录图片

## 情况描述

* 海外回国模式 || 测试时间：2020/5/3	8:06 PM

    | 服务 | 是否解锁 | 备注 |
    | :-----:| :-----: | :----: |
    | 腾讯视频 | 是✔ | 正常 |
    | 爱奇艺 | 否❌ | 地区受限 |
    | 网易云音乐 | 否❌ | 地区受限 |
    | Youtube | ✔ | 没问题 |
    | Google | ✔ | 没问题 |
    | Amazon Japan | ✔ | 没问题 |


    | 速度测试情况 | 速度 | 备注 |
    | :-----:| :-----: | :----: |
    | fast.com | 780Mbps | |
    | speedtest.org | 328Mbps |  |

    | ip测试情况 | 情况 | 备注 |
    | :-----:| :-----: | :----: |
    | www.ip111.cn | ![](https://s1.ax1x.com/2020/05/03/YpPVMj.png) |  |
    | https://ip.skk.moe | ![](https://s1.ax1x.com/2020/05/03/YpP3z4.png) |  |

* 全局模式（使用的广州的节点）|| 测试时间： 2020/5/3	7:52 PM

    | 服务 | 是否解锁/访问 | 备注 |
    | :-----:| :-----: | :----: |
    | 腾讯视频 | 是✔ | 正常 |
    | 爱奇艺 | 是✔ | 解决 |
    | 网易云音乐 | 不稳定✔ | 有的时候可以有的时候不可以 |
    | Youtube | ✔💀 | 全局模式不应该可以访问啊 |
    | Google | ✔💀 | 全局模式不应该可以访问啊 |
    | Amazon Japan | ❌ | 正常，全局本不能访问 |

    | 速度测试情况 | 速度 | 备注 |
    | :-----:| :-----: | :----: |
    | fast.com | 380Mbps | |
    | speedtest.org | 122Mbps | ![全局ST](https://s1.ax1x.com/2020/05/03/YpCqPO.png) |

    | ip测试情况 | 情况 | 备注 |
    | :-----:| :-----: | :----: |
    | www.ip111.cn | ![](https://s1.ax1x.com/2020/05/03/YpCzqI.png) |  |
    | https://ip.skk.moe | ![](https://s1.ax1x.com/2020/05/03/YpP9dP.png) |  |

* 不开启`S~S！R`  但客户机走“旁路由网关” || 2020/5/3	8:11 PM 

    | 服务 | 是否解锁 | 备注 |
    | :-----:| :-----: | :----: |
    | 腾讯视频 | 否❌ | 地区受限 |
    | 爱奇艺 | 否❌ | 地区受限 |
    | 网易云音乐 | 否❌ | 地区受限 |
    | Youtube | ✔ | 没问题 |
    | Google | ✔ | 没问题 |
    | Amazon Japan | ✔ | 没问题 |


    | 速度测试情况 | 速度 | 备注 |
    | :-----:| :-----: | :----: |
    | fast.com | 850Mbps | |
    | speedtest.org | 296Mbps | ![](https://s1.ax1x.com/2020/05/03/YpPYLR.png) |

    | ip测试情况 | 情况 | 备注 |
    | :-----:| :-----: | :----: |
    | www.ip111.cn | ![](https://s1.ax1x.com/2020/05/03/YpPBWD.png) |  |
    | https://ip.skk.moe | ![](https://s1.ax1x.com/2020/05/03/YpPgeI.png) |  |

* 不开启`S~S！R`  但客户机走“主路由网关” || 2020/5/3	8:26 PM

    | 服务 | 是否解锁 | 备注 |
    | :-----:| :-----: | :----: |
    | 腾讯视频 | 否❌ | 地区受限 |
    | 爱奇艺 | 否❌ | 地区受限 |
    | 网易云音乐 | 否❌ | 地区受限 |
    | Youtube | ✔ | 没问题 |
    | Google | ✔ | 没问题 |
    | Amazon Japan | ✔ | 没问题 |


    | 速度测试情况 | 速度 | 备注 |
    | :-----:| :-----: | :----: |
    | fast.com | 930Mbps | |
    | speedtest.org | 347Mbps |  |

    | ip测试情况 | 情况 | 备注 |
    | :-----:| :-----: | :----: |
    | www.ip111.cn | ![](https://s1.ax1x.com/2020/05/03/YpPBWD.png) |  |
    | https://ip.skk.moe | ![](https://s1.ax1x.com/2020/05/03/YpPgeI.png) |  |

## 问题描述（各种BUG）
1. 全局模式下：Google、Youtube都可以访问（黑人问好？？？），全局模式不应该就相当于全部走代理吗?我广州的节点为什么可以访问Google、YouTube呢？
2. 根据 “1.”提到的， 全局模式下可以访问Google、Youtube，但是不可以访问**亚马逊购物网站**
3. 当`S~S!R`打开的时候，旧电脑（运行虚拟机的客户机）网关设置为`192.168.1.1`时，除了YouTube、Google之外所有网站（包括国内国外）都打不开，像极了无法上网。但是如果其他设备比如手机恢复默认网关`192.168.1.1`正常上网是没有问题的；当`S~S!R`关闭的时候，没有上述问题。
4. 全局模式时 电报（Telegram）没法使用。回国模式，电报（Telegram）可以使用

## 其他
1. 在尝试求解的过程中，尝试刷过Openwrt的SSRPLUS的ipk文件，仍然没有结果，所以可以认为不是插件的锅。
2. OpenWRT虚拟镜像是网上下载的，应该是没有问题的

## 求助
* 希望大佬可以指导一下，是不是自己目前的网络拓扑有问题，抑或是软路由固件的问题，或者是网络设置的缘故。
* 家里网络有没有更好的配置方案，感觉NETGEAR RX120作为AP有点浪费了。（比如光猫改成桥接模式，只拨号，DHCP交给RX120）
* 在这样的需求（**解锁爱奇艺腾讯视频**）和目前的环境的情况下，有没有更好的解决方案 （*只考虑路由器端完成科学上网*）


## 附录
一些图片
![](https://s1.ax1x.com/2020/05/03/Yppyyn.png)
![](https://s1.ax1x.com/2020/05/03/YppDzj.png)
![](https://s1.ax1x.com/2020/05/03/YppsQs.png)
![](https://s1.ax1x.com/2020/05/03/YppBWQ.png)

**Comment by LaureatePoet** [comment]
> 将gfwlist倒过来拼就可以了：https://github.com/gfwlist/tsilwfg

大佬，可以帮我看看我上述补充的吗。🤕

**Comment by lizenghui** [comment]
看样子是DNS问题，具体可以电报联系我@lizenghui 帮你看看   挺简单的问题

**Comment by LaureatePoet** [comment]
@lizenghui 感谢大佬！我已经电报联系您了。

**Comment by zhushp** [comment]
@LaureatePoet 大哥我跟你的问题一模一样，你的解决了吗？

**Comment by greenmickey123** [comment]
我也遇到了同样的问题, 请问大佬最后是怎么解决的?

**Comment by zhushp** [comment]
> 我也遇到了同样的问题, 请问大佬最后是怎么解决的?

@greenmickey123 没有解决，感觉是爱奇艺会通过不在回国列表里的网址来检测用户是不是在国外，所以全局回国才能使用。

话说最近机场里的回国线路都下线了，你怎么回国的呢？

**Comment by zzm88** [comment]
> > 我也遇到了同样的问题, 请问大佬最后是怎么解决的?
> 
> @greenmickey123 没有解决，感觉是爱奇艺会通过不在回国列表里的网址来检测用户是不是在国外，所以全局回国才能使用。
> 
> 话说最近机场里的回国线路都下线了，你怎么回国的呢？

我遇到类似的问题，openwrt里开酸酸乳gfw模式就看不到爱奇艺了

**Comment by cicku** [comment]
有个子项目是讨论这个的GitHub.com/GFWList/tsilwfg，不过我很久没动了。如果有不在列表里面的网址，欢迎上报。

**Comment by shermanx** [comment]
把hk的ip也加进去（回国模式的rule）试下？

**Comment by weiba127** [comment]
问下， 你这个广州节点咋搞的？
