### ISSUE TITLE
dropbox api domains

### ISSUE THREAD

**Issue by gera2ld** [gfwlist/gfwlist#195]
```
||api.dropboxapi.com
||content.dropboxapi.com
```

**Comment by cicku** [comment]
content.dropboxapi.com 无法确认。

**Comment by s7lx** [comment]
api.dropboxapi.com 确认被墙
content.dropboxapi.com 确认可连

**Comment by gera2ld** [comment]
上海电信两个都连不上。
http://www.greatfirewallofchina.org/index.php?siteurl=content.dropboxapi.com 这里测试也是挂的。。

**Comment by gera2ld** [comment]
好吧，是DNS污染了，要close吗？

**Comment by cicku** [comment]
不用，我继续跟踪
