### ISSUE TITLE
请求添加https://www.notion.so/

### ISSUE THREAD

**Issue by qimy0521** [gfwlist/gfwlist#1958]
https://www.notion.so/

**Comment by lxk0301** [comment]
notion.so现在也被墙了。 也要添加了呀

**Comment by aquariuslt** [comment]
> notion.so现在也被墙了。 也要添加了呀

https://twitter.com/NotionStatus/status/1264713745105707009

Notion is blocked by a firewall in China. We are monitoring the situation and will continue to post updates.

8:23 AM · May 25, 2020

**Comment by gundaz-aghayev** [comment]
可以正常访问哦

**Comment by aquariuslt** [comment]
> 可以正常访问哦

后来貌似谈好了，又OK了

**Comment by cicku** [comment]
感谢反馈，如果后续被屏蔽请告知我。
