### ISSUE TITLE
*.githubusercontent.com is unstable

### ISSUE THREAD

**Issue by shingwasix** [gfwlist/gfwlist#196]
具体测试地址如下，以下地址均出现过连接被重置的现象
https://avatars0.githubusercontent.com/u/15024294?v=3&s=96
https://avatars1.githubusercontent.com/u/11025365?v=3&s=40
https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
https://camo.githubusercontent.com/11885b58bc743ff87b05bfa118c80577cb1188ab/68747470733a2f2f7472617669732d63692e6f72672f42696c6962696c692f696a6b706c617965722e7376673f6272616e63683d6d6173746572
https://raw.githubusercontent.com/Bilibili/ijkplayer/master/init-ios.sh
请求观察

**Comment by z344257899** [comment]
我的也是如此，无法访问。

**Comment by chengr28** [comment]
CNAME 出来都是 `github.map.fastly.net` 大概是 IP 地址的 443 端口被黑名单了

**Comment by cicku** [comment]
目前正常，估计为临时调整。
