### ISSUE TITLE
请求加入trojan-gfw.github.io

### ISSUE THREAD

**Issue by yu-chenxi** [gfwlist/gfwlist#1961]
> **[trojan官网](https://trojan-gfw.github.io/trojan/)** 已被墙

*个人经过测试是dns pollution.*

**Comment by SekiBetu** [comment]
只是被删除了吧，404啊

**Comment by MargaretteMoss** [comment]
trojan最好用的教程地址与trojan官网同样的现象，也可以加入一下。
```trojan-tutor.github.io```

**Comment by cicku** [comment]
Duplicate of #1860
