### ISSUE TITLE
GitHub Fastly CDN RST

### ISSUE THREAD

**Issue by gongjianhui** [gfwlist/gfwlist#197]
和 github.map.fastly.net. （103.245.222.133 Fastly Anycast）有关的域名全部 TCP RST(443)

其中包括：

主站 CSSJS ：
https://assets-cdn.github.com/assets/frameworks-c231663796a87f91c5c81548a237c760b1e7ec8adc6f04047a5c6eee5901d3bc.js

RAW：
https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt

Images：https://camo.githubusercontent.com/11885b58bc743ff87b05bfa118c80577cb1188ab/68747470733a2f2f7472617669732d63692e6f72672f42696c6962696c692f696a6b706c617965722e7376673f6272616e63683d6d6173746572

Avatar：
https://avatars0.githubusercontent.com/u/15024294?v=3&s=96

**Comment by gongjianhui** [comment]
部分网络下连接该 CDN 已经不再 RST。

**Comment by s7lx** [comment]
wget https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt 

--2016-04-05 22:01:19--  https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
Resolving raw.githubusercontent.com... 103.245.222.133
Connecting to raw.githubusercontent.com|103.245.222.133|:443... connected.
Unable to establish SSL connection.

**Comment by cicku** [comment]
现已恢复。
