### ISSUE TITLE
一个可替代的gfwlist

### ISSUE THREAD

**Issue by brijagstu7** [gfwlist/gfwlist#1970]
因为已经半年多没更新了，有很多网站的访问已经异常，我们必须找到一个新的gfwlist，正好我找到了一个：
[https://github.com/poctopus/gfwlist-plus](url)

**Comment by ylm98** [comment]
加一：
https://github.com/Loukky/gfwlist-by-loukky

**Comment by cicku** [comment]
早就说过了可以参与维护。

结果个个都是新开个项目造轮子。
