### ISSUE TITLE
路由上ssr-plus使用该list，安卓手机谷歌Play商店可以访问，但是无法下载应用

### ISSUE THREAD

**Issue by zhouzl7** [gfwlist/gfwlist#1981]
路由上ssr-plus使用该list，安卓手机谷歌Play商店可以访问，但是无法下载应用

**Comment by cicku** [comment]
貌似这个之前有人提到过，但是应该相应的域名早就添加了。

不知道您有没有机会试试流量分析看看是哪个域名的问题，路由器既然折腾了就应该有日志

**Comment by lizenghui** [comment]
> 路由上ssr-plus使用该list，安卓手机谷歌Play商店可以访问，但是无法下载应用

应该是ssr-plus的问题吧   我可以正常下载。
