### ISSUE TITLE
*.global.ssl.fastly.net when using HTTPS

### ISSUE THREAD

**Issue by dujiulun** [gfwlist/gfwlist#20]
#18 中提到的 fastly.net 可能跟我是一样的情况。

北方联通。直接访问 **http**://rubygems.global.ssl.fastly.net/ 没有问题，访问 **https**://rubygems.global.ssl.fastly.net/ 时就会 ERR_CONNECTION_RESET。

其它示例：
https://github.global.ssl.fastly.net/
https://inkscape.global.ssl.fastly.net/media/shields/icons/heart.png
（如果第一次能打开可能是缓存，请Ctrl+F5再试一次）

建议添加 https://*.global.ssl.fastly.net ，因为根据 https://docs.fastly.com/guides/securing-communications/ordering-a-paid-tls-option 的介绍：
> Customers using this service prepend their domain name to global.ssl.fastly.net (for example, <example domain>.global.ssl.fastly.net), then set up a backend for that domain and use that domain name.

**Comment by cicku** [comment]
联通打不开我可以确认，但是教育网就没这个问题。棘手。

**Comment by dujiulun** [comment]
刚测试了一下，教育网确实可以上……教育网的v4出口好像跟公网不一样，不知道电信用户能不能打开……

**Comment by cicku** [comment]
电信用户抽风

**Comment by poliang** [comment]
广东电信确认ip的443端口被ban

**Comment by meteormatt** [comment]
恩。我也一直发现.

**Comment by poliang** [comment]
fastly的dns记录调整，访问正常

**Comment by cicku** [comment]
+2016-01-09 HTTPS RST :x:

**Comment by cicku** [comment]
#209
