### ISSUE TITLE
请求添加github.blog

### ISSUE THREAD

**Issue by waynon** [gfwlist/gfwlist#2061]
请求添加github.blog

**Comment by cicku** [comment]
I cannot confirm this. Is it still inaccessible?

**Comment by waynon** [comment]
It's still inaccessible. @cicku

**Comment by waynon** [comment]
Could you please use some automated scripts to detect if a domain is blocked? Manualy checking each domain requires a lot of human labor and it's somewhat inaccurate.

**Comment by waynon** [comment]
gfwlist, a so important infrastructure is maintained by only one administrator. This is unbelievable!

**Comment by waynon** [comment]
Please inspect https://github.com/gfwlist/gfwlist/pull/1964, it's feasible.
