### ISSUE TITLE
inoreader.com is blocked

### ISSUE THREAD

**Issue by postadelmaga** [gfwlist/gfwlist#207]

**Comment by cicku** [comment]
No, only blog.inoreader.com is blocked and had been added since last report #165.

**Comment by postadelmaga** [comment]
No, also http://www.inoreader.com/ is blocked, at least here in Chengdu on my provider.
(sorry for late reply)

**Comment by cicku** [comment]
Please contact your ISP for more information.

**Comment by im-oasis** [comment]
Inoreader official twitter has confirmed that it has been completely blocked in the mainland of China. https://twitter.com/Inoreader/status/1245659240326238209 Please check.
