### ISSUE TITLE
iredmail.org is blocked (a free, open source mail server solution)

### ISSUE THREAD

**Issue by iredmail** [gfwlist/gfwlist#208]
Hi，

iredmail.org 是国人开发的一个免费、开源邮件服务解决方案，自 2011 年6月开始在国内无法直接访问。希望能加入 gfwlist。

**Comment by yungdeguo** [comment]
带来很多不便,非常希望加入gfwlist,谢谢!

**Comment by cicku** [comment]
早已包含。

**Comment by robbin10086** [comment]
Hi，

iredmail.org 是国人开发的一个免费、开源邮件服务解决方案，自 2011 年6月开始在国内无法直接访问。希望能加入 gfwlist。
