### ISSUE TITLE
请求添加pixiv图片和评论域名 pximg.net、pixiv-recommend.net

### ISSUE THREAD

**Issue by MaoSuSu** [gfwlist/gfwlist#2082]

**Comment by cicku** [comment]
请问现在访问 pixiv 大概是什么情况？

**Comment by MaoSuSu** [comment]
> 请问现在访问 pixiv 大概是什么情况？

pixiv对个别图片和评论引用的地址是pximg.net和pixiv-recommend.net，单纯pixiv.net无法实现全部图片和评论的代理

**Comment by ygsk10** [comment]
> 请问现在访问 pixiv 大概是什么情况？

仅仅是 `i.pximg.net` 需要代理, app 使用的 `i-cf.pximg.net` 没有被屏蔽。

`pixiv-recommend.net` 没有被屏蔽。

**Comment by pges-wings** [comment]
i.pximg.net是污染状态
s.pximg.net是正常解析状态
这两个域名都是图片归属的域名，且暂不清楚这图片归属域名的规律，并且由于IDCF目前电信方向双向NTT的网络状态，推荐将pximg.net整体加入list，整体提速

**Comment by cicku** [comment]
@pges-wings 已整体添加，如果有更好建议请及时通知。

**Comment by cicku** [comment]
Duplicate of #2115
