### ISSUE TITLE
request to add *.wikimedia.org

### ISSUE THREAD

**Issue by dongzhuoer** [gfwlist/gfwlist#2088]
wikipedia website refers to many contents from en.wikimedia.org

**Comment by cicku** [comment]
Duplicate of #2060

**Comment by dongzhuoer** [comment]
Can't connect to en.wiktionary.org, such as <https://en.wiktionary.org/wiki/%E6%9A%91>

**Comment by cicku** [comment]
Please do not reply old issues.
