### ISSUE TITLE
*.global.ssl.fastly.net 

### ISSUE THREAD

**Issue by jarod** [gfwlist/gfwlist#209]
具体文件 https://github-atom-io-herokuapp-com.global.ssl.fastly.net/assets/application-ba07c5c2889a34307a4b7d49410451d9.css
这应该是个CDN服务，这个域名被封导致 https://atom.io/packages 上的css样式加载不到

**Comment by cicku** [comment]
情况较为复杂，暂时无法添加。继续跟踪。

**Comment by cicku** [comment]
应该是 https://*.global.ssl.fastly.net/ 全线阵亡了。

**Comment by cicku** [comment]
Thanks for the report!
