### ISSUE TITLE
请求添加https://virmach.com/

### ISSUE THREAD

**Issue by iced-duck** [gfwlist/gfwlist#2093]
https://virmach.com/
是一个2014年成立的VPS服务商
数据中心位于洛杉矶、圣何塞、达拉斯及水牛城等11个地区，除了VPS以外，他家也提供独立服务器、游戏服务器及虚拟主机业务

**Comment by cicku** [comment]
请问有什么访问故障？

**Comment by iced-duck** [comment]
> 请问有什么访问故障？

virmach.com需要科学上网才可以接入，这个list中看着是不是没有？

**Comment by cicku** [comment]
可以直连

**Comment by av365app** [comment]
> [https://virmach.com/是一个2014年成立的VPS服务商](https://virmach.com/%E6%98%AF%E4%B8%80%E4%B8%AA2014%E5%B9%B4%E6%88%90%E7%AB%8B%E7%9A%84VPS%E6%9C%8D%E5%8A%A1%E5%95%86)
> 数据中心位于洛杉矶、圣何塞、达拉斯及水牛城等11个地区，除了VPS以外，他家也提供独立服务器、游戏服务器及虚拟主机业务

連結格式都不注意下。。。。想點開看，是真費勁。

**Comment by iced-duck** [comment]
> > [https://virmach.com/是一个2014年成立的VPS服务商](https://virmach.com/%E6%98%AF%E4%B8%80%E4%B8%AA2014%E5%B9%B4%E6%88%90%E7%AB%8B%E7%9A%84VPS%E6%9C%8D%E5%8A%A1%E5%95%86)
> > 数据中心位于洛杉矶、圣何塞、达拉斯及水牛城等11个地区，除了VPS以外，他家也提供独立服务器、游戏服务器及虚拟主机业务
> 
> 連結格式都不注意下。。。。想點開看，是真費勁。

现在呢？

**Comment by av365app** [comment]
> > > [https://virmach.com/是一个2014年成立的VPS服务商](https://virmach.com/%E6%98%AF%E4%B8%80%E4%B8%AA2014%E5%B9%B4%E6%88%90%E7%AB%8B%E7%9A%84VPS%E6%9C%8D%E5%8A%A1%E5%95%86)
> > > 数据中心位于洛杉矶、圣何塞、达拉斯及水牛城等11个地区，除了VPS以外，他家也提供独立服务器、游戏服务器及虚拟主机业务
> > 
> > 
> > 連結格式都不注意下。。。。想點開看，是真費勁。
> 
> 现在呢？

好啦。
