### ISSUE TITLE
mega网盘被dns污染

### ISSUE THREAD

**Issue by 1265578519** [gfwlist/gfwlist#2097]
这两个域名都没了，被dns污染
mega.nz
g.api.mega.co.nz

这个域名被HTTP连接重置阻断
sg.static.mega.co.nz
![image](https://user-images.githubusercontent.com/6442439/116592437-965cab00-a952-11eb-9b1f-2b5439071482.png)

**Comment by cicku** [comment]
+mega.co.nz

**Comment by 1265578519** [comment]
mega.io 官方新换的域名也进去了。。

**Comment by cicku** [comment]
@1265578519 请在今后新开 issue 上报。
