### ISSUE TITLE
几个Google的域名

### ISSUE THREAD

**Issue by ghost** [gfwlist/gfwlist#21]
https://get.how/
https://www.iam.soy/
https://www.registry.google/
http://はじめよう.みんな/
nic.youtube
nic.google
等

**Comment by cicku** [comment]
Access without problems, set back to WATCHING.

**Comment by aOJzQT** [comment]
谢谢，太棒了  
https://www.registry.google/  
**开拓网络新疆域**

欢迎使用Google域名注册系统。Google很快就要为大家推出一些新的域名。互联网的首要任务始终都是为用户搭建一个展示自我的舞台，而数以百计新域名的涌现则为互联网时代带来了勃勃生机，它预示着网络这一个变幻莫测的媒介即将迎来史上最无法预知的时刻。

一直以来，我们已习惯用 .EDU 表示教育单位、用 .GOV 表示政府机关、用 .ORG 表示公益组织。如今新域名的出现则表现出更为宽广的开放性，创意达人、商务人士、探险家、喜剧谐星以及各类专业人士都能在互联网上找到自己的一席之地。.HOW、.EAT、.SOY 分别代表什么意思呢？我们会提供一些建议，但如何开发您的这片网络地盘，归根结底，还是取决于您。无论您是位父亲、旅行爱好者，开发者、电影制作人还是导游，也不管您会不会说日语，网络都会是您挥洒创意的沃土。

**Comment by cicku** [comment]
nic.google
registry.google

Added.

**Comment by cicku** [comment]
https://www.iam.soy/
http://はじめよう.みんな/

Added.
