### ISSUE TITLE
请求添加xnxx-cdn.com

### ISSUE THREAD

**Issue by anye1998** [gfwlist/gfwlist#2100]
观看 https://www.xnxx.com/ 内视频时，视频加载不出，SwitchyOmega提示*.xnxx-cdn.com加载失败。
看到您把这个给取消代理了，但是我这边网络环境没这个cdn加载不出。
安徽移动

**Comment by cicku** [comment]
CDN 域名没有被墙，可能是移动的墙中墙，请自行添加规则吧。

**Comment by anye1998** [comment]
> 
> 
> CDN 域名没有被墙，可能是移动的墙中墙，请自行添加规则吧。

好的，感谢回复
