### ISSUE TITLE
请求添加https://www.bitwellex.com

### ISSUE THREAD

**Issue by bitwell-tech** [gfwlist/gfwlist#2101]
https://www.bitwellex.com 是一家数字资产衍生品服务平台, 目前被墙

**Comment by cicku** [comment]
这个域名在大陆统一解析到一个无效的 IP，请问是服务器做的手脚吗？

**Comment by av365app** [comment]
> 这个域名在大陆统一解析到一个无效的 IP，请问是服务器做的手脚吗？

看起來，這就是個「虛擬幣」交易網站啊，被大陸「強制」 DNS 了？

**Comment by s7lx** [comment]
<img width="366" alt="image" src="https://user-images.githubusercontent.com/3221213/168032540-f011d3e9-c35e-4e95-9ba6-a489447ad074.png">

by other CDN provider . Plz close it  @cicku
