### ISSUE TITLE
GFWList URL为什么一直显示：“605:status:500”？

### ISSUE THREAD

**Issue by tq01o3n** [gfwlist/gfwlist#2123]
近期xxnet一直显示“请检查浏览器代理设置”，经人提醒是switchOmega规则列表网址需要更换镜像网址，经搜索找到这里来了，更换了https://pagure.io/gfwlist/raw/master/f/gfwlist.txt ，终于“一切正常，你可以访问真正的互联网了。”但chrome打开任何墙外网站都提示“605:status:500”，包括Official mirror URLs也都显示“605:status:500”

**Comment by cicku** [comment]
请联系 xxnet。
