### ISSUE TITLE
两个被屏蔽的连接

### ISSUE THREAD

**Issue by freemeng** [gfwlist/gfwlist#219]
使用Firefox 45.0.2无法打开https://github.com/gfwlist/gfwlist 时，通过调试查看下列内容无法加载
https://assets-cdn.github.com/assets/frameworks-01ab74aec1f88b10018cfd6b44beeaffca2792e0fbe73b31f078adb893dbaa1e.css
https://avatars3.githubusercontent.com/u/686438?v=3&s=40

将两个连接的域 *://assets-cdn.github.com/*         和  *://avatars3.githubusercontent.com/*  通过新加坡代理时，https://github.com/gfwlist/gfwlist 能正常打开。

**Comment by Too-Naive** [comment]
表示异议..可以正常打开

**Comment by cicku** [comment]
请与您的 ISP 联系。
