### ISSUE TITLE
请求添加 *.cppreference.com

### ISSUE THREAD

**Issue by woshoxxx** [gfwlist/gfwlist#2197]
网址：*.cppreference.com
现象：zh.cppreference.com 的响应时间过长。
ISP：龙江网络元申光电
看法：不知道是不是只有这一个ISP有这个问题，开了全局就能访问了

**Comment by Black-Eagle-Jesse** [comment]
> 网址：*.cppreference.com 现象：zh.cppreference.com 的响应时间过长。 ISP：龙江网络元申光电 看法：不知道是不是只有这一个ISP有这个问题，开了全局就能访问了

我这是上海电信，也打不开了

**Comment by mega-optimus** [comment]
the IP (74.114.90.46) is blocked
