### ISSUE TITLE
diygod.me

### ISSUE THREAD

**Issue by BakaJzon** [gfwlist/gfwlist#2209]
![图片](https://user-images.githubusercontent.com/55239052/153863174-08706d71-65d6-4226-918b-7c12183c8712.png)

**Comment by s7lx** [comment]
<img width="301" alt="image" src="https://user-images.githubusercontent.com/3221213/168030254-d0a8fd1d-b5a1-4bbc-9422-9bf3c4c1c423.png">

dns pollution

**Comment by cicku** [comment]
域名换了。
