### ISSUE TITLE
plz delete v2ex.com

### ISSUE THREAD

**Issue by s7lx** [gfwlist/gfwlist#221]
plz delete v2ex.com

it's in China Mainland now

**Comment by cicku** [comment]
列表仅剩 V2EX DNS 规则，貌似已经恢复访问，可以移除。

**Comment by cicku** [comment]
经检测发现 .v2ex.com 仍被防火墙关键字屏蔽，dns.v2ex.com 也被重置。

我已经更新了列表规则，为 v2ex 部分域名设置了白名单。

请提供您的检测结果。
