### ISSUE TITLE
nyaa.eu

### ISSUE THREAD

**Issue by amphineko** [gfwlist/gfwlist#222]
ERR_CONNECTION_RESET

DNS: 223.5.5.5, 223.6.6.6

China Telecom @ Guangxi

**Comment by amphineko** [comment]
Personally, I thought it's caused by the IP banning, DNS records are clean.

**Comment by cicku** [comment]
-||nyaa.se --> | && .

情况暂时不明，https 正常，建议您改为 https 访问。

**Comment by amphineko** [comment]
It seems that HTTPS accesses will be redirected to HTTP.

**Comment by cicku** [comment]
nyaa.se 的 https 并不会跳转到 http。

请尽量使用 nyaa.se 访问。
