### ISSUE TITLE
cloudflare 的pages服务域名 *.pages.dev 

### ISSUE THREAD

**Issue by BFDZ** [gfwlist/gfwlist#2221]
*.pages.dev 被墙了

**Comment by cicku** [comment]
能问一下是连接超时还是被重置？是所有子域名，还是其他？

**Comment by BFDZ** [comment]
@cicku 是连接重置，所有子域名都墙了

**Comment by Leao9203** [comment]
> @cicku 是连接重置，所有子域名都墙了

原因估计是SNI导致的，Cloudflare 对于 pages.dev 域名签发的证书由原来的 R3 更换成 sni.cloudflare.com 了
