### ISSUE TITLE
请求添加 cdn.jsdelivr.net

### ISSUE THREAD

**Issue by iKirby** [gfwlist/gfwlist#2232]
域名: cdn.jsdelivr.net
现象: DNS 污染
网络: 电信，试过多个 DNS 均相同

这个应该会影响很多网站，类似以前的 ajax.googleapis.com 无法连接导致的问题
其他信息: https://v2ex.com/t/849894

**Comment by cicku** [comment]
貌似恢复了。这个域名归 Cloudflare，在中国有业务。

**Comment by cicku** [comment]
广场赛车纪念日快到了，暂时观望。

**Comment by cicku** [comment]
我先加进来了，以后再看。
