### ISSUE TITLE
请求添加wowhead.com

### ISSUE THREAD

**Issue by LenkaCarey** [gfwlist/gfwlist#2237]
![QQ截图20220508113758](https://user-images.githubusercontent.com/105139549/167280713-bfeaa433-8aae-407b-a3f0-b4053d74c2d9.png)

**Comment by cicku** [comment]
额，你的 IP 段是？

**Comment by luolingjun** [comment]
主动把我们大陆强了,腾T...讯X ...子..公司

**Comment by LenkaCarey** [comment]
中国ip都不行，他主动把中国ip墙了，疑似因为俄乌战争，不是无法访问，是访问了只有这个页面。 @cicku
