### ISSUE TITLE
translate.googleapis.com被墙

### ISSUE THREAD

**Issue by ly012** [gfwlist/gfwlist#2293]
启用gfwlist chrome无法翻译，改用全局正常翻译。isp安徽电信

**Comment by zdm9981** [comment]
同

**Comment by stardust-hu** [comment]
是因为有好多Google的域名被加到白名单中了
![image](https://user-images.githubusercontent.com/9612226/193173226-9299e5ee-6609-43f4-b6f3-8b13247b8a67.png)

**Comment by Polaris-cn** [comment]
谷歌退出服务了，包括谷歌翻译页面的一些字体也无法加载。

**Comment by rust17** [comment]
我觉得应该把这个规则移除掉，因为现在谷歌翻译必须走代理了，否则即使配置了代理也会因为屏蔽规则起效而没走代理
目前的清理方法：在本地找到 pac 文件删掉这一行

<img width="684" alt="image" src="https://user-images.githubusercontent.com/16575052/193433389-d8cbb897-2061-48ea-b924-09644cb4f372.png">

**Comment by simonsww** [comment]
直接在list里更新吧，强制走代理

**Comment by xhsui** [comment]
同

**Comment by cicku** [comment]
会后续处理，没动静是怀疑这是因为开会导致的短暂故障。
