### ISSUE TITLE
please delete  @@||translate.googleapis.com

### ISSUE THREAD

**Issue by benjamin09527** [gfwlist/gfwlist#2302]
google翻译 大陆已经被停止了，需要代理

**Comment by yinTang** [comment]
+1

**Comment by yinTang** [comment]
这几天google翻译都不能用了

**Comment by Linuxer003** [comment]
+1

**Comment by Linuxer003** [comment]
please delete all rules avoiding proxy to google translate.

**Comment by StrollStars** [comment]
https://github.com/gfwlist/gfwlist/issues/2293

**Comment by cicku** [comment]
Duplicate of https://github.com/gfwlist/gfwlist/issues/2293
