### ISSUE TITLE
hostloc.com

### ISSUE THREAD

**Issue by qwerttvv** [gfwlist/gfwlist#2311]
三网全挂

**Comment by cicku** [comment]
是 mjj 吗？🤣 

没看到挂的迹象，继续看一段时间。

**Comment by qwerttvv** [comment]
> 是 mjj 吗？🤣
> 
> 没看到挂的迹象，继续看一段时间。

hah，从落伍就是了
https://tool.chinaz.com/speedtest/hostloc.com
不过这里看是一片红啊

**Comment by cicku** [comment]
已处理。
