### ISSUE TITLE
yimg.com

### ISSUE THREAD

**Issue by Bitcion** [gfwlist/gfwlist#2324]
好像是yahoo的图片资源api，gfwlist没有收录这个只有yahoo，yahoo的网页载入并不完整

**Comment by cicku** [comment]
有具体的图片链接吗？请给一个

**Comment by ShadowOfTheDay** [comment]
Example: https://s.yimg.com/os/creatr-uploaded-images/2020-11/3164fc90-2e08-11eb-bffe-c46e0e6c95ae
国内网络环境下无法在网页中显示。如果在新标签页中打开图片会显示：2021 年 11 月 1 日起，用户将无法从中国大陆使用 Yahoo 的产品与服务。这并不影响 Yahoo 在全球其他地方的产品及服务。我们感谢你一直以來的支持。
