### ISSUE TITLE
downloader.disk.yandex.ru 移动、联通、电信，三网全挂 tcp reset

### ISSUE THREAD

**Issue by qwerttvv** [gfwlist/gfwlist#2343]
祖国山河一片红啊

移动、联通、电信，三网全挂
tcp reset
downloader.disk.yandex.ru

https://ping.chinaz.com/downloader.disk.yandex.ru
![image](https://user-images.githubusercontent.com/56712217/212449587-c0543422-89e6-4ab3-a122-4d4ce1e4df14.png)

**Comment by cicku** [comment]
我忘了什么时候添加的，列表里面是`||disk.yandex.ru`，包含该子域
