### ISSUE TITLE
nssurge.zendesk.com

### ISSUE THREAD

**Issue by im-Kalix** [gfwlist/gfwlist#2344]
`nssurge.zendesk.com`这个域名，白天的时候可以直连，到了晚上（大约下午五点开始）就断了。然后到了第二天白天又可以直连，似乎每天都是这样。
这大概可以拓展到`*.zendesk.com`

**Comment by cicku** [comment]
这些都是 Cloudflare 的IP，很难不被特殊关照。但并没有被墙。
