### ISSUE TITLE
请求添加 *.recaptcha.net

### ISSUE THREAD

**Issue by iKirby** [gfwlist/gfwlist#2364]
recaptcha.net 被 DNS 污染。测试网络为电信，多个 DNS 均返回不正常结果。

```
Non-authoritative answer:
Name:    recaptcha.net
Addresses:  2001::480e:cf5f
          31.13.94.7
```

**Comment by hhm1** [comment]
这应该是按地区来定的，我刚刚用站长工具ping了一下，有几个是正常的

**Comment by iKirby** [comment]
> 这应该是按地区来定的，我刚刚用站长工具ping了一下，有几个是正常的

又多测试了几个，有概率返回正常的 IPv4，但返回的 IPv6 不能连接。我记得 Google 在大陆应该没有 IPv6。可能是缓存还没完全刷新吧，可以等一天再测试看看。

**Comment by iKirby** [comment]
今天测试恢复正常了，多个 DNS 都没有问题。

**Comment by zonyitoo** [comment]
今日测试发现 `recaptcha.net` 被解析为 `58.63.233.34`

**Comment by iKirby** [comment]
> 今日测试发现 `recaptcha.net` 被解析为 `58.63.233.34` ，建议加入 `*.recaptcha.net`

搜索了一下这个 IP 地址，应该是 Google 专门为大陆用户解析的，这个不会影响使用验证码服务吧

**Comment by zonyitoo** [comment]
实际上会，或者可能是因为这个IP所对应的服务无法使用吧

```
 curl 'https://recaptcha.net/recaptcha/api2/anchor?ar=1&k=6LdCDO0bAAAAAOu_ckRlx051J.......' -v
* Host recaptcha.net:443 was resolved.
* IPv6: 2401:3800:4001:807::1002
* IPv4: 58.63.233.34
*   Trying [2401:3800:4001:807::1002]:443...
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLS connect error: error:00000000:lib(0)::reason(0)
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to recaptcha.net:443
* closing connection #0
curl: (35) TLS connect error: error:00000000:lib(0)::reason(0)
```

**Comment by iKirby** [comment]
刚才通过添加 hosts 测试了上面的 IPv4 和 IPv6，网络为联通，在 https://recaptcha.net/recaptcha/api2/demo 这个页面上都可以正常加载验证码，可能是部分地区或运营商的网络故障
