### ISSUE TITLE
+3 mining pools

### ISSUE THREAD

**Issue by newnoder** [gfwlist/gfwlist#2370]
ethermine.org
f2pool.com
hiveon.com

**Comment by s7lx** [comment]
ethermine.org  DNS POISONING
![image](https://github.com/gfwlist/gfwlist/assets/3221213/e32f90cb-4b91-4219-9f79-0717e625c4ae)

f2pool.com  TCP_RESET


hiveon.com  is OK , 
![image](https://github.com/gfwlist/gfwlist/assets/3221213/fb3a7589-4972-4d56-86a1-9f2c2fda697a)
