### ISSUE TITLE
tumblr short domain service (without encrypted)

### ISSUE THREAD

**Issue by s7lx** [gfwlist/gfwlist#242]
http://t.umblr.com/redirect?z=https%3A%2F%2Fs3-ap-southeast-1.amazonaws.com%2Ffqrouter%2Fyoutube.html&t=MTVmYmNlMzBmMjZiOTI5YjVmNzg5ZmMzNTFkYWU2N2VjNzU2MzMzNCxQbU1iMEMyUQ%3D%3D

**Comment by cicku** [comment]
并未被封锁，请与您的 ISP 联系。
