### ISSUE TITLE
Please add s.yimg.com

### ISSUE THREAD

**Issue by 17957384453** [gfwlist/gfwlist#2447]
https://s.yimg.com/aaq/wf/wf-clipboard-copy-1.0.2.js

2021 年 11 月 1 日起，用户将无法从中国大陆使用 Yahoo 的产品与服务。这并不影响 Yahoo 在全球其他地方的产品及服务。我们感谢你一直以來的支持。

**Comment by cicku** [comment]
Duplicate of #2324
