### ISSUE TITLE
add huggingface.co

### ISSUE THREAD

**Issue by lxfly2000** [gfwlist/gfwlist#2456]
参考 https://tool.chinaz.com/dns/huggingface.co
国内解析异常

**Comment by dfldylan** [comment]
Please!!

**Comment by s7lx** [comment]
![image](https://github.com/gfwlist/gfwlist/assets/3221213/e8eef692-a71a-4acc-b3a2-c8624c7897c2)
![image](https://github.com/gfwlist/gfwlist/assets/3221213/7d95f286-be5a-4425-a95d-f2b5e8ad8e3f)

DNS POISONING + TCP_RESET @cicku

**Comment by lxfly2000** [comment]
Fixed by #2442
