### ISSUE TITLE
cdn-telegram.org

### ISSUE THREAD

**Issue by seehirp** [gfwlist/gfwlist#2469]
link: `https://telegram.org/dl/android/apk` (Then it will be redirected to the cdn-telegram.org)
PR_CONNECT_RESET_ERROR
北京电信
![image](https://github.com/gfwlist/gfwlist/assets/152947844/978ac71d-29b0-4ce2-aef6-6582f6a80adc)

**Comment by cicku** [comment]
这个理论上应该是谷歌被定期干扰的结果，不像是被特殊关照，可以考虑添加。
