### ISSUE TITLE
Shadowsocks-windows 使用 gfwlist 后，即使开启 PAC 模式，国内常用网站打开速度还是会被拖慢

### ISSUE THREAD

**Issue by Loyalsoldier** [gfwlist/gfwlist#25]
```Shadowsocks-windows``` 2.5.7 以及 2.5.8 都有一个问题：
使用 ```PAC 模式```（与```全局模式```相斥）后，国内常用网站会被莫名拖慢速度。
而在```用户规则```中手动过滤掉该国内网站后，速度恢复正常。

请问是 ```gfwlist``` 过滤规则出问题了吗？

同时在Shadowssocks-windows 提了类似 issue，参见：https://github.com/shadowsocks/shadowsocks-windows/issues/332

**Comment by cicku** [comment]
Just hazard a guess, the occurrence is caused by whitelist part (URLs started with `@@`) in gfwlist. Likely it's the only part with domestic domains included.

Did you experience the same behavior in the past, prior to 2.5.7 especially?

**Comment by Loyalsoldier** [comment]
@cicku 
好像发现了门道。
用户规则里，```*.co``` 这样的设置好像也会触发屏蔽```.com```的网站。去掉```.co```之后，貌似速度就正常了。
