### ISSUE TITLE
Please add perplexity.ai

### ISSUE THREAD

**Issue by 17957384453** [gfwlist/gfwlist#2510]
https://www.perplexity.ai/

**Comment by s7lx** [comment]
DNS Poisoning+TCP RESET
![image](https://github.com/gfwlist/gfwlist/assets/3221213/f5edbae3-6aa3-4395-adc8-45cd604c1e0c)
![image](https://github.com/gfwlist/gfwlist/assets/3221213/3a75d832-df29-4831-89f3-6b32ee40cb4c)

**Comment by s7lx** [comment]
@cicku
