### ISSUE TITLE
Two url for list

### ISSUE THREAD

**Issue by dubiao** [gfwlist/gfwlist#254]
> ||.dropboxstatic.com
> ||s3.amazonaws.com

第一个是 dropbox 的文件存放服务器
第二个是 aws 的文件存放服务器
一些文件在下载时经过以上服务器会下载失败，添加后成功。

**Comment by cicku** [comment]
对于部分地区访问异常的站点，请自行添加自定义规则，gfwlist 只收录严格意义上被墙的站点。
