### ISSUE TITLE
beta.speedtest.net

### ISSUE THREAD

**Issue by yyzh** [gfwlist/gfwlist#256]
![1](https://cloud.githubusercontent.com/assets/4102990/15708457/2dc2d2c4-2831-11e6-9a73-bae8cbed8a64.jpg)

**Comment by yfdyh000** [comment]
我这里用4个8好像可以。
>nslookup beta.speedtest.net 8.8.8.8
服务器:  google-public-dns-a.google.com
Address:  8.8.8.8

非权威应答:
名称:    cs62.adn.edgecastcdn.net
Address:  110.232.178.82
Aliases:  beta.speedtest.net

**Comment by cicku** [comment]
```
$ dig -4 beta.speedtest.net @8.8.4.4 +multi +dnssec

; <<>> DiG 9.10.3-P4-RedHat-9.10.3-13.P4.fc25 <<>> -4 beta.speedtest.net @8.8.4.4 +dnssec +multi
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 43903
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 512
;; QUESTION SECTION:
;beta.speedtest.net.	IN A

;; ANSWER SECTION:
beta.speedtest.net.	3109 IN	CNAME cs62.adn.xicdn.net.
cs62.adn.xicdn.net.	3497 IN	A 110.232.178.82

;; Query time: 57 msec
;; SERVER: 8.8.4.4#53(8.8.4.4)
;; WHEN: Thu Jun 30 12:08:06 CST 2016
;; MSG SIZE  rcvd: 92

```

**Comment by yyzh** [comment]
服务器:  public1.alidns.com
Address:  223.5.5.5

非权威应答:
名称:    cs62.adn.xicdn.net
Address:  110.232.178.82
Aliases:  beta.speedtest.net

服务器:  public1.114dns.com
Address:  114.114.114.114

非权威应答:
名称:    cs62.adn.xicdn.net
Address:  110.232.178.82
Aliases:  beta.speedtest.net

服务器:  public1.sdns.cn
Address:  1.2.4.8

非权威应答:
名称:    cs62.adn.xicdn.net
Address:  110.232.178.82
Aliases:  beta.speedtest.net


服务器:  pdns.dnspod.cn
Address:  119.29.29.29

非权威应答:
名称:    cs62.adn.xicdn.net
Address:  110.232.178.82
Aliases:  beta.speedtest.net

problem fix
