### ISSUE TITLE
2.gravatar.com

### ISSUE THREAD

**Issue by phuslu** [gfwlist/gfwlist#263]
github 头像跳转服务
示例：https://github.com/phuslu/goproxy/commit/ef01bbe75a2f92e86c1741ff3d1201aab0df795e committer 头像不能载入
全局代理以后，会跳转到 https://i2.wp.com/assets-cdn.github.com/images/gravatars/gravatar-user-420.png?ssl=1

江苏电信

**Comment by phuslu** [comment]
找到一个相关链接 http://c7sky.com/unblock-gravatar.html

**Comment by cicku** [comment]
如果没有故障，应该是自动跳转的，我这里至少没有问题。
