### ISSUE TITLE
genymotion.com

### ISSUE THREAD

**Issue by interchen** [gfwlist/gfwlist#265]
Not all of genymotion.com can access, so suggest to proxy this site all

**Comment by cicku** [comment]
Would you care to elaborate?

**Comment by interchen** [comment]
Some functions can't use
* register
* using genymotion.app on Mac to deploy/upgrade a new virtual device

**Comment by cicku** [comment]
Sorry but:

1. I don't have any problem creating an account.

2. I hope you can provide some packet capture since I can't use Mac now.
