### ISSUE TITLE
fonts.googleapis.com & .cloudfront.net

### ISSUE THREAD

**Issue by kairee** [gfwlist/gfwlist#268]
广东电信用户
ShadowSocks + 最新 gfwlist，很多网页显示不正常，排查发现是这两个域下的url 无法加载。

在 user-rule.text 中加入：

```
fonts.googleapis.com
.cloudfront.net
```
重新生成 gfwlist，访问正常。

**Comment by cicku** [comment]
这两个站点均没有被封锁，但是您的 ISP 肯定针对它们做了一些调整，建议您自行添加自定义规则。
