### ISSUE TITLE
Pure ://google.com

### ISSUE THREAD

**Issue by cicku** [gfwlist/gfwlist#27]
Current gfwlist supports Google well except this:

http://google.com

It's been a issue for a long time, several users had reported this.

Reported by: ZmFpdGgwNzI1QG91dGxvb2suY29t

**Comment by dujiulun** [comment]
On line 1324 there is `/^https?:\/\/[^\/]+google\.(.*)/`. If you replace `+` with `*` it will match.

**Comment by cicku** [comment]
@dujiulun No, this solution has been mooted by several people, but it's incorrect.

`^https?:\/\/[^\/]*google\.(.*)` will match `google.com`, **AND** `usethefuckinggoogle.com` as well.

IMO `^https?:\/\/[^\/]*\bgoogle\.(.*)` is the best regex.

**Comment by dujiulun** [comment]
The original regex matches `xxxgoogle.com` anyway.

If `\b` is supported then it's perfect. Or we can use something like `([^\/]+\.)?google` since we only care about whether subdomain exists.

**Comment by cicku** [comment]
But `xxxgoogle.com` shouldn't be proxied as default if GFW doesn't block them at all.

My concern is also about the support of `\b`. I haven't weighed support from other methods, tests based on SwitchyOmega and Shadowsocks C# client have passed.

**Comment by cicku** [comment]
@dujiulun Ok, I think `([^\/]+\.)?google` is better for various implementations. I will update the rule soon.

Thank you! :100:

**Comment by dujiulun** [comment]
My pleasure. Thanks for the great project! ;)
