### ISSUE TITLE
[疑惑] 更新了最新的gfwlist之后，Autoproxy就无法上google？

### ISSUE THREAD

**Issue by tony-haibo-zhu** [gfwlist/gfwlist#272]
只有global可以用，而且有一点很迷惑，为什么在最新的js文件里，“google.com”  和 “||google.com”同存？另外，能解释下 在rules数组中|| 和 @@ 还有直接写网址各是什么意思吗？ 
非常抱歉我的issue没有按照您要求的格式写，因为我不是来报告某些网址不能用的。 
请见谅，谢谢。

**Comment by cicku** [comment]
1. autoproxy 基本上很早之前就不能用了，不太清楚现在火狐浏览器的情况，我大致记得火狐换过两次解析引擎。我现在测试规则只用 foxyproxy。

2. 请问您查看的 js 文件来源？

3. 原始规则匹配 `.google.com` 是因为防火墙有关键字屏蔽，而双竖线规则用于全站代理，并没有冲突。

4. 具体格式解释请查看 wiki，不过尚未完工，我还在补充完善。

**Comment by cicku** [comment]
您还可以阅读 #239。

**Comment by tony-haibo-zhu** [comment]
首先，感谢及时回复。
1. 我的浏览器是chrome，和firefox没有关系。
2. 我的js文件来源就是这个[gfwlist](https://github.com/gfwlist/gfwlist)。（就是您这个git库）
3，4 我后面会说我发现的奇怪现象。

情况是这样的，我之前从来没有更新过gfwlist，自从ss的客户端安装好后就没有碰过，所以Autoproxy一直都是正常的，只是有时候碰到一些网站需要手动切换，比较麻烦。然后今天研究了一下自己添加规则和更新规则列表（也就是gfwlist），结果发现完全不能上了，甚至global，我在想，是不是gfw2pac这个python模块对软件本身还有一些修改。（我一直以为只是将txt的文件反转为js）。所以我将ss客户端完全删除，重新安装，（也就是说，还是之前那个软件本身带的gfwlist），可以使用，而且是Autoproxy和Globalproxy都正常，和之前一样。
我不太明白您说的，Autoproxy很早之前就不能用了？
另外我还发现一个奇怪的现象，今天一天代理的效果都很差，我用那个软件本身带的gfwlist在下午怎么都访问不了github，谷歌访问时断时续，所以又一次扒开看gfwlist.js，然后将其中的条目，‘||github.com’删除了，然后github秒上。也就是说，现在我完全被这个文件搞糊涂了。

**Comment by tontwen-lyn** [comment]
autoproxy一般指火狐插件AutoProxy，所以你的表述容易造成误解。shadowsocks原版clowwindy已经不更新了，可以使用breakwa11 fork的版本shadowsocks-csharp。我认为你的问题不在于gfwlist，而在于浏览器代理和pac文件。谷歌代理插件请使用Proxy SwitchySharp，另外检查http://127.0.0.1:8090/proxy.pac。

**Comment by tony-haibo-zhu** [comment]
您好，我没有用chrome里的插件，觉得那个插件的体验并不是很好。我是直接在shadowsocks里选择Autoproxy/Globalproxy。另外，我已经在尝试修改user-rule.txt了，看看有没有收获，谢谢。

**Comment by tontwen-lyn** [comment]
有时不能穿，必须要切换自动代理／全局，或者切换服务器，这样的情况99.9%是因为浏览器自身的代理设置没有起作用。强烈建议使用SwitchySharp。

**Comment by cicku** [comment]
根据您描述的特征，我无法判断您使用的 shadowsocks 是否为目前通行的版本。建议您先更新软件。

**Comment by tony-haibo-zhu** [comment]
目前版本为2.6.3，另外，请问哪里可以更新ShadowsocksX现在？谢谢

**Comment by tontwen-lyn** [comment]
你反映的问题我使用safari chrome firefox都遇到过，win10 edge没问题。我不懂技术，无法推测原因，就使用而言，装浏览器代理插件可100%解决。ShadowsocksX已经停止更新，我还用的2.6.2，没有任何问题。

鉴于该issue与gfwlist无关，建议关闭。关于浏览器代理和ss的问题我们去v2ex讨论可好？:)

**Comment by tony-haibo-zhu** [comment]
好的，谢谢。
v2ex means what?
