### ISSUE TITLE
http://plantuml.sourceforge.net

### ISSUE THREAD

**Issue by zhengnairen** [gfwlist/gfwlist#274]
URL: http://plantuml.sourceforge.net

Issue: The connection keeps timing out.

ISP: China Unicom Beijing

Complementary Information:
```
$ nslookup plantuml.sourceforge.net
Server:  public1.114dns.com
Address:  114.114.114.114
Non-authoritative answer:
Name:    plantuml.sourceforge.net
Address:  216.34.181.96

$ ping plantuml.sourceforge.net
Pinging plantuml.sourceforge.net [216.34.181.96] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.
Ping statistics for 216.34.181.96:
    Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),
```

**Comment by smdhz** [comment]
ping plantuml.sourceforge.net

正在 Ping plantuml.sourceforge.net [216.34.181.96] 具有 32 字节的数据:
来自 216.34.181.96 的回复: 字节=32 时间=310ms TTL=234
来自 216.34.181.96 的回复: 字节=32 时间=327ms TTL=234
来自 216.34.181.96 的回复: 字节=32 时间=323ms TTL=234
来自 216.34.181.96 的回复: 字节=32 时间=325ms TTL=234

216.34.181.96 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 310ms，最长 = 327ms，平均 = 321ms

**Comment by zhengnairen** [comment]
ISP: China Unicom Beijing

Complementary Information:
```
$ tracert plantuml.sourceforge.net

Tracing route to plantuml.sourceforge.net [216.34.181.96]
over a maximum of 30 hops:

  1     5 ms     1 ms     5 ms  192.168.0.1
  2     4 ms     1 ms     1 ms  192.168.1.1
  3     5 ms     3 ms     3 ms  123.118.144.1
  4     7 ms     5 ms     7 ms  61.148.185.9
  5     5 ms     5 ms     5 ms  61.51.112.9
  6     *        *        *     Request timed out.
```

**Comment by cicku** [comment]
Redirected to `http://plantuml.com/`.
