### ISSUE TITLE
关于nicovideo

### ISSUE THREAD

**Issue by lazureice** [gfwlist/gfwlist#275]
问题:
订阅了gfwlist「https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt 」之后依然不能访问nicovideo.

1).查找本地gfwlist.txt,发现已经有了:
!--.nicovideo.jp/watch
!--||nicovideo.jp

2).使用代理扩展(autoproxy)订阅gfwlist,查找nico.图片如下:
http://i.imgur.com/pC4m5qR.png
两个nicovideo规则无法启用,似乎是因为它们的格式?其他规则前面都没有「!」.

**Comment by cicku** [comment]
gfwlist 包含该规则，但并没有启用，原因是 nicovideo 目前并没有被封锁，尽管过去是。

开头为半角叹号的行是注释，意味着该行无效。

请问您的 ISP？

**Comment by lazureice** [comment]
@cicku  原来是这个意思...谢谢解答.

现在是联通网络. nicovideo.jp的确没有被封锁,但是nicovideo.jp/watch被封锁了.
(我记得之前用电信也是同样的情况. 也可能是我记错了.


ISP:	China Unicom Liaoning
City:	Nanjing
Region:Jiangsu

**Comment by lazureice** [comment]
唔…我去niconico吧看了一下。的确有人能直连，但好像不稳定。我是一直不能…

**Comment by cicku** [comment]
封锁貌似又开始了，已经重新启用相关规则
