### ISSUE TITLE
一些想法

### ISSUE THREAD

**Issue by Moriaty911** [gfwlist/gfwlist#278]
1. 希望加入easybib.com。这个可以连上但是速度真的很慢很慢
2. 能不能将一些境外网站（如github）直接加入list，这样的话访问能快很多。

**Comment by gera2ld** [comment]
这种个性化的可以自己定制到用户规则里吧，不用给所有人都加上

**Comment by JiangMufan** [comment]
正解 发自网易邮箱大师 在2016年06月24日 09:50 ，Gerald写道： 这种个性化的可以自己定制到用户规则里吧，不用给所有人都加上 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by cicku** [comment]
1. 不能
2. 不能

请自行添加自定义规则。
