### ISSUE TITLE
Some adjustments

### ISSUE THREAD

**Issue by samho1234567** [gfwlist/gfwlist#28]
Please add this site:
https://www.vpndada.com/

And also remove the rule below:
`.x-berry.com`
as the domain is no longer accessible.

**Comment by cicku** [comment]
`vpndata.com` can be accessed without problem here.

`x-berry.com` is still alive from the perspective of whois. And it's still being blocked. But it now redirects itself to `wowrk.com` which is not blocked. I don't know the motives, but I will probably remove it in the future.
