### ISSUE TITLE
gvt2.com, gvt3.com

### ISSUE THREAD

**Issue by hyxxsfwy** [gfwlist/gfwlist#288]
网址：```*.gvt2.com```，```*.gvt3.com```
现象：Google 域名，被全面屏蔽
您的ISP：电信 + 移动
看法：既然 gvt0.com，gvt1.com 都有，那么这两个也加上吧。

whois 详情：
```
域名 gvt2.com
注册商 MARKMONITOR INC.
联系人 dns admin[whois反查]
联系方式 dns-admin@google.com
更新时间 2016年01月31日
创建时间 2008年03月03日
过期时间 2017年03月03日
域名服务器 whois.markmonitor.com
DNS
    NS1.GOOGLE.COM
    NS2.GOOGLE.COM
    NS3.GOOGLE.COM
    NS4.GOOGLE.COM
```

**Comment by cicku** [comment]
感谢反馈。

很久之前我就已经注意到这两个了，但是一直没找到什么“证据”。一个月前我还测试过。

我测试的情况是 gvt2.com 并未被墙，例如 beacons.gvt2.com，联通和教育网均可以正常访问。

gvt3.com 情况不明。

据我所知，gvt 是 Google 用于缓存 Play 市场和 YouTube 的域名，不知道您能否抓一些能重现的例子，例如您从这些站点下载文件，或者其他方式，证明您并不能访问。

加入两行规则并不困难，我只是希望更“精确”一些。

谢谢！

**Comment by cicku** [comment]
**gvt3.com confirmed.**
