### ISSUE TITLE
fonts.googleapis.com

### ISSUE THREAD

**Issue by zealotds** [gfwlist/gfwlist#293]

**Comment by cicku** [comment]
请问您想表达什么？

**Comment by zealotds** [comment]
Hi, 不是很确定我的理解是否正确：我看到fonts.googleapis.com是在白名单，但实际上请求还是会被block，所以想请求把它从白名单注释掉，以下是SwitchyOmega中GFWList的规则片段：
!################Whitelist Start################
@@||aliyun.com
@@||baidu.com
!--@@||bing.com
@@||bt.byr.cn
@@||chinaso.com
@@|http://nrch.culture.tw/
!--@@||dl.google.com
@@||fonts.googleapis.com

**Comment by cicku** [comment]
然而该域名目前并没有被 block。

**Comment by zealotds** [comment]
在完全不使用任何插件/proxy的情况下你可以打开https://fonts.googleapis.com/css?family=Open+Sans？

**Comment by zealotds** [comment]
ping fonts.googleapis.com
PING googleadapis.l.google.com (209.85.200.95) 56(84) bytes of data.
--- googleadapis.l.google.com ping statistics ---
23 packets transmitted, 0 received, 100% packet loss, time 22000ms

**Comment by cicku** [comment]
```
$ ping fonts.googleapis.com
PING googleadapis.l.google.com (203.208.41.40) 56(84) bytes of data.
64 bytes from 203.208.41.40: icmp_seq=1 ttl=45 time=65.9 ms
64 bytes from 203.208.41.40: icmp_seq=2 ttl=45 time=71.7 ms
64 bytes from 203.208.41.40: icmp_seq=3 ttl=45 time=71.0 ms
64 bytes from 203.208.41.40: icmp_seq=4 ttl=45 time=63.6 ms
64 bytes from 203.208.41.40: icmp_seq=5 ttl=45 time=70.2 ms
64 bytes from 203.208.41.40: icmp_seq=6 ttl=45 time=75.7 ms
64 bytes from 203.208.41.40: icmp_seq=7 ttl=45 time=65.5 ms
64 bytes from 203.208.41.40: icmp_seq=8 ttl=45 time=70.7 ms
64 bytes from 203.208.41.40: icmp_seq=9 ttl=45 time=64.6 ms
64 bytes from 203.208.41.40: icmp_seq=10 ttl=45 time=51.5 ms
64 bytes from 203.208.41.40: icmp_seq=11 ttl=45 time=73.8 ms
^C
--- googleadapis.l.google.com ping statistics ---
11 packets transmitted, 11 received, 0% packet loss, time 10005ms
rtt min/avg/max/mdev = 51.547/67.696/75.706/6.329 ms
```

北京谷歌

**Comment by zealotds** [comment]
ok 那可能是运营商的问题，我自己加规则好了

**Comment by xpader** [comment]
我这边不走代理时googlefont时通时不通，最蛋疼的是因为gfwlist特别排队了googlefont导致在shadowsocks中用户自定义规则就算加了也没法走代理。
所以我强烈建议将googlefont的网站从列表中移除，不在列表中时默认不是不走代理么，这样不仅不走代理，还能把选择权交给用户。

**Comment by marujun** [comment]
@cicku 麻烦问一下，您用的dns是哪个？我这也是北京，但是ping不通。
$ ping fonts.googleapis.com
PING fonts.googleapis.com (74.125.205.95): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3

**Comment by cicku** [comment]
@xpader 不知道你现在访问情况如何。

**Comment by xpader** [comment]
@cicku 后来使用的 ShadowsocksX-NG 调整了规则，把用户规则优先级调高了之后这个问题好像就没有了。
