### ISSUE TITLE
https://answers.yahoo.com/

### ISSUE THREAD

**Issue by zzhhbyt1** [gfwlist/gfwlist#294]
比如：https://answers.yahoo.com/question/index?qid=20101006020340AAdN8A7

ERR_CONNECTION_RESET

中国电信-河北

**Comment by cicku** [comment]
访问速度有点慢，但并没有 RST。

**Comment by zzhhbyt1** [comment]
咦，好奇怪。。又是那天完全上不去reset，今天又好了。。好吧，以后看看还遇得到不吧。

**Comment by zzhhbyt1** [comment]
刚才又试了几次：
1手机主站ok
2手机问题ok
3手机翻墙ok
4手机不翻墙问题rst
5手机不翻墙主站rst
6电脑刚开机不翻墙直接开问题rst
7电脑刚开机不翻墙主站rst

基本上还是不翻墙不能访问的样子呢。。

**Comment by cicku** [comment]
侦测到“安全连接失败”，继续跟踪。

**Comment by cicku** [comment]
无法侦测原因，可能是随机RST或者ISP故障造成。
