### ISSUE TITLE
http://www.w3schools.com/

### ISSUE THREAD

**Issue by SongzhouYang** [gfwlist/gfwlist#295]
http://www.w3schools.com/

**Comment by cicku** [comment]
访问正常，貌似北京地区有访问问题。建议您自行添加代理规则。

Ref: #35 #177

**Comment by aoisummer** [comment]
It maybe a DNS pollution of alias server of local ISP. (wac.bf9f.edgecastcdn.net)

- Local ISP: 37.61.54.158
- Tencent: 37.61.54.158
- 114: 37.61.54.158
- Google: 68.232.44.251
- OpenDNS: 68.232.44.251

ISP: China Telecom

**Comment by cicku** [comment]
问题出在 DNS 上，部分 DNS 对该域名甚至不返回查询结果。请自行更换。

CNNIC: 
```
$ dig A www.w3schools.com @1.2.4.8

; <<>> DiG 9.10.3-P4-RedHat-9.10.3-13.P4.fc25 <<>> A www.w3schools.com @1.2.4.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 51100
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 2, ADDITIONAL: 4

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.w3schools.com.		IN	A

;; ANSWER SECTION:
www.w3schools.com.	3597	IN	CNAME	wac.bf9f.edgecastcdn.net.
wac.bf9f.edgecastcdn.net. 2841	IN	A	37.61.54.158

;; AUTHORITY SECTION:
edgecastcdn.net.	92691	IN	NS	ns1.edgecastcdn.net.
edgecastcdn.net.	92691	IN	NS	ns2.edgecastcdn.net.

;; ADDITIONAL SECTION:
ns1.edgecastcdn.net.	17077	IN	AAAA	2606:2800:1::5
ns2.edgecastcdn.net.	1946	IN	A	37.61.54.158
ns2.edgecastcdn.net.	77135	IN	AAAA	2606:2800:1::6
```

针对特殊网络段针对性启用 DNS 污染（114在我这里就没有问题）:

```
$ dig A www.w3schools.com @114.114.114.114

; <<>> DiG 9.10.3-P4-RedHat-9.10.3-13.P4.fc25 <<>> A www.w3schools.com @114.114.114.114
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 26024
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.w3schools.com.		IN	A

;; ANSWER SECTION:
www.w3schools.com.	3354	IN	CNAME	wac.bf9f.edgecastcdn.net.
wac.bf9f.edgecastcdn.net. 3046	IN	A	159.106.121.75

;; Query time: 38 msec
;; SERVER: 114.114.114.114#53(114.114.114.114)
;; WHEN: Thu Jul 14 12:25:18 CST 2016
;; MSG SIZE  rcvd: 100
```

Baidu: 
```
$ dig A www.w3schools.com @180.76.76.76

; <<>> DiG 9.10.3-P4-RedHat-9.10.3-13.P4.fc25 <<>> A www.w3schools.com @180.76.76.76
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 52849
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.w3schools.com.		IN	A

;; ANSWER SECTION:
www.w3schools.com.	3610	IN	CNAME	wac.bf9f.edgecastcdn.net.
wac.bf9f.edgecastcdn.net. 3168	IN	A	37.61.54.158

;; Query time: 357 msec
;; SERVER: 180.76.76.76#53(180.76.76.76)
;; WHEN: Thu Jul 14 12:26:37 CST 2016
;; MSG SIZE  rcvd: 100
```

**Comment by zypA13510** [comment]
多地服务器测试结果：
https://en.greatfire.org/www.w3schools.com
根据这个记录，100%不能访问应该已经2年了。

本人也在三大电信网环境下都试过，均不能访问。即便是DNS的原因，难道就不应该加入列表吗？
或者说，这个list有没有明确的指标性的收录规则？

**Comment by cicku** [comment]
@zypA13510 Greatfire 的测试结果并不能作为依据，那个网站的所谓结果看看就好。

`即便是DNS的原因，难道就不应该加入列表吗？`

真的不能，因为修改 DNS 的成本太低，并不是很麻烦的事情，况且所有系统都支持多 DNS 设置，换成 8.8.4.4，再留一个运营商提供的，很难吗？

**Comment by zypA13510** [comment]
其他网我不清楚，不过我这里电信网经常间歇性无法ping通8.8.8.8

关于这个列表的用途，Chorme+SwitchyOmega也可以代理DNS解析，实际上使用该列表根据域名选择正确的DNS解析方式不是也是可行的解决方案之一吗？所以根本问题是该列表到底是应该支持且只支持一种假设“正确”的配置方式，还是允许根据环境及所需的用途选择？毕竟每个网络环境不可能完全一样

所以正如前述，指标性的收录规则是什么？你可以认为Greatfire的测试结果不够可靠，但是至少“Greatfire最近90天不可达超过50%”是可以量化的指标，是每个人都可以参考的。不然100个人就会有100种gfwlist。

**Comment by zypA13510** [comment]
曾经Google也可以改Hosts解决，那是否Google就不该进入当时的gfwlist？

**Comment by cicku** [comment]
我在联通、科技网和教育网，改好了 DNS，w3schools 可以正常访问，根本不用走代理。就冲这一点，Greatfire 所谓不可达根本就是不可信。Greatfire 的问题在于只要它检测的时候网站不能访问，就认为该网站不可达，显然它的逻辑也有问题，如果它的网络链路出了问题，甚至百度都打不开，那就说明被墙了，然而事实是这样吗？

至于您说的 Google，您要不说我还差点忘了，当年 GFWList 自从六月份 Google 全线沦陷后半年多一直没添加，就是因为改 Hosts 党存在。后来 Google 的 IP 都封得快干净了，我才考虑完善一下列表，Google 到今天的确还能通过改 Hosts 来访问，不过这种方式基本上没什么意义，因为用 GFWList 的人和改 Hosts 上网的几乎不是同一类人，那么 GFWList 也没必要为了所谓的严格意义的被墙而不添加 Google。

我如果今天因为这个事情把这个域名加进来，等于今后我也要把所有用 Edgecast CDN 的域名都要加进来。讲道理，我觉得这个列表 10MB 都不够。GFWList 的用户有很多会改 DNS，会用 DNSCRYPT，退一万步，还会添加自定义规则，10s 就能解决的事情，我相信这些用户不少，不然它们如此折腾还不如全局。既然这样，我也不用考虑不同网络造成的差异，用户自己选择合适的方法就行了。既然目的是翻墙，为什么还要让墙返回的错误结果干扰呢？

GFWList 添加的域名，都是用户想尽办法避免因自己配置不当造成的干扰却仍然无法访问的。用户尽量确保自己是干净的，该用的手段都用了，这种情况下依然无法访问，那我认为收录是必要的。至于您说的量化指标，既然中国地大物博，情况复杂，那就没有什么量化指标，因为这东西不能量化，只能取一个较为均衡的结果，最终的平衡由用户自行决定。

**Comment by zypA13510** [comment]
> 用户想尽办法避免因自己配置不当造成的干扰

所以使用电信DNS属于“配置不当”？我举个极端的例子吧，网络设置是可以被组策略锁定的，DNS可能是不可更改的。

> 既然目的是翻墙，为什么还要让墙返回的错误结果干扰呢？

是的，你说的很对。但是阻止DNS干扰的方式有很多，可以像你说的改DNS，也可以根据一个列表选择DNS是否使用代理。不然的话Socks5代理DNS的意义何在呢？

------------

换个角度思考，如果我DNS结果都正确了，我为什么还需要一个域名列表而不是一个路由表/ACL？GFWList要解决的根本问题是什么？只是解决连接重置吗？

关于指标性：这跟写需求规约是一个道理，如果需求与适用场景都不明确，那么结果也就不明确。今天有100个用户说我们要把w3schools加进来，所以就加了，那明天有200个用户说要删掉呢？量化才能指导具体个例的判断，才能实现自动化的检测/编译/部署。
关于Greatfire，我只是举了一个量化的具体例子，如果您有更好的解决方案您也可以提出来，但希望不是一味否定其他方案（如果你认为Greatfire检测机制存在问题，可以提给他们，也可以自己实现一套自动化检测系统）

关于文件大小：是的，我不否认加入CDN域名之后确实可能存在这样的问题，但是如果这个列表是自动化编译与上传的话，那也只是分编两个表的问题吧，一个minimal一个full

> 地大物博，情况复杂

~~所以我们没有条件民主普选~~，这是一个逻辑。

**Comment by paperbag** [comment]
> 关于Greatfire，我只是举了一个量化的具体例子，如果您有更好的解决方案您也可以提出来，但希望不是一味否定其他方案（如果你认为Greatfire检测机制存在问题，可以提给他们，也可以自己实现一套自动化检测系统）

挖个坟，针对这句话作回复。关键词屏蔽（包括URL和DNS）的都很好判断，但屏蔽的是IP，即使是人也不能迅速判断出来，自动化检测机制是不现实的。拿过去一年中国内无法访问GitHub的事来说，真的无法判断是GitHub的IP被墙了，还是链路故障。Greatfire 的东西的确是华而不实。
