### ISSUE TITLE
https://www.videolan.org/

### ISSUE THREAD

**Issue by zzhhbyt1** [gfwlist/gfwlist#304]
https://www.videolan.org/
Win10, Chrome: ERR_CONNECTION_TIMED_OUT
Win10, Edge: Hmm, we can't reach this page.
iOS 9.3.2, Safari: Safari could not open the page because the server stopped responding.
Android: (No respond.)

ISP: China Telecom Hebei

Accessible after used proxy.

**Comment by cicku** [comment]
访问正常，可能是服务器或线路临时故障。

**Comment by zzhhbyt1** [comment]
��������������������������ss����������������������
