### ISSUE TITLE
disqus.com is blocked by DNS poisoning

### ISSUE THREAD

**Issue by BROBIRD** [gfwlist/gfwlist#310]
包括*.disqus.com，disq.us， *.disquscdn.com等

[https://zh.greatfire.org/disqus.com](https://zh.greatfire.org/disqus.com)
[http://ping.chinaz.com/?host=disqus.com&linetype=%E7%94%B5%E4%BF%A1%2C%E5%A4%9A%E7%BA%BF%2C%E8%81%94%E9%80%9A%2C%E7%A7%BB%E5%8A%A8](http://ping.chinaz.com/?host=disqus.com&linetype=%E7%94%B5%E4%BF%A1%2C%E5%A4%9A%E7%BA%BF%2C%E8%81%94%E9%80%9A%2C%E7%A7%BB%E5%8A%A8)

**Comment by cicku** [comment]
disqus.com 已经在今晨的更新中加入，防火墙有对 `.disqus.com` 的关键字屏蔽。

剩下两个域名 gfwlist 没有计划加入，原因是并没有被真正的封锁。

解决  DNS 污染不是靠 gfwlist，建议您自行添加规则。

**Comment by BROBIRD** [comment]
可以参考一下ipip.net及chinaz.com的测试结果，其他两个域名已经部分被墙。
