### ISSUE TITLE
http://www.w3schools.com/

### ISSUE THREAD

**Issue by linzian** [gfwlist/gfwlist#316]
http://www.w3schools.com/ 
无法访问
电信

**Comment by lhuanyun** [comment]
自己去把规则添加进去，善用搜索。

**Comment by cicku** [comment]
W3Schools 使用 EdgeCast 进行加速，然而后者在国内是被频繁**干扰**的，一般情况下更换 DNS 为未受污染的即可打开（如 8.8.8.8），注意更换后要根据您使用的操作系统手动清理 DNS 缓存。

#295
