### ISSUE TITLE
PAC模式下访问fonts.googleapis.com 的响应时间过长

### ISSUE THREAD

**Issue by ScottLiu0** [gfwlist/gfwlist#318]
网址：https://fonts.googleapis.com/css?family=Open+Sans:300,400&subset=latin,latin-ext,cyrillic,greek,vietnamese
现象：Chrome提示fonts.googleapis.com 的响应时间过长。SS使用PAC模式一直加载不出来，改用全局之后能正常打开了
ISP：移动

**Comment by cicku** [comment]
建议您投诉中国移动。

**Comment by orangemi** [comment]
上海电信（CN2链路）也出现此问题 2016年12月初至今（2017年1月）

**Comment by cicku** [comment]
@orangemi 这只能通过您自行添加规则解决，这个域名国内99%地区均可访问，因为被解析到 Google 在国内的数据中心。

**Comment by xpader** [comment]
@cicku fonts.googleapis.com 在国内的访问不稳定，就算到国内的数据中心，也时常出现无法连接的情况。建议还是走代理。

安徽电信
