### ISSUE TITLE
http://a1.v2.phobos.apple.com.edgesuite.net/

### ISSUE THREAD

**Issue by sunhr** [gfwlist/gfwlist#320]
URL: http://a1.v2.phobos.apple.com.edgesuite.net/us/r1000/000/Features/atv/AutumnResources/videos/b1-1.mov

ISP: 辽宁电信、辽宁联通、辽宁移动

现象: 开SS和VPN可以访问，直连不行

**Comment by cicku** [comment]
+`phobos.apple.com.edgesuite.net/video`
