### ISSUE TITLE
Superfluous rules?

### ISSUE THREAD

**Issue by lolilolicon** [gfwlist/gfwlist#325]
Are the following rules correctly written? Where's the slash?
```
.google.*facebook
.google.*falun
.google.*twitter
```
Besides, all *.google.* domains are now covered by _that_ regex; surely these are redundant?

Adding to this, all the following seem to be missing slashes.
```
.bbc.co*zhongwen
.bbc.co.uk*chinese
.hkheadline.com*blog
blog.qooza.hk*dafengqixi
global.hkepc.com*forum
markmail.org*message
nemesis2.qx.net*pages*MyEnTunnel
timesofindia.indiatimes.com*dalai
zh.wikibooks.org*%E7%AA%81%E7%A0%B4%E7%BD%91%E7%BB%9C%E5%AE%A1%E6%9F%A5
```
```
search*freegate
search*safeweb
search*%BC%CD%D4%AA
search*%BC%D3%C3%DC%B4%FA%C0%ED
search*%E4%B8%AD%E5%8A%9F
search*%E4%B8%AD%E5%9B%BD%E8%AE%BA%E5%9D%9B
search*%E4%B8%AD%E5%AE%A3%E9%83%A8
search*%E5%85%AD%E5%9B%9B
search*%E5%8A%A0%E5%AF%86%E4%BB%A3%E7%90%86
search*%E5%8D%9A%E8%AE%AF
search*%E5%A4%9A%E7%B6%AD
search*%E5%A4%9A%E7%BB%B4
search*%E5%A4%A7%E7%BA%AA%E5%85%83
search*%E5%AD%A6%E8%BF%90
search*%E6%88%91%E7%9A%84%E5%A5%8B%E6%96%97
search*%E6%96%87%E5%AD%97%E7%8B%B1
search*%E6%96%B0%E5%94%90%E4%BA%BA
search*%E6%96%B0%E8%AF%AD%E4%B8%9D
search*%E6%97%A0%E7%95%8C
search*%E6%B1%9F%E6%B5%81%E6%B0%93
search*%E6%B3%95%E4%BC%9A
search*%E7%8E%8B%E5%B8%8C%E5%93%B2
search*%E7%9C%8B%E4%B8%AD%E5%9B%BD
search*%E7%BD%91%E7%89%B9
search*%E8%89%B2%E6%83%85
search*%E8%8A%B1%E8%8A%B1%E5%85%AC%E5%AD%90
search*%E9%82%AA%E6%81%B6
search*%E9%92%93%E9%B1%BC%E5%B2%9B
search*%E9%AD%8F%E4%BA%AC%E7%94%9F
```

**Comment by lolilolicon** [comment]
While we are at it, here's another faulty rule (missing `|`)
```
http://beta.iset.com.tw/forum
```

**Comment by cicku** [comment]
1. `.google.*($)` rules were correct in the past (as I added these rules when I was working on GSoC and found Google Melange couldn't be displayed properly), but I just tested and found GFW had updated the rules so they don't apply anymore. Google regex in GFWList doesn't cover that, in fact, the old regex covered these rules but I revised it and now it doesn't cover paths.

2. In the past GFWList didn't care about the slash, because some patterns were only used by specific websites, and rules with or without slashes don't matter.

3. For the others, they are old rules (including the iset rule, the URL there doesn't exist anymore, moreover, new home at settv doesn't keep the old links well.), along with infra change and shutdown, providentially some of them don't work anymore.

**Comment by lolilolicon** [comment]
Regardless whether the rules still matches the GFW, these rules by themselves seem wrong to me.
Your 2nd point says "in the past", so that's not true anymore now, right?
Some of these patterns I mentioned are still unfixed as of 031d763.
Here's what I think the patterns are meant to be:
```
.bbc.co*zhongwen => .bbc.co*/*zhongwen
search*freegate => */search*freegate
```

**Comment by cicku** [comment]
```
Regardless whether the rules still match the GFW, these rules by themselves seem wrong to me.
Your 2nd point says "in the past", so that's not true anymore now, right?
```

It depends.

```
Some of these patterns I mentioned are still unfixed as of 031d763.
Here's what I think the patterns are meant to be:
```

**Only Issue closed means solved.** Before that, it's not.

```
.bbc.co*zhongwen => .bbc.co*/*zhongwen
search*freegate => */search*freegate
especially the former, .bbc.co*zhongwen would seem to match a domain which is ridiculous (right?...)
```

Please elaborate for the bbc rule.

For those search* rules, I've cleared them out of the list as they are just leftovers.

```
Regarding point 1, well if the google domains are covered by the regex, google rules with paths, being more specific, should be superseded already, no?
```

I don't quite understand what you are trying to express.

```
EDIT: The following are all the patterns I've found that seem suspicious.

HTTPS with path doesn't make sense, right?

|https://github.com/programthink/zhao
```

Your utterance are opening yourself to nescience.

```
Is %2F meant to be / here?

bbs.sina.com%2F
dailynews.sina.com%2F
news.now.com%2Fhome
```

Yes, some Ad providers redirect URLs with slash substituted.

```
Change | to || here?

|falunasia.info
|osaka69.com
```

falunasia fixed. osaka69 removed.

```
Likely fixes:

.bbc.co*zhongwen => .bbc.co*/zhongwen
.bbc.co.uk*chinese => .bbc.co.uk/*chinese
.hkheadline.com*blog => .hkheadline.com/*blog
blog.qooza.hk*dafengqixi => blog.qooza.hk/*dafengqixi
markmail.org*message => markmail.org/*message
nemesis2.qx.net*pages*MyEnTunnel => nemesis2.qx.net/*pages*MyEnTunnel
timesofindia.indiatimes.com*dalai => timesofindia.indiatimes.com/*dalai
zh.wikibooks.org*%E7%AA%81%E7%A0%B4%E7%BD%91%E7%BB%9C%E5%AE%A1%E6%9F%A5 => zh.wikibooks.org/*%E7%AA%81%E7%A0%B4%E7%BD%91%E7%BB%9C%E5%AE%A1%E6%9F%A5
```

markmail removed. No intention working on others.

```
Unnecessary regex:

/twimg\.edgesuite\.net\/\/?appledaily/ => |http://twimg.edgesuite.net/*appledaily
/^https?:\/\/[^\/]+blogspot\.(.*)/ => ||blogspot.*
```

That's your preference. For some converter programs, ||blogspot.* is worse than regex.

```
Purely path keywords, suggested fix: foo => */*foo

%E5%88%98%E6%99%93%E6%B3%A2
%E5%8A%A8%E6%80%81%E7%BD%91
%E6%B0%91%E8%BF%90
%E6%B0%91%E8%BF%9B%E5%85%9A
%E6%B3%95%E8%BC%AA%E5%8A%9F
%E6%B3%95%E8%BD%AE%E5%8A%9F
%E6%B3%95%E8%BD%AE%E5%A4%A7%E6%B3%95
%E7%8E%8B%E4%B8%B9
%E7%BD%A2%E8%AF%BE
%E7%BE%8E%E5%9B%BD%E4%B9%8B%E9%9F%B3
%E8%83%A1%E6%B5%B7%E5%B3%B0
%E8%83%A1%E6%B5%B7%E6%B8%85
64memo
aHR0cHM6Ly95ZWNsLm5ldA
freenet
prisoner-state-secret-journal-premier
q%3DTriangle
q%3Dfreedom
q=freedom
q=triangle
remembering_tiananmen_20_years
search*%BC%CD%D4%AA
search*%BC%D3%C3%DC%B4%FA%C0%ED
search*%E4%B8%AD%E5%8A%9F
search*%E4%B8%AD%E5%9B%BD%E8%AE%BA%E5%9D%9B
search*%E4%B8%AD%E5%AE%A3%E9%83%A8
search*%E5%85%AD%E5%9B%9B
search*%E5%8A%A0%E5%AF%86%E4%BB%A3%E7%90%86
search*%E5%8D%9A%E8%AE%AF
search*%E5%A4%9A%E7%B6%AD
search*%E5%A4%9A%E7%BB%B4
search*%E5%A4%A7%E7%BA%AA%E5%85%83
search*%E5%AD%A6%E8%BF%90
search*%E6%88%91%E7%9A%84%E5%A5%8B%E6%96%97
search*%E6%96%87%E5%AD%97%E7%8B%B1
search*%E6%96%B0%E5%94%90%E4%BA%BA
search*%E6%96%B0%E8%AF%AD%E4%B8%9D
search*%E6%97%A0%E7%95%8C
search*%E6%B1%9F%E6%B5%81%E6%B0%93
search*%E6%B3%95%E4%BC%9A
search*%E7%8E%8B%E5%B8%8C%E5%93%B2
search*%E7%9C%8B%E4%B8%AD%E5%9B%BD
search*%E7%BD%91%E7%89%B9
search*%E8%89%B2%E6%83%85
search*%E8%8A%B1%E8%8A%B1%E5%85%AC%E5%AD%90
search*%E9%82%AA%E6%81%B6
search*%E9%92%93%E9%B1%BC%E5%B2%9B
search*%E9%AD%8F%E4%BA%AC%E7%94%9F
search*freegate
search*safeweb
ultrareach
ultrasurf
zhengjian
```
I don't see any enhancements of changing above.

Thank you anyway.

**Comment by lolilolicon** [comment]
OK, I'll explain.
```
.bbc.co*zhongwen => .bbc.co*/*zhongwen
```
What is this trying to match? I think it's mostly `http://www.bbc.com/zhongwen` or other bbc domain + /zhongwen.
If I understand, `.bbc.co*zhongwen` theoretically matches the above, plus `http://www.bbc.co.zhongwen` and perhaps `http://a.b/c.bbc.co/zhongwen`.

Regarding nescience... I stand corrected. By "order of the Chinese government" is a nice one, GitHub.

**Comment by cicku** [comment]
It stands for matching `www.bbc.com/zhongwen` and `www.bbc.co.uk/zhongwen` as far as I can find on the Internet.

`http://www.bbc.co.zhongwen` is invalid for now.
`http://a.b/c.bbc.co/zhongwen`, again, please find a real example.

**Comment by lolilolicon** [comment]
So why not `.bbc.co*/*zhongwen` but the much inexact `.bbc.co*zhongwen`? Best would be `|http://*.bbc.co*/zhongwen`

**Comment by cicku** [comment]
Initially it's for more coverage with less rules needed. But I haven't decided to divide into 2 parts (bbc.com/bbc.co.uk), as far as I can see most of BBC rules at GFW block both of them with same keywords.

```
 Best would be |http://*.bbc.co*/zhongwen
```

It doesn't help at all. Test `http://example.com/.bbc.co.uk/zhongwen` on your own.

**Comment by lolilolicon** [comment]
Ah, gotcha. Then best would be
```
|http://*.bbc.co*/zhongwen
|http://*/*.bbc.co*/zhongwen
```

**Comment by cicku** [comment]
```
Ah, gotcha. Then best would be

|http://*.bbc.co*/zhongwen
|http://*/*.bbc.co*/zhongwen
Anyway, all I'm saying, is if you cast your net too wide, you end up catch some rocks and boots.
```

Again, no.

I've modified the rules to be more verbose.

**Comment by lolilolicon** [comment]
I see, you made the change,
```diff
-.bbc.co.uk*chinese
+.bbc.co.uk/chinese
```
```diff
-.bbc.co*zhongwen
+.bbc.co.uk/zhongwen
+.bbc.com/zhongwen
```
Cool, that's fine. Thanks for your time.
