### ISSUE TITLE
m-team.cc layer13.net

### ISSUE THREAD

**Issue by WernerLi** [gfwlist/gfwlist#327]
m-team.cc 应该已经解封 
layer13.net 于上周发现被墙

ISP 教育网 IPv6+v4 双栈

**Comment by cicku** [comment]
_**HTTPS 不在讨论范围之内。**_

m-team.cc 只有首页能正常访问，`.m-team.cc` 关键字被屏蔽。

`http://forum.m-team.cc` 连接被重置；
`http://tp.m-team.cc` 连接被重置。

综上：

现有规则不变，可加入针对首页的白名单规则。

**Comment by cicku** [comment]
经检查首页会被随机重置，所以不打算对首页加白名单了。

layer13 因为使用了 OVH 机房而超时，这个无解。OVH 抽风实在是太正常了。
