### ISSUE TITLE
ctext.org

### ISSUE THREAD

**Issue by hyxxsfwy** [gfwlist/gfwlist#329]
http://ctext.org/zhs
中国哲学书电子化计划官方网站，确认被墙，
http://www.greatfirewallofchina.org/index.php?siteurl=http%3A%2F%2Fctext.org%2F

**Comment by cicku** [comment]
并没有被墙。（甚至，该网站是有备案的）

`http://www.greatfirewallofchina.org` 不具有任何参考价值。

**Comment by xFelino** [comment]
@cicku ctext.org ERR_CONNECTION_ABORTED CMCC-SH
