### ISSUE TITLE
客户端问题

### ISSUE THREAD

**Issue by Quiet95scholar** [gfwlist/gfwlist#338]
开启影梭pac模式，TGP游戏平台网页打不开，全局模式和关闭状态都没问题，
运营商：济南移动
DNS：119.29.29.29    8.8.8.8

**Comment by cicku** [comment]
您好，我不是很清楚您的情况，我认为这跟 GFWList 没有任何关系。

如果您使用的相关软件使用了 GFWList，请与相关软件开发人员取得联系。
