### ISSUE TITLE
signup.live.com blocked?

### ISSUE THREAD

**Issue by hubanya** [gfwlist/gfwlist#343]
Running SS with GFWlist. Can not open this site until I manually added it to GFWlist configuration.

Used http://ping.chinaz.com/ to test, all timed out.

onedrive.live.com is already in the GFWlist, but did not see signup.live.com.

Thanks!!

**Comment by cicku** [comment]
I'm afraid not, `signup.live.com` may just block any ICMP packet.

There is no problem accessing it.
