### ISSUE TITLE
某些遗漏的规则

### ISSUE THREAD

**Issue by iliuweiming** [gfwlist/gfwlist#347]
! --------------常规--------------
intangibleobject.com
! --------------XXX---------------
wowgirls.com
wowporn.com
18onlygirls.com
allfinegirls.com
hegre-art.com
passion-hd.com
0img.net
mfcimg.com
myfreecams.com
stumble-upon.com
redditstatic.com

现象：无法访问

ISP：上海电信

其它：不知写成这样是否可行，请酌情加入list。

**Comment by xfl12345** [comment]
还有这些：（openbittorrent.com的udp传送被GFW挡掉了）
1mobile.com
fotile.me
openbittorrent.com
publicbt.com
bell.wiki

**Comment by xfl12345** [comment]
好像openbittorrent.com没有被挡……

**Comment by cicku** [comment]
1mobile.com 在规则里面，请问您是怎么访问的？

其他部分并未被墙，我会近期筛选完成添加。

**Comment by cicku** [comment]
```
wowgirls.com
wowporn.com
myfreecams.com
fotile.me
bell.wiki
```
已添加。
