### ISSUE TITLE
websites blocked

### ISSUE THREAD

**Issue by lanshunfang** [gfwlist/gfwlist#35]
```javascript
||www.shwchurch.org
||dropbox.com
||wsj.com
||base64encode.org
||base64decode.org
||sstatic.net
||ggpht.com
||cloudfront.net
||s3.amazonaws.com
||gmail.com
||life.com.tw
||liangyou.net
||angularjs.org
||eslite.com
||firebase.com
||typekit.net
||akamaihd.net
*fbcdn-*
||disquscdn.com
*.googleapis.*
||chrome.com
||typekit.com
||gravatar.com
||wp.com
||wsjhk.com
||googlevideo.com
||w3schools.com
||rd.com
||wikipedia.org
||vpn.tibco-support.com
````

**Comment by lanshunfang** [comment]
这些是我个人的列表里导出的，并非全部 block，但很多都是被 gfw 故意拖延响应时间。如果加到翻墙列表，速度就会有提升——特别是不少 cdn域名。国内的域名服务器不少是没有及时更新国外的 cdn 服务器，导致一些网站打开特别慢。

**Comment by lanshunfang** [comment]
w3schools.com 是最无语的，目前只发现北京地区不能上，其他地方好像可以。高抬贵手，这个对于前端工程师来说，还是相当重要。

**Comment by lanshunfang** [comment]
fbcdn-的源码里有 星号，可能是被 MarkDown 给解析了。

**Comment by cicku** [comment]
我希望今后您提交汇报的时候，先跟列表比对一下，删掉重复的域名。

您的这份列表我很难加入，这也是 gfwlist 目前的缺陷。

如果可能，今后我会弄一个更激进的列表来加入这些被间歇性干扰的域名。

**Comment by lanshunfang** [comment]
特别期待那个“激进的列表” 😊

相信那个列表的用户体验会有进一步的提升～

sent from Paul's Sony Z3 Compact
2015年10月10日 上午9:17，"Christopher Meng" <notifications@github.com>写道：
