### ISSUE TITLE
duckduckgo 下面的 *.yahoo.net 被墙了。

### ISSUE THREAD

**Issue by Fezreal** [gfwlist/gfwlist#353]
*.yahoo.net
是这个域名被墙了。

**Comment by cicku** [comment]
您好，请问能否给出重现该问题的 duckduckgo 页面地址？

**Comment by cicku** [comment]
已经查明：`https://duckduckgo-owned-server.yahoo.net/`

GFW 对该地址有 DNS 污染，可能是亚马逊牵连，也可能是针对 Duck。

Google DNS 出了教育网几乎没什么用途，您可修改 DNS 为 OpenDNS 或加入自定义规则解决该问题，GFWList 暂时不予添加。
