### ISSUE TITLE
wikileaks.org 解封

### ISSUE THREAD

**Issue by PillowSky** [gfwlist/gfwlist#354]
wikileaks.org 已解封，可正常访问
ISP: 杭州华数

**Comment by cicku** [comment]
北京歌华+联通+教育网亲自测试，并没有解封。

**Comment by PillowSky** [comment]
麻烦测试了！抱歉各地情况不一样。

**Comment by mraandtux** [comment]
联通广州，HTTPS访问没问题，没改h0st5。

**Comment by cicku** [comment]
@mraandtux 请单独开一个issue。不要回复过去内容。
