### ISSUE TITLE
gfwlist.txt清空了？

### ISSUE THREAD

**Issue by hbprotoss** [gfwlist/gfwlist#356]

**Comment by sunzongzheng** [comment]
同问

**Comment by LingRay** [comment]
Bad news！！

**Comment by soncy** [comment]
啊，清空了啊

**Comment by doukai** [comment]
GFW的封锁新思路吗?

**Comment by zhanghanyun** [comment]
谁能提供个GFWLIST的下载，我的SS，pac模式已跪了

**Comment by hbprotoss** [comment]
@zhanghanyun 不是有history么，速度fork

**Comment by CasparLi** [comment]
赶紧clone！

**Comment by zhangchunlin** [comment]
看样子如果在working了应该是误操作...

**Comment by ikacarrot** [comment]
同问，什么情况

**Comment by sec314** [comment]
希望只是出错了

**Comment by cicku** [comment]
**给您造成不便，敬请谅解。**
   
   
    
故障来源：https://github.com/gfwlist/gfwlist/commit/fca34
故障经过：上午做例行更新，更新完毕后运行脚本（checksum(python)->base64(openssl)->commit(git)->push(git+ssh)）收尾，由于全程不需要人工干预（commit log sign 日期），所以没有发现问题。直到下午收发邮件发现有人联系我本人告知 GFWList 被意外清空，随即上线排查。排查了大约1个小时，依然对造成这次意外的根源没有头绪，因为之前从未出现过该问题。个人推断是 base64 这一步操作失败写入空数据，导致文件被清空。

至于 base64 为何操作失败，目前无法判断，可能与 I/O 有关。

今后将在 base64 后加入文件是否为空验证，以避免该问题再次发生。

**Comment by q158073378252010** [comment]
该列表太臃肿了。

**Comment by cicku** [comment]
@q158073378252010 如果您有任何想法，请单独开一个 issue。

**Comment by Kisesy** [comment]
为什么以 base64 来编码？ 
如果以明文 commit 还可以方便查看每次更新内容，而且 base64 起不到加密也起不到压缩的作用，现在的编码版比明文版大不少。。。
好像gfwlist一直一来都是 base64 编码，不太了解，所以问一下。。

**Comment by yfdyh000** [comment]
@Kisesy http时，防关键词过滤、识别或干扰替换。

**Comment by cicku** [comment]
base64 在 [RFC2045](https://www.ietf.org/rfc/rfc2045.txt) 中规定为混淆算法，**本身不是加密算法**。

GFWList 通过 Github HTTPS 网络分发，没有 HTTP 的顾虑，但不代表别处的镜像分发一定采用 HTTPS。如果 list 被 HTTP 明文传输，GFW 是可以直接检测出来的。因此 GFWList 需要躲避 GFW 特征识别。采用 base64，是因为 base64 普及度非常高。我曾考虑过更换为 Ascii85，但是该算法的实现有多个版本，我不确定我的更改能否让所有人都能用上。最重要一点，我并不认为 GFWList 很大，即便是嵌入式设备。只是 GFWList 包含的一些地址对大部分人来讲可能一辈子也用不到，我便开设了 [tinylist](https://github.com/gfwlist/tinylist)，尽管尚未完善无法使用。

**Comment by Kisesy** [comment]
哦，明白了。
话说以前在googlecode的时候，还往里提交过网址，发现又要改Checksum，又要改时间啥的，很麻烦
原来是脚本自动生成的 :trollface:

**Comment by q158073378252010** [comment]
@cicku 抱歉在这讨论另一个问题，。很支持你开另一个精简版本，建议你采用网站区分规则，以分隔符分隔每个网站内的链接。例如 google系，twitter系，相同的系写在同一分割符内。这样比较好的知道这个系内有哪些被墙哪些没有被墙。因有时GFW 并非屏蔽该系的所有域名，这样可以避免规则被重复。

**Comment by cicku** [comment]
@q158073378252010 完全可以用 `!` 进行注释。tinylist 还在不断完善，欢迎任何建议。
