### ISSUE TITLE
twitch.tv

### ISSUE THREAD

**Issue by SexyPilus** [gfwlist/gfwlist#361]
www.twitch.tv
游戏直播网站，可以直连但是速度很慢很慢
ISP是电信
百度出来的规则是
"||twitch.tv"
||ttvnw.net
希望能有帮助

**Comment by nxtreaming** [comment]
Certainly refused!

**Comment by cicku** [comment]
Twitch 访问快慢和 GFW 没任何关系，就好比在海外看国内的流服务。

如果您觉得访问特定网站速度不理想，请自行添加自定义规则。至于如何添加，请查阅相关资料。
