### ISSUE TITLE
关于 v2ex 规则问题

### ISSUE THREAD

**Issue by LisonFan** [gfwlist/gfwlist#364]
目前的规则：
!!---V2EX---
.v2ex.com
!--Included in above rule: dns.v2ex.com
@@|http://v2ex.com
@@|http://cdn.v2ex.com
@@|http://cn.v2ex.com
@@|http://hk.v2ex.com
@@|http://i.v2ex.com
@@|http://lax.v2ex.com
@@|http://neue.v2ex.com
@@|http://pagespeed.v2ex.com
@@|http://static.v2ex.com
@@|http://workspace.v2ex.com
@@|http://www.v2ex.com

建议改成：
!!---V2EX---
||dns.v2ex.com

v2ex 目前没有被墙了，目前貌似只有 dns.v2ex.com 拒绝 China IP

**Comment by cicku** [comment]
请自行测试`http://example.com/.v2ex.com`。

**Comment by cicku** [comment]
#221
