### ISSUE TITLE
thepiratebay.org

### ISSUE THREAD

**Issue by dujiulun** [gfwlist/gfwlist#370]
网址: https://thepiratebay.org
现象: 带https的地址在SwitchyOmega中无法匹配，现在默认就是https了
您的ISP: 山东联通
其他帮助提示或看法: 对应行thepiratebay.org，是否应该加上"||"开头？
谢谢！

**Comment by cicku** [comment]
天津联通 HTTPS 正常。

**Comment by dujiulun** [comment]
测试了两个公共DNS，都返回的是93.46.8.89，DNS被污染之后HTTPS也应该没法访问吧。

**Comment by cicku** [comment]
OK，我发现是我的代理工具解析 GFWList 貌似有 bug。

天津联通确认。
