### ISSUE TITLE
Please add "www.w3schools.com" to the list

### ISSUE THREAD

**Issue by chnt7305** [gfwlist/gfwlist#373]
Can not connect this web site with no proxy
Area:ZheJiang
ISP:China Telecom China Mobile China Unicom
Thanks !

**Comment by mraandtux** [comment]
本人已改h05t5，没问题，来源： racaljk/hosts
68.232.44.251 w3schools.com
68.232.44.251 www.w3schools.com
站长中国IP地址解出机挨服打不溜所使用的DNS污染地址：93.46.8.89 ，建议加入。

**Comment by chnt7305** [comment]
I don't use hosts very much.
Adding this address to the GFWlist will be more convenient.

**Comment by jdk200** [comment]
duplicates of #295.
