### ISSUE TITLE
some websites should be add to the list

### ISSUE THREAD

**Issue by sirius0427** [gfwlist/gfwlist#376]
*.githubapp.com
*.doubleclick.net
*.googleadservices.com

**Comment by cicku** [comment]
Please state briefly the reasons.

**Comment by sirius0427** [comment]
Because they are blocked by gfw in Jiangsu province,china unicom.

2016年10月17日 下午5:38，"Christopher Meng" <notifications@github.com>写道：

**Comment by cicku** [comment]
If you meet this again, please manually add custom rules since these are not blocked in most areas of China.
