### ISSUE TITLE
github.io 被墙

### ISSUE THREAD

**Issue by KelaKim** [gfwlist/gfwlist#379]
域名：
github.io
*.github.io

现象：
链接重置

**Comment by BROBIRD** [comment]
从IPIP.NET检测的结果看没有异常，请说明您的网络环境

**Comment by KelaKim** [comment]
刚刚去 17ce 测试了一下，似乎只有中国移动才会出现这样的情况。

**Comment by BROBIRD** [comment]
@KelaKim ![](http://i.imgur.com/wOowQng.png) 测试结果似乎也没有异常

**Comment by KelaKim** [comment]
![Guangdong CMCC](https://cloud.githubusercontent.com/assets/16115012/19426462/53107e50-946f-11e6-899b-c791783c5024.png)

我是广东移动的，我这样测试了一下链接还是被重置了，说明是广东移动对 github.io 整个域名给屏蔽了

![17ce](https://cloud.githubusercontent.com/assets/16115012/19426492/92bedd26-946f-11e6-9830-0d7bcb14a73b.png)

然后17ce移动也是，有 github.io 这个域就连接失败。（目前只有一个监测点响应了）

以上测试都使用 HTTP

**Comment by BROBIRD** [comment]
*.github.io推荐使用https访问。既然好像广东移动对此域名进行了额外的限制，建议你单独把它加入代理白名单。

**Comment by cicku** [comment]
@KelaKim 中国移动自带防火墙会屏蔽非常多的境外网站，与 GFW 无关。

建议您投诉。

**Comment by cicku** [comment]
GFWList 当前对此类网址的策略：https://github.com/gfwlist/gfwlist/wiki/ISP-support
