### ISSUE TITLE
i-scmp.com 錯誤503 上海電信

### ISSUE THREAD

**Issue by xFelino** [gfwlist/gfwlist#381]

**Comment by BROBIRD** [comment]
这个域名没有解析记录

**Comment by xFelino** [comment]
@BROBIRD http://cdn4.i-scmp.com/sites/default/files/styles/980x551/public/images/methode/2016/09/27/fe6d1f80-84af-11e6-8fff-f52227c06034_1280x720.jpg?itok=H8lvneD2

**Comment by BROBIRD** [comment]
并不能打开这个链接

2016-10-15 19:03 GMT+08:00 xFelino <notifications@github.com>:

**Comment by sharp-tasting** [comment]
可以打开啊，会显示图片无法展示
@BROBIRD

**Comment by xFelino** [comment]
@BROBIRD 从以下链接的网页中挖出来的链接 http://www.scmp.com/news/hong-kong/politics/article/2023026/hong-kong-lawmakers-warned-stick-exact-wording-their-oaths

**Comment by BROBIRD** [comment]
@sharp-tasting 没错

**Comment by BROBIRD** [comment]
@xFelino 那你应该写准确的域名cdn*.i-scmp.com，而不是i-scmp.com，另外我这里只有部分js文件出现503，而单独打开这些链接又正常，不是很懂，感觉不是墙的原因
