### ISSUE TITLE
duanzhihu.com

### ISSUE THREAD

**Issue by sharp-tasting** [gfwlist/gfwlist#382]
连接被重置

北京，CERNET和中国联通都连不上。

**Comment by BROBIRD** [comment]
这个网站以非授权方式爬取知乎网站内容并且二次传播，不建议加入gfwlist

**Comment by cicku** [comment]
@BROBIRD GFWList 不站在道德制高点上批判任何网站的行为，无论对错与否。

**Comment by BROBIRD** [comment]
@cicku 对本项目中立性表示理解。我出于保护版权的想法提出建议，但是也只是建议而已。感谢回复
