### ISSUE TITLE
dmm.com

### ISSUE THREAD

**Issue by imoyakin** [gfwlist/gfwlist#383]
建议添加dmm.com。虽然dmm.com并没有被墙，但是其服务限制于日本IP使用。为了便捷考虑，希望加入dmm.com。就之如之前的dmm.co.jp

**Comment by cicku** [comment]
dmm.com 许多内容是对所有地区开放的，请给出具体页面。

**Comment by imoyakin** [comment]
//仅限日本IP使用的DMM游戏
http://www.dmm.com/netgame_s/
如果仍认为过于宽泛，可以看下
//舰娘相关
http://www.dmm.com/netgame_s/kancolle/
http://www.dmm.com/netgame/social/-/gadgets/=/app_id=854854/

**Comment by cicku** [comment]
请问还有其他网址吗？如果没有我就提交您提供的这些了。

**Comment by biergaizi** [comment]
建议将所有锁区的网络单独标记和处理，避免和政府主导的网络审查相混淆，影响相关的测试研究。

**Comment by cicku** [comment]
@biergaizi 列表中有注释区分，如果有可能今后会拆开。
