### ISSUE TITLE
域名提交

### ISSUE THREAD

**Issue by 10089** [gfwlist/gfwlist#384]
blovcdn.com
bjs.org
china-a.de
chosun.com
cloudfront.net
edgesuite.net
epochtimes.com.au
digwebinterface.com
gbc.tw
hao123img.com
hyperspaceproxy.info
issuu.com
kanzhongguo.com.au
n2.hk
nasa.gov
navy.mil
ntdtv.com.tw
osaka69.com
projectosx.com
rssing.com
soompi.com
t9h.club
twitterstat.us
uncyc.org
uspto.gov
waknow.com
wenweipo.com
wsjemail.com
zhengjian.org
zhicat.com
zynamics.com
zyzc9.com
zzcartoon.com

bbc.com   ?

**Comment by 10089** [comment]
再提交一个域名污染
   help.vine.co

**Comment by e8732** [comment]
guga.ga

**Comment by cicku** [comment]
`bjs.org`
`issuu.com`

**Comment by cicku** [comment]
`cnnews.chosun.com/client/news/viw.asp?cate=C01&mcate`，KW: `C01`

**Comment by goudiao** [comment]
*.mediaite.com  被墙

**Comment by thisistianqi** [comment]
app.pomodoneapp.com
pomodoneapp.com
my.pomodoneapp.com/account/

**Comment by cicku** [comment]
@thisistianqi 挖坟是一种很不礼貌的行为。如果您想汇报，请新开 issue。
