### ISSUE TITLE
建议去掉apple.com

### ISSUE THREAD

**Issue by pi1ot** [gfwlist/gfwlist#389]
目前gfwlist包含apple.com，我所知的apple服务在国内都是可以联通的，这样会导致使用gfwlist的osx和ios用户的系统相关服务和应用连接变慢。

**Comment by cicku** [comment]
Apple 只是一个网址有访问故障，并不是全站需要代理。

并且近期我没有测试原有规则，暂不确定情况。

待我稍后重新测试做决定。

**Comment by cicku** [comment]
经测试现有规则仍然有效，无法去除。
