### ISSUE TITLE
去掉风车动漫 dm530.net

### ISSUE THREAD

**Issue by jeremy0714** [gfwlist/gfwlist#393]
用了直连，上风车看视频一周都没有问题
而且用在线群ping，国内国外ip解析都是一样的
可以把他拿掉了吧

**Comment by cicku** [comment]
请问您什么网络？

至少我这里测试的情况是全部拒绝访问。

**Comment by cicku** [comment]
检测结果为 `http://m.dm530.net/` 可以正常访问。

**Comment by jeremy0714** [comment]
湖北电信宽带  ping 域名是  184.105.154.154

在线ping  http://ping.chinaz.com/www.dm530.net
除了少数几个联通的，其他的好像都是正常的
