### ISSUE TITLE
Need explanation of the data format

### ISSUE THREAD

**Issue by fortuna** [gfwlist/gfwlist#401]
I couldn't figure out what the data format is. I did find out that it's base64-encoded, and we can get the clean text with:

    curl https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt | base64 -D

But then, what do all those prefixes mean?

`````
||dish.com
|http://img.dlsite.jp/
!--||share.dmhy.org
||dmm.co.jp
!--||dmm.com
||eesti.ee
.expekt.com
````

It would be great if the format was specified in the README file. Thank you!

**Comment by s7lx** [comment]
The format of gfwlist is AutoProxy……so plz google it by yourself

**Comment by cicku** [comment]
https://github.com/gfwlist/gfwlist/wiki/Syntax
