### ISSUE TITLE
Please add gochrome.info

### ISSUE THREAD

**Issue by qw4096** [gfwlist/gfwlist#402]
Please add gochrome.info,this domain I can't resolve IP address.Thank you!

**Comment by s7lx** [comment]
dig gochrome.info  @114.114.114.114

; <<>> DiG 9.8.3-P1 <<>> gochrome.info @114.114.114.114
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 60764
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;gochrome.info.			IN	A

;; ANSWER SECTION:
gochrome.info.		38	IN	A	185.28.21.103

;; Query time: 46 msec
;; SERVER: 114.114.114.114#53(114.114.114.114)
;; WHEN: Fri Nov 11 15:04:34 2016
;; MSG SIZE  rcvd: 47
