### ISSUE TITLE
https://services.mtps.microsoft.com/ServiceAPI/catalogs/dev14/en-us

### ISSUE THREAD

**Issue by zzhhbyt1** [gfwlist/gfwlist#405]
https://services.mtps.microsoft.com/ServiceAPI/catalogs/dev14/en-us
如果不在ss中开启全局代理，Visual Studio 2015的帮助查看器无法拉去在线书籍列表——提示`Error Connecting https://services.mtps.microsoft.com/ServiceAPI/catalogs/dev14/en-us`。开启全局可以解决此问题。
中国电信，江苏。
令人不解的是直接访问这个页面是可以打开的，我怀疑是不是VS里面单独设置了什么验证等更多需要访问的内容被屏蔽了。

**Comment by zzhhbyt1** [comment]
书籍的下载亦是开全局才可以在任务管理器中监测到下载流量，否则无法检测到正常的下载流量大小。

**Comment by cicku** [comment]
您给出的 URL 没有访问问题，不太清楚是什么原因。

我也无法测试，没有这个软件，也不用 Windows 系统。

**Comment by zzhhbyt1** [comment]
今天又进行了测试，似乎能正常了。可能是官方抽风吧。。如果再出问题我再来报吧。
