### ISSUE TITLE
dl.google.com 解封

### ISSUE THREAD

**Issue by PillowSky** [gfwlist/gfwlist#406]
dl.google.com

该域名重新解析到北京CDN，可以移出列表了
下载Chrome，Android SDK等都可以获得CDN加速了

附ping测试图
![capture](https://cloud.githubusercontent.com/assets/4303296/20515375/508dabca-b0cc-11e6-86d2-52089cf09b1a.PNG)

**Comment by lazyhero** [comment]
建议还是在列表里

**Comment by cicku** [comment]
@lazyhero 我认为目前该地址可以正常访问。

待无法访问的时候请开 Issue。
