### ISSUE TITLE
ddns.info解封

### ISSUE THREAD

**Issue by qiangliu8183** [gfwlist/gfwlist#410]

**Comment by cicku** [comment]
怎么个解封法？我这里无法访问

**Comment by qiangliu8183** [comment]
@cicku 这是DDNS动态域名，要解析到ip地址你才能访问

**Comment by cicku** [comment]
我找了一个域名：http://w7hd.ddns.info，链接被重置。

又测试了一下关键字：访问 http://example.com/.ddns.info，还是被重置。

**Comment by cicku** [comment]
如果您发现部分 ddns.info 动态域名解析至国内，请继续在此反馈。
