### ISSUE TITLE
ptt

### ISSUE THREAD

**Issue by jaccsr** [gfwlist/gfwlist#418]
https://www.ptt.cc
ERR_CONNECTION_TIMED_OUT
tianjin, china unicom

**Comment by cicku** [comment]
Tianjin Unicom tested, everything is fine.

Please recheck and report if possible.

Thanks!

**Comment by jaccsr** [comment]
您好
今天打开的结果是
DNS_PROBE_FINISHED_NXDOMAIN
我在使用chrome,，电脑的dns是8.8.4.4
改成联通dns之后，打开的结果是 ERR_CONNECTION_TIMED_OUT
非常感谢您维护这个列表。

**Comment by jaccsr** [comment]
您好
今天打开的结果是
DNS_PROBE_FINISHED_NXDOMAIN
我在使用chrome,，电脑的dns是8.8.4.4
改成联通dns之后，打开的结果是 ERR_CONNECTION_TIMED_OUT
非常感谢您维护这个列表。

**Comment by cicku** [comment]
It'd be better for you to switch to some clean public DNS like OpenDNS, and test again.

**Comment by jaccsr** [comment]
Hi there, I found the problem. The url of gfwlist in the SwitchyOmega suddenly became the old one http://autoproxy-gfwlist.googlecode.com/svn/trunk/gfwlist.txt So I can't access ptt.
