### ISSUE TITLE
报告功能可以和autoproxy-ng整合吗

### ISSUE THREAD

**Issue by luweitest** [gfwlist/gfwlist#421]
现在的那个report to gfwlist的功能似乎是失效的

**Comment by cicku** [comment]
1. 首先我不是很清楚您说的 `autoproxy-ng` 是哪个项目。
2. 所谓整合汇报功能，也是那边的事。
3. 报告问题地址改为 `https://github.com/gfwlist/gfwlist/issues/new` 即可解决这类问题。
4. 建议您联系对方。

**Comment by luweitest** [comment]
On 2016-12-2 13:46, Christopher Meng wrote:
>  1. 首先我不是很清楚您说的 |autoproxy-ng| 是哪个项目。
autoproxy的衍生版本之一

>  2. 所谓整合汇报功能，也是那边的事。
的确

>  3. 报告问题地址改为 |https://github.com/gfwlist/gfwlist/issues/new| 即
>     可解决这类问题。
>  4. 建议您联系对方。
已照您建议解决，谢谢！


-- 
Regards,
Lu Wei
PGP key ID: 0x A12F EF75 92CC E1EA
