### ISSUE TITLE
*.akamaihd.net

### ISSUE THREAD

**Issue by Missliaoo** [gfwlist/gfwlist#425]
包括UBI，战网海外版，Origin等游戏平台内容的下载都是经由这个域名，直接连接的速度很慢甚至无法连接，中转后能大幅提高连接速度，希望加入列表

**Comment by cicku** [comment]
凑巧，我目前正在完善 `https://github.com/gfwlist/gfwlist/wiki/Custom-Rules`。这个维基页面会包含一些不通畅连接的自定义规则解决方案。

CDN 类域名您只能暂时自行添加到自定义规则，因为我要考虑其他人的使用。CDN 为部分网站单独设置的二级域名可能会被添加，但是大多数情况下不会。
