### ISSUE TITLE
无法使用google play下载应用

### ISSUE THREAD

**Issue by Aidan-K** [gfwlist/gfwlist#427]
使用GFWlist模式无法google play下载应用，全局和大陆白名单模式下均可下载。是不是域名或IP为加进GFWlist？

**Comment by cicku** [comment]
麻烦汇报一下您的设备环境。

**Comment by Aidan-K** [comment]
安卓4.4
MIUI8
Google Play服务10.0.84(036-137749526)
Google Play商店7.2.13J-all[0][PR]138561921
SSR3.2.7.14
日本节点

**Comment by Aidan-K** [comment]
还需要什么信息吗？

**Comment by cicku** [comment]
如果有抓包软件就更好了，因为我暂时没有安卓设备……

**Comment by Aidan-K** [comment]
不会抓包咦

**Comment by Aidan-K** [comment]
要不教一下我，我抓好数据给你？

**Comment by yaoguaishou** [comment]
@Aidan-K http://www.coolapk.com/apk/app.greyshirts.sslcapture

**Comment by Aidan-K** [comment]
它是通过VPN抓包的，SSR一挂就没法抓包了

**Comment by Aidan-K** [comment]
一连接SSR就不能抓包了

**Comment by cicku** [comment]
不用连接 SSR，直接抓。

顺便我不太清楚您用的 SSR 配置文件是否是由 GFWList 转换的。

**Comment by BROBIRD** [comment]
是不是提示DF-DFERH-01错误？

**Comment by Aidan-K** [comment]
不连接SSR抓包？难道不是用GFWlist和绕过大陆和局域网两个抓包信息，把域名加进GFWlist吗？

**Comment by cicku** [comment]
@BROBIRD #464

**Comment by cicku** [comment]
@Aidan-K 您好，我已经在另一个汇报中发现了可能导致您无法下载 App 的原因，并更新了列表规则。如果您测试新的列表后一切正常，请告知我。

**Comment by fuckgfwgcd** [comment]
googles.com
googleapis.cn
gvt0.com
gvt1.com
gvt2.com
gvt3.com
在路由器ss中把这几个网址加入黑名单后，可以打开google paly app了，但是无法下载。但开全局模式可以下载。肯定还有什么域名被阻挡了，没有添加进gfwlist，有会抓包的同学研究下 @cicku

**Comment by cicku** [comment]
@fuckgfwgcd 感谢提供信息。您提供的这些网址除了 gvt2，GFWList 都有了。

**Comment by luweitest** [comment]
我这边用把安卓的系统代理设到Privoxy，打开Google play后的记录：
2017-01-24 15:34:30.343 0000095c Request: play.googleapis.com:443/
2017-01-24 15:34:31.187 00000f40 Request: android.clients.google.com:443/
2017-01-24 15:34:31.328 00000b1c Request: android.clients.google.com:443/
2017-01-24 15:34:31.437 00000200 Request: lh4.googleusercontent.com:443/
2017-01-24 15:34:31.468 000009b4 Request: android.clients.google.com:443/
2017-01-24 15:34:31.546 00000fec Request: android.clients.google.com:443/
2017-01-24 15:35:09.515 00000400 Request: lh3.googleusercontent.com:443/
2017-01-24 15:35:34.453 00000960 Request: android.clients.google.com:443/
2017-01-24 15:35:34.734 00000e7c Request: android.clients.google.com:443/
2017-01-24 15:35:35.500 000005d8 Request: android.clients.google.com:443/
2017-01-24 15:35:36.000 00000fa4 Request: android.clients.google.com:443/
2017-01-24 15:35:39.562 00000118 Request: android.clients.google.com:443/
2017-01-24 15:35:43.562 00000dd8 Request: android.clients.google.com:443/
2017-01-24 15:35:43.828 00000558 Request: android.clients.google.com:443/
2017-01-24 15:35:44.062 000009f0 Request: android.clients.google.com:443/
2017-01-24 15:36:12.312 00000194 Request: android.clients.google.com:443/
2017-01-24 15:36:16.296 00000f54 Request: android.clients.google.com:443/
2017-01-24 15:36:16.765 00000ab0 Request: android.clients.google.com:443/
然后超时失败。
感觉是android.clients.google.com这个网址很难在代理下访问，我试过在电脑上也不能访问，然而VPN模式下就可以打开Google play，不知为何

**Comment by cicku** [comment]
理论上不应该有访问故障，因为 GFWList 有对 google.com 的全站匹配。

**Comment by cicku** [comment]
我现在好像明白移动设备为什么有问题了，可能是你们使用的 GFWList 没有包含那个超长的正则规则。

GFWList 目前匹配 Google 是通过正则规则匹配 Google 全站（HTTP+HTTPS），用点号开头的规则匹配 HTTP 下的 Google 关键字。

而@luweitest 给出的日志很明显是 HTTPS 规则，然而移动设备下支持 js 正则的 PAC 我貌似还没见过，因此你们用的转换后的 PAC，可能不包含这个规则，导致 HTTPS 连接不上。

如果谁能够检查一下自己的 PAC，并告诉我这个猜想是正确的，那我将修改一下。

这个问题在 #113 已经被我考虑到了，不过过了这么久才有这样一个例子。

**Comment by luweitest** [comment]
安卓不支持本地PAC，我用的是 https://github.com/ssfdust/autoproxy2privoxy 这里转换来的gfwlist.action文件，因为Privoxy需要的是类似PAC的action文件。我找了一下里面有一行是  *.*google.com ，应该是已经全站匹配了。

**Comment by luweitest** [comment]
Update: 手工添加 android.clients.google.com 后，Google play 访问正常。应该是privoxy的action语法对通配符*的使用不包括"."吧。所以我的问题跟楼主的可能不是一回事啦

**Comment by Aidan-K** [comment]
我是用SSR-功能设置-路由-仅代理中国大陆无法访问的地址
使用的应该是原版GFW list吧？
https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt

**Comment by cicku** [comment]
@Aidan-K 理论上是原版，但是转换成 PAC 就不一定是原版的效果了。要看 PAC。

**Comment by Aidan-K** [comment]
那现在是要看看PAC的内容是怎么样的？PAC是在手机本地存储？

**Comment by cicku** [comment]
我没有用过 SSR，不是很清楚。PAC 是在本地存储的，应该软件内就可以查看，如果不行恐怕就需要自己找了。

**Comment by luweitest** [comment]
On 2017-1-24 22:26, Aidan-K wrote:
> 那现在是要看看PAC的内容是怎么样的？PAC是在手机本地存储？
> 
Android不支持本地存储PAC。估计要到你的SSR服务器上找，如果没有更改过，那就到SSR的软件包里找。


-- 
Regards,
Lu Wei
PGP key ID: 0x A12F EF75 92CC E1EA

**Comment by BROBIRD** [comment]
@Aidan-K 是本地的一个ACL文件

**Comment by smthvitas** [comment]
@cicku 我这也有这个问题。
域名列表是直接从gfwlist转换来的，其中有1e100.net这一条。手机上抓包看到的访问地址大部分是这个的子域名，解析后的ip在路由器ipset里边已经全有了，肯定走的是代理，但就是下载不了。如果直接绕过中国大陆地址就可以下，好奇怪。

**Comment by thinkingpad** [comment]
xn--ngstr-lra8j.com
加上这个应用下载就正常了。

**Comment by cicku** [comment]
已经按照 https://github.com/gfwlist/gfwlist/issues/427#issuecomment-289054570 添加，希望大家能够再次测试一下。

**Comment by Aidan-K** [comment]
如果还是使用SSR-功能设置-路由-“仅代理中国大陆无法访问的地址”的情况下，Google play store依然是能访问但无法下载应用。

**Comment by cicku** [comment]
我开始怀疑是不是手机上的代理功能有问题。

**Comment by BROBIRD** [comment]
可以尝试一下 https://github.com/ACL4SSR/ACL4SSR 里的规则是否可以正常使用Google Play

**Comment by Aidan-K** [comment]
@BROBIRD 试了一下，也不行

**Comment by Aidan-K** [comment]
https://github.com/breakwa11/GFWList2PAC/
不知道这个有没有关系

**Comment by darkgeek** [comment]
我用的是最新版地gfwlist，里面包含了 @thinkingpad 提到的xn--ngstr-lra8j.com
 ，但现在看来还是不能下载app……

**Comment by Aidan-K** [comment]
并非GFWlist及ShadowsocksR的问题
是由于小米手机的MIUI系统默认使用迅雷下载引擎导致在SSR中使用“仅代理中国大陆无法访问的地址”时无法下载Google Play中的APP

**Comment by cicku** [comment]
真的吗？:rofl:

**Comment by Aidan-K** [comment]
是的
关了迅雷下载引擎以后，不论是使用仅代理中国大陆无法访问的地址还是自定义acl都可以下载google play里的app

**Comment by Aidan-K** [comment]
是的
关了迅雷下载引擎以后，不论是使用仅代理中国大陆无法访问的地址还是自定义acl都可以下载google play里的app

**Comment by wpaengd** [comment]
xn--ngstr-lra8j.com
googleapis.cn
这两个添加后就可以了

**Comment by lzl119** [comment]
请问下你这现在解决了么

**Comment by galloperleon** [comment]
我有样的问题。现在找到了解决方法。

用全局模式，但是不要分应用代理，就可以正常使用。

**Comment by a94821** [comment]
通过packet capture抓包和比对shadowsocks自带的规则，确定是gvt0.com，gvt1.com，gvt3.com这三个域名缺失，k2路由器添加后手机play可以正常下载，望修复。

> 不用连接 SSR，直接抓。
> 
> 顺便我不太清楚您用的 SSR 配置文件是否是由 GFWList 转换的。

**Comment by eromoe** [comment]
一直要用全局，gfw 模式 就没法用

**Comment by frederick-wang** [comment]
> xn--ngstr-lra8j.com
> googleapis.cn
> 这两个添加后就可以了

确认有效，感谢！小米手机不用关迅雷引擎，关闭分应用代理，选用户规则，用户规则导入gfwlist后再把这两个域名添加上，然后就可以正常访问了。

**Comment by lakedai** [comment]
现在仍然有这个问题，google play可以访问，无法下载

**Comment by yang2git** [comment]
> xn--ngstr-lra8j.com
> googleapis.cn
> 这两个添加后就可以了

好像之前就没这问题，这个亲测有效，添加完之后Google Play就可以顺利更新app了。谢谢
