### ISSUE TITLE
建议加入share.dmhy.org

### ISSUE THREAD

**Issue by qw4096** [gfwlist/gfwlist#428]
虽然能上，但是速度很慢，加入pac后速度就正常了，这网站用的人应该挺多，所有建议加上

**Comment by biozzl** [comment]
GFWList doesn't provide prompt update for URLs submitted, normally they will be fully tested before adding into the list

**Comment by cicku** [comment]
早先该地址出于某种不可告人的原因是禁止国内IP访问的，后来解封了。

但是现在该地址并没有被墙，因此加入 GFWList 本身就是不成立的，如果`能上`但是`速度很慢`，您可以自行添加自定义规则解决。

**Comment by qw4096** [comment]
了解了，多谢
