### ISSUE TITLE
googleadservices.com谷歌的某个服务

### ISSUE THREAD

**Issue by 7senchen** [gfwlist/gfwlist#430]
打开某些网页时，时常遇到页面长时间载入不完的情况，后发现是因为某些页面元素来自于googleadservices.com这个域名，后将googleadservices.com添加至shadowsocks PAC文件中即解决，期待尽早加入gfwlist，谢谢！

**Comment by cicku** [comment]
只能说您的 ISP 封锁过于严重，因为该域名并没有被墙。请自行添加自定义规则解决此类问题。
