### ISSUE TITLE
多个直连无法打开的网址

### ISSUE THREAD

**Issue by 7senchen** [gfwlist/gfwlist#433]
以下网址，均未直连打不开或者载入奇慢的站点，挂代理后打开正常，期待加入gfwlist，谢谢！
sugumiru18.com
javmobile.net
sokmil.com
cosplayjav.pl
footjob-movie.com
findyoutube.com
nylonjp2.com
jav68.tv
hegre-art.com
hot-jav.com
allfinegirls.com
jamo.tv
watch8x.com
18cyber.com
jav68.me
3xhen.com
g-area.org
caribbeancompr.com
av28.com
jav2be.com
tumview.com

**Comment by cicku** [comment]
感谢整理，我稍后测试完毕根据结果加入至列表。
