### ISSUE TITLE
*.sourceforge.net

### ISSUE THREAD

**Issue by 476210180** [gfwlist/gfwlist#437]
Cannot access *.sourceforge.net (eg: openwrt-dist.sourceforge.net).
sourceforge.net (sourceforge main site) is accessible.

ISP: China Unicom, Liaoning province
Problem: Connection timed out

**Comment by cicku** [comment]
**It's better for you to provide the IP resolving result of `openwrt-dist.sourceforge.net`.**

I've tested through Beijing Telecom and Beijing Unicom, Tianjin Unicom, CERNET, the example you provided seems good to me. In the past it's blocked intermittently, but now I can't detect any blocks.

If you still have trouble accessing *.sourceforge.net, please add custom rules by yourself.
