### ISSUE TITLE
read01.com壹讀

### ISSUE THREAD

**Issue by 7senchen** [gfwlist/gfwlist#438]
read01.com 壹讀
需挂代理后才能打开，期待加入gfwlist，谢谢。
上海电信

**Comment by cicku** [comment]
我认为是该网站和 Cloudflare 之间存在问题，目前该网站可以正常打开但是返回500错误。

**Comment by cicku** [comment]
返回403错误，考虑添加。

**Comment by cicku** [comment]
该网站可能在配置 CDN 上出了问题，因为 Cloudflare 一直返回500错误，如果该网站屏蔽大陆地址，应该返回403，除非该网站不遵守标准。如果您有能力，可以联系该网站管理员询问。在此问题得到解决之前，请自行添加代理规则解决。
