### ISSUE TITLE
连接被重置

### ISSUE THREAD

**Issue by yaoguaishou** [gfwlist/gfwlist#440]
网站:www.sm-miracle.com
(p.s这个issues都快成开车区了)

**Comment by cicku** [comment]
您确定不是403而是连接被重置？

**Comment by yaoguaishou** [comment]
是的，链接被重置，使用gae代理可以正常访问

**Comment by cicku** [comment]
这就奇怪了……因为我无论如何也得不到连接被重置，类似的日本色情业网站我已经监控很久了，但是我发现了很奇怪的现象就是这些网站看似返回403屏蔽了大陆IP，但是使用特殊的浏览器和特殊的语言区域却可以直连。

**Comment by yaoguaishou** [comment]
那么应该是我这里运营商的问题了。
那么就不要加进去了，刚才发现不少vpn也是被403的

**Comment by cicku** [comment]
暂时保留这个汇报，稍后另行处理。
