### ISSUE TITLE
bt.byr.cn 被设置为忽略状态

### ISSUE THREAD

**Issue by huangfeihong** [gfwlist/gfwlist#442]
![image](https://cloud.githubusercontent.com/assets/15089154/21321089/4c2373a2-c64e-11e6-8aec-81bfa533e83c.png)
好像从SS更新的gfwlist默认是忽略bt.byr.cn，但有时候希望能在ipv4环境下访问，因此每次都需要手动将代理的忽略去掉，请问这个忽略能去掉么？还是有别的原因保留这项忽略比较合适？

**Comment by cicku** [comment]
北邮人 BT 不是只有 IPv6 能用吗？

**Comment by huangfeihong** [comment]
最近在尝试ipv4通过支持ipv6的SS代理访问，测试貌似访问和下载没问题，但gfwlist里面@@的等级貌似比允许代理更高，这样导致每次更新gfwlist就要手动删除@@，比较麻烦，六维的域名貌似也是这样的情况。

**Comment by huangfeihong** [comment]
六维地址是bt.neu6.edu.cn

**Comment by cicku** [comment]
我没遇到过您这种情况（您的意思是兜了一大圈代理最后又回到了国内），因为 GFWList 默认不支持 IPv6，我才加入的这些白名单规则，倒是可以删掉。

**Comment by huangfeihong** [comment]
主要是有时候需要通过代理访问ipv6的网站但每次都要手动把白名单里面的项目去掉才行，所以有点麻烦。

**Comment by cicku** [comment]
已经移除，感谢汇报。
