### ISSUE TITLE
请添加下面地址

### ISSUE THREAD

**Issue by Jacky89** [gfwlist/gfwlist#444]
http://utvpn.tsukuba.ac.jp/  深圳电信无法访问，全局模式才能正常访问
谢谢。

**Comment by cicku** [comment]
这货早就被 Softether 取代了，我认为没有必要加入。

**Comment by Jacky89** [comment]
2016/11/27    17:19        <dir> v4.22-9634-beta-2016.11.27-tree
下载链接这么新  我下载里面的文件 都是今年11月份更新 个人感觉不存在替代关系吧

**Comment by Jacky89** [comment]
PacketiX 这个是他的商业版本 除了增加授权 几无更改 确实无需添加
