### ISSUE TITLE
新增被墙网站

### ISSUE THREAD

**Issue by JoySky** [gfwlist/gfwlist#446]
Telegram一直无法使用，用全局代理的话又导致国内访问太慢，麻烦添加一下，谢谢

**Comment by JoySky** [comment]
刚才看了一下PAC文件，telegram.org已经添加了，但是使用PAC模式，仍然连接不上，我猜测是不是没有添加telegram.me导致的

**Comment by JoySky** [comment]
我自己把telegram.me添加到PAC中，仍然不好用，不知道为什么。

**Comment by Mirr0ch1** [comment]
还有tdesktop.com / tdesktop.org

**Comment by IxsCN** [comment]
telegram是直接使用ip的方式，所以自己抓包比较好。

**Comment by cicku** [comment]
@Mirr0ch1 您提供的两个域名都会自动跳转到 `telegram.org`。

**Comment by cicku** [comment]
@JoySky 问一下您使用 TG 的平台。

**Comment by cicku** [comment]
Telegram 使用多个 IP 段，GFWList 实在无法添加，如果各位能够解析出一些常用的，倒是可以进入列表。

**Comment by cicku** [comment]
由于 Telegram 近期全面被封锁，我正考虑添加IP段至列表中，撤销之前不添加的决定。

**Comment by cicku** [comment]
See #736
