### ISSUE TITLE
Please add lastpass.com into GFWList

### ISSUE THREAD

**Issue by davidshen84** [gfwlist/gfwlist#447]
`lastpass.com` can be access directly some times. But it takes too long and often cause time out on the client.

The website can be access quickly if connecting through a proxy or vpn. So I suggest adding it to the GFWList.

**Comment by yfdyh000** [comment]
不应该添加。首先它不是被全面封锁访问（我这里近年相对正常），所以按惯例也不会添加。其次是添加会导致基于GAE的客户端按规则用GAE访问该网站，而这严重增加用户的安全风险。

你可以添加IP到hosts文件试试，lastpass的可用入口IP不少的。我知道的有：
38.127.167.7 lastpass.com
38.127.167.7 www.lastpass.com
38.127.167.7 herndon-router-2.lastpass.com
以及 128.121.22.133、128.121.22.176、 23.43.189.197 等，适用上述域名。
你可以 https://[ip] 访问来试试速度和看SSL证书的适用范围，ping看网络延迟。
如果还有其他域名导致缓慢，网络抓包查看，查DNS包即可。

**Comment by cicku** [comment]
Please add custom rules if you have trouble accessing lastpass.
