### ISSUE TITLE
loganalyzer的报错页面在pac模式下无法打开

### ISSUE THREAD

**Issue by Jacky89** [gfwlist/gfwlist#458]
页面地址：http://kb.monitorware.com/kbeventdb-list-12-Adiscon-phpLogCon-11.html
报错内容：You don't have permission to access /kbeventdb-list-12-Adiscon-phpLogCon-11.html on this server.
全局代理模式可以打开，请添加规则，谢谢！
广东惠州  电信

**Comment by cicku** [comment]
请问您是否了解该站点屏蔽大陆IP的原因？我翻了翻这个网站，很多内容都是多年以前的，不太清楚。

**Comment by Jacky89** [comment]
具体原因不了解 最新的loganalyzer错误日志跳转到上述页面后 就有上述描述的问题
