### ISSUE TITLE
Inclusion and exclusion criteria?

### ISSUE THREAD

**Issue by zypA13510** [gfwlist/gfwlist#462]
AFAIK, there is no clear standard for the inclusion and exclusion of a certain domain/URL.
E.g. [#295](https://github.com/gfwlist/gfwlist/issues/295#issuecomment-270302210)

**Comment by zypA13510** [comment]
Updated the title to better reflect the current state of this issue.

**Comment by luweitest** [comment]
I think from cicku's reply, it is clear that his inclusion standard is "not directly accessible by IP address".

**Comment by zypA13510** [comment]
> |https://github.com/programthink/zhao

> |http://imgur.com/upload

> |http://www.nbc.com/live

Not directly accessible by IP indeed, I guess ;)

Btw, why use URL/domain name rather than route table if we're only to deal with inaccessible IPs/ASN?

**Comment by luweitest** [comment]
My interpretation does not mean I fully agree with his standard. I think gfwlist's initial purpose is to include any URL that  "not directly accessible by name". That's a more friendly way. However gfwlist seems now too big, and I second that some abridgement be done, to be maintained as a core list (a separate fully list could be maintained too, if resource permits). But in the case of w3schools.com, I am with you that it should be included, as it's a very useful site and should not be gfwed in anyway. (Maybe it is reported by some evil rival sites.)

**Comment by zypA13510** [comment]
I agree that "not directly accessible by name" is a more acceptable standard, and DNS poisoning (or anything similar) is part of the firewall, in my opinion. But that part is open for discussion.

What I'm trying to argue is that, from a project management perspective, a clear goal and specification make it easier to manage, especially when the project grows bigger. The dilemma here is caused by not having a specification, a clear inclusion criteria. Large projects, even those not related to software, need this to guide their future development. For example, Wikipedia has its own [inclusion guideline - notability](https://en.wikipedia.org/wiki/Wikipedia:Notability) and [exclusion guideline - what Wikipedia is not](https://en.wikipedia.org/wiki/Wikipedia:What_Wikipedia_is_not) so that people can reach consensus. And in this case about `w3schools.com`, this is what we need. People could have different idea, different standard, but to reach **consensus**, we need **guideline**.

And such specification can help in maintaining this list by allowing automation. The process of splitting this list into multiple parts, e.g. a core list and an extended/full list, could also get a lot easier.

**Comment by luweitest** [comment]
I thought that guideline was apparent, but obviously I am wrong. Yes we
need one. And you always have the option to fork -- someone may suggest,
though I hope this is not the answer.

-- 
Regards,
Lu Wei
PGP key ID: 0x A12F EF75 92CC E1EA
