### ISSUE TITLE
googleapis.cn

### ISSUE THREAD

**Issue by Pason2C** [gfwlist/gfwlist#464]
会导致GMS套件及Play store无法连接网络。 “从服务器检索信息时出错。[DF-DFERH-01] ” 
googleapis.cn

**Comment by cicku** [comment]
该域名目前被解析至中国大陆外 Google 数据中心，因此准许加入。至于您所提到的 Play 市场错误，我还不能判定是否与之有关。

**Comment by BROBIRD** [comment]
@cicku 经过抓包确认play store的问题是由此导致的，华为的研发人员反馈是应该是谷歌那边的问题。

**Comment by cicku** [comment]
这个错误在世界各地都出现过，所以很可能是谷歌的问题，我认为和谷歌的 SSL 证书加密有关，但是我也不确定。

**Comment by BROBIRD** [comment]
@cicku 应该不是SSL的问题，感觉是谷歌框架返回了错误的地址。因为我测试了一个正常的机器，访问的是android.clients.google.com，而不是出问题的services.googleapis.cn

**Comment by weizhen199** [comment]
现在还是有这个问题吧
