### ISSUE TITLE
some gfwed website

### ISSUE THREAD

**Issue by zhxhwyzh14** [gfwlist/gfwlist#470]
"||sipdir.online.lync.com",
  "||webdir.online.lync.com",
  "||autodiscover.outlook.com",
  "||sipfed.online.lync.com",
  "||d.docs.live.net",
  ".lync.com",
  ".live.net",
  ".live.com",
  ".microsoft.com",
  ".windows.com",
  ".livefilestore.com",
  ".gfx.ms",
  ".sfx.ms",
  "||skyapi.onedrive.live.com",

**Comment by zhxhwyzh14** [comment]
To improve the using experience of Onedrive, Onenote and Skype for Business.
There may are many unnecessary duplicate rules, please help me to delete them. Thanks a lot.

**Comment by cicku** [comment]
I will add these suggestions to wiki for future betterments when I finish the probe.

https://github.com/gfwlist/gfwlist/wiki/Custom-Rules#microsoft-office

Thanks!

_Plus: assets.onestore.ms -> ||onestore.ms_

**Comment by HankAviator** [comment]
please also consider
```
||skype.com^
||gvt1.com^
||live.com^
```
