### ISSUE TITLE
https://hstspreload.org/

### ISSUE THREAD

**Issue by ivysrono** [gfwlist/gfwlist#475]
https://hstspreload.org/

**Comment by cicku** [comment]
可以直连啊，请问您的 ISP？

**Comment by ivysrono** [comment]
Jiangsu unicom

**Comment by dujiulun** [comment]
I was gonna confirm the page is timed out from Shandong Mobile (Broadband), but it actually loads after 29.3 seconds...

I'm calling it a timeout anyway. ;)

**Comment by cicku** [comment]
Then someone will ask me for another criteria since 29.3s whether +1s or not is about half a minute, 51% people will decry me as they can wait for it and the rest of them have some droll thoughts against formers. :)
