### ISSUE TITLE
提交一個PAC地址

### ISSUE THREAD

**Issue by DeloresD** [gfwlist/gfwlist#476]
kkbox.com
說明：網站能打開，該公司音樂服務尚未開通大陸IP，需海外IP地址才能正常使用！

**Comment by cicku** [comment]
不知为何我使用香港 IP 访问依旧被检测为不支持地区，用日本 IP 就可以访问，请问该网站是不是只支持台湾和日本地址呢？希望了解更多情况，谢谢。

**Comment by DeloresD** [comment]
這個情況我不知道，我也是用日本的IP，詳細的你可以問一下KKBOX的客服
