### ISSUE TITLE
list里面有个url有问题？

### ISSUE THREAD

**Issue by ProkillerJ** [gfwlist/gfwlist#477]
[https://steamcommunity.com/groups/LibetTibet](url) LibetTibet？
![image](https://cloud.githubusercontent.com/assets/10797757/22180771/c9842460-e0b4-11e6-97b6-03ea908001e8.png)

**Comment by cicku** [comment]
什么问题？

**Comment by ProkillerJ** [comment]
抛开xx不谈，这样单独给一个组或个人添加难免会有种做广告的感觉的说

**Comment by cicku** [comment]
请自行访问 `http://example.com/steamcommunity.com/groups/LibetTibet`。
