### ISSUE TITLE
Please remove ftchinese and all similar rules(if exist)

### ISSUE THREAD

**Issue by luweitest** [gfwlist/gfwlist#481]
There are too many ftchinese lines. The main ftchinese.com site could be accessed directly. Those pages may be blocked because of full-text keyword filtering. This is not the case what gfwlist intended for. I just spot this one, there maybe others. Are there some automatic checking of gfwlist?

**Comment by cicku** [comment]
`This is not the case what gfwlist intended for`

Pointless.

**Comment by luweitest** [comment]
Because that will add too much rules into the list, For example any web page containing "KEYWORD" will trigger a reset.

**Comment by cicku** [comment]
You misunderstand why these URLs were added.

Visit `http://example.com/.ftchinese.com/story/001069516` on your own.

**Comment by luweitest** [comment]
On 2017-1-25 7:47, Christopher Meng wrote:
> You misunderstand why these URLs were added.
> 
> Visit |http://example.com/.ftchinese.com/story/001069516| on your own.
> 
I did visited some of them before I post. Some still blocked, some not.
If my guess (full-text keyword filtering) is wrong, please correct me.
Anyway, the site ftchinese is not blocked, neither sub domain nor
sub-directory of the site is blocked, but only some page of it is
blocked, and it is clear that those page contain "sensitive" keyword, so
as a non-tech I have this guess. If my guess it correct, do you agree
with my suggestion?

-- 
Regards,
Lu Wei
PGP key ID: 0x A12F EF75 92CC E1EA
