### ISSUE TITLE
Connection reset for http://i.imgur.com/* 

### ISSUE THREAD

**Issue by mario1103** [gfwlist/gfwlist#483]
Firefox reports "The connection was reset" when visiting i.imgur.com, and websites that use imgur for picture storage (like reddit) will have problem loading images.

**Comment by cicku** [comment]
Cannot confirm.

**Comment by mario1103** [comment]
Just tested reddit again and it seems that all pictures could load without any problem, but visiting i.imgur.com on firefox without using proxy still gets the connection reset error instead of getting redirected to imgur.com. Maybe it's just a temporary issue. More info on ISP: China Mobile Shandong, IP: 223.96.*.*

**Comment by cicku** [comment]
Thanks for the details, can you also provide the Reddit link?

**Comment by mario1103** [comment]
New update: Reddit could be visited directly without any problem, since all images on reddit are linked to imgur using https connection, while for some personal blogs that use http connection images on imgur could not be loaded. You can try to visit http://i.imgur,com and https://i.imgur.com

**Comment by cicku** [comment]
I can confirm from Beijing CMNET, but I believe it's a temporary block deployed at CMNET firewall only.
