### ISSUE TITLE
instmatrix.com DNS污染

### ISSUE THREAD

**Issue by ephz3nt** [gfwlist/gfwlist#486]
CN
![1](https://cloud.githubusercontent.com/assets/2176968/22615267/1e680336-eacc-11e6-9076-4381a5bf40db.png)

HK
![2](https://cloud.githubusercontent.com/assets/2176968/22615268/21ea9b4a-eacc-11e6-9389-42af36c1e81f.png)

**Comment by Ephzent** [comment]
![ping _ ip _ipip net](https://cloud.githubusercontent.com/assets/2176968/22615275/4d169d50-eacc-11e6-9cf6-bc27a1ecdcd1.png)

**Comment by cicku** [comment]
跳转到 `edgevpn.com`。

**Comment by cicku** [comment]
域名已作废，Edgevpn 访问正常。
