### ISSUE TITLE
twitch很慢，  *.ttvnw.net *.jtvnw.net *.akamaized.net  是twitch video主页

### ISSUE THREAD

**Issue by levenwindy** [gfwlist/gfwlist#488]
*.ttvnw.net
*.jtvnw.net
*.akamaized.net
添加这几个网址，翻墙看twitch就可以走ss了

**Comment by cicku** [comment]
Twitch 本身并没有被墙，因此无法添加到列表。但是 wiki 中已经加入相关自定义规则推荐，您可以在此查看：

`https://github.com/gfwlist/gfwlist/wiki/Custom-Rules#streaming`
