### ISSUE TITLE
Add google variants from different locales

### ISSUE THREAD

**Issue by raptordt** [gfwlist/gfwlist#503]
GFW doesnt have a number of google variants and therefore hangs on loading for various google international domains.

For example: http://www.google.com.sg/, google.com.tw, google.com.hk

**Comment by cicku** [comment]
GFWList has already included them for years, which platform are you using?

**Comment by raptordt** [comment]
I am using a 3rd party VPN called vpngui from 12vpn. Chrome 56 on Mac 10.10.5. Any good way to figure out why the localized google sites wouldnt work?

**Comment by cicku** [comment]
Are you using [this](https://github.com/FelisCatus/SwitchyOmega/wiki/GFWList)?
