### ISSUE TITLE
*.reutersmedia.net

### ISSUE THREAD

**Issue by octopusthu** [gfwlist/gfwlist#516]
curl reutersmedia.net
curl: (6) Could not resolve host: reutersmedia.net

Confirmed subdomains include the following, as is shown in the screenshot.
s2.reutersmedia.net
s3.reutersmedia.net
s4.reutersmedia.net

![screenshot-reutersmedia.net](https://cloud.githubusercontent.com/assets/5061611/23685909/927fda2c-03e1-11e7-9d74-eaa6f1701217.png)

**Comment by cicku** [comment]
Please tell me the source URL.
