### ISSUE TITLE
facebook 已经入华

### ISSUE THREAD

**Issue by renyouguo** [gfwlist/gfwlist#52]
全国范围内可以直接访问，经测试，图片等均可正常显示。

**Comment by sunsan05** [comment]
你翻墙了吧。哈哈。

**Comment by renyouguo** [comment]
@sunsan05 没有，非常确定是直连。你可以去查下，蔡英文的脸书被灌爆已经上新闻了。
而且我这twitter也解封了，但google没有。

**Comment by Ginko-1113** [comment]
楼上别闹快翻回来，该休息了。

**Comment by nxtreaming** [comment]
你钓鱼？

上海这边还是上不去。

2015-11-11 20:03 GMT+08:00 renyouguo <notifications@github.com>:

> @sunsan05 <https://github.com/sunsan05> 没有，非常确定是直连。你可以去查下，蔡英文的脸书被灌爆已经上新闻了。
> 而且我这twitter也解封了，但google没有。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gfwlist/gfwlist/issues/52#issuecomment-155758227>.
>



-- 
Founder of http://coogle.io

**Comment by nxtreaming** [comment]
楼主： 该吃药了。

**Comment by renyouguo** [comment]
蔡英文被中国大陆网民facebook大量留言 引起网战 - 8频道新闻及时事节目
http://www.channel8news.sg/news8/latestnews/20151111-wld-tw-tsai-ing/2252622.html
蔡英文脸书帐户突然出现大量中国网友 - BBC 中文网
http://www.bbc.com/zhongwen/simp/china/2015/11/151111_tsai_ing_wen_facebook

**Comment by nxtreaming** [comment]
你用表达什么？

赶紧回家吃药去！

2015-11-11 20:35 GMT+08:00 renyouguo <notifications@github.com>:

> 蔡英文被中国大陆网民facebook大量留言 引起网战 - 8频道新闻及时事节目
>
> http://www.channel8news.sg/news8/latestnews/20151111-wld-tw-tsai-ing/2252622.html
> 蔡英文脸书帐户突然出现大量中国网友 - BBC 中文网
> http://www.bbc.com/zhongwen/simp/china/2015/11/151111_tsai_ing_wen_facebook
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gfwlist/gfwlist/issues/52#issuecomment-155765563>.
>



-- 
Founder of http://coogle.io

**Comment by nxtreaming** [comment]
台独不台独不在这里讨论。

你有病，赶紧吃药去。

2015-11-11 20:35 GMT+08:00 renyouguo <notifications@github.com>:

> 蔡英文被中国大陆网民facebook大量留言 引起网战 - 8频道新闻及时事节目
>
> http://www.channel8news.sg/news8/latestnews/20151111-wld-tw-tsai-ing/2252622.html
> 蔡英文脸书帐户突然出现大量中国网友 - BBC 中文网
> http://www.bbc.com/zhongwen/simp/china/2015/11/151111_tsai_ing_wen_facebook
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gfwlist/gfwlist/issues/52#issuecomment-155765563>.
>



-- 
Founder of http://coogle.io

**Comment by falseen** [comment]
我晕，人家只是想证明facebook可以从大陆访问了而已，用得着恶意相向么。
另外问下 @renyouguo  你是什么地区的？我这里还是访问不了。

**Comment by renyouguo** [comment]
@falseen 江苏。电信和联通都测了。
网上看到浙江也可以了。
有猜测是部分放开，内测中。

**Comment by falseen** [comment]
估计又是政治性的临时解封，不然解封之后的第一条新闻不会是“蔡英文脸书被刷爆”，这明显是有政治意图的。

**Comment by renyouguo** [comment]
不知道是否与我用了dns加密有关。
先放着吧，我暂时将fb和twitter都加入了白名单，过几天看看再说。
