### ISSUE TITLE
myspacecdn.com

### ISSUE THREAD

**Issue by 10089** [gfwlist/gfwlist#523]
[Myspace](https://myspace.com)   cdn 域名 
[如css](https://x.myspacecdn.com/new/common/css/authentication.FFEE5865CE38A4E0A1E2710990243503.min.css)
[图片](https://a1-images.myspacecdn.com/images04/1/3a87e46a6c4b467ea29ede444297c0c9/300x300.jpg)

**Comment by 10089** [comment]
[cdn-images.mailchimp.com](https://cdn-images.mailchimp.com/embedcode/slim-081711.css)

国外很多域名的网站用到这域名

**Comment by cicku** [comment]
#526
