### ISSUE TITLE
GOOGLE的字体网站不在列表里

### ISSUE THREAD

**Issue by ccimage** [gfwlist/gfwlist#527]
fonts.gstatic.com

测试地址https://fonts.gstatic.com/s/roboto/v15/d-6IYplOFocCacKzxwXSOFtXRa8TVwTICgirnJhmVJw.woff2

**Comment by ccimage** [comment]
ISP杭州电信， DNS阿里云223.6

**Comment by ccimage** [comment]
测试了一下，是我的DNS解析不出来，那是为什么呢

**Comment by cicku** [comment]
您使用的 DNS 有问题。正常情况下都会解析到国内的 Google 服务器。
