### ISSUE TITLE
bloom.bg

### ISSUE THREAD

**Issue by Cloverr0** [gfwlist/gfwlist#53]
short url for bloomberg.com

**Comment by poliang** [comment]
广东电信正常，但无法跳转
```
% >> curl bloom.bg -v
* Rebuilt URL to: bloom.bg/
*   Trying 69.58.188.49...
* Connected to bloom.bg (69.58.188.49) port 80 (#0)
> GET / HTTP/1.1
> Host: bloom.bg
> User-Agent: curl/7.45.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Server: nginx
< Date: Sat, 05 Dec 2015 16:12:55 GMT
< Content-Type: text/html; charset=UTF-8
< Content-Length: 0
< Connection: keep-alive
< Location: http://www.bloomberg.com/
< Pragma: no-cache
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< 
* Connection #0 to host bloom.bg left intact
```
```
% >> curl bloom.bg -v -L
* Rebuilt URL to: bloom.bg/
*   Trying 69.58.188.49...
* Connected to bloom.bg (69.58.188.49) port 80 (#0)
> GET / HTTP/1.1
> Host: bloom.bg
> User-Agent: curl/7.45.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Server: nginx
< Date: Sat, 05 Dec 2015 16:14:34 GMT
< Content-Type: text/html; charset=UTF-8
< Content-Length: 0
< Connection: keep-alive
< Location: http://www.bloomberg.com/
< Pragma: no-cache
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< 
* Connection #0 to host bloom.bg left intact
* Issue another request to this URL: 'http://www.bloomberg.com/'
*   Trying 159.106.121.75...
^C
```

**Comment by cicku** [comment]
HTTPS RST

**Comment by cicku** [comment]
HTTP RST (After first successful connection)

**Comment by cicku** [comment]
--> bit.ly

**Comment by cicku** [comment]
$ curl https://bloom.bg -v -L
* Rebuilt URL to: https://bloom.bg/
*   Trying 69.58.188.49...
* Connected to bloom.bg (69.58.188.49) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* ALPN, server accepted to use http/1.1
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
* 	subject: CN=bloom.bg
* 	start date: Apr 06 21:41:00 2016 GMT
* 	expire date: Jul 05 21:41:00 2016 GMT
* 	common name: bloom.bg
* 	issuer: CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US
> GET / HTTP/1.1
> Host: bloom.bg
> User-Agent: curl/7.48.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Content-Length: 0
< Content-Type: text/html; charset=UTF-8
< Date: Mon, 25 Apr 2016 08:32:33 GMT
< Location: http://www.bloomberg.com/
< Pragma: no-cache
< Server: nginx
< 
* Connection #0 to host bloom.bg left intact
* Issue another request to this URL: 'http://www.bloomberg.com/'
*   Trying 72.247.118.137...
* Connected to www.bloomberg.com (72.247.118.137) port 80 (#1)
> GET / HTTP/1.1
> Host: www.bloomberg.com
> User-Agent: curl/7.48.0
> Accept: */*
> 
* Recv failure: Connection reset by peer
* Closing connection 1
curl: (56) Recv failure: Connection reset by peer
