### ISSUE TITLE
bbc中文网不能访问

### ISSUE THREAD

**Issue by sky123456789sky** [gfwlist/gfwlist#533]
看了下少了句 if (dnsDomainIs(host, ".bbc.com/zhongwen") || host == "bbc.com/zhongwen") return "PROXY GOAGENT_LISTEN";

**Comment by cicku** [comment]
没看懂您想说明什么？

**Comment by sky123456789sky** [comment]
@cicku 是这样的 使用XX-NET的PAC模式翻墙时候 BBC中文网 http://www.bbc.com/zhongwen/simp 无法访问 然后在PAC文件里填了句     if (dnsDomainIs(host, ".bbc.com/zhongwen") || host == "bbc.com/zhongwen") return "PROXY GOAGENT_LISTEN"; 便可以了  不知道这是否和gfwlist有关系？？

**Comment by cicku** [comment]
```
$ cat list.txt | grep bbc[.]com
.bbc.com/ukchina
.bbc.com/zhongwen
.bbc.com%2Fzhongwen
```

如果您通过 `http://www.bbc.com/zhongwen/simp` 访问，理论上不会出现问题。

**Comment by yfdyh000** [comment]
@sky123456789sky xx的pac（未测试最新）里有 `if (url.indexOf(".bbc.com/zhongwen") >= 0) return "PROXY GOAGENT_LISTEN";`

**Comment by sky123456789sky** [comment]
对 我也看到里面有他的地址 但是就是不行 最奇怪的是使用chrome的SwitchyOmega的pac模式是没有问题的 但是win10自带的Edge和IOS的浏览器使用PAC模式时 是怎么都打不开BBC中文网的 然后按照纽约时报中文网的格式添了句 就没有问题了 很奇怪哦

**Comment by yfdyh000** [comment]
但你的代码很奇怪，给dnsDomainIs与host的都不是主机名，怎么匹配成功而返回呢。
是否是测试失误、只需刷新呢。

**Comment by sky123456789sky** [comment]
@yfdyh000 看了下定义 额 代码本身写的就不对啊 哈哈 自己加的全部删掉 然后重启 竟然神奇的可以上了 这是个什么情况 整整一年PAC模式不能上BBC中文网啊

**Comment by yfdyh000** [comment]
是否之前系统代理的设置有误呢。另外，Edge等UWP应用印象中不能访问本地环回（127.0.0.1），除非Fiddler（或其他工具？）为应用设置例外。不确定后续情况如何。xx-net的讨论区有不少Edge的issue可参考。

**Comment by sky123456789sky** [comment]
@yfdyh000 代理设置就没有动 和以前是一样的 XX是装在路由器里的 手机通过PAC模式直接翻墙 反正是去年突然之间BBC不能上了 然后昨天其实什么都没有动 只在PAC文件里加了句 就可以了 刚刚又删了 然后保存 还是可以 那么只能说是网络发神经了。。。。。。。。。

**Comment by cicku** [comment]
反正我是一直觉得 PAC 支持有 bug，不管怎样，问题解决了就好。
