### ISSUE TITLE
今日更新之后 BBC中文网 PAC模式再次失效

### ISSUE THREAD

**Issue by sky123456789sky** [gfwlist/gfwlist#535]
如题 又加上if (url.indexOf(".bbc.com") >= 0) return "PROXY GOAGENT_LISTEN"; 又可以用了 希望下次更新可以加上此条   
 .bbc.com/zhongwen 这条是不起作用的

**Comment by cicku** [comment]
`.bbc.com` 关键字并没有被墙，因此不能加入。

建议您与 XX-NET 反馈问题。

**Comment by yscia007** [comment]
能否把www.seleniumhq.org 加入到list中呢 





在 2017-03-22 13:25:31，"sky123456789sky" <notifications@github.com> 写道：


如题 又加上if (url.indexOf(".bbc.com") >= 0) return "PROXY GOAGENT_LISTEN"; 又可以用了 希望下次更新可以加上此条
.bbc.com/zhongwen 这条是不起作用的
