### ISSUE TITLE
linksys官网被墙

### ISSUE THREAD

**Issue by sec314** [gfwlist/gfwlist#536]
北京联通、重庆电信都无法连接
C:\>ping www.linksys.com

正在 Ping dj8ljw9pzna3b.cloudfront.net [93.46.8.89] 具有 32 字节的数据:
请求超时。
请求超时。
请求超时。
请求超时。

93.46.8.89 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 0，丢失 = 4 (100% 丢失)，

**Comment by cicku** [comment]
现在官网已经能打开，提示是否跳转到中国区网站。

**Comment by sec314** [comment]
我这里还是解析到那个IP

**Comment by cicku** [comment]
```
>nslookup www.linksys.com 8.8.8.8
服务器:  google-public-dns-a.google.com
Address:  8.8.8.8

非权威应答:
名称:    dj8ljw9pzna3b.cloudfront.net
Addresses:  54.182.2.62
          54.182.2.143
          54.182.2.74
          54.182.2.78
          54.182.2.106
          54.182.2.92
          54.182.2.12
          54.182.2.192
Aliases:  www.linksys.com
```

**Comment by cicku** [comment]
93.46.8.89 是 GFW 的欺骗应答。

请注意您在科学上网时应该**主动**避免受到 DNS 污染，应自行绕过（远程解析 DNS，或者 TCP 解析 DNS），注意使用 Google Public DNS 也不能解决问题，因为 Google Public DNS 也是**被照顾**的，但根据 ISP 策略，部分 ISP 并没有干扰。

现在没关闭的多个 Issue 都是要求加入这种因使用被 DNS 污染的 CDN 服务的网站，这类网站数不胜数，但是受制于 DNS 污染程度（`http://ping.chinaz.com/www.linksys.com`，这个页面可能你过一小时再访问一遍，结果又不一样），GFWList 暂时不能加入它们。

请您暂时添加自定义规则解决。

**Comment by sec314** [comment]
好的，我先自定义规则吧。
