### ISSUE TITLE
{a1,typeface,static01}.nyt.com

### ISSUE THREAD

**Issue by dujiulun** [gfwlist/gfwlist#561]
* 域名：a1.nyt.com, typeface.nyt.com, static01.nyt.com
（前两个CNAME到nytimes.map.fastly.net，最后一个直接污染）
* 现象：DNS污染。使用a1.nyt.com测试，各运营商都有污染。
* 相关Issue：#262（把这个域名注释掉了）

**Comment by cicku** [comment]
`nytimes.map.fastly.net` RST.
