### ISSUE TITLE
vimeo有个cdn链接不在pac文件里，导致出现访问vimeo，不能加载css

### ISSUE THREAD

**Issue by jeanim** [gfwlist/gfwlist#563]
cdn链接： f.vimeocdn.com

**Comment by cicku** [comment]
请给出引用页面。

**Comment by jeanim** [comment]
就vimeo主页

**Comment by cicku** [comment]
访问并无异常，请问您的 ISP？

**Comment by gefangshuai** [comment]
这俩无法正常访问：
```
*.gtrk.s3.amazonaws.com
*.vimeocdn.com
```
@cicku

**Comment by jeanim** [comment]
这是用户出现的情况，我这也是正常的，对方ISP是：浦东联通，我在他的pac文件里加上f.vimeocdn.com后就正常了
@cicku

**Comment by cicku** [comment]
`fresnel.vimeocdn.com`

**Comment by cicku** [comment]
vimeocdn.com 没有被墙，只是因为地理位置缘故国内访问会很慢。

GFWList 无法加入没有被墙的网址，但已写入 wiki 说明。
