### ISSUE TITLE
fonts.googleapis.com国内能使用，建议出除

### ISSUE THREAD

**Issue by xujiangit** [gfwlist/gfwlist#565]
还有groups.google.cn域名已消失
nslookup fonts.googleapis.com
Server:		192.168.1.1
Address:	192.168.1.1#53

Non-authoritative answer:
fonts.googleapis.com	canonical name = googleadapis.l.google.com.
Name:	googleadapis.l.google.com
Address: 203.208.41.35
Name:	googleadapis.l.google.com
Address: 203.208.41.46
Name:	googleadapis.l.google.com
Address: 203.208.41.36
Name:	googleadapis.l.google.com
Address: 203.208.41.38
Name:	googleadapis.l.google.com
Address: 203.208.41.39
Name:	googleadapis.l.google.com
Address: 203.208.41.32
Name:	googleadapis.l.google.com
Address: 203.208.41.34
Name:	googleadapis.l.google.com
Address: 203.208.41.40
Name:	googleadapis.l.google.com
Address: 203.208.41.33
Name:	googleadapis.l.google.com
Address: 203.208.41.37
Name:	googleadapis.l.google.com
Address: 203.208.41.41
Name:	googleadapis.l.google.com
Address: 2404:6800:4005:804::200a

nslookup fonts.googleapis.com 114.114.114.114 
Server:		114.114.114.114
Address:	114.114.114.114#53

Non-authoritative answer:
fonts.googleapis.com	canonical name = googleadapis.l.google.com.
Name:	googleadapis.l.google.com
Address: 203.208.39.228
Name:	googleadapis.l.google.com
Address: 203.208.39.230
Name:	googleadapis.l.google.com
Address: 203.208.39.224
Name:	googleadapis.l.google.com
Address: 203.208.39.238
Name:	googleadapis.l.google.com
Address: 203.208.39.231
Name:	googleadapis.l.google.com
Address: 203.208.39.225
Name:	googleadapis.l.google.com
Address: 203.208.39.233
Name:	googleadapis.l.google.com
Address: 203.208.39.226
Name:	googleadapis.l.google.com
Address: 203.208.39.227
Name:	googleadapis.l.google.com
Address: 203.208.39.232
Name:	googleadapis.l.google.com
Address: 203.208.39.229
Name:	googleadapis.l.google.com
Address: 2404:6800:4005:800::200a

**Comment by cicku** [comment]
fonts.googleapis.com 是作为白名单排除的，不走代理呀。

**Comment by nonozone** [comment]
这个只是个别区域吧，明明这个地址还是需要走代理的。及时我在下面添加了这个地址，依然不走代理，好郁闷啊。
