### ISSUE TITLE
.ftchinese.com

### ISSUE THREAD

**Issue by Wows233** [gfwlist/gfwlist#572]
.ftchinese.com

**Comment by cicku** [comment]
FTChinese 只是部分页面被墙，如果您要汇报，请给出具体页面链接。

#240

**Comment by Wows233** [comment]
此网站不稳定。。我发布时直接连接无法访问。。

**Comment by cicku** [comment]
略认可您的说法，前几天该站全站被和谐，随后过了一天又恢复正常。
