### ISSUE TITLE
google earth web版要全局才能访问

### ISSUE THREAD

**Issue by fuckgfwgcd** [gfwlist/gfwlist#577]
google earth web版要全局才能访问:https://earth.google.com/web    
不知道还有那些网址被墙，求大神找到加入到gfwlist之中

**Comment by fuckgfwgcd** [comment]
如果不开全局，就始终停留在加载页面 
![qq 20170501005501](https://cloud.githubusercontent.com/assets/25108569/25566331/3efdd6cc-2e09-11e7-8533-83dee4f8958b.jpg)

**Comment by cicku** [comment]
```
您的连接不是私密连接

攻击者可能会试图从kh.google.com窃取您的信息（例如：密码、通讯内容或信用卡信息）。 NET::ERR_CERT_COMMON_NAME_INVALID
```
疑似中间人攻击呢，再看看。`kh.google.com` 之间根据某人建议，加入了白名单，因为国内可以访问。

**Comment by fuckgfwgcd** [comment]
把kh.google.com加入代理名单还是不行

**Comment by cicku** [comment]
现在貌似正常了，估计是服务器的问题。

**Comment by fuckgfwgcd** [comment]
还是要全局才行，关键是找不到那个网址被墙

**Comment by cicku** [comment]
查阅了源代码。如果 kh 加入代理规则仍不能解决问题，那只能试试加入 `fonts.googleapis.com`，除此之外所有元素均已被 GFWList 覆盖。

**Comment by fuckgfwgcd** [comment]
可以了，把fonts.googleapis.com加入代理列表就OK了！ @cicku
