### ISSUE TITLE
synd.co 遭重置

### ISSUE THREAD

**Issue by xFelino** [gfwlist/gfwlist#58]

**Comment by poliang** [comment]
广东电信一切正常  
![2015-12-05 23-22-52](https://cloud.githubusercontent.com/assets/5986078/11608573/f41f8dd4-9ba7-11e5-85f4-6b65aa7df4f6.png)

**Comment by cicku** [comment]
第一次连接正常，随后RST

**Comment by cicku** [comment]
您好，请问 https 的网址您最早是如何发现的？

**Comment by cicku** [comment]
Keyword: `bit.ly`, `HTTPS`

**Comment by cicku** [comment]
目前应该没有问题了。
