### ISSUE TITLE
api.nuget.org

### ISSUE THREAD

**Issue by zzhhbyt1** [gfwlist/gfwlist#589]
Affect installation of nuget packages in Visual Studio.
China Telecom, Jiangsu.

**Comment by cicku** [comment]
Direct connection works and I can't see any problem under China Unicom.

Can you particularize the issue you met?

**Comment by zzhhbyt1** [comment]
Seems Microsoft fixed the issue, maybe it's due to nuget's Chinese CDN failure not gfw.
Anyway it works normally now. Before, night's raw packages can't be downloaded.

**Comment by zzhhbyt1** [comment]
Mis-typed: Nuget's raw packages can't be downloaded.
