### ISSUE TITLE
please add those blocked domain

### ISSUE THREAD

**Issue by cpmbwo** [gfwlist/gfwlist#59]
*.thumbsnap.com
*.bzpics.com
*.vivthomas.com
*realitykings.com
*ddfcash.com
*.99btgc01.???
*.phncdn.com
*.mxn.com

**Comment by cicku** [comment]
Still NEEDINFO/TRACKING of following:

*.thumbsnap.com
*.bzpics.com
*realitykings.com
*ddfcash.com
*.mxn.com

**Comment by cpmbwo** [comment]
mxn.com may pass.
missing point (.) between * and the first letter:
    *.realitykings.com
    *.ddfcash.com
see:http://nats.ddfcash.com/#!home and http://www.realitykings.com/main.htm
    realitykings.com lead to *.rk.com and is blocked too.
just visit http://thumbsnap.com/
*.bzpics.com is strange. I forget where to find it. but I am sure it is a picture web site includeing porn.

**Comment by cicku** [comment]
All these above can be accessed without issues here. Please check if there is any ISP fixes.

Tracking still.

**Comment by cicku** [comment]
Please open a new issue if these above get blocked in the future. Closing.
