### ISSUE TITLE
Add more banned websites

### ISSUE THREAD

**Issue by techyanWP** [gfwlist/gfwlist#597]
The following websites are blocked by GFW, but not included in GFWList. I cannot make sure that all websites are banned, but base on my test, they are inaccessible in mainland China.

- Mobile versions of wuu and yue Wikipedia. The m.wikipedia.org subdomains are not added to the list.

- www.exelate.com

- bluekai.com

- pixcdn.tw

- cpx.to

- tw-blog.com

- binux.me

**Comment by cicku** [comment]
Hi,

I believe all domains you mentioned above which veritably meet the criteria have been added into the list. Should you have any questions, please feel free to comment.

Thanks for your support.
