### ISSUE TITLE
blogspot.com被墙

### ISSUE THREAD

**Issue by sadan9** [gfwlist/gfwlist#6]
blogspot.com无法直接访问，用代理可以

**Comment by cicku** [comment]
blogspot 列表都包含了好几年了，不应该出现这个问题啊。

**Comment by kimw** [comment]
经查，在 gfwlist.txt 中确实没有这个域名。

**Comment by cicku** [comment]
blogspot 在 list 中是以正则表达式的形式存在的

**Comment by sadan9** [comment]
好吧= =b，我的错……
我的用法是解析gfwlist.txt，然后将域名加入到openwrt的/etc/dnsmasq.conf里，目前解析程序是不处理正则的……

不过也提个建议，是否能考虑下不支持正则的设备……

**Comment by cicku** [comment]
你的想法很好，跟我学用挖掘机炒菜吧 :joy: 所有域名都有 Google 的预留，正则基本上是为 Google 准备的...列表全加上估计会很难看的...正则能解决的都尽可能解决，除非你真的用挖掘机炒菜... 

这可能可以成为一个 feature，计划写程序自动转换。
