### ISSUE TITLE
https://*.v2ex.com 请取消

### ISSUE THREAD

**Issue by cevin** [gfwlist/gfwlist#603]

**Comment by shansing** [comment]
I agree.

https://*.v2ex.com can already be accessed in mainland China normally, so it should be removed from the list.

**Comment by mengyaoss77** [comment]
+1 .

**Comment by c118160** [comment]
此站已在国内备案，应该是可以取消了。

**Comment by mailsuhua** [comment]
链接时好时坏，有时必须添加到代理里才能访问。

**Comment by cicku** [comment]
#221
