### ISSUE TITLE
请添加https://www.fuckbilibili.com/

### ISSUE THREAD

**Issue by Marchlie** [gfwlist/gfwlist#609]
该网址限制为在不使用代理的情况下无法访问

**Comment by jinliming2** [comment]
其实可以直接访问。。。
右键查看网页源代码，或是Chrome浏览器Ctrl+U，或是F12，在head里有提示哦。。。
顺便一提，这种简单的md5随便找个网站在线就能破解了。。。比如cmd5。。。

**Comment by cicku** [comment]
这种操作我也没有办法呀……
