### ISSUE TITLE
fonts.googleapis.com 能走proxy吗

### ISSUE THREAD

**Issue by elvis-macak** [gfwlist/gfwlist#610]
感觉这个不是很稳定, 
我在上海的电信和联通, 这个经常访问不了

```
$ nslookup fonts.googleapis.com
Server:		8.8.8.8
Address:	8.8.8.8#53

Non-authoritative answer:
fonts.googleapis.com	canonical name = googleadapis.l.google.com.
Name:	googleadapis.l.google.com
Address: 172.217.25.10

$ ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
```

**Comment by elvis-macak** [comment]
Along with `https://fonts.gstatic.com`, It cannot be accessed, also.

**Comment by yvbbrjdr** [comment]
+1 googleapis.com 和 gstatic.com 好像都挂了
建议把cloudfront也加进去

**Comment by BROBIRD** [comment]
感觉是你自己的DNS策略问题啊

**Comment by elvis-macak** [comment]
@BROBIRD 你的意思是？我DNS用8.8.8.8不对？

_Sent from my LGE LGUS992 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by BROBIRD** [comment]
![default](https://user-images.githubusercontent.com/7692707/27517542-ff323a8c-5a00-11e7-8331-cdc826a77efc.png)
![default](https://user-images.githubusercontent.com/7692707/27517549-1669ca76-5a01-11e7-880e-43497d66c370.png)
不清楚你那边的状况……我这里不存在问题，8.8.8.8也是解析到国内
