### ISSUE TITLE
Pls remove

### ISSUE THREAD

**Issue by iam3ddy** [gfwlist/gfwlist#614]
pls remove singaporepools.com

**Comment by cicku** [comment]
Can you please particularize the reason?

**Comment by iam3ddy** [comment]
![untitled](https://user-images.githubusercontent.com/21017389/27368231-de6cc1ee-5683-11e7-8e3a-2b175f40a9be.jpg)


geo-block on this website.

**Comment by cicku** [comment]
I can't access the domain if it is not handled through proxy. Always RESET.
