### ISSUE TITLE
please remove the domain  ifanr.com

### ISSUE THREAD

**Issue by qingyi** [gfwlist/gfwlist#624]
remove the domain  ifanr.com,  它在内地，通过代理反而访问不了

**Comment by cicku** [comment]
列表只是包含了一个关键字，并非全站。

该关键字仍然有效，但是鉴于该网站的网页命名方式早已变化，因此移除。

您使用的 GFWList 并非我们建议的方法，可能是通过某些程序转换得出的“列表”，只能保证大致的使用不出问题，无法精细匹配网址。
