### ISSUE TITLE
xxshe.com  dns 污染，无法解析

### ISSUE THREAD

**Issue by bob0627** [gfwlist/gfwlist#628]
www. 被污染，其他子域名也一样。

**Comment by cicku** [comment]
HTTPS?

**Comment by bob0627** [comment]
也是不行的，默认已经用了hsts，国内ping的话都是被解析到其他了跟Google一样

**Comment by bob0627** [comment]
而且是部分地区解析感染，少数部分地区还是能正常解析的。。这个时候回国有用？

**Comment by cicku** [comment]
我可以正常访问 HTTPS。

**Comment by bob0627** [comment]
https://i.imgur.com/v2Q0bHh.jpg  @cicku   只有少数部分用户可以正常解析，要不然我先换个国内的ns试试看吧。
