### ISSUE TITLE
请求增加 https://*.wordpress.com

### ISSUE THREAD

**Issue by c118160** [gfwlist/gfwlist#632]
经查看当前过滤列表，只有
```
.wordpress.com
|http://*.wordpress.com
```
在foxyproxy下不能正常代理https协议的 wordpress.com 。

**Comment by cicku** [comment]
并不是所有的 wordpress.com 子域的 HTTPS 连接是被干扰的，我的观测是 GFW 应该对部分不和谐的网址特殊关照，如果您发现了不能访问的地址，请在此提交。
