### ISSUE TITLE
希望能将ipv6地址不通过代理访问

### ISSUE THREAD

**Issue by czt95** [gfwlist/gfwlist#64]
贴个网址 http://bt.byr.cn/torrents.php http://bt.neu6.edu.cn/search.php

**Comment by cicku** [comment]
gfwlist 依赖于域名，对于域名指向的地址，无能为力。

但是，鉴于您提出的两个域名是国内大学的 BT 网站，应该是仅允许 IPv6 访问，我可以将它们加入白名单。
