### ISSUE TITLE
whatsapp的網站不能登錄, whatsapp的圖片視頻不能用

### ISSUE THREAD

**Issue by WhiteSoulss** [gfwlist/gfwlist#649]

**Comment by Tsahao** [comment]
今天貌似恢复了

**Comment by WhiteSoulss** [comment]
還是不能

**Comment by 10467106** [comment]
根据whatsapp的网页介绍，建议增加 *.whatsapp.com *.whatsapp.net进gfwlist。我在PC端更新pac的时候手动加了这两条，测试ok了。

**Comment by h0ward** [comment]
adding `*.whatsapp.com` to user rules solved the problem.

**Comment by cicku** [comment]
@h0ward I can't confirm that.

**Comment by cicku** [comment]
Duplicate of #894
