### ISSUE TITLE
有好多网站PING不通但都关站了

### ISSUE THREAD

**Issue by learningis1st** [gfwlist/gfwlist#65]
list的更新是怎样实现的？？人力？？

**Comment by learningis1st** [comment]
还有，要多少省PING不通才能上名单？

**Comment by cicku** [comment]
gfwlist 不存在自动维护的可能性。

gfwlist 只有在90%的省份或地区确认后才会加入。

部分作废的 URL 会在今后被我随机移除。而且，有些即便关了，仍然在墙的过滤规则上。
