### ISSUE TITLE
Request to add "http://www.chineseinla.com", ISP: China-Telecom

### ISSUE THREAD

**Issue by justwjx** [gfwlist/gfwlist#650]
Request to add "http://www.chineseinla.com", 
ISP: China-Telecom

I am in Jiangsu Province, encounter  ERR_CONNECTION_RESET with Google Chrome.
![aaa](https://user-images.githubusercontent.com/30104710/28398514-1b670f56-6d3a-11e7-9546-b63f951768f8.jpg)

**Comment by cicku** [comment]
北京联通可以正常访问，继续观测。

**Comment by cicku** [comment]
津ICP备17000945号-1
