### ISSUE TITLE
http://www.tensorflow.org/

### ISSUE THREAD

**Issue by Vigi0303** [gfwlist/gfwlist#66]
一个google的人工智能library，纯学术的网站，呵呵

**Comment by cicku** [comment]
访问正常

**Comment by learningis1st** [comment]
正常

**Comment by Vigi0303** [comment]
为啥我访问不了。。
from ip.cn
来自：北京市 歌华有线

GeoIP: Beijing, China

**Comment by s7lx** [comment]
深圳电信表示打不开

**Comment by yfdyh000** [comment]
北京联通，连接超时。这个网站，ghs.googlehosted.com

**Comment by cypsh1** [comment]
如果你的代理设置为国内外分流，请改为全局或将TensorFlow添加到PAC
