### ISSUE TITLE
A request of adding github.io to the list (China Unicom Beijing)

### ISSUE THREAD

**Issue by ukyoi** [gfwlist/gfwlist#670]
Sorry to report here but I didn't find any official preferred way to report the blocked URL. Maybe I should open a pull request?

ISP: China Unicom (Beijing)
Location: Beijing, China
URL: `||github.io`

**Comment by EMLVIRUS** [comment]
IMHO, we don't need to add it

**Comment by cicku** [comment]
I could not see anything different, seems invalid IMO. As a corollary, please contact with your ISP.
