### ISSUE TITLE
能不能把规则中的.github.com   改成 *github.com ?

### ISSUE THREAD

**Issue by arsenalpoll** [gfwlist/gfwlist#674]
博主你好，我看规则中写的是.github.com。但是访问GitHub的时候并不是ss访问的。因为GitHub域名就是根域名。所以能不能改成*github.com？

**Comment by cicku** [comment]
实际上该规则已经失效了，之前对这个有 **HTTP** 关键字屏蔽，但是昨天我测试发现没有了，一会儿修正一下。

顺便告知一下，我不是什么`博主`……

**Comment by dreampiggy** [comment]
谁把github.com加进去的……实际上github.com目前是没有被GFW的，导致代理上了反而更慢

**Comment by cicku** [comment]
@dreampiggy GFWList 现在根本没有 github.com 的规则。
