### ISSUE TITLE
请求增加mozilla.net

### ISSUE THREAD

**Issue by myrshfrs** [gfwlist/gfwlist#680]
![mozilla](https://user-images.githubusercontent.com/6205312/29241296-48e27eee-7fa9-11e7-9479-eb4187922d9b.png)
最近nightly都不能更新了。

**Comment by EMLVIRUS** [comment]
首先 我不觉得我们需要加那个 其次 Firefox更新流量来源于 s3 的CDN而不是mozilla.net
