### ISSUE TITLE
希望增加pinterest，behance

### ISSUE THREAD

**Issue by y1024** [gfwlist/gfwlist#683]
"||pinterest.com/",
  "||pinterest.jp/",
  "||behance.net/",

**Comment by cicku** [comment]
您好，

Pinterest 在许多地区使用了对应的地区顶级域名提供服务，除 `.jp` 无法访问外，还有大量域名也无法访问，我尽可能的搜索了一番，把能找到的都添加进列表了，如果您发现还有遗漏，请随时反馈。

Behance 是 Adobe 提供的服务，目前暂未发现问题，如果您无法访问，可能与您的 ISP 有关，这种不稳定可能是持续的，也可能是间歇性的。

在未发现明显的特征前，暂不能添加至列表中。
