### ISSUE TITLE
https://raw.githubusercontent.com/programthink/zhao/ 会显示 “The content you requested has not been found”

### ISSUE THREAD

**Issue by 9yu** [gfwlist/gfwlist#684]
测试网址：
https://raw.githubusercontent.com/programthink/zhao/master/download/pdf/04-%E7%AC%AC2%E4%BB%A3%E9%AB%98%E5%AE%98.pdf
https://raw.githubusercontent.com/programthink/zhao/master/download/pdf/04-%E7%AC%AC2%E4%BB%A3%E9%AB%98%E5%AE%98.pdf
挂上代理才可以下载。

请求添加 `|https://raw.githubusercontent.com/programthink/zhao`

**Comment by cicku** [comment]
我记得新版的 Google Chrome 不支持 HTTPS 网址匹配啊？
