### ISSUE TITLE
github.io在广州地区时常上不去 请求添加

### ISSUE THREAD

**Issue by fufjvnvnf** [gfwlist/gfwlist#690]
如题 在github.io host的网站都会出现这个问题 这是我在试图访问http://cs231n.github.io 时发现的。在shadowsocks打开全局之后便可正常访问了。目前暂时知道北京貌似不会出现这个问题。希望能考虑把github.io也加进list里。Thank you for all your work!

**Comment by cicku** [comment]
无法验证，建议添加到自定义规则中解决。
