### ISSUE TITLE
请求增加ign.com

### ISSUE THREAD

**Issue by alesky** [gfwlist/gfwlist#695]
中国大陆用户访问ign主站会被强行重定向到 ign.中国 。这两个站点的内容完全不一致，所以无论点击ign主站的任何链接均会被重定向到 ign.中国 的主页，无法正常查阅。
如果想访问IGN中国版的话可以直接通过ign.中国这个地址访问。

**Comment by cicku** [comment]
很抱歉，请自行添加自定义规则。

（一位老年 IGN 读者）

**Comment by cicku** [comment]
建议您为 IGN 添加书签并设定网址为：`http://cn.ign.com/ccpref/us`

**Comment by alesky** [comment]
然而不开启代理的情况下，您上文所写的这个地址同样会被强制重定向到ign.中国。
我自己fork一个出去加上好了orz，主要是因为我会经常换不同的设备…每个都自定义的话就有点麻烦。
