### ISSUE TITLE
http://*.alternativeto.net

### ISSUE THREAD

**Issue by pluush** [gfwlist/gfwlist#697]
It is likely that http://*.alternativeto.net is blocked. https works fine. Please confirm.

If it doesn't block it straight away, try opening one of the links (ex. Adobe Photoshop) redirecting to http://alternativeto.net/*

ISP: CERNET at Harbin Institute of Technology. Forced IPv6 opens the normal http version just fine.
+ISP: CMNet Heilongjiang

Connection reset.

**Comment by cicku** [comment]
Cannot confirm within CHINANET & CHINA169.

CMNET has been neglected since years ago, China Mobile has a built in firewall to filter without respect.

**Comment by cicku** [comment]
If you can provide any links similar to `http://*.alternativeto.net`, please continue.

`alternativeto.net/software` is already in the list, by far there is no crucial issue with it.

**Comment by cicku** [comment]
Still frustrating at reproduction via your instruction, closing.
