### ISSUE TITLE
请求添加 files.minecraftforge.net

### ISSUE THREAD

**Issue by SciUnivMoring** [gfwlist/gfwlist#702]
在大陆可以解析，但是打开速度十分缓慢，有根本打不开

**Comment by cicku** [comment]
秒开。

**Comment by cicku** [comment]
此类网站没有访问故障。需要特别注意的是，部分网页的设计并未考虑异步加载等问题，因此页面打开较慢。

如果您经常访问的网站出现此类情况，请自行添加自定义规则，以方便您今后访问，但是 GFWList 无法受理您的请求。
