### ISSUE TITLE
http://www.thumbapps.org/

### ISSUE THREAD

**Issue by Thessalhydra** [gfwlist/gfwlist#704]
连接超时

www.thumbapps.org 的服务器响应时间过长。

**Comment by cicku** [comment]
可以正常访问。

**Comment by cicku** [comment]
访问超时，继续观测。

**Comment by paperbag** [comment]
这类托管在 Google 上的博客，域名的 CNAME 记录是这两个中的一个：
```
ghs.google.com
ghs.googlehosted.com
```
应该都是在 gfwlist 里的；要是 PAC 文件能够判断 DNS 的解析情况就好了:sweat_smile:，这类网站实在太多。

**Comment by cicku** [comment]
是的。
