### ISSUE TITLE
疑问-求助

### ISSUE THREAD

**Issue by kyzypm** [gfwlist/gfwlist#714]
网站地址已经加入到gwflist里面了，不知道为啥却不走代理呢，网站已经被干扰了，但是访问网站依然打不开

**Comment by cicku** [comment]
请问，是自己添加的规则，还是本列表内的规则？

**Comment by kyzypm** [comment]
申请添加到列表里面的规则 https://www.kyzyhello.com ，看了下列表中解出来有 .kyzyhello.com 的规则

**Comment by kyzypm** [comment]
话说有群吗，想加个好友^  ^
