### ISSUE TITLE
Pixiv 遭到DNS污染

### ISSUE THREAD

**Issue by sjxnwnqksnrlq** [gfwlist/gfwlist#720]
经过测试，已经在大陆遭到了DNS污染，无法直接访问（除非找到一个干净的DNS），所以索性直接加入代理列表把。

**Comment by MoeKing** [comment]
https://github.com/gfwlist/gfwlist/issues/718

**Comment by sjxnwnqksnrlq** [comment]
@MoeKing thanks。I haven't searched the former issues。sorry。

**Comment by cicku** [comment]
Duplicate of #718
