### ISSUE TITLE
请移除.m-team.cc

### ISSUE THREAD

**Issue by LannSoros** [gfwlist/gfwlist#725]
tp.m-team.cc 以及 wiki.m-team.cc 这两个网址并没有被墙。
另外，由于这是一个PT站点，奉行一人一号制度，网站会依靠IP地址来判断你是否使用多账号。
这个列表会导致使用公开SS服务的朋友因相同IP登入不同账号，从而导致封号。

**Comment by paperbag** [comment]
你提到的两个都有 TCP RST，经检查那个 RST 包是伪包。
![screenshot](https://user-images.githubusercontent.com/19257585/30642282-c8b1493c-9e3c-11e7-9575-9969d908febb.PNG)

**Comment by LannSoros** [comment]
抱歉，刚刚测试了一下，在HTTP下被RST，在HTTPS下可以直连。
同样我测试了一下，在SwitchyOmega中规则可以被正确识别，在HTTPS下正确直连，但在OWRT的路由中，拉取下来的规则会被简化为一条.m-team.cc。
对于其他网站可能这没什么，但比较严重的问题是m-team这个网站会因为相同IP登入而BAN人，甚至连坐。
考虑到OWRT类路由的保有量，使用公开SS服务的用户很难保证不会躺着中枪。
因此个人依旧认为，提升的部分体验（无需手动改为HTTPS连接）与造成的隐忧（封号甚至连坐）相比，移除相关条目可能是更好的选择。

**Comment by paperbag** [comment]
> 但在OWRT的路由中，拉取下来的规则会被简化为一条.m-team.cc。

我去看了一下，规则里是这么写的，木有被简化。
```
!--------------------MM-------------------------
.m-team.cc
!--m-team.cc/forum
[...]
```

…所以改成这样会更好？@cicku 
```
|http://m-team.cc
|http://tp.m-team.cc
|http://wiki.m-team.cc
```

**Comment by LannSoros** [comment]
目前使用的插件是openwrt-ssr，相关的提取脚本应该在这里，但具体哪里出错我也不太清楚：

https://github.com/ywb94/openwrt-ssr/blob/master/files/shadowsocksr.gfw

![image](https://user-images.githubusercontent.com/7830924/30644187-2b5e751c-9e44-11e7-82e9-477f5b9a1ad9.png)

执行更新之后，相关条目会被简化：

![image](https://user-images.githubusercontent.com/7830924/30644206-40d54146-9e44-11e7-8cf2-66a724c68829.png)

**Comment by cicku** [comment]
Duplicate of #564
