### ISSUE TITLE
请求添加 hacg.me

### ISSUE THREAD

**Issue by XinSSS** [gfwlist/gfwlist#730]
如果维护者访问hacg.me也不行的话, 希望能够加入到gfwlist中

**Comment by paperbag** [comment]
可以访问。

**Comment by XinSSS** [comment]
@paperbag 那可能是我这边的网络问题吧, 不翻墙上不去

**Comment by paperbag** [comment]
唔，我错了。之前在移动的网络下没有发现问题。

刚才在学校机房试了一下 `hacg.me` 没有问题，`www.hacg.me` 有 TCP RST。

**Comment by XinSSS** [comment]
是的, www 无法访问

**Comment by XinSSS** [comment]
同网站的另外一个URL
http://llss.me/wp/
我这里还是不行

**Comment by paperbag** [comment]
嗯，最短关键词为`.llss.me/`。
居然有斜杠，这样就提供了更多的玩法XD，比如这样 http://www.llss.me./wp/。
