### ISSUE TITLE
外星人网站不支持国内IP

### ISSUE THREAD

**Issue by wang93wei** [gfwlist/gfwlist#732]
然后也不在gfwlist里
![wx20170926-094002](https://user-images.githubusercontent.com/6371053/30838563-cac4eb46-a29e-11e7-8c14-97c7c1c93722.png)

https://na.alienwarearena.com/

**Comment by cicku** [comment]
应该是服务器开小差了。

**Comment by wang93wei** [comment]
怎么可能？？？人家是把国内IP屏蔽了，翻出去就立马能访问了。不信你试试。

**Comment by cicku** [comment]
直连可以打开，打不开是你自己ISP的事情。
