### ISSUE TITLE
whatsapp text message service has been block 

### ISSUE THREAD

**Issue by s7lx** [gfwlist/gfwlist#733]
China telecom \ China Unicom
All of whatsapp ip list is https://github.com/ukanth/afwall/wiki/HOWTO-blocking-WhatsApp

suggestion:
add *.whatsapp.net 
add *.whatsapp.com

**Comment by cicku** [comment]
whatsapp.net is already in the list.

**Comment by cicku** [comment]
Duplicate of #894
