### ISSUE TITLE
captive.apple.com

### ISSUE THREAD

**Issue by metalbreeze** [gfwlist/gfwlist#744]
国内wifi认证的时候，如果处于翻墙ss状态，此网址不会打开。如果把翻墙ss关闭，此网址能顺利打开，加入无线网。请把此网址加入不翻墙名单。大概原因，国内有此网址服务器，如果翻墙到国外，此网址反而不能正常工作。

**Comment by cicku** [comment]
👴……和 GFWList 没关系吧？GFWList 从来就没包含过 Apple 的域名。
