### ISSUE TITLE
3 Microsoft domains got blocked(?)

### ISSUE THREAD

**Issue by Elepover** [gfwlist/gfwlist#752]
Testing environment: China Mobile (SC / Cellular Data / CMNET)

Blocked domains:
msdn.microsoft.com
technet.microsoft.com
social.technet.microsoft.com

Error code: ERR_ CONNECTION_CLOSED

Other carriers:
China Telecom: Pass.
China Unicom: Pass.

**Comment by cicku** [comment]
ERR_TOO_MANY_REDIRECTS

**Comment by Elepover** [comment]
Adding 2 more domains:
docs.microsoft.com
social.msdn.microsoft.com

btw, error code has changed:
ERR_CONNECTION_REFUSED

Looks like DNS poisoning.

**Comment by cicku** [comment]
GFW doesn't handle any issues regarding CMNET, because China Mobile has a builtin firewall which sucks a lot. Please file a complaint to its local branch in your city.
