### ISSUE TITLE
http://software.schmorp.de/ and http://pod.tst.eu/ is blocked

### ISSUE THREAD

**Issue by thunder1** [gfwlist/gfwlist#755]
http://software.schmorp.de/ and http://pod.tst.eu/ is blocked

**Comment by cicku** [comment]
`http://pod.tst.eu/` seems down.

`http://software.schmorp.de/` is located in Hetzner DC, I saw an issue at #757, but cannot confirm.

**Comment by cicku** [comment]
I can access http://software.schmorp.de/ without any problem, requesting your feedback now.
