### ISSUE TITLE
关于steam社群的域名steamcommunity.com

### ISSUE THREAD

**Issue by SoukinOKATU** [gfwlist/gfwlist#769]
steamcommunity.com（steam社群的域名）在黑名单，但是他并未出现什么问题（偶尔有连接困难，但并不是完全无法连接），如果使用shadowshocks的GFWLIST模式的话，这个地址会走代理，结果就是直接导致新注册的steam帐号默认的支付地区是代理所在的国家，然后必须关了代理或者设置白名单才可以设置回中国区，因为steam有严格的跨区购买的惩罚（没有相应的证件和地址跨区购买是违规的），这样会对很多steam新用户造成麻烦。

**Comment by cicku** [comment]
这跟 GFWList 根本没任何关系。
