### ISSUE TITLE
校验和不匹配

### ISSUE THREAD

**Issue by zjhxmjl** [gfwlist/gfwlist#771]
请问下有哪位朋友遇到过此问题：
![qq 20171016144015](https://user-images.githubusercontent.com/4043922/31598404-1062b4f8-b280-11e7-8cbc-b4d46eaa471f.png)

**Comment by paperbag** [comment]
https://github.com/gfwlist/gfwlist/issues/770

**Comment by zjhxmjl** [comment]
win 7上更新出现此问题，linux上未提示

**Comment by cicku** [comment]
不应该啊……我每次都是自动更新时间戳的，怎么会呢……我又更新了一次，麻烦再看一下。

**Comment by zjhxmjl** [comment]
sorry,好像还是不行！

**Comment by RedTea** [comment]
@cicku 我刚刚更新了，哈希值还是不对。要不公布一下Checksum生成的算法？

**Comment by nemozqqz** [comment]
Firefox下的foxyproxy也遇到同样的问题
![default](https://user-images.githubusercontent.com/7521329/31644927-9c54ab28-b32b-11e7-96b4-48f7e773a289.png)
gfwlist.txt是一个base64之后的文档，解开后的开头是
```
[AutoProxy 0.2.9]
! Checksum: V+a70sp49CSwQDxywFG81g
! Expires: 6h
! Title: GFWList4LL
! GFWList with EVERYTHING included
! Last Modified: Mon, 16 Oct 2017 04:52:33 -0400
```
所以可能是这个checksum不对，[checksum的算法](https://github.com/cicku/autoproxy-gfwlist/blob/master/validateChecksum.pl)是把list去除 `Checksum: XXX`这行和所有空行后算一个md5然后base64。 奇怪的是我用这个validateChecksum.pl算出来的值是一样的，都是`V+a70sp49CSwQDxywFG81g`，所以很奇怪

**Comment by Clockwork-LeyLine** [comment]
同样是这个错误，从13号开始就一直显示“校验和不匹配”了，到现在autoproxy都没更新成功过规则。
但是用chrome的SwitchyOmega是可以正常更新的，不出现“校验和不匹配”的提示框。

**Comment by cicku** [comment]
Duplicate of #778
