### ISSUE TITLE
校验和不匹配的原因

### ISSUE THREAD

**Issue by xyzrrr** [gfwlist/gfwlist#778]
debase64后gfwlist.txt的4138行：
!鈫撯啌69.16.175.42

那三个中文应该是不知道什么原因出现的乱码
debase64的时候autoproxy用的是atob，atob大家都知道，解不了中文
这个文件里就不能出现中文

对于维护者提出批评，这么多天这么个低级错误都发现不了，对于别人提出的Issues也不够重视，粗心+怠惰！

**Comment by paperbag** [comment]
其实那个是向下的箭头😄：
```
!↓↓69.16.175.42
```

ref: https://github.com/meiyopeng/gfwlist/commit/42eb41189073cbaa2f9d7c3879908e2ee2752811#diff-4cdf108243072169882882931a2ded71R3996

**Comment by cicku** [comment]
首先，我的确没有一个 commit 一个 commit 地看，因为我确实很忙。怠惰可以，但说我粗心我并不接受。

其次，这个也谈不上低级错误，因为我不懂 Javascript 的各种坑。

还有，我所有打出来的中文字符，全部来在 iOS 输入法和 Google 云输入法，计算机上打不出来中文。下箭头并不是中文字符。

最后，非常感谢您的汇报，这个问题我会尽快处理。

**Comment by liCN** [comment]
我还以为是ff更新后导致的呢
这边也几天了，但是chrome又没有问题？？

**Comment by zjhxmjl** [comment]
thx @cicku ,说批评严重了，毕竟他也是无偿维护！友情提醒更合适！
