### ISSUE TITLE
如何检查某个url是否在gfwlist中

### ISSUE THREAD

**Issue by PMExtra** [gfwlist/gfwlist#784]
如题，是否有可读的版本，或者有简易的测试工具可以检查输入的url是否命中gfwlist规则

**Comment by cicku** [comment]
只要有 Linux，都好办… 😨 

# let :trollface: = 待测试URL:
## require coreutils, wget;
```base64 -d <(wget -qO- -nv https://pagure.io/gfwlist/raw/master/f/gfwlist.txt) | grep ```:trollface:

## require python, wget;
```echo `wget -qO- -nv https://pagure.io/gfwlist/raw/master/f/gfwlist.txt` | python -m base64 -d | grep ```:trollface:

## require openssl, wget;
`wget -qO- -nv https://pagure.io/gfwlist/raw/master/f/gfwlist.txt | openssl enc -d -base64 | grep `:trollface:

## require perl, wget;
```echo `wget -qO- -nv https://pagure.io/gfwlist/raw/master/f/gfwlist.txt` | perl -e 'use MIME::Base64; print decode_base64(<STDIN>);' | grep ```:trollface:

---

如果你更熟悉cURL，一样…
# let :trollface: = 待测试URL:
## require coreutils, curl;
```base64 -d <(curl -s https://pagure.io/gfwlist/raw/master/f/gfwlist.txt) | grep ```:trollface:

## require python, curl;
```echo `curl -s https://pagure.io/gfwlist/raw/master/f/gfwlist.txt` | python -m base64 -d | grep ```:trollface:

## require openssl, curl;
```curl -s https://pagure.io/gfwlist/raw/master/f/gfwlist.txt | openssl enc -d -base64 | grep ```:trollface:

## require perl, curl;
```echo `curl -s https://pagure.io/gfwlist/raw/master/f/gfwlist.txt` | perl -e 'use MIME::Base64; print decode_base64(<STDIN>);' | grep ```:trollface:

**Comment by PMExtra** [comment]
善
