### ISSUE TITLE
keyword: ai.binwang.me/couplet

### ISSUE THREAD

**Issue by paperbag** [gfwlist/gfwlist#785]
`ai.binwang.me/couplet`

另外，`ai.binwang.me`似乎在国内被 DNSPOD 停止解析了，但海外还是可以正常解析的。

**Comment by wb14123** [comment]
DNSPOD 可能是我自己设置的问题。另外国内的话使用 HTTPS 可以访问。

**Comment by paperbag** [comment]
> 另外国内的话使用 HTTPS 可以访问。

倒是可以添加一条规则把 https://ai.binwang.me 排除出去，原关键词仍然保留。@cicku
```
ai.binwang.me/couplet
@@||https://ai.binwang.me
```
