### ISSUE TITLE
请求添加网址

### ISSUE THREAD

**Issue by d1sm** [gfwlist/gfwlist#797]
http://tcpspeed.com
http://www.tcpspeed.com
谢谢!

**Comment by cicku** [comment]
域名自动跳转，没发现问题

**Comment by d1sm** [comment]
只是临时应急用了国内服务器来跳转,直接解析到国外就访问不了

**Comment by cicku** [comment]
我没看出是临时，我只看到了`本站域名修改为   WWW.TCPSPEED.CO  请通过新域名访问`……虽然原域名被关键字照顾了。

不过我看了一圈国内的解析结果，基本都对上了腾讯云，除了两个仍然解析到`46.82.174.69`，可能刷新的时间有点长吧……

**Comment by cicku** [comment]
See also #815
