### ISSUE TITLE
请求添加网址

### ISSUE THREAD

**Issue by LYCX2015** [gfwlist/gfwlist#801]
可能会有条别没有被墙，但打开速度也极其慢。
http://osair.cn
https://freecat.pw
https://ss.levyhsu.com
https://www.sproxy.info
https://www.javbus.in
https://www.javbus.xyz
https://www.feiyun.us
https://www.tizige.net
https://feisu.in
https://www.52ssr.info
https://www.ovvvo.me
https://betaclouds.net
http://www.yooooooo.xyz
http://v.getworld.in
http://jiasuqi.tk
https://ss.wuaomiao.win
http://sspod.xyz
https://www.haoss.cf
http://www.lh123.me
https://ss.zfuyun.top
https://startss.today
http://www.sspod.xyz
http://free.hwss.pw
http://www.wanzhihu.com
https://ss.fastssr.net
https://www.acss.red
https://ss.levyhsu.com
http://www.shadower.cc
http://osair.cn
https://www.ym555.com
https://www.cmsky.com
https://www.91yun.org
https://greasyfork.org
http://www.btpipi.com
http://www.btsoula.com
http://www.renrenbt.org
http://ww1.btavmo.com
http://www.libredmm.com
http://www.btany.com
http://www.btdaquan.net
http://www.magwu.com
http://www.clpig.com
http://m.baqicun.cc
http://www.cilisou.cn
https://puleng.pw
https://www.haoss.cf
https://www.shadowsky.bid
https://forum.xda-developers.com
https://basketbuild.com
https://bwh1.net
https://xtunnel.net
https://sspaces.org
http://ss.sshome.win
http://ss.supra.tw
http://www.snode.club
https://www.68zz.gq
http://www.hui-ss.cc
http://www.hiahiahia.org
https://danran.win
http://www.gate.freedoms.land
https://s2.ysee.me
http://www.yscat.ml
http://www.ezcar.io
http://47.88.13.179
http://manage.qilu.party
http://www.ssacce.com
https://www.sharess.xyz
https://www.feiyun.us
https://fyss1.tk
https://icafe.tech
https://cross.cf
https://www.freereaper.club
https://prss.tech
https://www.voncop.tk
http://ss.acghx.net
http://snode.club
https://console.sockspeed.com
https://egg.tn
https://cb.digac.top
https://www.6yhy.com
https://qspssf.ga
https://ss.dou-bi.pw
http://fyss1.tk
https://teddysun.com
https://okgo.xyz

**Comment by paperbag** [comment]
好多都是可以访问的…

> http://osair.cn 关键词`osair.cn`重置
> https://freecat.pw 解析到局域网了
> https://ss.levyhsu.com 有
> https://www.sproxy.info 有
> https://www.javbus.in 有
> https://www.javbus.xyz 没有
> https://www.feiyun.us 没有
> https://www.tizige.net 没有
> https://feisu.in 没有
> https://www.52ssr.info 没有
> https://www.ovvvo.me 没有
> https://betaclouds.net 没有
> http://www.yooooooo.xyz 没有
> http://v.getworld.in 没有
> http://jiasuqi.tk 网站本身无法访问
> https://ss.wuaomiao.win 没有
> http://sspod.xyz 没有
> https://www.haoss.cf 有
> http://www.lh123.me
> https://ss.zfuyun.top
> https://startss.today
> http://www.sspod.xyz
> http://free.hwss.pw
> http://www.wanzhihu.com
> https://ss.fastssr.net
> https://www.acss.red
> https://ss.levyhsu.com
> http://www.shadower.cc
> http://osair.cn
> https://www.ym555.com
> https://www.cmsky.com
> https://www.91yun.org
> https://greasyfork.org
> http://www.btpipi.com
> http://www.btsoula.com
> http://www.renrenbt.org
> http://ww1.btavmo.com
> http://www.libredmm.com
> http://www.btany.com
> http://www.btdaquan.net
> http://www.magwu.com
> http://www.clpig.com
> http://m.baqicun.cc
> http://www.cilisou.cn
> https://puleng.pw
> https://www.haoss.cf
> https://www.shadowsky.bid
> https://forum.xda-developers.com
> https://basketbuild.com
> https://bwh1.net
> https://xtunnel.net
> https://sspaces.org
> http://ss.sshome.win
> http://ss.supra.tw
> http://www.snode.club
> https://www.68zz.gq
> http://www.hui-ss.cc
> http://www.hiahiahia.org
> https://danran.win
> http://www.gate.freedoms.land
> https://s2.ysee.me
> http://www.yscat.ml
> http://www.ezcar.io
> http://47.88.13.179
> http://manage.qilu.party
> http://www.ssacce.com
> https://www.sharess.xyz
> https://www.feiyun.us
> https://fyss1.tk
> https://icafe.tech
> https://cross.cf
> https://www.freereaper.club
> https://prss.tech
> https://www.voncop.tk
> http://ss.acghx.net
> http://snode.club
> https://console.sockspeed.com
> https://egg.tn
> https://cb.digac.top
> https://www.6yhy.com
> https://qspssf.ga
> https://ss.dou-bi.pw
> http://fyss1.tk
> https://teddysun.com
> https://okgo.xyz

**Comment by LYCX2015** [comment]
额，有和没有是啥意思……还有http://osair.cn/挂全局是可以访问的……
