### ISSUE TITLE
请求删除部分@@URL

### ISSUE THREAD

**Issue by murongxu** [gfwlist/gfwlist#803]
您是否可以考虑删除@@jd.com和@@taobao.com呢？
因为公司网络有屏蔽，每次更新list之后都会把上面的例外重新加载进来，
而我的user-rule是被添加到最后，总是会被之前的@@URL先解析。
您是否可以删除@@的URL呢？
谢谢

**Comment by cicku** [comment]
理论上所有 GFWList 实现都是 user rule 优先级最高，不知道您用的是什么实现。

**Comment by murongxu** [comment]
我是现在user-rule.txt加入【||jd.com】和【||taobao.com】，然后pac.txt文件中的最后就自动多了我加的这两行，浏览器键入jd之后显示无法连接，然后删了pac.txt中原先的【@@jd.com】就可以连上了。

**Comment by cicku** [comment]
这个是实现存在问题。

GFWList 列表中的规则，如果与用户自定义规则重复，那么在处理 GFWList 时应该做一个重复对比，就像您所说的 `@@||jd.com`，如果它存在于 GFWList 中，实现需要先读取用户自定义规则，如果发现 `||jd.com`，那么在生成 PAC 时，`@@||jd.com` 就应被忽略了。而不是单纯的加入到 PAC 最后一行，这种偷懒的做法，是没有意义的……

目前 Google Chrome + SwitchyOmega 插件方案就没有问题，如果您只是单纯浏览网页，建议您试试这个方案。

不过由于上述两个站点均启用了 HTTPS，因此这两条规则我还是决定去掉。

**Comment by murongxu** [comment]
因为开发需要多个浏览器，所以没有在每个浏览器上逐一安装插件。
只是安装了ss客户端，每次都是在ss的编辑用户规则中填写，不清楚是不是客户端本身user-rule解析会有问题。

在此感谢您的回答。
