### ISSUE TITLE
请添加 earthexplorer.usgs.gov

### ISSUE THREAD

**Issue by Zhang-Siyang** [gfwlist/gfwlist#829]
测试数据 ： https://www.17ce.com/site/http/201712_86bdba8a79ed3001fd87eda279598e2e.html

usgs.gov 也不怎么样 ： https://www.17ce.com/site/http/201712_586def71b20da229bd29ab15ed7c1961.html

**Comment by paperbag** [comment]
> usgs.gov 也不怎么样 

什么叫不怎么样，看了下基本上状态码都是 200 呀。

**Comment by Zhang-Siyang** [comment]
@paperbag 连通性太差呀

**Comment by cicku** [comment]
3秒就能打开页面……北京电信

**Comment by Zhang-Siyang** [comment]
@cicku 应该是地区性因素吧，如果这个列表比较谨慎还是不要添加了；但这个域名在 Google 结果里也有很多人称无法访问需要翻墙

**Comment by cicku** [comment]
GFWList 肯定是谨慎的，这毫无疑问。

但是说无法访问是根本不可能的，USGS 页面包含的 Google 元素（图层、注册页面验证码）都在列表覆盖范围内，其他元素并没有被墙。
