### ISSUE TITLE
*.steamcommunity.com 疑似被墙

### ISSUE THREAD

**Issue by nikzhang2016** [gfwlist/gfwlist#837]
网络环境：上海电信
测试：ping steamcommunity.com得到的ip为69.171.247.71、31.13.66.1等，经whoisip查询属于Facebook。
打开Steam客户端，“社区”已无法加载，显示108错误。
解决：在桌面版ShadowsocksRR的用户规则里加入
`||steamcommunity.com`
后，“社区”迅速加载完成，排除Steam自身问题。
结论：steamcommunity.com可能已被墙，建议加入gfwlist

**Comment by nikzhang2016** [comment]
补充：ping得到的ip每次都会变，目前测试过的两个都属于Facebook，有消息称还有被定向到Twitter的情况

**Comment by houbaron** [comment]
![](https://i.imgur.com/uRAhhgZ.jpg)

steam 怕是要凉。

**Comment by lzghzr** [comment]
@cicku 单纯把steamcommunity.com加入列表会导致steamcommunity.com登录失效
因为steam有根据ip判断账号风险的机制，且steamcommunity.com与store.steampowered.com两域名cookie共享，当有域名切换动作，比如加入购物车，加入愿望单，因ip变动就会导致登录失效
此现象只会发生在浏览器，因为steam客户端并不需要cookie验证用户身份

**Comment by cicku** [comment]
@lzghzr `steamcommunity.com` 是必须加的，这辈子都必须加的，不加社区根本打不开，就是加了，才能维持得了能访问这个样子。
