### ISSUE TITLE
gravatar

### ISSUE THREAD

**Issue by nmgwddj** [gfwlist/gfwlist#84]
http://s.gravatar.com/

这个域名一直无法访问，在国内。能否更新一下？

**Comment by cicku** [comment]
提交 Issue 之前请检查是否更新 gfwlist 为最新版本。gravatar.com 是全站被收录进 gfwlist 的，理论上您不应该出现问题。

但是 gravatar 的封锁我已经很久没有跟踪，所以我可能会更新一下规则。

**Comment by nmgwddj** [comment]
是的，已经更新了。

<img width="490" alt="2015-12-13 9 43 32" src="https://cloud.githubusercontent.com/assets/13995319/11767256/9815a64a-a1e2-11e5-9042-48ab1b6bf6ce.png">

全局模式是可以打开的。
