### ISSUE TITLE
www.jd.com匹配不正确

### ISSUE THREAD

**Issue by longhr** [gfwlist/gfwlist#840]
您好,我使用SwitchyOmega内部调用gfwlist表，规则列表最后更新时间：2017年12月20日 上午9:49:54。
我在登陆www.jd.com 的时候会自动跳转到global.jd.com

但是输入 https://www.jd.com/index.html 跳转是正确的。

由于分析能力有限，怀疑jd CDN与gfwlist表匹配有问题，建议详细测试一下。但是在1个月前并没有发现类似问题，建议从最近更新的规则下手。

谢谢

**Comment by cicku** [comment]
我无法重现您的问题……

但是一旦您访问了国际版京东，必须清空浏览器缓存才能默认跳转回国内版。清除 DNS 缓存都没有用的。
