### ISSUE TITLE
Please add https://www.codingforentrepreneurs.com/

### ISSUE THREAD

**Issue by litt1eseven** [gfwlist/gfwlist#846]
url：https://www.codingforentrepreneurs.com/       thanks.

**Comment by LavaFalls233** [comment]
并未被墙。
用的cdn amazon aws在国内访问缓慢。
你多等会试试

**Comment by litt1eseven** [comment]
是的，但是访问速度特别缓慢。用全局的话就可以解决。未被墙不可以添加吗？

**Comment by cicku** [comment]
访问正常的网站不可以添加，请通过自定义规则解决。
