### ISSUE TITLE
please add http://www.zxcs8.com/

### ISSUE THREAD

**Issue by jzmswe** [gfwlist/gfwlist#848]
http://www.zxcs8.com/

thanks
还有下面这个，GoProxy PAC看很卡，全局看就很流畅，建议加入gfwlist：
https://hk.video.appledaily.com/actionnews/index/

这个网站也是，可以上，但比较卡，全局流畅，建议加入gfwlist：
http://hk.apple.nextmedia.com/

**Comment by LavaFalls233** [comment]
黑龙江电信一切正常。

网站卡顿一般情况下和墙没关系，而是因为线路问题。

**Comment by cicku** [comment]
`http://www.zxcs8.com/` 访问正常。

`https://hk.video.appledaily.com/actionnews/index/` 在列表中。

`http://hk.apple.nextmedia.com/` 也在列表中。
