### ISSUE TITLE
维基百科日文版可能被墙，方式同Steam社区相似

### ISSUE THREAD

**Issue by nikzhang2016** [gfwlist/gfwlist#849]
症状：在不打开翻墙工具的前提下，日文维基百科 `https://ja.wikipedia.org/` 无法加载，开启翻墙工具后正常加载。网络环境为上海电信。
测试：执行 `ping ja.wikipedia.org` 返回的结果为 69.171.233.37，丢包100%，查询 whoisip 发现该ip属于Facebook，而 `ping zh.wikipedia.org` 返回的ip同样属于Facebook。
结论：`ja.wikipedia.org` 可能已经被墙，封锁方式同中文维基，还有此前的Steam社区都类似。建议针对该情况更新gfwlist。

**Comment by nikzhang2016** [comment]
当然，维基作为一个在当局眼中”不听话“的信息平台，被全面封锁应该只是时间问题，我在中文维基被墙以前就一直把 `*.wikipedia.org` 放在代理列表里，以防不测

**Comment by cicku** [comment]
北京电信确认，稍后测试联通。
