### ISSUE TITLE
Add telegra.ph ?

### ISSUE THREAD

**Issue by Jack-Works** [gfwlist/gfwlist#850]
Connection reset appeared these days.

**Comment by cicku** [comment]
![image](https://user-images.githubusercontent.com/686438/34485876-c12dd56e-f007-11e7-987d-a81db48cb7c7.png)

**Comment by ThomasHawaiiKing** [comment]
I think telegra.ph is blocked in mainland China. According to the picture below, it only can be connected in Hong Kong.
![屏幕截图(29)](https://user-images.githubusercontent.com/14331965/55286210-2d995200-53cb-11e9-8800-bb6b3b781198.png)
test via https://www.17ce.com/

**Comment by yogaskung** [comment]
https://zh.greatfire.org/telegra.ph
Not blocked until 2019.Add this

**Comment by cicku** [comment]
Duplicate of #1847
