### ISSUE TITLE
https://archive.is 似未被匹配到

### ISSUE THREAD

**Issue by Artoria2e5** [gfwlist/gfwlist#855]
目前这家的规则有这几行：
```
.archive.is
|http://archive.is
.archive.fo
```
但实际上 https 的 archive.is 也不好使（timeout；上海电信 4G）；archive.fo 直接 NXDOMAIN。话说域名之前那个点有什么用吗？archive.is/fo 家基本不用子域名的。

**Comment by cicku** [comment]
我隐约记得最早这个加入到列表的时候该站不支持 HTTPS，现在可能支持了但是被X了。

不管如何，我会稍后更新。
