### ISSUE TITLE
如何使用这个项目？

### ISSUE THREAD

**Issue by 123ysys** [gfwlist/gfwlist#858]
请问该如何查看？谢谢。

**Comment by michaeldyl520** [comment]
base64解密

**Comment by 123ysys** [comment]
不懂，求详解。谢谢。

**Comment by Dcryfm** [comment]
@123ysys 
你打开这个连接 [gfwlist.txt](https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt) 看到的是用 `base64` 加密算法加密过后的信息，想看原文用 `base64` 解码工具解码即可，百度、谷歌搜一搜就有解码工具了。

**Comment by 123ysys** [comment]
@Dcryfm 谢谢。

**Comment by gqqnbig** [comment]
请问为什么需要加密呢？
