### ISSUE TITLE
Steam商店域名 store.steampowered.com 开始受到干扰

### ISSUE THREAD

**Issue by nikzhang2016** [gfwlist/gfwlist#861]
有人反映：
http://store.steampowered.com/app/333600/NEKOPARA_Vol_1/?snr=1_7_7_230_150_1
直连下打开网页端会提示连接被重置（客户端是101），然后整个商店都会被屏蔽几分钟时间。
目前0～3和ova还没有这个情况。
经测试该情况属实，网络环境上海电信。

**尽管目前steam商店和steam主站都还没有遭到和社区一样的封锁，但频繁干扰已经说明封锁是未来的趋势。**
将 `store.steampowered.com` 甚至 `*.steampowered.com` 加入GFWLIST，指日可待。

**Comment by snh487sensesakira** [comment]
看了下，应该是直接访问任意以 http://store.steampowered.com/app/333600 开头的链接都会触发connection reset并持续5分钟，比如 http://store.steampowered.com/app/333600/ftuyfituyfdituydit 这种键盘上随便敲出来的，实际并不存在的
网络环境为广西电信

**Comment by cicku** [comment]
`.store.steampowered.com/app/333600`
