### ISSUE TITLE
TextNow Domain - DNS Spoofing

### ISSUE THREAD

**Issue by BROBIRD** [gfwlist/gfwlist#871]
`*.textnow.me`

For example, `api.textnow.me`

**Comment by BROBIRD** [comment]
What's going on? @cicku

**Comment by Rysle** [comment]
+1

**Comment by huiyifyj** [comment]
The link just redirect to .com domain currently.
And it can Load the page normally.

**Comment by BROBIRD** [comment]
@huiyifyj No, you should test it with TextNow Android APP, not via browsers.
