### ISSUE TITLE
请去掉这条规则："@@|http://translate.google.com",

### ISSUE THREAD

**Issue by wccy168** [gfwlist/gfwlist#879]
选择PAC下不能翻译，只有在全局模式下正常翻译，S3扩展不能正常翻译，有些网站的翻译工具条也出不来。排查了下找到"@@||translate.googleapis.com",
去掉这条规则PAC下就能翻译了。本地我还能改，但是我用在线的话就不方便了，请请去掉这条规则。

**Comment by cicku** [comment]
GFWList 没这条规则。

**Comment by wccy168** [comment]
我是在ssr,ss更新的啊，在差不多最后面"@@|系列啊，有这一条。

**Comment by cicku** [comment]
`translate.googleapis.com`?

[访问正常啊](http://ping.chinaz.com/translate.googleapis.com)，敢问ISP？

**Comment by wccy168** [comment]
我这边是江苏电信的。
问题是火狐S3扩展PAC下不能正常在当前网页翻译（划词翻译可以，在新标签页翻译也可以），有些网站的google翻译工具条也出不来，只有在全局模式下才正常。但我把"@@||translate.googleapis.com",去掉就能翻译了，正常了。
关键我还有用到在线的规则，那没法改，这样很不方便，我喜欢在当前网页翻译，每次翻译先要切换到全局，希望能去掉。

**Comment by Neil-Steven** [comment]
我也是江苏无锡电信，今天用Android Studio更新发现连不上，然后ping了一下国内的几个Google服务器都不通，挂SS上Google也是时快时慢，甚至国内的Google翻译和开发者网站都上不了（地图倒是可以上），一开始还以为是ISP的DNS出问题了，后来发现直接ping dl.google.com等网站的ip地址都不通。
我猜测是因为手机整天挂着Google服务，所以自己的ip被GFW盯上了，最后重启下路由器，重新获得个新ip地址就好了……

**Comment by cicku** [comment]
北京电信也是这样……

**Comment by BoyuanJiang** [comment]
遇到同样的问题

**Comment by Auva-Z** [comment]
江苏联通也无法正常访问Google翻译页面，无法使用网页Google翻译扩展，最新的pac文件里有这条：@@||translate.googleapis.com，希望能把这条去掉，并添加translate.google.com, 谢谢！

**Comment by jan-bar** [comment]
最近`@@||translate.googleapis.com`貌似访问不了，我这在线翻译都有问题了。

**Comment by jan-bar** [comment]
https://github.com/FelisCatus/SwitchyOmega/issues/264#issuecomment-1300395584

最近发现用不了这个翻译是Chrome浏览器本身的问题，很多人的解决方案都是改为全局代理，但是我很不喜欢（浪费资源，以及转发正常流量）。所以我研究了上面的方案，同时搜到了N年前别人就遇到的这个问题。

**Comment by cicku** [comment]
其实N年前和近期的屏蔽没有多大关系。

Duplicate of https://github.com/gfwlist/gfwlist/issues/2293

**Comment by feko2018** [comment]
直接在 检查更新 中更新新pac文件即可

**Comment by ziluepan** [comment]
> 
我怎么没想到呢，在忙上忙下各种修改检测的时候，有你这种人间清醒。。
