### ISSUE TITLE
blogspot.tw

### ISSUE THREAD

**Issue by jaccsr** [gfwlist/gfwlist#882]
blogspot.tw
tianjin unicom
connection timeout

**Comment by huiyifyj** [comment]
According to whois information, this domain belong to Google. And it redirect to google website.
And blogspot.com also belong to Google, even redirect to blogger.com.
So, those domains is used in blogger.
@cicku 
You also should add `blogspot.com` in the gfwlist.

**Comment by jaccsr** [comment]
yeah, it is not fake website, just another domain name of blogspot.
