### ISSUE TITLE
tellapart.com被Switchyomega提示未加载!

### ISSUE THREAD

**Issue by Steve789** [gfwlist/gfwlist#889]
而我直接用代理访问tellapart.com却被定向到 https://business.twitter.com/ 成功访问。这是什么问题？

**Comment by cicku** [comment]
请粘贴当初提示“未加载”的页面的URL。

重定向说明 www 子域访问正常。

**Comment by Steve789** [comment]
补充说明我的使用条件是chrome+switchyOmega+GFWlist自动代理，tellapart.com被Switchyomega提示未加载时访问就是https://twitter.com/，这种情形出现了大概一个多月，之前无此提示。

**Comment by Steve789** [comment]
@cicku 原因该域名被屏蔽吗？

**Comment by cicku** [comment]
貌似解析故障，可以加进来，因为都是Twitter的。

**Comment by cicku** [comment]
不过，貌似这个域名挂了代理也是打不开的。

**Comment by Steve789** [comment]
@cicku 谢谢你的解释和回复。
