### ISSUE TITLE
去除 hiwifi.com添加github全局

### ISSUE THREAD

**Issue by mexifan** [gfwlist/gfwlist#890]
去除 hiwifi.com添加github全局

**Comment by cicku** [comment]
hiwifi 存在关键字屏蔽，GFWList 为防止错误，已经手动加了白名单规则。如果转换脚本智商不足，则转换后的结果可能是 hiwifi 仍然被代理。

如果路由器等使用转换脚本配置规则，则无法完整使用 GFWList 功能，请向相关项目作者建议在转换时遇到同一域名既属于黑名单又属于白名单时，丢弃或者让用户选择。
