### ISSUE TITLE
Mastodon websites

### ISSUE THREAD

**Issue by ghost** [gfwlist/gfwlist#895]
DNS cache poisoning:
* [x] mastodon.host
* [x] www.freechinaweibo.com

~To be continued? May more Mastodon websites will be blocked.~

**Comment by paperbag** [comment]
cmx.im

站长的权威 DNS 服务器似乎在国内，手机上我没办法确认，导致国外的解析也被污染了。 （原先解析到 80.208.224.5）。

**Comment by paperbag** [comment]
* [ ] g0v.social

**Comment by paperbag** [comment]
* [ ] counter.social `Geo-blocking`

**Comment by paperbag** [comment]
* [ ] mao.daizhige.org

**Comment by paperbag** [comment]
* [ ] mastodon.cloud

**Comment by paperbag** [comment]
* [ ] bangdream.space

**Comment by cicku** [comment]
> * [x]  joinmastodon.org
> * [x]  g0v.social

**Comment by cicku** [comment]
> * [x]  mastodon.social

Invalid:
> *  t.con.sh
> *  toot.moe
> *  tootcn.com

**Comment by cicku** [comment]
> * [x] counter.social
> * [x] niu.moe

**Comment by cicku** [comment]
> * [x]  mastodon.cloud
> * [x]  bangdream.space
