### ISSUE TITLE
路由器gfwlist下 telegram和d100 radio app无法访问网络。

### ISSUE THREAD

**Issue by ntgeralt** [gfwlist/gfwlist#898]
你好，最近发现gfwlist下无法访问这两个app。需国外走代理模式才能访问，在此反馈一下。

**Comment by xmlf** [comment]
是的，我在路由器下面抓包发现telegram竟然走172段。。所以连接不上

**Comment by cicku** [comment]
172段是什么意思？

**Comment by xmlf** [comment]
我也不知道什么情况。在路由器下gfwlist，连接不上，我就用packet capture抓包，发现telegram进入连接的是172.16段，这不是内部IP吗？
但是但我开启手机端的SS，用gfwlist，就很正常。
