### ISSUE TITLE
www.wjbk.org

### ISSUE THREAD

**Issue by learningis1st** [gfwlist/gfwlist#90]
虽然上报了，但一点实用性也没有。。。这网站甚至还混点广告进去

**Comment by learningis1st** [comment]
Github上有其他实用性强的list吗？

**Comment by cicku** [comment]
没明白您的意思。

**Comment by learningis1st** [comment]
就是短小精悍的list。。。或者说没有必要。。。好吧。。。

**Comment by cicku** [comment]
有必要，当然有必要 :laughing: 

gfwlist/pragmalist

不过计划尚未出炉。
