### ISSUE TITLE
steam社区静态资源（cdn.akamai.steamstatic.com）无法显示

### ISSUE THREAD

**Issue by YogiLiu** [gfwlist/gfwlist#910]
将cdn.akamai.steamstatic.com添加到本地pac之后，静态资源显示正常，请求将cdn.akamai.steamstatic.com加入GFWList，谢谢。
![截图](https://i.loli.net/2018/02/18/5a88e829854d3.png)
![截图](https://i.loli.net/2018/02/18/5a88e8298cc1b.png)

**Comment by cicku** [comment]
请告诉我 ISP。

**Comment by YogiLiu** [comment]
广西联通
