### ISSUE TITLE
谷歌翻译被墙了

### ISSUE THREAD

**Issue by EmpRamses** [gfwlist/gfwlist#919]
网页能上，但是不能翻译

**Comment by cicku** [comment]
请给 URL。

**Comment by EmpRamses** [comment]
https://translate.google.cn/

**Comment by cicku** [comment]
可以正常访问，请给 ISP。

**Comment by EmpRamses** [comment]
https://translate.google.cn/#en/zh-CN/represent
类似于这种就不能访问了
ISP：
中国联通，辽宁，沈阳节点
Network | AS4837 CHINA UNICOM China169 Backbone
Route | 42.176.0.0/13

**Comment by cicku** [comment]
如果您仍然不能访问，请向运营商投诉。
