### ISSUE TITLE
带google套件的手机，在添加google时无法连接网络，但是用浏览器打开google一切正常

### ISSUE THREAD

**Issue by leizitgit** [gfwlist/gfwlist#920]
带google套件的手机，在添加google时无法连接网络，但是用浏览器打开google一切正常。
手机无法添加google账户，手机无法添加google账户，手机无法添加google账户
使用浏览器上google正常，使用浏览器上google正常，使用浏览器上google正常
谢谢

**Comment by cicku** [comment]
请说一下手机系统环境。

**Comment by leizitgit** [comment]
索尼手机 Android8.0.0系统
 手机可以正常访问google，就是在添加账户那里，添加google账户后会有google通讯录，gmail，日历等。

2018年2月26日星期一，ᴄʜʀɪsᴛᴏᴘʜᴇʀ ᴍᴇɴɢ <notifications@github.com> 写道：

**Comment by lzl119** [comment]
services.googleapi.cn该域名会解析到国内网络导致gcm/fcm无法使用，香港ip无法连接Google play，目前只有全局，已经向gfwlist和其他的acl文件规则提交，但是代理了这个域名也不一定会解决

**Comment by cicku** [comment]
@lzl119 这个域名早就在列表里面了，您的汇报与此无关。

**Comment by lzl119** [comment]
好多，谢谢
