### ISSUE TITLE
could u add a normal text gfwlist?

### ISSUE THREAD

**Issue by fastfading** [gfwlist/gfwlist#928]
could u add a normal text gfwlist?
not pac format .
just like this 
https://539go.com/Img/Other/gfwlist.txt
example ：  
-------------------------
google.com.hk
youtu.be
youtube.com
youtube.com
youtube-nocookie.com
youtubeeducation.com
youtubegaming.com
yt.be

I need this on shadowsock plugin on some smart router

**Comment by cicku** [comment]
No.
