### ISSUE TITLE
关于部分网站直连强行被转到百度云加速服务器验证的问题求教？

### ISSUE THREAD

**Issue by Ywang1233** [gfwlist/gfwlist#935]
验证后可以直连，但貌似有时限并且好像是从百度云的机房转连过去的。山东联通

**Comment by paperbag** [comment]
FYI. https://www.cloudflare.com/zh/network/china/
https://support.cloudflare.com/hc/en-us/articles/203366080-Why-do-I-see-a-captcha-or-challenge-page-Attention-Required-trying-to-visit-a-site-protected-by-Cloudflare-as-a-site-visitor-

**Comment by cicku** [comment]
Cloudflare 和 Baidu 早就开始合作了。
