### ISSUE TITLE
5ch.net访问不了

### ISSUE THREAD

**Issue by jeremy0714** [gfwlist/gfwlist#937]
5ch.net日本最大留言板
以前打开有个百度云验证可以直接登陆
 现在貌似是直接屏蔽了中国的ip了
希望添加到gfwlist里

![qq 20180306114837](https://user-images.githubusercontent.com/12095602/37013419-bd26a35c-2134-11e8-9610-53461f6c7ed1.png)

**Comment by paperbag** [comment]
FYI https://support.cloudflare.com/hc/en-us/articles/217074967-How-do-I-control-IP-access-to-my-site-

**Comment by cicku** [comment]
我这里访问正常。

是不是您的IP有问题？

**Comment by jeremy0714** [comment]
试了，应该是电信IP被ban了，移动的IP可以直连
算了，我还是挂梯子吧
