### ISSUE TITLE
一系列数字货币交易所域名被 DNS 污染

### ISSUE THREAD

**Issue by gongjianhui** [gfwlist/gfwlist#947]
- [x] *.gate.io
- [x] *.huobi.pro
- [x] *.binance.com
- [x] *.bitfinex.com
- [x] *.okex.com

**Comment by gongjianhui** [comment]
*.coinegg.com
*.hitbtc.com

**Comment by gongjianhui** [comment]
*.bitmex.com

**Comment by gongjianhui** [comment]
www.aex.com

**Comment by cicku** [comment]
非常感谢您的汇报。

不过，部分网址在我之前跟踪时并未发现异常，并且由于﹝你懂的﹞正在召开，本项目暂不处理新汇报的问题，等﹝你懂的﹞结束再看。

**Comment by cicku** [comment]
@gongjianhui I cannot confirm `aex.com`

**Comment by cicku** [comment]
@Timolol2012 reported:

~~- [ ] gate.io~~
- [ ] bcex.ca
- [ ] big.one
- [ ] jex.com
- [ ] cex.com
- [ ] exx.com

~~- [ ] aex.com~~
- [ ] yobit.net
- [ ] bjex.com
- [ ] bit-z.com
- [ ] tidex.com
- [ ] lbank.info
- [ ] bibox.com
- [ ] coinw.com
- [ ] allcoin.com
- [ ] coinex.com
- [ ] btctrade.im
- [ ] topbtc.com
- [ ] kucoin.com
- [ ] leekico.com
- [ ] chaoex.com
- [ ] shapeshift.io

~~- [ ] coinegg.com~~
- [ ] coolcoin.com
- [ ] ico-china.info
- [ ] ebtcbank.com
- [ ] etherdelta.com
- [ ] bitcoinworld.com

**Comment by Timolol2012** [comment]
gate.io
aex.com
coinegg.com

这3个交易所的网站确实被墙或者污染了，手动添加到SSR的PAC文件中就可以打开了

**Comment by cicku** [comment]
[...] +403

**Comment by cicku** [comment]
Those do not have connectivity issues have been commented out.
