### ISSUE TITLE
BBC中文网的链接无效

### ISSUE THREAD

**Issue by ddyllen-z** [gfwlist/gfwlist#960]
用的SS-windows版本的PAC模式，发现BBC中文网的规则无效。就发现这一个无效，全局模式没问题。不知道是不是这个规则列表的问题。

**Comment by ddyllen-z** [comment]
我自己增加了一条规则：`".bbc.com"`，这样就有效，自带的带二级目录的规则神效不了。

**Comment by cicku** [comment]
跟 GFWList 没有任何关系。
