### ISSUE TITLE
Please consider add "pinterest.com" to the list

### ISSUE THREAD

**Issue by LzVae** [gfwlist/gfwlist#967]
[Pinterest(https://www.pinterest.com/)](https://www.pinterest.com/) is a web site where designers need to go frequently. But it has never been able to visit  from  China. So please consider add "pinterest.com" to the GFWlist

**Comment by JohnSmithdesu** [comment]
_www.pinterest.com_ is already on the list, you may found these rules in current version of it. 

```
||pinterest.at
||pinterest.co.kr
||pinterest.co.uk
.pinterest.com
||pinterest.com
||pinterest.de
||pinterest.dk
||pinterest.fr
||pinterest.jp
||pinterest.nl
||pinterest.se
```

**Comment by JohnSmithdesu** [comment]
_www.pinterest.com_ is already on the list, you may find these rules in current version of it. 

```
||pinterest.at
||pinterest.co.kr
||pinterest.co.uk
.pinterest.com
||pinterest.com
||pinterest.de
||pinterest.dk
||pinterest.fr
||pinterest.jp
||pinterest.nl
||pinterest.se
```

**Comment by LzVae** [comment]
I updated the PAC from GFWlist. Now that I have pinterest.com in my PAC file, thanks for your notification, I will close this issue

**Comment by cicku** [comment]
#517
