### ISSUE TITLE
请将services.googleapi.cn加入代理列表

### ISSUE THREAD

**Issue by lzl119** [gfwlist/gfwlist#968]
该域名会解析到国内网络导致gcm/fcm无法使用，香港ip无法连接Google play

**Comment by cicku** [comment]
Duplicate of #464

**Comment by lzl119** [comment]
但是在#464上没看到怎么处理。安卓的ssr感觉没有iOS的shadowrocket/surge灵活

**Comment by cicku** [comment]
`googleapi.cn` 全站都会被代理。
