### ISSUE TITLE
Remove link

### ISSUE THREAD

**Issue by NakornC** [gfwlist/gfwlist#971]
melon-peach.com
通过ipip测试已正常ping

**Comment by NakornC** [comment]
2dbook.com
4tern.com
adorama.com
agnesb.fr
qq.co.za
redtube.com
acg18.me
danke4china.net

**Comment by NakornC** [comment]
akiba-web.com
alien-ufos.com

**Comment by cicku** [comment]
Some remain there because they still trigger TCP RST.
