### ISSUE TITLE
www.chinatimes.com

### ISSUE THREAD

**Issue by houbaron** [gfwlist/gfwlist#977]
www.chinatimes.com 内大部分内容均可直连。但该网站使用 http 协议，似乎当包含某些敏感词汇时，就会触发 TCP_RST。
比如这条：[每天超過1萬支 陸首現無人機走私iPhone](http://www.chinatimes.com/realtimenews/20180331002224-260409)，访问就会被重置。大概触发了「走私」二字？

**Comment by mraandtux** [comment]
中时可以用https
