### ISSUE TITLE
申请添加白名单

### ISSUE THREAD

**Issue by jacksky007** [gfwlist/gfwlist#986]
*.longzhu.com
*.longzhulive.com
*.plu.cn
这些是[龙珠直播](http://longzhu.com)平台所用的站点和CDN对应域名，希望可以添加白名单处理，谢谢。

**Comment by cicku** [comment]
？？？

GFWList 白名单收录网址规定：

1. 本身没有被 GFW 盯上，但是却由于 GFWList 规则而被错误的覆盖进来。一个新鲜的例子是 #979

2. 简化规则，比如一个网站除了二级域 X，全部被墙。如果该网站有10个二级域，显然添加10条规则，不如全站匹配再添加 X 到白名单更合理。

龙珠的服务器在墙内，没有到国际网络出口就意味着没有 TCP Reset，输入什么都不会触发 TCP Reset。所以我觉得没有添加龙珠直播到白名单的必要。

**Comment by cicku** [comment]
`国内访问时科学上网走境外代理`

您这番话让我有点丈二和尚——摸不着头脑。GFWList 默认不会代理龙珠直播，为什么要走代理？
