### ISSUE TITLE
please add reddit to gfwlist

### ISSUE THREAD

**Issue by kevin-lucifer** [gfwlist/gfwlist#987]
site: www.reddit.com

**Comment by Forest-13** [comment]
You could add the following lines manually:
"||reddit.com",
"||redditmedia.com",
"||redd.it||",
"||redditstatic.com||",
They work for me.

**Comment by cicku** [comment]
See #1173 

@Forest-13 Please do not reply old issues.

**Comment by kevin-lucifer** [comment]
Thanks forest ,it helps.
